import { BlockType } from '../types'
import type { SlashCommandItem } from '../types'

export const SLASH_COMMANDS: SlashCommandItem[] = [
  {
    id: 'text',
    label: 'Text',
    description: 'Plain text block',
    icon: 'Type',
    type: BlockType.Paragraph,
    keywords: ['text', 'plain', 'paragraph'],
  },
  {
    id: 'heading1',
    label: 'Heading 1',
    description: 'Large heading',
    icon: 'Heading1',
    type: BlockType.Heading1,
    keywords: ['h1', 'title', 'large', 'heading'],
  },
  {
    id: 'heading2',
    label: 'Heading 2',
    description: 'Medium heading',
    icon: 'Heading2',
    type: BlockType.Heading2,
    keywords: ['h2', 'subtitle', 'medium', 'heading'],
  },
  {
    id: 'heading3',
    label: 'Heading 3',
    description: 'Small heading',
    icon: 'Heading3',
    type: BlockType.Heading3,
    keywords: ['h3', 'small', 'heading'],
  },
  {
    id: 'bullet-list',
    label: 'Bulleted List',
    description: 'Bulleted list item',
    icon: 'List',
    type: BlockType.BulletList,
    keywords: ['bullet', 'unordered', 'list', 'ul'],
  },
  {
    id: 'numbered-list',
    label: 'Numbered List',
    description: 'Numbered list item',
    icon: 'ListOrdered',
    type: BlockType.NumberedList,
    keywords: ['number', 'ordered', 'list', 'ol'],
  },
  {
    id: 'toggle',
    label: 'Toggle',
    description: 'Collapsible content',
    icon: 'ChevronRight',
    type: BlockType.Toggle,
    keywords: ['toggle', 'collapse', 'expand', 'dropdown'],
  },
  {
    id: 'callout',
    label: 'Callout',
    description: 'Highlighted callout box',
    icon: 'MessageSquare',
    type: BlockType.Callout,
    keywords: ['callout', 'info', 'warning', 'note', 'highlight'],
  },
  {
    id: 'code',
    label: 'Code',
    description: 'Code block',
    icon: 'Code',
    type: BlockType.Code,
    keywords: ['code', 'snippet', 'pre'],
  },
  {
    id: 'quote',
    label: 'Quote',
    description: 'Block quote',
    icon: 'Quote',
    type: BlockType.Quote,
    keywords: ['quote', 'blockquote', 'citation'],
  },
  {
    id: 'divider',
    label: 'Divider',
    description: 'Horizontal divider',
    icon: 'Minus',
    type: BlockType.Divider,
    keywords: ['divider', 'hr', 'separator', 'line'],
  },
  {
    id: 'image',
    label: 'Image',
    description: 'Image block',
    icon: 'Image',
    type: BlockType.Image,
    keywords: ['image', 'picture', 'photo', 'img'],
  },
]
