import { BlockType } from '../types'
import type { PageTemplate } from '../types'

export const PAGE_TEMPLATES: PageTemplate[] = [
  {
    id: 'blank',
    title: 'Blank',
    icon: '📄',
    description: 'Start with an empty page',
    blocks: [],
  },
  {
    id: 'meeting-notes',
    title: 'Meeting Notes',
    icon: '📝',
    description: 'Capture meeting notes and action items',
    blocks: [
      { type: BlockType.Heading1, content: 'Meeting Notes' },
      { type: BlockType.BulletList, content: 'Date: ' },
      { type: BlockType.BulletList, content: 'Attendees: ' },
      { type: BlockType.Heading2, content: 'Agenda' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Action Items' },
      { type: BlockType.BulletList, content: '' },
    ],
  },
  {
    id: 'project-brief',
    title: 'Project Brief',
    icon: '🎯',
    description: 'Outline a new project',
    blocks: [
      { type: BlockType.Heading1, content: 'Project Brief' },
      { type: BlockType.Heading2, content: 'Overview' },
      { type: BlockType.Paragraph, content: '' },
      { type: BlockType.Heading2, content: 'Goals' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Timeline' },
      { type: BlockType.Paragraph, content: '' },
      { type: BlockType.Heading2, content: 'Resources' },
      { type: BlockType.BulletList, content: '' },
    ],
  },
  {
    id: 'weekly-review',
    title: 'Weekly Review',
    icon: '📊',
    description: 'Review your week',
    blocks: [
      { type: BlockType.Heading1, content: 'Weekly Review' },
      { type: BlockType.Heading2, content: 'Wins' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Challenges' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Next Week' },
      { type: BlockType.BulletList, content: '' },
    ],
  },
  {
    id: 'decision-log',
    title: 'Decision Log',
    icon: '⚖️',
    description: 'Record important decisions',
    blocks: [
      { type: BlockType.Heading1, content: 'Decision Log' },
      { type: BlockType.Paragraph, content: 'Record important decisions and their rationale here.' },
      { type: BlockType.Divider, content: '' },
    ],
  },
  {
    id: 'sprint-planning',
    title: 'Sprint Planning',
    icon: '🏃',
    description: 'Plan your sprint goals and backlog',
    blocks: [
      { type: BlockType.Heading1, content: 'Sprint Planning - {{date}}' },
      { type: BlockType.Heading2, content: 'Sprint Goals' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Backlog' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Timeline' },
      { type: BlockType.Paragraph, content: '' },
    ],
    variables: { date: new Date().toISOString().split('T')[0] ?? '' },
  },
  {
    id: 'bug-report',
    title: 'Bug Report',
    icon: '🐛',
    description: 'Document a bug with reproduction steps',
    blocks: [
      { type: BlockType.Heading1, content: '{{title}}' },
      { type: BlockType.Heading2, content: 'Description' },
      { type: BlockType.Paragraph, content: '' },
      { type: BlockType.Heading2, content: 'Steps to Reproduce' },
      { type: BlockType.NumberedList, content: '' },
      { type: BlockType.Heading2, content: 'Expected Behavior' },
      { type: BlockType.Paragraph, content: '' },
      { type: BlockType.Heading2, content: 'Actual Behavior' },
      { type: BlockType.Paragraph, content: '' },
    ],
    variables: { title: 'Bug Report' },
  },
  {
    id: 'product-roadmap',
    title: 'Product Roadmap',
    icon: '🗺️',
    description: 'Plan your product vision and quarterly goals',
    blocks: [
      { type: BlockType.Heading1, content: 'Product Roadmap' },
      { type: BlockType.Heading2, content: 'Vision' },
      { type: BlockType.Paragraph, content: '' },
      { type: BlockType.Heading2, content: 'Q1 Goals' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Q2 Goals' },
      { type: BlockType.BulletList, content: '' },
    ],
  },
  {
    id: 'design-doc',
    title: 'Design Doc',
    icon: '📐',
    description: 'Technical design document with proposal and alternatives',
    blocks: [
      { type: BlockType.Heading1, content: '{{title}}' },
      { type: BlockType.Heading2, content: 'Background' },
      { type: BlockType.Paragraph, content: '' },
      { type: BlockType.Heading2, content: 'Proposal' },
      { type: BlockType.Paragraph, content: '' },
      { type: BlockType.Heading2, content: 'Alternatives' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Decision' },
      { type: BlockType.Paragraph, content: '' },
    ],
    variables: { title: 'Design Doc' },
  },
  {
    id: 'user-research',
    title: 'User Research',
    icon: '🔍',
    description: 'Capture research questions, methodology, and findings',
    blocks: [
      { type: BlockType.Heading1, content: 'User Research - {{date}}' },
      { type: BlockType.Heading2, content: 'Research Questions' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Methodology' },
      { type: BlockType.Paragraph, content: '' },
      { type: BlockType.Heading2, content: 'Findings' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Recommendations' },
      { type: BlockType.BulletList, content: '' },
    ],
    variables: { date: new Date().toISOString().split('T')[0] ?? '' },
  },
  {
    id: 'retrospective',
    title: 'Retrospective',
    icon: '🔄',
    description: 'Reflect on what went well and what to improve',
    blocks: [
      { type: BlockType.Heading1, content: 'Retrospective - {{date}}' },
      { type: BlockType.Heading2, content: 'What went well' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'What could improve' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Action items' },
      { type: BlockType.BulletList, content: '' },
    ],
    variables: { date: new Date().toISOString().split('T')[0] ?? '' },
  },
  {
    id: '1on1-notes',
    title: '1:1 Notes',
    icon: '🤝',
    description: 'Track updates, discussions, and action items from 1:1s',
    blocks: [
      { type: BlockType.Heading1, content: '1:1 Notes - {{date}}' },
      { type: BlockType.Heading2, content: 'Updates' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Discussion' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Action items' },
      { type: BlockType.BulletList, content: '' },
    ],
    variables: { date: new Date().toISOString().split('T')[0] ?? '' },
  },
  {
    id: 'company-wiki',
    title: 'Company Wiki',
    icon: '🏢',
    description: 'Central knowledge base for your team',
    blocks: [
      { type: BlockType.Heading1, content: '{{title}}' },
      { type: BlockType.Heading2, content: 'Overview' },
      { type: BlockType.Paragraph, content: '' },
      { type: BlockType.Heading2, content: 'Team' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Processes' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Resources' },
      { type: BlockType.BulletList, content: '' },
    ],
    variables: { title: 'Company Wiki' },
  },
  {
    id: 'feature-spec',
    title: 'Feature Spec',
    icon: '📋',
    description: 'Define a feature with requirements and success metrics',
    blocks: [
      { type: BlockType.Heading1, content: '{{title}}' },
      { type: BlockType.Heading2, content: 'Problem' },
      { type: BlockType.Paragraph, content: '' },
      { type: BlockType.Heading2, content: 'Solution' },
      { type: BlockType.Paragraph, content: '' },
      { type: BlockType.Heading2, content: 'Requirements' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Success Metrics' },
      { type: BlockType.BulletList, content: '' },
    ],
    variables: { title: 'Feature Spec' },
  },
  {
    id: 'release-notes',
    title: 'Release Notes',
    icon: '🚀',
    description: 'Document new features, improvements, and bug fixes',
    blocks: [
      { type: BlockType.Heading1, content: 'Release Notes - {{date}}' },
      { type: BlockType.Heading2, content: 'New Features' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Improvements' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Bug Fixes' },
      { type: BlockType.BulletList, content: '' },
    ],
    variables: { date: new Date().toISOString().split('T')[0] ?? '' },
  },
]
