import { BlockType } from '../types'
import type { PageTemplate } from '../types'

export const PAGE_TEMPLATES: PageTemplate[] = [
  {
    id: 'blank',
    title: 'Blank',
    icon: '📄',
    description: 'Start with an empty page',
    blocks: [],
  },
  {
    id: 'meeting-notes',
    title: 'Meeting Notes',
    icon: '📝',
    description: 'Capture meeting notes and action items',
    blocks: [
      { type: BlockType.Heading1, content: 'Meeting Notes' },
      { type: BlockType.BulletList, content: 'Date: ' },
      { type: BlockType.BulletList, content: 'Attendees: ' },
      { type: BlockType.Heading2, content: 'Agenda' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Action Items' },
      { type: BlockType.BulletList, content: '' },
    ],
  },
  {
    id: 'project-brief',
    title: 'Project Brief',
    icon: '🎯',
    description: 'Outline a new project',
    blocks: [
      { type: BlockType.Heading1, content: 'Project Brief' },
      { type: BlockType.Heading2, content: 'Overview' },
      { type: BlockType.Paragraph, content: '' },
      { type: BlockType.Heading2, content: 'Goals' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Timeline' },
      { type: BlockType.Paragraph, content: '' },
      { type: BlockType.Heading2, content: 'Resources' },
      { type: BlockType.BulletList, content: '' },
    ],
  },
  {
    id: 'weekly-review',
    title: 'Weekly Review',
    icon: '📊',
    description: 'Review your week',
    blocks: [
      { type: BlockType.Heading1, content: 'Weekly Review' },
      { type: BlockType.Heading2, content: 'Wins' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Challenges' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Next Week' },
      { type: BlockType.BulletList, content: '' },
    ],
  },
  {
    id: 'decision-log',
    title: 'Decision Log',
    icon: '⚖️',
    description: 'Record important decisions',
    blocks: [
      { type: BlockType.Heading1, content: 'Decision Log' },
      { type: BlockType.Paragraph, content: 'Record important decisions and their rationale here.' },
      { type: BlockType.Divider, content: '' },
    ],
  },
  {
    id: 'sprint-planning',
    title: 'Sprint Planning',
    icon: '🏃',
    description: 'Plan your sprint goals and backlog',
    blocks: [
      { type: BlockType.Heading1, content: 'Sprint Planning - {{date}}' },
      { type: BlockType.Heading2, content: 'Sprint Goals' },
      { type: BlockType.TodoList, content: '' },
      { type: BlockType.TodoList, content: '' },
      { type: BlockType.TodoList, content: '' },
      { type: BlockType.Heading2, content: 'Backlog Items' },
      { type: BlockType.TodoList, content: '' },
      { type: BlockType.TodoList, content: '' },
      { type: BlockType.Heading2, content: 'Capacity & Risks' },
      { type: BlockType.BulletList, content: 'Team capacity: ' },
      { type: BlockType.BulletList, content: 'Risks: ' },
      { type: BlockType.Heading2, content: 'Timeline' },
      { type: BlockType.Paragraph, content: '' },
    ],
    variables: { date: new Date().toISOString().split('T')[0] ?? '' },
  },
  {
    id: 'bug-report',
    title: 'Bug Report',
    icon: '🐛',
    description: 'Document a bug with reproduction steps',
    blocks: [
      { type: BlockType.Heading1, content: '{{title}}' },
      { type: BlockType.Heading2, content: 'Summary' },
      { type: BlockType.Paragraph, content: '' },
      { type: BlockType.Heading2, content: 'Environment' },
      { type: BlockType.BulletList, content: 'Browser: ' },
      { type: BlockType.BulletList, content: 'OS: ' },
      { type: BlockType.BulletList, content: 'Version: ' },
      { type: BlockType.Heading2, content: 'Steps to Reproduce' },
      { type: BlockType.NumberedList, content: '' },
      { type: BlockType.NumberedList, content: '' },
      { type: BlockType.NumberedList, content: '' },
      { type: BlockType.Heading2, content: 'Expected Behavior' },
      { type: BlockType.Paragraph, content: '' },
      { type: BlockType.Heading2, content: 'Actual Behavior' },
      { type: BlockType.Paragraph, content: '' },
      { type: BlockType.Heading2, content: 'Screenshots' },
      { type: BlockType.Paragraph, content: '' },
      { type: BlockType.Heading2, content: 'Severity' },
      { type: BlockType.Paragraph, content: '' },
    ],
    variables: { title: 'Bug Report' },
  },
  {
    id: 'product-roadmap',
    title: 'Product Roadmap',
    icon: '🗺️',
    description: 'Plan your product vision and quarterly goals',
    blocks: [
      { type: BlockType.Heading1, content: 'Product Roadmap' },
      { type: BlockType.Heading2, content: 'Vision' },
      { type: BlockType.Paragraph, content: '' },
      { type: BlockType.Divider, content: '' },
      { type: BlockType.Heading2, content: 'Q1 Goals' },
      { type: BlockType.TodoList, content: '' },
      { type: BlockType.TodoList, content: '' },
      { type: BlockType.Heading2, content: 'Q2 Goals' },
      { type: BlockType.TodoList, content: '' },
      { type: BlockType.TodoList, content: '' },
      { type: BlockType.Heading2, content: 'Q3 Goals' },
      { type: BlockType.TodoList, content: '' },
      { type: BlockType.TodoList, content: '' },
      { type: BlockType.Heading2, content: 'Q4 Goals' },
      { type: BlockType.TodoList, content: '' },
      { type: BlockType.TodoList, content: '' },
    ],
  },
  {
    id: 'design-doc',
    title: 'Design Doc',
    icon: '📐',
    description: 'Technical design document with goals, non-goals, and approach',
    blocks: [
      { type: BlockType.Heading1, content: '{{title}}' },
      { type: BlockType.Heading2, content: 'Overview' },
      { type: BlockType.Paragraph, content: '' },
      { type: BlockType.Heading2, content: 'Goals' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Non-Goals' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Approach' },
      { type: BlockType.Paragraph, content: '' },
      { type: BlockType.Heading2, content: 'Alternatives Considered' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Timeline' },
      { type: BlockType.Paragraph, content: '' },
      { type: BlockType.Heading2, content: 'Open Questions' },
      { type: BlockType.BulletList, content: '' },
    ],
    variables: { title: 'Design Doc' },
  },
  {
    id: 'user-research',
    title: 'User Research',
    icon: '🔍',
    description: 'Capture questions, participants, findings, and recommendations',
    blocks: [
      { type: BlockType.Heading1, content: 'User Research - {{date}}' },
      { type: BlockType.Heading2, content: 'Research Questions' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Participants' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Methodology' },
      { type: BlockType.Paragraph, content: '' },
      { type: BlockType.Heading2, content: 'Findings' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Recommendations' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Next Steps' },
      { type: BlockType.TodoList, content: '' },
    ],
    variables: { date: new Date().toISOString().split('T')[0] ?? '' },
  },
  {
    id: 'retrospective',
    title: 'Retrospective',
    icon: '🔄',
    description: 'Reflect on what went well, what did not, and action items',
    blocks: [
      { type: BlockType.Heading1, content: 'Retrospective - {{date}}' },
      { type: BlockType.Heading2, content: 'What went well' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'What did not go well' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Action Items' },
      { type: BlockType.TodoList, content: '' },
      { type: BlockType.TodoList, content: '' },
      { type: BlockType.TodoList, content: '' },
    ],
    variables: { date: new Date().toISOString().split('T')[0] ?? '' },
  },
  {
    id: '1on1-notes',
    title: '1:1 Notes',
    icon: '🤝',
    description: 'Track talking points, action items, and follow-ups from 1:1s',
    blocks: [
      { type: BlockType.Heading1, content: '1:1 Notes - {{date}}' },
      { type: BlockType.Heading2, content: 'Talking Points' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Action Items' },
      { type: BlockType.TodoList, content: '' },
      { type: BlockType.TodoList, content: '' },
      { type: BlockType.Heading2, content: 'Follow-ups' },
      { type: BlockType.TodoList, content: '' },
    ],
    variables: { date: new Date().toISOString().split('T')[0] ?? '' },
  },
  {
    id: 'company-wiki',
    title: 'Company Wiki',
    icon: '🏢',
    description: 'Central knowledge base with team directory, policies, and tools',
    blocks: [
      { type: BlockType.Heading1, content: '{{title}}' },
      { type: BlockType.Callout, content: 'Welcome to the company wiki. This is the central hub for all team knowledge.' },
      { type: BlockType.Heading2, content: 'Team Directory' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Policies' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Tools & Integrations' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Onboarding' },
      { type: BlockType.BulletList, content: '' },
    ],
    variables: { title: 'Company Wiki' },
  },
  {
    id: 'feature-spec',
    title: 'Feature Spec',
    icon: '📋',
    description: 'Define problem, solution, requirements, and milestones',
    blocks: [
      { type: BlockType.Heading1, content: '{{title}}' },
      { type: BlockType.Heading2, content: 'Problem Statement' },
      { type: BlockType.Paragraph, content: '' },
      { type: BlockType.Heading2, content: 'Proposed Solution' },
      { type: BlockType.Paragraph, content: '' },
      { type: BlockType.Heading2, content: 'Requirements' },
      { type: BlockType.TodoList, content: '' },
      { type: BlockType.TodoList, content: '' },
      { type: BlockType.Heading2, content: 'Milestones' },
      { type: BlockType.TodoList, content: '' },
      { type: BlockType.TodoList, content: '' },
      { type: BlockType.Heading2, content: 'Success Metrics' },
      { type: BlockType.BulletList, content: '' },
    ],
    variables: { title: 'Feature Spec' },
  },
  {
    id: 'release-notes',
    title: 'Release Notes',
    icon: '🚀',
    description: 'Document version, new features, fixes, and known issues',
    blocks: [
      { type: BlockType.Heading1, content: 'Release Notes - {{date}}' },
      { type: BlockType.Paragraph, content: 'Version: ' },
      { type: BlockType.Paragraph, content: 'Release date: {{date}}' },
      { type: BlockType.Divider, content: '' },
      { type: BlockType.Heading2, content: 'New Features' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Improvements' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Bug Fixes' },
      { type: BlockType.BulletList, content: '' },
      { type: BlockType.Heading2, content: 'Known Issues' },
      { type: BlockType.BulletList, content: '' },
    ],
    variables: { date: new Date().toISOString().split('T')[0] ?? '' },
  },
]

/**
 * Apply template variables to block content.
 * Replaces {{key}} with the corresponding value.
 */
export function applyTemplateVariables(
  content: string,
  variables: Record<string, string>
): string {
  let result = content
  for (const [key, value] of Object.entries(variables)) {
    result = result.replace(new RegExp(`\\{\\{${key}\\}\\}`, 'g'), value)
  }
  return result
}
