import type { LucideIcon } from 'lucide-react'
import {
  FileText,
  Layout,
  CircleDot,
  Calendar,
  Database,
  Settings,
  Bot,
  Home,
  FolderKanban,
  FileSignature,
  Inbox,
  Brain,
  Receipt,
  Code2,
  Plus,
  Sun,
  Moon,
  PanelLeft,
  Keyboard,
  Upload,
  Download,
  Zap,
  Globe,
  BookOpen,
  Users,
  CreditCard,
  BarChart3,
  Search,
  MessageSquare,
  Play,
} from 'lucide-react'

const icons: Record<string, LucideIcon> = {
  'file-text': FileText,
  'layout': Layout,
  'circle-dot': CircleDot,
  'calendar': Calendar,
  'database': Database,
  'settings': Settings,
  'bot': Bot,
  'home': Home,
  'folder-kanban': FolderKanban,
  'file-signature': FileSignature,
  'inbox': Inbox,
  'brain': Brain,
  'receipt': Receipt,
  'code-2': Code2,
  'plus': Plus,
  'sun': Sun,
  'moon': Moon,
  'panel-left': PanelLeft,
  'keyboard': Keyboard,
  'upload': Upload,
  'download': Download,
  'zap': Zap,
  'globe': Globe,
  'book-open': BookOpen,
  'users': Users,
  'credit-card': CreditCard,
  'bar-chart': BarChart3,
  'search': Search,
  'message-square': MessageSquare,
  'play': Play,
}

export function resolveIcon(name: string): LucideIcon | null {
  return icons[name] ?? null
}
