import type { EventType, Booking } from '../types'
import {
  EventTypeCategory,
  BookingStatus,
  DEFAULT_SCHEDULE,
  EVENT_TYPE_COLORS,
} from '../types'

export const SAMPLE_EVENT_TYPES: EventType[] = [
  {
    id: 'et-quick-chat',
    name: 'Quick Chat',
    description: 'A brief 15-minute call to answer quick questions or catch up.',
    slug: 'quick-chat',
    category: EventTypeCategory.OneOnOne,
    color: EVENT_TYPE_COLORS[5]!, // Blue
    durationMinutes: 15,
    bufferBeforeMinutes: 5,
    bufferAfterMinutes: 5,
    maxBookingsPerDay: 8,
    minimumNoticeMinutes: 60,
    schedulingWindowDays: 30,
    schedule: DEFAULT_SCHEDULE,
    dateOverrides: [],
    customQuestions: [],
    maxAttendees: 1,
    isActive: true,
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'et-product-demo',
    name: 'Product Demo',
    description: 'A 30-minute walkthrough of SignOf features and capabilities.',
    slug: 'product-demo',
    category: EventTypeCategory.OneOnOne,
    color: EVENT_TYPE_COLORS[1]!, // Green
    durationMinutes: 30,
    bufferBeforeMinutes: 10,
    bufferAfterMinutes: 10,
    maxBookingsPerDay: 4,
    minimumNoticeMinutes: 120,
    schedulingWindowDays: 60,
    schedule: DEFAULT_SCHEDULE,
    dateOverrides: [],
    customQuestions: [
      {
        id: 'cq-1',
        label: 'What is your company name?',
        type: 'text',
        required: true,
      },
      {
        id: 'cq-2',
        label: 'What features are you most interested in?',
        type: 'textarea',
        required: false,
      },
    ],
    maxAttendees: 1,
    isActive: true,
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'et-team-standup',
    name: 'Team Standup',
    description: 'Daily team standup to share updates and blockers.',
    slug: 'team-standup',
    category: EventTypeCategory.Group,
    color: EVENT_TYPE_COLORS[4]!, // Purple
    durationMinutes: 15,
    bufferBeforeMinutes: 0,
    bufferAfterMinutes: 5,
    maxBookingsPerDay: 2,
    minimumNoticeMinutes: 30,
    schedulingWindowDays: 14,
    schedule: DEFAULT_SCHEDULE,
    dateOverrides: [],
    customQuestions: [],
    maxAttendees: 10,
    isActive: true,
    createdAt: '2026-01-20T08:00:00Z',
    updatedAt: '2026-01-20T08:00:00Z',
  },
  {
    id: 'et-contract-signing',
    name: 'Contract Signing',
    description: 'A guided signing session for contract documents with real-time support.',
    slug: 'contract-signing',
    category: EventTypeCategory.SigningSession,
    color: EVENT_TYPE_COLORS[2]!, // Red
    durationMinutes: 45,
    bufferBeforeMinutes: 15,
    bufferAfterMinutes: 15,
    maxBookingsPerDay: 3,
    minimumNoticeMinutes: 240,
    schedulingWindowDays: 90,
    schedule: DEFAULT_SCHEDULE,
    dateOverrides: [],
    customQuestions: [
      {
        id: 'cq-3',
        label: 'Contract or document reference number',
        type: 'text',
        required: true,
      },
      {
        id: 'cq-4',
        label: 'How many signers will participate?',
        type: 'select',
        required: true,
        options: ['1', '2', '3', '4', '5+'],
      },
    ],
    maxAttendees: 5,
    isActive: true,
    createdAt: '2026-01-25T14:00:00Z',
    updatedAt: '2026-01-25T14:00:00Z',
  },
]

export const SAMPLE_BOOKINGS: Booking[] = [
  {
    id: 'bk-1',
    eventTypeId: 'et-quick-chat',
    date: '2026-02-11',
    startTime: '10:00',
    endTime: '10:15',
    timezone: 'America/New_York',
    status: BookingStatus.Confirmed,
    attendees: [
      { name: 'Alice Johnson', email: 'alice@example.com', timezone: 'America/New_York' },
    ],
    notes: 'Follow up on Q1 proposal',
    createdAt: '2026-02-05T09:00:00Z',
    updatedAt: '2026-02-05T09:00:00Z',
  },
  {
    id: 'bk-2',
    eventTypeId: 'et-product-demo',
    date: '2026-02-12',
    startTime: '14:00',
    endTime: '14:30',
    timezone: 'America/Chicago',
    status: BookingStatus.Confirmed,
    attendees: [
      {
        name: 'Bob Chen',
        email: 'bob@acmecorp.com',
        timezone: 'America/Chicago',
        responses: {
          'cq-1': 'Acme Corp',
          'cq-2': 'Document signing and team collaboration',
        },
      },
    ],
    notes: '',
    createdAt: '2026-02-06T11:00:00Z',
    updatedAt: '2026-02-06T11:00:00Z',
  },
  {
    id: 'bk-3',
    eventTypeId: 'et-team-standup',
    date: '2026-02-10',
    startTime: '09:00',
    endTime: '09:15',
    timezone: 'America/New_York',
    status: BookingStatus.Completed,
    attendees: [
      { name: 'Carol Davis', email: 'carol@signof.com', timezone: 'America/New_York' },
      { name: 'Dan Evans', email: 'dan@signof.com', timezone: 'America/New_York' },
      { name: 'Eve Foster', email: 'eve@signof.com', timezone: 'Europe/London' },
    ],
    notes: 'Monday standup',
    createdAt: '2026-02-07T08:00:00Z',
    updatedAt: '2026-02-10T09:20:00Z',
  },
  {
    id: 'bk-4',
    eventTypeId: 'et-contract-signing',
    date: '2026-02-13',
    startTime: '11:00',
    endTime: '11:45',
    timezone: 'America/Los_Angeles',
    status: BookingStatus.Confirmed,
    attendees: [
      {
        name: 'Frank Garcia',
        email: 'frank@lawfirm.com',
        timezone: 'America/Los_Angeles',
        responses: {
          'cq-3': 'CTR-2026-0042',
          'cq-4': '2',
        },
      },
    ],
    notes: 'Partnership agreement signing',
    createdAt: '2026-02-04T15:00:00Z',
    updatedAt: '2026-02-04T15:00:00Z',
  },
  {
    id: 'bk-5',
    eventTypeId: 'et-quick-chat',
    date: '2026-02-09',
    startTime: '15:00',
    endTime: '15:15',
    timezone: 'Europe/London',
    status: BookingStatus.Cancelled,
    attendees: [
      { name: 'Grace Hopper', email: 'grace@tech.io', timezone: 'Europe/London' },
    ],
    notes: 'Cancelled — scheduling conflict',
    cancelReason: 'Scheduling conflict with another meeting',
    createdAt: '2026-02-03T12:00:00Z',
    updatedAt: '2026-02-08T10:00:00Z',
  },
  {
    id: 'bk-6',
    eventTypeId: 'et-product-demo',
    date: '2026-02-08',
    startTime: '10:00',
    endTime: '10:30',
    timezone: 'Asia/Tokyo',
    status: BookingStatus.Rescheduled,
    attendees: [
      {
        name: 'Hiro Tanaka',
        email: 'hiro@jpcompany.co.jp',
        timezone: 'Asia/Tokyo',
        responses: {
          'cq-1': 'JP Company Ltd.',
          'cq-2': 'Database and scheduling features',
        },
      },
    ],
    notes: 'Rescheduled from Feb 7 to Feb 8',
    createdAt: '2026-02-01T06:00:00Z',
    updatedAt: '2026-02-07T02:00:00Z',
  },
]
