import type { WorkflowNodeDefinition } from '../../types'

export const actionNodes: WorkflowNodeDefinition[] = [
  {
    type: 'connector_action',
    category: 'action',
    label: 'Connector Action',
    description: 'Execute an action from a connected platform',
    icon: 'plug',
    color: '#3B82F6',
    inputs: [{ id: 'in', label: 'Input', type: 'flow' }],
    outputs: [{ id: 'out', label: 'Output', type: 'flow' }],
    parameters: [
      { key: 'connectorId', label: 'Connector', type: 'string', required: true, placeholder: 'gmail' },
      { key: 'actionId', label: 'Action', type: 'string', required: true, placeholder: 'gmail-send' },
      { key: 'params', label: 'Parameters', type: 'json', required: false, placeholder: '{}' },
    ],
    defaultData: { connectorId: '', actionId: '', params: {} },
  },
  {
    type: 'tool_action',
    category: 'action',
    label: 'OriginA Tool',
    description: 'Execute an OriginA cross-module tool',
    icon: 'wrench',
    color: '#3B82F6',
    inputs: [{ id: 'in', label: 'Input', type: 'flow' }],
    outputs: [{ id: 'out', label: 'Output', type: 'flow' }],
    parameters: [
      {
        key: 'toolName', label: 'Tool', type: 'select', required: true,
        options: [
          { label: 'Create Page', value: 'create_page' },
          { label: 'Search Pages', value: 'search_pages' },
          { label: 'Create Issue', value: 'create_issue' },
          { label: 'List Issues', value: 'list_issues' },
          { label: 'Create Booking', value: 'create_booking' },
          { label: 'Create Invoice', value: 'create_invoice' },
          { label: 'Send Notification', value: 'send_notification' },
          { label: 'Get Workspace Stats', value: 'get_workspace_stats' },
        ],
      },
      { key: 'input', label: 'Input Data', type: 'json', required: false, placeholder: '{}' },
    ],
    defaultData: { toolName: '', input: {} },
  },
  {
    type: 'http_request',
    category: 'action',
    label: 'HTTP Request',
    description: 'Make a generic HTTP request',
    icon: 'globe',
    color: '#3B82F6',
    inputs: [{ id: 'in', label: 'Input', type: 'flow' }],
    outputs: [{ id: 'out', label: 'Output', type: 'flow' }],
    parameters: [
      { key: 'url', label: 'URL', type: 'string', required: true, placeholder: 'https://api.example.com' },
      { key: 'method', label: 'Method', type: 'select', required: true, options: [{ label: 'GET', value: 'GET' }, { label: 'POST', value: 'POST' }, { label: 'PUT', value: 'PUT' }, { label: 'DELETE', value: 'DELETE' }] },
      { key: 'headers', label: 'Headers', type: 'json', required: false, placeholder: '{}' },
      { key: 'body', label: 'Body', type: 'json', required: false, placeholder: '{}' },
    ],
    defaultData: { url: '', method: 'GET', headers: {}, body: {} },
  },
  {
    type: 'send_notification',
    category: 'action',
    label: 'Send Notification',
    description: 'Send an email, Slack, or in-app notification',
    icon: 'bell',
    color: '#3B82F6',
    inputs: [{ id: 'in', label: 'Input', type: 'flow' }],
    outputs: [{ id: 'out', label: 'Output', type: 'flow' }],
    parameters: [
      { key: 'channel', label: 'Channel', type: 'select', required: true, options: [{ label: 'In-App', value: 'in_app' }, { label: 'Email', value: 'email' }, { label: 'Slack', value: 'slack' }] },
      { key: 'title', label: 'Title', type: 'string', required: true, placeholder: 'Notification title' },
      { key: 'message', label: 'Message', type: 'string', required: true, placeholder: 'Notification body' },
    ],
    defaultData: { channel: 'in_app', title: '', message: '' },
  },
]
