import type { WorkflowNodeDefinition } from '../../types'

export const triggerNodes: WorkflowNodeDefinition[] = [
  {
    type: 'manual_trigger',
    category: 'trigger',
    label: 'Manual Trigger',
    description: 'Start workflow manually with a button click',
    icon: 'play',
    color: '#8B5CF6',
    inputs: [],
    outputs: [{ id: 'out', label: 'Output', type: 'flow' }],
    parameters: [],
    defaultData: {},
  },
  {
    type: 'schedule_trigger',
    category: 'trigger',
    label: 'Schedule Trigger',
    description: 'Start workflow on a cron schedule',
    icon: 'clock',
    color: '#8B5CF6',
    inputs: [],
    outputs: [{ id: 'out', label: 'Output', type: 'flow' }],
    parameters: [
      { key: 'cron', label: 'Cron Expression', type: 'string', required: true, placeholder: '0 9 * * MON' },
      { key: 'timezone', label: 'Timezone', type: 'string', required: false, default: 'UTC', placeholder: 'America/New_York' },
    ],
    defaultData: { cron: '0 9 * * MON', timezone: 'UTC' },
  },
  {
    type: 'webhook_trigger',
    category: 'trigger',
    label: 'Webhook Trigger',
    description: 'Start workflow from an incoming HTTP request',
    icon: 'globe',
    color: '#8B5CF6',
    inputs: [],
    outputs: [{ id: 'out', label: 'Output', type: 'flow' }],
    parameters: [
      { key: 'method', label: 'HTTP Method', type: 'select', required: true, options: [{ label: 'POST', value: 'POST' }, { label: 'GET', value: 'GET' }, { label: 'PUT', value: 'PUT' }] },
      { key: 'path', label: 'Path', type: 'string', required: true, placeholder: '/webhook/my-flow' },
    ],
    defaultData: { method: 'POST', path: '/webhook/' },
  },
  {
    type: 'event_trigger',
    category: 'trigger',
    label: 'Event Trigger',
    description: 'Start workflow when a message bus event occurs',
    icon: 'zap',
    color: '#8B5CF6',
    inputs: [],
    outputs: [{ id: 'out', label: 'Output', type: 'flow' }],
    parameters: [
      { key: 'topic', label: 'Topic', type: 'string', required: true, placeholder: 'system.alerts' },
    ],
    defaultData: { topic: 'system.alerts' },
  },
  {
    type: 'connector_trigger',
    category: 'trigger',
    label: 'Connector Trigger',
    description: 'Start workflow when a connector event fires',
    icon: 'plug',
    color: '#8B5CF6',
    inputs: [],
    outputs: [{ id: 'out', label: 'Output', type: 'flow' }],
    parameters: [
      { key: 'connectorId', label: 'Connector', type: 'string', required: true, placeholder: 'gmail' },
      { key: 'event', label: 'Event', type: 'string', required: true, placeholder: 'new_email' },
    ],
    defaultData: { connectorId: '', event: '' },
  },
]
