import { useCallback, useEffect, useState } from 'react'
import { Bot, Zap, Check, RefreshCw, Info, Server, ChevronRight, ExternalLink, Key, Terminal } from 'lucide-react'
import useLLMConfigStore, { PROVIDER_MODELS } from '../../ai/stores/useLLMConfigStore'
import type { LLMProvider } from '../../ai/types'
import './AISettings.css'

const PROVIDER_LABELS: Record<LLMProvider, string> = {
  anthropic: 'Anthropic',
  openai: 'OpenAI',
  google: 'Google Gemini',
  minimax: 'MiniMax',
  deepseek: 'DeepSeek',
  mistral: 'Mistral',
  groq: 'Groq',
  openrouter: 'OpenRouter',
  xai: 'xAI',
}

const PROVIDER_ENV_VARS: Record<LLMProvider, string> = {
  anthropic: 'ANTHROPIC_API_KEY',
  openai: 'OPENAI_API_KEY',
  google: 'GOOGLE_API_KEY',
  minimax: 'MINIMAX_API_KEY',
  deepseek: 'DEEPSEEK_API_KEY',
  mistral: 'MISTRAL_API_KEY',
  groq: 'GROQ_API_KEY',
  openrouter: 'OPENROUTER_API_KEY',
  xai: 'XAI_API_KEY',
}

const ALL_PROVIDERS: LLMProvider[] = [
  'anthropic', 'openai', 'google', 'minimax', 'deepseek', 'mistral', 'groq', 'openrouter', 'xai',
]

export default function AISettings() {
  const mode = useLLMConfigStore((s) => s.mode)
  const connectionStatus = useLLMConfigStore((s) => s.connectionStatus)
  const provider = useLLMConfigStore((s) => s.provider)
  const model = useLLMConfigStore((s) => s.model)
  const availableProviders = useLLMConfigStore((s) => s.availableProviders)
  const lastCheckedAt = useLLMConfigStore((s) => s.lastCheckedAt)
  const errorMessage = useLLMConfigStore((s) => s.errorMessage)
  const checkConnection = useLLMConfigStore((s) => s.checkConnection)
  const setProvider = useLLMConfigStore((s) => s.setProvider)
  const setModel = useLLMConfigStore((s) => s.setModel)

  const [isTesting, setIsTesting] = useState(false)
  const [expandedProvider, setExpandedProvider] = useState<LLMProvider | null>(null)

  useEffect(() => {
    if (connectionStatus === 'unknown') {
      checkConnection()
    }
  }, [connectionStatus, checkConnection])

  const handleTestConnection = useCallback(async () => {
    setIsTesting(true)
    await checkConnection()
    setIsTesting(false)
  }, [checkConnection])

  const handleProviderChange = useCallback((e: React.ChangeEvent<HTMLSelectElement>) => {
    setProvider(e.target.value as LLMProvider)
  }, [setProvider])

  const handleModelChange = useCallback((e: React.ChangeEvent<HTMLSelectElement>) => {
    setModel(e.target.value)
  }, [setModel])

  const isProviderAvailable = useCallback((p: LLMProvider) => {
    return availableProviders.some((ap) => ap.provider === p && ap.available)
  }, [availableProviders])

  const handleProviderCardClick = useCallback((p: LLMProvider) => {
    setExpandedProvider((prev) => prev === p ? null : p)
  }, [])

  const modelsForProvider = PROVIDER_MODELS[provider] ?? []
  const isLive = mode === 'live'
  const lastChecked = lastCheckedAt
    ? new Date(lastCheckedAt).toLocaleTimeString()
    : null

  return (
    <div className="ai-settings">
      <h1 className="ai-settings__title">AI / Copilot</h1>
      <p className="ai-settings__subtitle">Configure AI providers and model preferences</p>

      {/* Mode Banner */}
      <div className="ai-settings__mode-banner">
        <div className={`ai-settings__mode-icon ai-settings__mode-icon--${isLive ? 'live' : 'demo'}`}>
          {isLive ? <Zap size={20} /> : <Bot size={20} />}
        </div>
        <div className="ai-settings__mode-info">
          <p className="ai-settings__mode-label">
            {isLive ? 'Live Mode' : 'Demo Mode'}
          </p>
          <p className="ai-settings__mode-desc">
            {isLive
              ? 'Connected to AI providers. Responses are generated by real models.'
              : 'No providers connected. All AI features use simulated responses.'}
          </p>
        </div>
        <span className={`ai-settings__mode-badge ai-settings__mode-badge--${isLive ? 'live' : 'demo'}`}>
          {isLive ? 'Live' : 'Demo'}
        </span>
      </div>

      {/* Provider Status Grid */}
      <div className="ai-settings__section">
        <h3 className="ai-settings__section-title">Provider Status</h3>
        <div className="ai-settings__provider-grid">
          {ALL_PROVIDERS.map((p) => {
            const available = isProviderAvailable(p)
            const modelCount = PROVIDER_MODELS[p].length
            const isExpanded = expandedProvider === p
            return (
              <div key={p} className={`ai-settings__provider-card ${isExpanded ? 'ai-settings__provider-card--expanded' : ''}`}>
                <button
                  className="ai-settings__provider-card-btn"
                  onClick={() => handleProviderCardClick(p)}
                  aria-expanded={isExpanded}
                >
                  <div className="ai-settings__provider-icon">
                    <Server size={16} />
                  </div>
                  <div className="ai-settings__provider-info">
                    <p className="ai-settings__provider-name">{PROVIDER_LABELS[p]}</p>
                    <p className="ai-settings__provider-models">
                      {modelCount} model{modelCount !== 1 ? 's' : ''}
                    </p>
                  </div>
                  <span className={`ai-settings__provider-badge ai-settings__provider-badge--${available ? 'connected' : 'not-configured'}`}>
                    {available ? (
                      <><Check size={10} /> Connected</>
                    ) : (
                      <><ChevronRight size={12} className={`ai-settings__provider-chevron ${isExpanded ? 'ai-settings__provider-chevron--open' : ''}`} /> Configure</>
                    )}
                  </span>
                </button>
                {isExpanded && !available && (
                  <div className="ai-settings__provider-setup">
                    <div className="ai-settings__setup-step">
                      <div className="ai-settings__setup-step-num">1</div>
                      <div className="ai-settings__setup-step-content">
                        <p className="ai-settings__setup-step-title">Get API key</p>
                        <p className="ai-settings__setup-step-desc">
                          Visit {PROVIDER_LABELS[p]} dashboard to create an API key
                        </p>
                        <button className="ai-settings__setup-link" type="button">
                          <ExternalLink size={12} /> Open {PROVIDER_LABELS[p]}
                        </button>
                      </div>
                    </div>
                    <div className="ai-settings__setup-step">
                      <div className="ai-settings__setup-step-num">2</div>
                      <div className="ai-settings__setup-step-content">
                        <p className="ai-settings__setup-step-title">Add to environment</p>
                        <code className="ai-settings__setup-code">
                          <Key size={12} /> {PROVIDER_ENV_VARS[p]}=sk-...
                        </code>
                      </div>
                    </div>
                    <div className="ai-settings__setup-step">
                      <div className="ai-settings__setup-step-num">3</div>
                      <div className="ai-settings__setup-step-content">
                        <p className="ai-settings__setup-step-title">Test connection</p>
                        <p className="ai-settings__setup-step-desc">
                          <Terminal size={12} /> Restart the server and test from the Connection section below
                        </p>
                      </div>
                    </div>
                  </div>
                )}
                {isExpanded && available && (
                  <div className="ai-settings__provider-setup">
                    <div className="ai-settings__setup-connected">
                      <Check size={16} />
                      <div>
                        <p className="ai-settings__setup-step-title">Connected</p>
                        <p className="ai-settings__setup-step-desc">
                          {modelCount} model{modelCount !== 1 ? 's' : ''} available. Select this provider in Active Configuration below.
                        </p>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            )
          })}
        </div>
      </div>

      {/* Active Configuration */}
      <div className="ai-settings__section">
        <h3 className="ai-settings__section-title">Active Configuration</h3>
        <div className="ai-settings__config-row">
          <div className="ai-settings__config-field">
            <label className="ai-settings__config-label" htmlFor="ai-provider-select">
              Provider
            </label>
            <select
              id="ai-provider-select"
              className="ai-settings__select"
              value={provider}
              onChange={handleProviderChange}
              aria-label="AI Provider"
            >
              {ALL_PROVIDERS.map((p) => (
                <option key={p} value={p}>{PROVIDER_LABELS[p]}</option>
              ))}
            </select>
          </div>
          <div className="ai-settings__config-field">
            <label className="ai-settings__config-label" htmlFor="ai-model-select">
              Model
            </label>
            <select
              id="ai-model-select"
              className="ai-settings__select"
              value={model}
              onChange={handleModelChange}
              aria-label="AI Model"
            >
              {modelsForProvider.map((m) => (
                <option key={m.id} value={m.id}>
                  {m.name} ({(m.contextWindow / 1000).toFixed(0)}K)
                </option>
              ))}
            </select>
          </div>
        </div>
      </div>

      {/* Test Connection */}
      <div className="ai-settings__section">
        <h3 className="ai-settings__section-title">Connection</h3>
        <div className="ai-settings__test-row">
          <button
            className={`btn--secondary ai-settings__test-btn ${isTesting ? 'ai-settings__test-btn--loading' : ''}`}
            onClick={handleTestConnection}
            disabled={isTesting}
            aria-label="Test connection"
          >
            <RefreshCw size={14} className={isTesting ? 'ai-settings__spin-icon' : ''} />
            {isTesting ? 'Testing...' : 'Test Connection'}
          </button>
          {lastChecked && (
            <span className={`ai-settings__test-status ${
              connectionStatus === 'connected' ? 'ai-settings__test-status--success' :
              connectionStatus === 'error' || connectionStatus === 'disconnected' ? 'ai-settings__test-status--error' : ''
            }`}>
              {connectionStatus === 'connected' && 'Connected'}
              {connectionStatus === 'disconnected' && 'Disconnected'}
              {connectionStatus === 'error' && (errorMessage ?? 'Connection error')}
              {connectionStatus !== 'unknown' && ` \u00B7 Last checked ${lastChecked}`}
            </span>
          )}
        </div>
      </div>

      {/* Help Text */}
      <div className="ai-settings__help">
        <Info size={16} className="ai-settings__help-icon" />
        <p className="ai-settings__help-text">
          Add API keys to your server&apos;s <code>.env</code> file to enable live AI responses.
          Without API keys, all AI features use simulated responses.
          Supported variables: <code>ANTHROPIC_API_KEY</code>, <code>OPENAI_API_KEY</code>,{' '}
          <code>GOOGLE_API_KEY</code>, <code>DEEPSEEK_API_KEY</code>, <code>MISTRAL_API_KEY</code>,{' '}
          <code>GROQ_API_KEY</code>.
        </p>
      </div>
    </div>
  )
}
