import type { ChannelDefinition } from '../types'
import { ChannelType, ChannelAuthType, ChannelCapability } from '../types'

export const CHANNEL_DEFINITIONS: ChannelDefinition[] = [
  {
    type: ChannelType.WhatsApp,
    name: 'WhatsApp',
    icon: 'message-circle',
    description: 'Connect to WhatsApp Business API for messaging with customers and contacts.',
    authType: ChannelAuthType.ApiKey,
    configFields: [
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, placeholder: 'Enter your WhatsApp Business API key' },
      { key: 'phoneNumberId', label: 'Phone Number ID', type: 'text', required: true, placeholder: 'e.g. 1234567890' },
      { key: 'businessAccountId', label: 'Business Account ID', type: 'text', required: true, placeholder: 'e.g. 9876543210' },
      { key: 'webhookUrl', label: 'Webhook URL', type: 'url', required: false, placeholder: 'https://your-domain.com/webhook/whatsapp' },
    ],
    capabilities: [ChannelCapability.Text, ChannelCapability.Media, ChannelCapability.ReadReceipts],
  },
  {
    type: ChannelType.Telegram,
    name: 'Telegram',
    icon: 'send',
    description: 'Connect a Telegram bot to receive and send messages via the Telegram Bot API.',
    authType: ChannelAuthType.BotToken,
    configFields: [
      { key: 'botToken', label: 'Bot Token', type: 'password', required: true, placeholder: 'e.g. 123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11' },
      { key: 'webhookUrl', label: 'Webhook URL', type: 'url', required: false, placeholder: 'https://your-domain.com/webhook/telegram' },
      { key: 'allowGroups', label: 'Allow Group Messages', type: 'checkbox', required: false },
    ],
    capabilities: [ChannelCapability.Text, ChannelCapability.Media, ChannelCapability.Reactions, ChannelCapability.Threads],
  },
  {
    type: ChannelType.Slack,
    name: 'Slack',
    icon: 'hash',
    description: 'Integrate with Slack workspaces to send and receive messages in channels and DMs.',
    authType: ChannelAuthType.OAuth2,
    configFields: [
      { key: 'clientId', label: 'Client ID', type: 'text', required: true, placeholder: 'Your Slack app Client ID' },
      { key: 'clientSecret', label: 'Client Secret', type: 'password', required: true, placeholder: 'Your Slack app Client Secret' },
      { key: 'signingSecret', label: 'Signing Secret', type: 'password', required: true, placeholder: 'Your Slack app Signing Secret' },
      { key: 'defaultChannel', label: 'Default Channel', type: 'text', required: false, placeholder: '#general' },
    ],
    capabilities: [ChannelCapability.Text, ChannelCapability.Media, ChannelCapability.Reactions, ChannelCapability.Threads],
  },
  {
    type: ChannelType.Discord,
    name: 'Discord',
    icon: 'gamepad-2',
    description: 'Connect a Discord bot to interact with users across servers and channels.',
    authType: ChannelAuthType.BotToken,
    configFields: [
      { key: 'botToken', label: 'Bot Token', type: 'password', required: true, placeholder: 'Your Discord bot token' },
      { key: 'applicationId', label: 'Application ID', type: 'text', required: true, placeholder: 'Your Discord application ID' },
      { key: 'guildId', label: 'Server ID (optional)', type: 'text', required: false, placeholder: 'Restrict to a specific server' },
    ],
    capabilities: [ChannelCapability.Text, ChannelCapability.Media, ChannelCapability.Reactions, ChannelCapability.Threads, ChannelCapability.Voice],
  },
  {
    type: ChannelType.Teams,
    name: 'Microsoft Teams',
    icon: 'users',
    description: 'Connect to Microsoft Teams for enterprise messaging and collaboration.',
    authType: ChannelAuthType.OAuth2,
    configFields: [
      { key: 'tenantId', label: 'Tenant ID', type: 'text', required: true, placeholder: 'Azure AD Tenant ID' },
      { key: 'clientId', label: 'Client ID', type: 'text', required: true, placeholder: 'Azure App Registration Client ID' },
      { key: 'clientSecret', label: 'Client Secret', type: 'password', required: true, placeholder: 'Azure App Registration Client Secret' },
    ],
    capabilities: [ChannelCapability.Text, ChannelCapability.Media, ChannelCapability.Reactions, ChannelCapability.Threads],
  },
  {
    type: ChannelType.Signal,
    name: 'Signal',
    icon: 'shield',
    description: 'Connect to Signal via the Signal CLI REST API for end-to-end encrypted messaging.',
    authType: ChannelAuthType.ApiKey,
    configFields: [
      { key: 'apiUrl', label: 'Signal CLI API URL', type: 'url', required: true, placeholder: 'http://localhost:8080' },
      { key: 'phoneNumber', label: 'Registered Phone Number', type: 'text', required: true, placeholder: '+1234567890' },
    ],
    capabilities: [ChannelCapability.Text, ChannelCapability.Media, ChannelCapability.ReadReceipts],
  },
  {
    type: ChannelType.Matrix,
    name: 'Matrix',
    icon: 'grid-3x3',
    description: 'Connect to the decentralized Matrix protocol for interoperable messaging.',
    authType: ChannelAuthType.ApiKey,
    configFields: [
      { key: 'homeserverUrl', label: 'Homeserver URL', type: 'url', required: true, placeholder: 'https://matrix.org' },
      { key: 'accessToken', label: 'Access Token', type: 'password', required: true, placeholder: 'Your Matrix access token' },
      { key: 'userId', label: 'User ID', type: 'text', required: true, placeholder: '@bot:matrix.org' },
    ],
    capabilities: [ChannelCapability.Text, ChannelCapability.Media, ChannelCapability.Reactions, ChannelCapability.Threads],
  },
  {
    type: ChannelType.Sms,
    name: 'SMS',
    icon: 'smartphone',
    description: 'Send and receive SMS messages via Twilio or compatible SMS gateway.',
    authType: ChannelAuthType.ApiKey,
    configFields: [
      { key: 'accountSid', label: 'Account SID', type: 'text', required: true, placeholder: 'Twilio Account SID' },
      { key: 'authToken', label: 'Auth Token', type: 'password', required: true, placeholder: 'Twilio Auth Token' },
      { key: 'phoneNumber', label: 'Phone Number', type: 'text', required: true, placeholder: '+1234567890' },
    ],
    capabilities: [ChannelCapability.Text],
  },
  {
    type: ChannelType.Email,
    name: 'Email',
    icon: 'mail',
    description: 'Send and receive email messages via SMTP/IMAP or API-based email services.',
    authType: ChannelAuthType.Smtp,
    configFields: [
      { key: 'smtpHost', label: 'SMTP Host', type: 'text', required: true, placeholder: 'smtp.gmail.com' },
      { key: 'smtpPort', label: 'SMTP Port', type: 'text', required: true, placeholder: '587' },
      { key: 'username', label: 'Username', type: 'text', required: true, placeholder: 'you@example.com' },
      { key: 'password', label: 'Password', type: 'password', required: true, placeholder: 'App-specific password' },
      { key: 'imapHost', label: 'IMAP Host', type: 'text', required: false, placeholder: 'imap.gmail.com' },
      { key: 'useTls', label: 'Use TLS', type: 'checkbox', required: false },
    ],
    capabilities: [ChannelCapability.Text, ChannelCapability.Media, ChannelCapability.Threads],
  },
  {
    type: ChannelType.Irc,
    name: 'IRC',
    icon: 'terminal',
    description: 'Connect to IRC networks and channels for real-time text communication.',
    authType: ChannelAuthType.None,
    configFields: [
      { key: 'server', label: 'Server', type: 'text', required: true, placeholder: 'irc.libera.chat' },
      { key: 'port', label: 'Port', type: 'text', required: true, placeholder: '6697' },
      { key: 'nickname', label: 'Nickname', type: 'text', required: true, placeholder: 'orchestree-bot' },
      { key: 'channels', label: 'Channels (comma-separated)', type: 'text', required: true, placeholder: '#general, #support' },
      { key: 'password', label: 'Server Password', type: 'password', required: false },
      { key: 'useSsl', label: 'Use SSL', type: 'checkbox', required: false },
    ],
    capabilities: [ChannelCapability.Text],
  },
  {
    type: ChannelType.WebChat,
    name: 'Web Chat',
    icon: 'message-square',
    description: 'Embed a live chat widget on your website for direct visitor communication.',
    authType: ChannelAuthType.ApiKey,
    configFields: [
      { key: 'siteId', label: 'Site ID', type: 'text', required: true, placeholder: 'Your website identifier' },
      { key: 'apiKey', label: 'Widget API Key', type: 'password', required: true, placeholder: 'Auto-generated on save' },
      { key: 'allowedOrigins', label: 'Allowed Origins', type: 'text', required: false, placeholder: 'https://yourdomain.com' },
      { key: 'showAvatar', label: 'Show Agent Avatar', type: 'checkbox', required: false },
    ],
    capabilities: [ChannelCapability.Text, ChannelCapability.Media, ChannelCapability.ReadReceipts],
  },
  {
    type: ChannelType.Webhook,
    name: 'Webhook',
    icon: 'webhook',
    description: 'Send and receive messages via HTTP webhooks for custom integrations.',
    authType: ChannelAuthType.Webhook,
    configFields: [
      { key: 'inboundUrl', label: 'Inbound Webhook URL', type: 'url', required: false, placeholder: 'Auto-generated on save' },
      { key: 'outboundUrl', label: 'Outbound Webhook URL', type: 'url', required: true, placeholder: 'https://your-service.com/webhook' },
      { key: 'secret', label: 'Webhook Secret', type: 'password', required: false, placeholder: 'Shared secret for signature verification' },
      { key: 'verifySignature', label: 'Verify Signatures', type: 'checkbox', required: false },
    ],
    capabilities: [ChannelCapability.Text, ChannelCapability.Media],
  },
  {
    type: ChannelType.Custom,
    name: 'Custom Channel',
    icon: 'puzzle',
    description: 'Build a custom channel integration using the Orchestree Gateway SDK.',
    authType: ChannelAuthType.ApiKey,
    configFields: [
      { key: 'channelName', label: 'Channel Name', type: 'text', required: true, placeholder: 'My Custom Channel' },
      { key: 'apiKey', label: 'API Key', type: 'password', required: true, placeholder: 'Your custom integration API key' },
      { key: 'endpointUrl', label: 'Endpoint URL', type: 'url', required: true, placeholder: 'https://your-service.com/api' },
      { key: 'customHeaders', label: 'Custom Headers (JSON)', type: 'text', required: false, placeholder: '{"X-Custom": "value"}' },
    ],
    capabilities: [ChannelCapability.Text],
  },
]
