import { FieldType, type Template } from '../../../types'

export const SAMPLE_TEMPLATES: Template[] = [
  {
    id: 'tmpl-employment',
    name: 'Employment Agreement',
    description: 'Standard employment agreement with signature, date, full name, and initials.',
    documentName: 'Employment Agreement',
    recipientRoles: [
      { id: 'role-employee', label: 'Employee', order: 1 },
      { id: 'role-employer', label: 'Employer', order: 2 },
    ],
    fields: [
      {
        id: 'ef1',
        type: FieldType.Signature,
        recipientId: 'role-employee',
        page: 1,
        x: 100,
        y: 700,
        width: 200,
        height: 60,
        required: true,
        label: 'Employee Signature',
        placeholder: 'Sign here',
      },
      {
        id: 'ef2',
        type: FieldType.DateSigned,
        recipientId: 'role-employee',
        page: 1,
        x: 350,
        y: 710,
        width: 150,
        height: 30,
        required: true,
        label: 'Date',
      },
      {
        id: 'ef3',
        type: FieldType.Text,
        recipientId: 'role-employee',
        page: 1,
        x: 100,
        y: 650,
        width: 200,
        height: 30,
        required: true,
        label: 'Full Name',
        placeholder: 'Enter your full name',
      },
      {
        id: 'ef4',
        type: FieldType.Initial,
        recipientId: 'role-employee',
        page: 1,
        x: 500,
        y: 710,
        width: 80,
        height: 40,
        required: true,
        label: 'Initials',
        placeholder: 'Initials',
      },
    ],
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'tmpl-nda',
    name: 'Non-Disclosure Agreement',
    description: 'Mutual NDA with signature, date, and acceptance checkbox.',
    documentName: 'Non-Disclosure Agreement',
    recipientRoles: [
      { id: 'role-signer1', label: 'Signer 1', order: 1 },
    ],
    fields: [
      {
        id: 'nf1',
        type: FieldType.Signature,
        recipientId: 'role-signer1',
        page: 1,
        x: 100,
        y: 750,
        width: 200,
        height: 60,
        required: true,
        label: 'Signature',
        placeholder: 'Sign here',
      },
      {
        id: 'nf2',
        type: FieldType.DateSigned,
        recipientId: 'role-signer1',
        page: 1,
        x: 350,
        y: 760,
        width: 150,
        height: 30,
        required: true,
        label: 'Date Signed',
      },
      {
        id: 'nf3',
        type: FieldType.Checkbox,
        recipientId: 'role-signer1',
        page: 1,
        x: 100,
        y: 700,
        width: 24,
        height: 24,
        required: true,
        label: 'Accept Terms',
      },
    ],
    createdAt: '2026-01-20T14:30:00Z',
    updatedAt: '2026-01-20T14:30:00Z',
  },
  {
    id: 'tmpl-sales',
    name: 'Sales Contract',
    description: 'Two-party sales contract with buyer and seller signatures, amount, and payment terms.',
    documentName: 'Sales Contract',
    recipientRoles: [
      { id: 'role-buyer', label: 'Buyer', order: 1 },
      { id: 'role-seller', label: 'Seller', order: 2 },
    ],
    fields: [
      {
        id: 'sf1',
        type: FieldType.Signature,
        recipientId: 'role-buyer',
        page: 1,
        x: 100,
        y: 700,
        width: 200,
        height: 60,
        required: true,
        label: 'Buyer Signature',
        placeholder: 'Sign here',
      },
      {
        id: 'sf2',
        type: FieldType.Signature,
        recipientId: 'role-seller',
        page: 1,
        x: 400,
        y: 700,
        width: 200,
        height: 60,
        required: true,
        label: 'Seller Signature',
        placeholder: 'Sign here',
      },
      {
        id: 'sf3',
        type: FieldType.DateSigned,
        recipientId: 'role-buyer',
        page: 1,
        x: 100,
        y: 770,
        width: 150,
        height: 30,
        required: true,
        label: 'Buyer Date',
      },
      {
        id: 'sf4',
        type: FieldType.DateSigned,
        recipientId: 'role-seller',
        page: 1,
        x: 400,
        y: 770,
        width: 150,
        height: 30,
        required: true,
        label: 'Seller Date',
      },
      {
        id: 'sf5',
        type: FieldType.Text,
        recipientId: 'role-buyer',
        page: 1,
        x: 100,
        y: 600,
        width: 200,
        height: 30,
        required: true,
        label: 'Amount',
        placeholder: 'Enter sale amount',
      },
      {
        id: 'sf6',
        type: FieldType.Dropdown,
        recipientId: 'role-buyer',
        page: 1,
        x: 100,
        y: 640,
        width: 200,
        height: 30,
        required: true,
        label: 'Payment Terms',
        options: ['Net 30', 'Net 60', 'Net 90', 'Upon Receipt'],
      },
    ],
    createdAt: '2026-02-01T09:00:00Z',
    updatedAt: '2026-02-01T09:00:00Z',
  },
]
