import type { Project, Issue, Cycle, Member, Label } from '../types'
import { IssueStatus, IssuePriority, CycleStatus, ViewType } from '../types'

export function createSampleMembers(): Member[] {
  return [
    { id: 'member-1', name: 'Alex Chen', email: 'alex@signof.com', avatarUrl: '' },
    { id: 'member-2', name: 'Sarah Kim', email: 'sarah@signof.com', avatarUrl: '' },
    { id: 'member-3', name: 'Marcus Johnson', email: 'marcus@signof.com', avatarUrl: '' },
    { id: 'member-4', name: 'Priya Patel', email: 'priya@signof.com', avatarUrl: '' },
    { id: 'member-5', name: 'Jordan Lee', email: 'jordan@signof.com', avatarUrl: '' },
  ]
}

const SO_LABELS: Label[] = [
  { id: 'lbl-bug', name: 'Bug', color: '#EF4444' },
  { id: 'lbl-feature', name: 'Feature', color: '#8B5CF6' },
  { id: 'lbl-improvement', name: 'Improvement', color: '#3B82F6' },
  { id: 'lbl-docs', name: 'Documentation', color: '#14B8A6' },
]

const MKT_LABELS: Label[] = [
  { id: 'lbl-content', name: 'Content', color: '#F59E0B' },
  { id: 'lbl-design', name: 'Design', color: '#EC4899' },
  { id: 'lbl-seo', name: 'SEO', color: '#22C55E' },
]

export function createSampleProjects(): Record<string, Project> {
  return {
    'proj-signof': {
      id: 'proj-signof',
      name: 'SignOf Platform',
      description: 'Core platform development for the SignOf everything-app. Includes document signing, workspace, and project management.',
      prefix: 'SO',
      color: '#4F46E5',
      memberIds: ['member-1', 'member-2', 'member-3', 'member-4', 'member-5'],
      labels: SO_LABELS,
      nextIssueNumber: 9,
      currentView: ViewType.Board,
      createdAt: '2026-01-15T10:00:00Z',
      updatedAt: '2026-02-08T14:30:00Z',
    },
    'proj-marketing': {
      id: 'proj-marketing',
      name: 'Marketing Website',
      description: 'Public-facing marketing site with landing pages, pricing, and blog.',
      prefix: 'MKT',
      color: '#059669',
      memberIds: ['member-2', 'member-4', 'member-5'],
      labels: MKT_LABELS,
      nextIssueNumber: 5,
      currentView: ViewType.List,
      createdAt: '2026-01-20T09:00:00Z',
      updatedAt: '2026-02-07T11:00:00Z',
    },
  }
}

export function createSampleIssues(): Record<string, Issue> {
  return {
    'issue-so-1': {
      id: 'issue-so-1',
      projectId: 'proj-signof',
      identifier: 'SO-1',
      title: 'Implement multi-signer document flow',
      description: 'Support sending documents to multiple signers with sequential or parallel signing order.',
      status: IssueStatus.Done,
      priority: IssuePriority.High,
      assigneeId: 'member-1',
      labelIds: ['lbl-feature'],
      estimate: 8,
      dueDate: '2026-02-01',
      parentIssueId: null,
      cycleId: 'cycle-so-1',
      createdAt: '2026-01-16T10:00:00Z',
      updatedAt: '2026-01-30T16:00:00Z',
    },
    'issue-so-2': {
      id: 'issue-so-2',
      projectId: 'proj-signof',
      identifier: 'SO-2',
      title: 'Add audit trail to document signatures',
      description: 'Track every action (view, sign, decline) with timestamps and IP addresses.',
      status: IssueStatus.Done,
      priority: IssuePriority.Medium,
      assigneeId: 'member-3',
      labelIds: ['lbl-feature', 'lbl-improvement'],
      estimate: 5,
      dueDate: null,
      parentIssueId: null,
      cycleId: 'cycle-so-1',
      createdAt: '2026-01-17T11:00:00Z',
      updatedAt: '2026-02-02T09:00:00Z',
    },
    'issue-so-3': {
      id: 'issue-so-3',
      projectId: 'proj-signof',
      identifier: 'SO-3',
      title: 'Fix signature pad not rendering on Safari iOS',
      description: 'Canvas element fails to initialize on Safari mobile. Need to check DPR handling.',
      status: IssueStatus.InProgress,
      priority: IssuePriority.Urgent,
      assigneeId: 'member-2',
      labelIds: ['lbl-bug'],
      estimate: 3,
      dueDate: '2026-02-10',
      parentIssueId: null,
      cycleId: 'cycle-so-1',
      createdAt: '2026-02-03T14:00:00Z',
      updatedAt: '2026-02-08T10:00:00Z',
    },
    'issue-so-4': {
      id: 'issue-so-4',
      projectId: 'proj-signof',
      identifier: 'SO-4',
      title: 'Build workspace block editor',
      description: 'Implement Notion-style block editor with slash commands, inline formatting, and page hierarchy.',
      status: IssueStatus.InReview,
      priority: IssuePriority.High,
      assigneeId: 'member-1',
      labelIds: ['lbl-feature'],
      estimate: 13,
      dueDate: '2026-02-15',
      parentIssueId: null,
      cycleId: 'cycle-so-1',
      createdAt: '2026-01-20T09:00:00Z',
      updatedAt: '2026-02-07T17:00:00Z',
    },
    'issue-so-5': {
      id: 'issue-so-5',
      projectId: 'proj-signof',
      identifier: 'SO-5',
      title: 'Add dark mode toggle to settings',
      description: 'User-facing toggle for light/dark/system theme preference.',
      status: IssueStatus.Todo,
      priority: IssuePriority.Low,
      assigneeId: 'member-4',
      labelIds: ['lbl-improvement'],
      estimate: 2,
      dueDate: null,
      parentIssueId: null,
      cycleId: null,
      createdAt: '2026-02-01T08:00:00Z',
      updatedAt: '2026-02-01T08:00:00Z',
    },
    'issue-so-6': {
      id: 'issue-so-6',
      projectId: 'proj-signof',
      identifier: 'SO-6',
      title: 'Write API documentation for signing endpoints',
      description: 'Document all REST endpoints for the signing module with examples.',
      status: IssueStatus.Backlog,
      priority: IssuePriority.None,
      assigneeId: null,
      labelIds: ['lbl-docs'],
      estimate: 3,
      dueDate: null,
      parentIssueId: null,
      cycleId: null,
      createdAt: '2026-02-04T10:00:00Z',
      updatedAt: '2026-02-04T10:00:00Z',
    },
    'issue-so-7': {
      id: 'issue-so-7',
      projectId: 'proj-signof',
      identifier: 'SO-7',
      title: 'Optimize document list rendering for large datasets',
      description: 'Virtual scrolling or pagination for when users have 100+ documents.',
      status: IssueStatus.Backlog,
      priority: IssuePriority.Medium,
      assigneeId: null,
      labelIds: ['lbl-improvement'],
      estimate: 5,
      dueDate: null,
      parentIssueId: null,
      cycleId: null,
      createdAt: '2026-02-05T11:00:00Z',
      updatedAt: '2026-02-05T11:00:00Z',
    },
    'issue-so-8': {
      id: 'issue-so-8',
      projectId: 'proj-signof',
      identifier: 'SO-8',
      title: 'Add email notifications for signing requests',
      description: 'Send email when a document is sent for signature and when signing is complete.',
      status: IssueStatus.Todo,
      priority: IssuePriority.High,
      assigneeId: 'member-5',
      labelIds: ['lbl-feature'],
      estimate: 5,
      dueDate: '2026-02-20',
      parentIssueId: null,
      cycleId: 'cycle-so-1',
      createdAt: '2026-02-06T09:00:00Z',
      updatedAt: '2026-02-06T09:00:00Z',
    },
    'issue-mkt-1': {
      id: 'issue-mkt-1',
      projectId: 'proj-marketing',
      identifier: 'MKT-1',
      title: 'Design hero section for landing page',
      description: 'Create an engaging hero section with product screenshots and CTA.',
      status: IssueStatus.InProgress,
      priority: IssuePriority.High,
      assigneeId: 'member-4',
      labelIds: ['lbl-design'],
      estimate: 5,
      dueDate: '2026-02-12',
      parentIssueId: null,
      cycleId: 'cycle-mkt-1',
      createdAt: '2026-01-22T10:00:00Z',
      updatedAt: '2026-02-07T15:00:00Z',
    },
    'issue-mkt-2': {
      id: 'issue-mkt-2',
      projectId: 'proj-marketing',
      identifier: 'MKT-2',
      title: 'Write comparison page copy (vs DocuSign, vs Notion)',
      description: 'Feature-by-feature comparison with competitor products.',
      status: IssueStatus.Todo,
      priority: IssuePriority.Medium,
      assigneeId: 'member-5',
      labelIds: ['lbl-content', 'lbl-seo'],
      estimate: 3,
      dueDate: null,
      parentIssueId: null,
      cycleId: 'cycle-mkt-1',
      createdAt: '2026-01-25T09:00:00Z',
      updatedAt: '2026-01-25T09:00:00Z',
    },
    'issue-mkt-3': {
      id: 'issue-mkt-3',
      projectId: 'proj-marketing',
      identifier: 'MKT-3',
      title: 'Set up blog with MDX and SEO meta tags',
      description: 'Blog infrastructure with syntax highlighting, social cards, and sitemap.',
      status: IssueStatus.Backlog,
      priority: IssuePriority.Low,
      assigneeId: null,
      labelIds: ['lbl-seo'],
      estimate: 8,
      dueDate: null,
      parentIssueId: null,
      cycleId: null,
      createdAt: '2026-02-01T10:00:00Z',
      updatedAt: '2026-02-01T10:00:00Z',
    },
    'issue-mkt-4': {
      id: 'issue-mkt-4',
      projectId: 'proj-marketing',
      identifier: 'MKT-4',
      title: 'Create pricing page with tier comparison',
      description: 'Three-tier pricing with feature matrix and FAQ section.',
      status: IssueStatus.Todo,
      priority: IssuePriority.Medium,
      assigneeId: 'member-2',
      labelIds: ['lbl-design', 'lbl-content'],
      estimate: 5,
      dueDate: '2026-02-18',
      parentIssueId: null,
      cycleId: 'cycle-mkt-1',
      createdAt: '2026-02-02T11:00:00Z',
      updatedAt: '2026-02-02T11:00:00Z',
    },
  }
}

export function createSampleCycles(): Record<string, Cycle> {
  return {
    'cycle-so-1': {
      id: 'cycle-so-1',
      projectId: 'proj-signof',
      name: 'Sprint 3',
      startDate: '2026-02-03',
      endDate: '2026-02-14',
      status: CycleStatus.Active,
    },
    'cycle-mkt-1': {
      id: 'cycle-mkt-1',
      projectId: 'proj-marketing',
      name: 'Launch Prep',
      startDate: '2026-02-10',
      endDate: '2026-02-21',
      status: CycleStatus.Upcoming,
    },
  }
}
