import { AgentDomain, AgentCategory, AgentType, CostTier, LatencyProfile } from '../../types'
import type { AgentCapabilityManifest } from '../../types'

export const AGENTS: AgentCapabilityManifest[] = [
  {
    agentTypeId: 'accounting.invoice-reconciliation',
    displayName: 'Invoice Reconciliation Agent',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Finance,
    description: 'Matches invoices against purchase orders, delivery receipts, and bank transactions to identify discrepancies and reconcile accounts payable.',
    capabilities: {
      tools: ['create_invoice', 'get_invoice_summary', 'get_account_balance', 'analyze_expenses'],
      connectors: ['quickbooks', 'xero', 'bank-feed'],
      inputTypes: ['invoice', 'purchase-order', 'bank-statement'],
      outputTypes: ['reconciliation-report', 'discrepancy-list'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['write-off-over-500'],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You are a meticulous accounts reconciliation specialist. Cross-reference every line item and flag any variance above 1%.',
      specialInstructions: ['Always match by PO number first, then by amount', 'Flag duplicate invoice numbers'],
    },
    icon: 'FileCheck',
    color: '#059669',
  },
  {
    agentTypeId: 'accounting.expense-categorizer',
    displayName: 'Expense Categorizer Agent',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Automatically categorizes expenses by GL code, department, and tax deductibility using merchant data and transaction descriptions.',
    capabilities: {
      tools: ['create_expense', 'analyze_expenses', 'get_account_balance'],
      connectors: ['bank-feed', 'receipt-scanner'],
      inputTypes: ['transaction', 'receipt', 'expense-report'],
      outputTypes: ['categorized-expense', 'category-suggestion'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You are an expense classification expert. Map every transaction to the correct GL account and flag tax-deductible items.',
      specialInstructions: ['Use merchant category codes as primary signal', 'Default to asking when confidence is below 80%'],
    },
    icon: 'Tags',
    color: '#8B5CF6',
  },
  {
    agentTypeId: 'accounting.cash-flow-forecaster',
    displayName: 'Cash Flow Forecaster',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Projects future cash inflows and outflows based on historical patterns, receivables aging, and scheduled payments to predict liquidity positions.',
    capabilities: {
      tools: ['review_cash_flow', 'get_account_balance', 'get_invoice_summary', 'analyze_expenses'],
      connectors: ['bank-feed', 'erp'],
      inputTypes: ['cash-flow-statement', 'receivables-aging', 'payables-schedule'],
      outputTypes: ['cash-flow-forecast', 'liquidity-alert'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 80000,
      maxCostUsdBudget: 3.0,
    },
    persona: {
      systemPromptAddition: 'You are a treasury analyst specializing in cash flow modeling. Provide 30/60/90-day projections with confidence intervals.',
      specialInstructions: ['Weight recent 90 days more heavily', 'Factor in seasonality from prior year'],
    },
    icon: 'TrendingUp',
    color: '#0EA5E9',
  },
  {
    agentTypeId: 'accounting.ap-manager',
    displayName: 'Accounts Payable Manager',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Finance,
    description: 'Manages the full accounts payable lifecycle from invoice receipt through approval routing, payment scheduling, and vendor communication.',
    capabilities: {
      tools: ['create_invoice', 'get_invoice_summary', 'analyze_expenses', 'get_account_balance'],
      connectors: ['email', 'erp', 'bank-feed'],
      inputTypes: ['vendor-invoice', 'approval-request', 'payment-schedule'],
      outputTypes: ['payment-batch', 'approval-routing', 'vendor-statement'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['payment-over-10000', 'new-vendor-setup'],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You are an AP specialist. Prioritize early-payment discounts, enforce approval policies, and maintain clean vendor records.',
      specialInstructions: ['Check for duplicate payments before processing', 'Flag invoices without matching PO'],
    },
    icon: 'Send',
    color: '#DC2626',
  },
  {
    agentTypeId: 'accounting.ar-manager',
    displayName: 'Accounts Receivable Manager',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Finance,
    description: 'Tracks outstanding receivables, sends payment reminders, manages collections workflows, and monitors customer credit risk.',
    capabilities: {
      tools: ['create_invoice', 'get_invoice_summary', 'get_account_balance', 'review_cash_flow'],
      connectors: ['email', 'crm', 'bank-feed'],
      inputTypes: ['customer-invoice', 'payment-receipt', 'aging-report'],
      outputTypes: ['collection-action', 'payment-reminder', 'aging-summary'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['write-off-bad-debt', 'credit-limit-change'],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You are an AR specialist. Balance firm collection practices with customer relationship preservation. Escalate aged items proactively.',
      specialInstructions: ['Escalate invoices over 90 days to management', 'Track DSO trends weekly'],
    },
    icon: 'Inbox',
    color: '#F59E0B',
  },
  {
    agentTypeId: 'accounting.payroll-validator',
    displayName: 'Payroll Validation Agent',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Compliance,
    description: 'Validates payroll calculations including gross pay, deductions, tax withholdings, and benefits contributions before each pay run.',
    capabilities: {
      tools: ['get_payroll_summary', 'analyze_expenses', 'get_account_balance'],
      connectors: ['payroll-system', 'hr-system'],
      inputTypes: ['payroll-register', 'timesheet', 'benefit-enrollment'],
      outputTypes: ['validation-report', 'payroll-discrepancy', 'compliance-check'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['payroll-adjustment'],
      maxTokenBudget: 60000,
      maxCostUsdBudget: 2.5,
    },
    persona: {
      systemPromptAddition: 'You are a payroll compliance specialist. Verify every calculation against tax tables and employment agreements. Zero tolerance for errors.',
      specialInstructions: ['Cross-check tax withholding against current brackets', 'Verify overtime calculations for non-exempt employees'],
    },
    icon: 'UserCheck',
    color: '#10B981',
  },
  {
    agentTypeId: 'accounting.budget-analyst',
    displayName: 'Budget Analysis Agent',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Compares actual spending against budgets, identifies variances, and provides department-level spending insights with trend analysis.',
    capabilities: {
      tools: ['analyze_expenses', 'get_account_balance', 'review_cash_flow', 'get_workspace_stats'],
      connectors: ['erp', 'spreadsheet'],
      inputTypes: ['budget-plan', 'actual-spending', 'variance-request'],
      outputTypes: ['variance-report', 'budget-forecast', 'spending-alert'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 60000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You are a budget analyst. Highlight material variances, identify spending trends, and recommend corrective actions.',
      specialInstructions: ['Flag variances exceeding 10% of budget', 'Break down by cost center and GL code'],
    },
    icon: 'PieChart',
    color: '#6366F1',
  },
  {
    agentTypeId: 'accounting.audit-trail-monitor',
    displayName: 'Audit Trail Monitor',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Compliance,
    description: 'Continuously monitors financial transaction logs for anomalies, unauthorized changes, and policy violations to maintain audit readiness.',
    capabilities: {
      tools: ['get_account_balance', 'get_invoice_summary', 'analyze_expenses'],
      connectors: ['erp', 'audit-log'],
      inputTypes: ['transaction-log', 'change-log', 'access-log'],
      outputTypes: ['anomaly-alert', 'audit-report', 'compliance-finding'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 70000,
      maxCostUsdBudget: 2.5,
    },
    persona: {
      systemPromptAddition: 'You are an internal audit specialist. Scrutinize every transaction for compliance and flag suspicious patterns immediately.',
      specialInstructions: ['Check for segregation of duties violations', 'Monitor for after-hours transaction entries'],
    },
    icon: 'Shield',
    color: '#EF4444',
  },
  {
    agentTypeId: 'accounting.journal-entry-reviewer',
    displayName: 'Journal Entry Reviewer',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Reviewer,
    description: 'Reviews manual journal entries for accuracy, proper authorization, supporting documentation, and adherence to accounting standards.',
    capabilities: {
      tools: ['get_account_balance', 'get_invoice_summary', 'analyze_expenses'],
      connectors: ['erp', 'document-store'],
      inputTypes: ['journal-entry', 'supporting-document', 'approval-chain'],
      outputTypes: ['review-result', 'correction-suggestion', 'escalation'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['reverse-posted-entry'],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You are a senior accountant reviewing journal entries. Verify debits equal credits, accounts are valid, and entries have proper support.',
      specialInstructions: ['Reject entries without supporting documentation', 'Flag round-number entries for extra scrutiny'],
    },
    icon: 'BookOpen',
    color: '#14B8A6',
  },
  {
    agentTypeId: 'accounting.vendor-payment-optimizer',
    displayName: 'Vendor Payment Optimizer',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Planner,
    description: 'Optimizes payment timing to maximize early-payment discounts while maintaining adequate cash reserves and vendor relationships.',
    capabilities: {
      tools: ['get_invoice_summary', 'review_cash_flow', 'get_account_balance', 'analyze_expenses'],
      connectors: ['bank-feed', 'erp'],
      inputTypes: ['payment-terms', 'cash-position', 'vendor-invoice'],
      outputTypes: ['payment-schedule', 'discount-capture-plan', 'cash-impact-analysis'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['accelerate-payment'],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You are a treasury optimization specialist. Maximize discount capture while ensuring cash reserves stay above minimum thresholds.',
      specialInstructions: ['Prioritize 2/10 net 30 discounts', 'Never recommend payment that drops reserves below 2x monthly burn'],
    },
    icon: 'Zap',
    color: '#F97316',
  },
  {
    agentTypeId: 'accounting.tax-provision-estimator',
    displayName: 'Tax Provision Estimator',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Tax,
    description: 'Estimates quarterly and annual tax provisions based on pre-tax income, permanent/temporary differences, and applicable tax rates.',
    capabilities: {
      tools: ['analyze_expenses', 'get_account_balance', 'review_cash_flow'],
      connectors: ['erp', 'tax-engine'],
      inputTypes: ['income-statement', 'tax-adjustment', 'rate-schedule'],
      outputTypes: ['tax-provision-estimate', 'effective-rate-analysis', 'deferred-tax-schedule'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['provision-booking'],
      maxTokenBudget: 100000,
      maxCostUsdBudget: 5.0,
    },
    persona: {
      systemPromptAddition: 'You are a tax accounting specialist. Calculate provisions accurately using ASC 740 guidelines and document all assumptions.',
      specialInstructions: ['Separate permanent from temporary differences', 'Apply blended state rate to state provision'],
    },
    icon: 'Calculator',
    color: '#7C3AED',
  },
  {
    agentTypeId: 'accounting.month-end-closer',
    displayName: 'Month-End Close Agent',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Coordinator,
    description: 'Coordinates month-end close activities including accruals, prepaid amortization, intercompany eliminations, and close checklist tracking.',
    capabilities: {
      tools: ['get_account_balance', 'get_invoice_summary', 'analyze_expenses', 'get_upcoming_deadlines'],
      connectors: ['erp', 'task-tracker'],
      inputTypes: ['close-checklist', 'trial-balance', 'accrual-schedule'],
      outputTypes: ['close-status', 'accrual-entry', 'variance-explanation'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['post-closing-adjustment'],
      maxTokenBudget: 60000,
      maxCostUsdBudget: 2.5,
    },
    persona: {
      systemPromptAddition: 'You are a close process coordinator. Track every task, ensure nothing is missed, and drive toward a 5-day close target.',
      specialInstructions: ['Run through the close checklist in order', 'Verify all sub-ledgers are reconciled before closing GL'],
    },
    icon: 'CalendarCheck',
    color: '#0891B2',
  },
  {
    agentTypeId: 'accounting.financial-statement-preparer',
    displayName: 'Financial Statement Preparer',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Writer,
    description: 'Generates formatted financial statements (income statement, balance sheet, cash flow statement) from trial balance data with proper GAAP presentation.',
    capabilities: {
      tools: ['get_account_balance', 'review_cash_flow', 'analyze_expenses', 'get_workspace_stats'],
      connectors: ['erp', 'reporting-tool'],
      inputTypes: ['trial-balance', 'prior-period-statements', 'disclosure-notes'],
      outputTypes: ['income-statement', 'balance-sheet', 'cash-flow-statement'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['publish-statements'],
      maxTokenBudget: 80000,
      maxCostUsdBudget: 3.0,
    },
    persona: {
      systemPromptAddition: 'You are a financial reporting specialist. Present financial data clearly following GAAP classification and disclosure requirements.',
      specialInstructions: ['Ensure balance sheet balances to zero', 'Include comparative prior period figures'],
    },
    icon: 'FileText',
    color: '#1D4ED8',
  },
  {
    agentTypeId: 'accounting.expense-policy-enforcer',
    displayName: 'Expense Policy Enforcer',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Compliance,
    description: 'Reviews expense reports against company policy, flagging out-of-policy items, missing receipts, and spending limit violations.',
    capabilities: {
      tools: ['analyze_expenses', 'create_expense', 'get_invoice_summary'],
      connectors: ['expense-system', 'receipt-scanner'],
      inputTypes: ['expense-report', 'receipt', 'policy-document'],
      outputTypes: ['policy-violation', 'approval-recommendation', 'exception-request'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You are an expense compliance reviewer. Apply policy rules consistently and provide clear explanations for any rejections.',
      specialInstructions: ['Check per-diem rates against GSA tables', 'Require itemized receipts for meals over $75'],
    },
    icon: 'ClipboardCheck',
    color: '#D97706',
  },
  {
    agentTypeId: 'accounting.bank-reconciliation',
    displayName: 'Bank Reconciliation Agent',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Finance,
    description: 'Matches bank statement transactions to general ledger entries, identifies outstanding items, and prepares bank reconciliation reports.',
    capabilities: {
      tools: ['get_account_balance', 'analyze_expenses', 'get_invoice_summary'],
      connectors: ['bank-feed', 'erp'],
      inputTypes: ['bank-statement', 'gl-transactions', 'outstanding-checks'],
      outputTypes: ['reconciliation-report', 'unmatched-items', 'adjustment-entries'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You are a bank reconciliation specialist. Match every transaction and investigate unreconciled differences promptly.',
      specialInstructions: ['Match by amount and date first, then by description', 'Flag items outstanding more than 30 days'],
    },
    icon: 'Building',
    color: '#475569',
  },
  {
    agentTypeId: 'accounting.depreciation-calculator',
    displayName: 'Depreciation Calculator',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Calculates depreciation schedules for fixed assets using straight-line, declining balance, or units-of-production methods per company policy.',
    capabilities: {
      tools: ['analyze_expenses', 'get_account_balance'],
      connectors: ['asset-register', 'erp'],
      inputTypes: ['asset-record', 'depreciation-policy', 'disposal-notice'],
      outputTypes: ['depreciation-schedule', 'journal-entry', 'asset-summary'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['asset-disposal', 'useful-life-change'],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You are a fixed asset accountant. Apply the correct depreciation method per asset class and maintain accurate asset registers.',
      specialInstructions: ['Use half-year convention for new acquisitions', 'Check for impairment indicators annually'],
    },
    icon: 'TrendingDown',
    color: '#92400E',
  },
  {
    agentTypeId: 'accounting.intercompany-eliminator',
    displayName: 'Intercompany Elimination Agent',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Finance,
    description: 'Identifies and eliminates intercompany transactions for consolidated financial reporting, ensuring balances net to zero.',
    capabilities: {
      tools: ['get_account_balance', 'get_invoice_summary', 'analyze_expenses'],
      connectors: ['erp', 'consolidation-system'],
      inputTypes: ['intercompany-balance', 'transfer-pricing', 'entity-trial-balance'],
      outputTypes: ['elimination-entry', 'imbalance-report', 'consolidation-worksheet'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['post-elimination-entry'],
      maxTokenBudget: 60000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You are a consolidation accountant. Ensure all intercompany balances eliminate cleanly and investigate any differences.',
      specialInstructions: ['Match by IC partner code and transaction type', 'Report imbalances by entity pair'],
    },
    icon: 'GitMerge',
    color: '#7E22CE',
  },
  {
    agentTypeId: 'accounting.revenue-recognition',
    displayName: 'Revenue Recognition Agent',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Compliance,
    description: 'Applies ASC 606 five-step revenue recognition model to contracts, determining performance obligations and appropriate recognition timing.',
    capabilities: {
      tools: ['get_invoice_summary', 'get_account_balance', 'review_cash_flow'],
      connectors: ['crm', 'billing-system', 'erp'],
      inputTypes: ['contract', 'invoice', 'delivery-record'],
      outputTypes: ['revenue-schedule', 'recognition-memo', 'deferred-revenue-entry'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['revenue-recognition-override'],
      maxTokenBudget: 80000,
      maxCostUsdBudget: 4.0,
    },
    persona: {
      systemPromptAddition: 'You are a revenue accounting specialist applying ASC 606. Identify distinct performance obligations and allocate transaction price appropriately.',
      specialInstructions: ['Document the five-step analysis for each contract', 'Flag variable consideration for constraint assessment'],
    },
    icon: 'DollarSign',
    color: '#059669',
  },
  {
    agentTypeId: 'accounting.cost-allocation-engine',
    displayName: 'Cost Allocation Engine',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Allocates shared costs (rent, utilities, IT, overhead) across departments and projects using defined allocation bases and methodologies.',
    capabilities: {
      tools: ['analyze_expenses', 'get_account_balance', 'get_workspace_stats'],
      connectors: ['erp', 'hr-system'],
      inputTypes: ['cost-pool', 'allocation-base', 'department-mapping'],
      outputTypes: ['allocation-result', 'cost-center-report', 'journal-entry'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['change-allocation-method'],
      maxTokenBudget: 35000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You are a cost accounting specialist. Apply allocation methodologies consistently and ensure full cost recovery.',
      specialInstructions: ['Use headcount for people-related costs, square footage for facility costs', 'Document allocation basis for audit trail'],
    },
    icon: 'Share2',
    color: '#6D28D9',
  },
  {
    agentTypeId: 'accounting.fraud-detector',
    displayName: 'Fraud Detection Agent',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Security,
    description: 'Analyzes transaction patterns to detect potential fraud including duplicate payments, ghost vendors, unusual amounts, and Benford\'s Law violations.',
    capabilities: {
      tools: ['analyze_expenses', 'get_invoice_summary', 'get_account_balance'],
      connectors: ['erp', 'bank-feed', 'audit-log'],
      inputTypes: ['transaction-log', 'vendor-master', 'payment-history'],
      outputTypes: ['fraud-alert', 'risk-score', 'investigation-referral'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 70000,
      maxCostUsdBudget: 3.0,
    },
    persona: {
      systemPromptAddition: 'You are a forensic accounting analyst. Apply statistical and pattern-based detection methods to identify potential fraudulent activity.',
      specialInstructions: ['Run Benford analysis on first-digit distribution', 'Cross-reference vendor addresses with employee addresses'],
    },
    icon: 'AlertTriangle',
    color: '#DC2626',
  },
  {
    agentTypeId: 'accounting.1099-processor',
    displayName: '1099 Processing Agent',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Tax,
    description: 'Identifies vendors requiring 1099 reporting, validates TIN information, calculates reportable amounts, and prepares 1099-MISC/NEC forms.',
    capabilities: {
      tools: ['analyze_expenses', 'get_invoice_summary', 'create_invoice'],
      connectors: ['erp', 'tax-engine', 'irs-tin-match'],
      inputTypes: ['vendor-payment-history', 'w9-form', 'vendor-master'],
      outputTypes: ['1099-form', 'tin-mismatch-report', 'threshold-report'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['file-1099'],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You are a tax information reporting specialist. Ensure all 1099-reportable vendors are identified and forms are accurate.',
      specialInstructions: ['Apply $600 threshold for 1099-NEC', 'Verify TIN matches W-9 on file'],
    },
    icon: 'FileSpreadsheet',
    color: '#B45309',
  },
  {
    agentTypeId: 'accounting.currency-converter',
    displayName: 'Multi-Currency Agent',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Finance,
    description: 'Manages multi-currency transactions, calculates realized/unrealized FX gains and losses, and revalues foreign-denominated balances at period end.',
    capabilities: {
      tools: ['get_account_balance', 'analyze_expenses', 'review_cash_flow'],
      connectors: ['fx-rate-service', 'erp', 'bank-feed'],
      inputTypes: ['foreign-transaction', 'rate-table', 'balance-revaluation-request'],
      outputTypes: ['converted-amount', 'fx-gain-loss', 'revaluation-entry'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 4,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You are a multi-currency accounting specialist. Apply correct exchange rates and properly classify FX gains and losses.',
      specialInstructions: ['Use spot rate for transaction date', 'Use closing rate for balance sheet revaluation'],
    },
    icon: 'Globe',
    color: '#0284C7',
  },
  {
    agentTypeId: 'accounting.lease-accountant',
    displayName: 'Lease Accounting Agent',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Compliance,
    description: 'Applies ASC 842 lease accounting standard, calculating right-of-use assets and lease liabilities for operating and finance leases.',
    capabilities: {
      tools: ['get_account_balance', 'analyze_expenses', 'review_cash_flow'],
      connectors: ['lease-management', 'erp'],
      inputTypes: ['lease-agreement', 'payment-schedule', 'modification-notice'],
      outputTypes: ['rou-asset-schedule', 'lease-liability-schedule', 'disclosure-note'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['lease-classification-change'],
      maxTokenBudget: 80000,
      maxCostUsdBudget: 4.0,
    },
    persona: {
      systemPromptAddition: 'You are a lease accounting expert applying ASC 842. Properly classify leases and calculate ROU assets and liabilities.',
      specialInstructions: ['Apply the $5,000 short-term lease exemption threshold', 'Recalculate on lease modifications'],
    },
    icon: 'Home',
    color: '#64748B',
  },
  {
    agentTypeId: 'accounting.credit-memo-processor',
    displayName: 'Credit Memo Processor',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Finance,
    description: 'Processes credit memos from returns, allowances, and billing corrections, matching them to original invoices and applying credits properly.',
    capabilities: {
      tools: ['create_invoice', 'get_invoice_summary', 'get_account_balance'],
      connectors: ['erp', 'billing-system'],
      inputTypes: ['credit-request', 'return-authorization', 'original-invoice'],
      outputTypes: ['credit-memo', 'applied-credit', 'refund-request'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 4,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['credit-over-5000', 'refund-request'],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You are a billing adjustment specialist. Process credits accurately and ensure proper matching to original transactions.',
      specialInstructions: ['Verify return authorization before processing', 'Apply credits to oldest outstanding invoices first'],
    },
    icon: 'RotateCcw',
    color: '#EA580C',
  },
  {
    agentTypeId: 'accounting.purchase-order-matcher',
    displayName: 'Purchase Order Matcher',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Performs three-way matching between purchase orders, goods receipts, and vendor invoices to authorize payment and identify discrepancies.',
    capabilities: {
      tools: ['get_invoice_summary', 'analyze_expenses', 'create_expense'],
      connectors: ['erp', 'procurement-system'],
      inputTypes: ['purchase-order', 'goods-receipt', 'vendor-invoice'],
      outputTypes: ['match-result', 'discrepancy-report', 'payment-authorization'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['override-mismatch'],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You are a procurement-to-pay specialist. Perform rigorous three-way matching and flag any quantity or price discrepancies.',
      specialInstructions: ['Allow 2% price tolerance for rounding', 'Flag quantity variances of any amount'],
    },
    icon: 'CheckSquare',
    color: '#16A34A',
  },
  {
    agentTypeId: 'accounting.financial-ratio-analyzer',
    displayName: 'Financial Ratio Analyzer',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Calculates and analyzes key financial ratios (liquidity, profitability, leverage, efficiency) with industry benchmark comparisons.',
    capabilities: {
      tools: ['get_account_balance', 'review_cash_flow', 'analyze_expenses', 'get_workspace_stats'],
      connectors: ['erp', 'market-data'],
      inputTypes: ['financial-statement', 'industry-benchmark', 'prior-period-ratios'],
      outputTypes: ['ratio-analysis', 'trend-report', 'peer-comparison'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You are a financial analysis specialist. Calculate ratios accurately, identify trends, and provide actionable insights.',
      specialInstructions: ['Include current ratio, quick ratio, debt-to-equity, ROE, and gross margin at minimum', 'Compare to industry median'],
    },
    icon: 'BarChart2',
    color: '#2563EB',
  },
  {
    agentTypeId: 'accounting.sales-tax-calculator',
    displayName: 'Sales Tax Calculator',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Tax,
    description: 'Determines correct sales tax rates based on product type, customer location, and nexus rules, and prepares sales tax filings.',
    capabilities: {
      tools: ['get_invoice_summary', 'analyze_expenses', 'create_invoice'],
      connectors: ['tax-engine', 'erp', 'e-commerce'],
      inputTypes: ['sales-transaction', 'tax-exemption-cert', 'nexus-assessment'],
      outputTypes: ['tax-calculation', 'filing-return', 'exemption-validation'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: ['file-return'],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You are a sales tax compliance specialist. Apply the correct jurisdiction rates and handle exemptions properly.',
      specialInstructions: ['Check for economic nexus thresholds by state', 'Validate exemption certificates are current'],
    },
    icon: 'Percent',
    color: '#B91C1C',
  },
  {
    agentTypeId: 'accounting.grant-tracker',
    displayName: 'Grant Accounting Tracker',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Finance,
    description: 'Tracks grant funding, monitors spending against budget restrictions, ensures compliance with grant terms, and prepares grantor reports.',
    capabilities: {
      tools: ['analyze_expenses', 'get_account_balance', 'review_cash_flow', 'get_upcoming_deadlines'],
      connectors: ['erp', 'grant-portal'],
      inputTypes: ['grant-agreement', 'expenditure-report', 'budget-modification'],
      outputTypes: ['grant-status-report', 'compliance-check', 'drawdown-request'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['drawdown-request', 'budget-modification'],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You are a grant accountant. Ensure all expenditures comply with grant restrictions and reporting deadlines are met.',
      specialInstructions: ['Track cost-share requirements separately', 'Flag unallowable costs immediately'],
    },
    icon: 'Award',
    color: '#0D9488',
  },
  {
    agentTypeId: 'accounting.consolidation-agent',
    displayName: 'Financial Consolidation Agent',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Finance,
    description: 'Consolidates financial data from multiple entities, handling currency translation, minority interests, and elimination entries for group reporting.',
    capabilities: {
      tools: ['get_account_balance', 'review_cash_flow', 'analyze_expenses', 'get_workspace_stats'],
      connectors: ['erp', 'consolidation-system'],
      inputTypes: ['entity-trial-balance', 'ownership-structure', 'translation-rates'],
      outputTypes: ['consolidated-statements', 'elimination-schedule', 'translation-adjustment'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['publish-consolidated'],
      maxTokenBudget: 100000,
      maxCostUsdBudget: 5.0,
    },
    persona: {
      systemPromptAddition: 'You are a consolidation accountant. Ensure accurate aggregation across entities with proper eliminations and currency translation.',
      specialInstructions: ['Apply current rate method for foreign subsidiaries', 'Verify ownership percentages before consolidating'],
    },
    icon: 'Layers',
    color: '#4338CA',
  },
  {
    agentTypeId: 'accounting.variance-explainer',
    displayName: 'Variance Explanation Agent',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Writer,
    description: 'Automatically generates variance explanations for budget vs. actual differences, providing narrative commentary for management reports.',
    capabilities: {
      tools: ['analyze_expenses', 'get_account_balance', 'review_cash_flow'],
      connectors: ['erp', 'reporting-tool'],
      inputTypes: ['variance-data', 'budget-plan', 'prior-period-data'],
      outputTypes: ['variance-narrative', 'management-commentary', 'action-item'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You are a financial reporting analyst. Write clear, concise variance explanations that identify root causes and business impact.',
      specialInstructions: ['Focus on material variances over 5% or $10K', 'Distinguish between volume, rate, and timing variances'],
    },
    icon: 'MessageSquare',
    color: '#0369A1',
  },
  {
    agentTypeId: 'accounting.accounts-cleanup',
    displayName: 'Chart of Accounts Cleanup Agent',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Reviewer,
    description: 'Reviews chart of accounts for inactive accounts, duplicates, misclassifications, and naming inconsistencies to maintain a clean GL structure.',
    capabilities: {
      tools: ['get_account_balance', 'analyze_expenses'],
      connectors: ['erp'],
      inputTypes: ['chart-of-accounts', 'account-activity-report', 'naming-convention'],
      outputTypes: ['cleanup-recommendation', 'merge-plan', 'reclassification-entry'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['deactivate-account', 'merge-accounts'],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You are a GL structure specialist. Recommend consolidation and cleanup to maintain a lean, well-organized chart of accounts.',
      specialInstructions: ['Flag accounts with zero activity for 12+ months', 'Ensure consistent naming convention across segments'],
    },
    icon: 'Eraser',
    color: '#78716C',
  },
  {
    agentTypeId: 'accounting.billing-automation',
    displayName: 'Billing Automation Agent',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Coordinator,
    description: 'Automates recurring billing cycles including invoice generation, delivery, payment tracking, and dunning for subscription and contract billing.',
    capabilities: {
      tools: ['create_invoice', 'get_invoice_summary', 'get_account_balance', 'get_upcoming_deadlines'],
      connectors: ['billing-system', 'email', 'payment-gateway'],
      inputTypes: ['billing-schedule', 'contract-terms', 'usage-data'],
      outputTypes: ['invoice', 'dunning-notice', 'billing-summary'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 4,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['send-dunning-notice'],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You are a billing operations specialist. Ensure invoices go out on time, track payments, and manage the dunning process professionally.',
      specialInstructions: ['Generate invoices 5 days before billing date', 'Escalate dunning after 3 unsuccessful attempts'],
    },
    icon: 'Clock',
    color: '#9333EA',
  },
  {
    agentTypeId: 'accounting.profit-center-reporter',
    displayName: 'Profit Center Reporter',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Generates profit and loss reports by business unit, product line, or project, enabling segment-level performance visibility.',
    capabilities: {
      tools: ['analyze_expenses', 'get_account_balance', 'review_cash_flow', 'get_workspace_stats'],
      connectors: ['erp', 'reporting-tool'],
      inputTypes: ['segment-mapping', 'revenue-data', 'cost-allocation'],
      outputTypes: ['segment-pnl', 'margin-analysis', 'contribution-report'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You are a management reporting analyst. Provide clear segment-level financial visibility with actionable margin insights.',
      specialInstructions: ['Include contribution margin and operating margin', 'Highlight segments below target profitability'],
    },
    icon: 'Target',
    color: '#E11D48',
  },
  {
    agentTypeId: 'accounting.working-capital-optimizer',
    displayName: 'Working Capital Optimizer',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Planner,
    description: 'Analyzes working capital components (receivables, payables, inventory) and recommends optimization strategies to improve cash conversion cycle.',
    capabilities: {
      tools: ['review_cash_flow', 'get_account_balance', 'get_invoice_summary', 'analyze_expenses'],
      connectors: ['erp', 'bank-feed'],
      inputTypes: ['aging-report', 'inventory-levels', 'payment-terms'],
      outputTypes: ['working-capital-report', 'optimization-plan', 'ccc-analysis'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['change-payment-terms'],
      maxTokenBudget: 60000,
      maxCostUsdBudget: 2.5,
    },
    persona: {
      systemPromptAddition: 'You are a working capital management specialist. Identify opportunities to reduce cash conversion cycle without damaging vendor or customer relationships.',
      specialInstructions: ['Track DSO, DPO, and DIO trends monthly', 'Recommend specific actions per component'],
    },
    icon: 'Repeat',
    color: '#0D9488',
  },
  {
    agentTypeId: 'accounting.travel-expense-auditor',
    displayName: 'Travel Expense Auditor',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Reviewer,
    description: 'Audits travel expense reports for policy compliance, reasonable pricing, proper documentation, and potential personal expenses mixed with business travel.',
    capabilities: {
      tools: ['analyze_expenses', 'create_expense'],
      connectors: ['expense-system', 'travel-booking', 'receipt-scanner'],
      inputTypes: ['travel-expense-report', 'booking-confirmation', 'receipt'],
      outputTypes: ['audit-result', 'policy-exception', 'reimbursement-amount'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You are a travel expense compliance auditor. Verify all travel expenses follow corporate travel policy and flag exceptions.',
      specialInstructions: ['Compare hotel rates to GSA per-diem rates', 'Check for personal days embedded in business trips'],
    },
    icon: 'Plane',
    color: '#0EA5E9',
  },
  {
    agentTypeId: 'accounting.commission-calculator',
    displayName: 'Commission Calculator',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Finance,
    description: 'Calculates sales commissions based on plan structures, quota attainment, accelerators, and clawback provisions with ASC 606 capitalization.',
    capabilities: {
      tools: ['get_invoice_summary', 'analyze_expenses', 'get_payroll_summary'],
      connectors: ['crm', 'payroll-system', 'erp'],
      inputTypes: ['commission-plan', 'sales-data', 'quota-assignment'],
      outputTypes: ['commission-statement', 'accrual-entry', 'capitalization-schedule'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['clawback-execution'],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You are a commission accounting specialist. Calculate commissions accurately per plan terms and handle ASC 606 capitalization requirements.',
      specialInstructions: ['Apply accelerators only after quota is met', 'Capitalize commissions for multi-year contracts'],
    },
    icon: 'Trophy',
    color: '#CA8A04',
  },
  {
    agentTypeId: 'accounting.prepaid-amortizer',
    displayName: 'Prepaid Amortization Agent',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Finance,
    description: 'Manages prepaid expense schedules, calculating monthly amortization amounts and generating journal entries for insurance, rent, and software subscriptions.',
    capabilities: {
      tools: ['analyze_expenses', 'get_account_balance'],
      connectors: ['erp'],
      inputTypes: ['prepaid-schedule', 'vendor-invoice', 'amortization-policy'],
      outputTypes: ['amortization-entry', 'prepaid-balance-report', 'expiration-alert'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You are a prepaid expense specialist. Maintain accurate amortization schedules and ensure timely recognition of expenses.',
      specialInstructions: ['Amortize on straight-line basis unless otherwise specified', 'Alert when prepaid balances are within 30 days of full amortization'],
    },
    icon: 'Calendar',
    color: '#6B7280',
  },
  {
    agentTypeId: 'accounting.kpi-dashboard-builder',
    displayName: 'Financial KPI Dashboard Builder',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Designer,
    description: 'Creates executive financial dashboards with key metrics including revenue growth, EBITDA margin, burn rate, runway, and unit economics.',
    capabilities: {
      tools: ['get_account_balance', 'review_cash_flow', 'analyze_expenses', 'get_workspace_stats'],
      connectors: ['erp', 'reporting-tool', 'bi-platform'],
      inputTypes: ['financial-data', 'metric-definition', 'target-set'],
      outputTypes: ['dashboard-config', 'metric-summary', 'trend-visualization'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You are a financial reporting designer. Build clear, actionable dashboards that tell the financial story at a glance.',
      specialInstructions: ['Include MoM and YoY comparisons', 'Use red/yellow/green indicators for targets'],
    },
    icon: 'LayoutDashboard',
    color: '#3B82F6',
  },
  {
    agentTypeId: 'accounting.accrual-estimator',
    displayName: 'Accrual Estimation Agent',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Estimates month-end accruals for received but unbilled services, earned but unpaid wages, and other timing differences between cash and accrual basis.',
    capabilities: {
      tools: ['analyze_expenses', 'get_account_balance', 'get_invoice_summary'],
      connectors: ['erp', 'hr-system', 'vendor-portal'],
      inputTypes: ['service-contract', 'payroll-calendar', 'historical-accruals'],
      outputTypes: ['accrual-estimate', 'journal-entry', 'true-up-analysis'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['accrual-over-50000'],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You are an accrual accounting specialist. Estimate accruals accurately to ensure proper period matching of revenues and expenses.',
      specialInstructions: ['Use historical patterns when actuals are unavailable', 'Track and report true-up variances from prior estimates'],
    },
    icon: 'Clock3',
    color: '#A855F7',
  },
  {
    agentTypeId: 'accounting.inventory-costing',
    displayName: 'Inventory Costing Agent',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Manages inventory valuation using FIFO, LIFO, or weighted average methods, calculates COGS, and identifies obsolete or slow-moving inventory.',
    capabilities: {
      tools: ['analyze_expenses', 'get_account_balance', 'review_cash_flow'],
      connectors: ['erp', 'warehouse-system'],
      inputTypes: ['inventory-movement', 'cost-layer', 'physical-count'],
      outputTypes: ['inventory-valuation', 'cogs-calculation', 'obsolescence-reserve'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['write-down-inventory', 'change-costing-method'],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You are an inventory cost accountant. Maintain accurate cost layers and identify items requiring valuation adjustments.',
      specialInstructions: ['Apply lower of cost or net realizable value', 'Flag items with no movement in 180+ days'],
    },
    icon: 'Package',
    color: '#92400E',
  },
  {
    agentTypeId: 'accounting.statutory-reporter',
    displayName: 'Statutory Reporting Agent',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Compliance,
    description: 'Prepares statutory financial reports required by regulators including SEC filings, annual returns, and jurisdiction-specific compliance reports.',
    capabilities: {
      tools: ['get_account_balance', 'review_cash_flow', 'analyze_expenses', 'get_upcoming_deadlines'],
      connectors: ['erp', 'filing-portal', 'xbrl-generator'],
      inputTypes: ['financial-statement', 'regulatory-template', 'filing-calendar'],
      outputTypes: ['statutory-report', 'xbrl-filing', 'compliance-checklist'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['submit-filing'],
      maxTokenBudget: 100000,
      maxCostUsdBudget: 5.0,
    },
    persona: {
      systemPromptAddition: 'You are a statutory reporting specialist. Ensure filings meet all regulatory requirements and deadlines with zero deficiencies.',
      specialInstructions: ['Validate XBRL tags against taxonomy', 'Cross-reference all figures to source financial statements'],
    },
    icon: 'Landmark',
    color: '#1E3A5F',
  },
  {
    agentTypeId: 'accounting.petty-cash-manager',
    displayName: 'Petty Cash Manager',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Finance,
    description: 'Tracks petty cash fund balances, processes replenishment requests, verifies receipts, and ensures proper documentation for small cash disbursements.',
    capabilities: {
      tools: ['create_expense', 'analyze_expenses', 'get_account_balance'],
      connectors: ['expense-system'],
      inputTypes: ['petty-cash-voucher', 'receipt', 'replenishment-request'],
      outputTypes: ['petty-cash-reconciliation', 'replenishment-entry', 'shortage-report'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['replenishment-over-500'],
      maxTokenBudget: 10000,
      maxCostUsdBudget: 0.2,
    },
    persona: {
      systemPromptAddition: 'You are a petty cash custodian. Maintain tight controls over the fund and ensure every disbursement is properly documented.',
      specialInstructions: ['Count and reconcile fund weekly', 'Require receipts for all disbursements over $5'],
    },
    icon: 'Wallet',
    color: '#65A30D',
  },
  {
    agentTypeId: 'accounting.debt-covenant-monitor',
    displayName: 'Debt Covenant Monitor',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Compliance,
    description: 'Monitors compliance with debt covenant requirements including financial ratios, reporting obligations, and restricted payment provisions.',
    capabilities: {
      tools: ['get_account_balance', 'review_cash_flow', 'analyze_expenses', 'get_upcoming_deadlines'],
      connectors: ['erp', 'loan-system'],
      inputTypes: ['debt-agreement', 'covenant-test', 'financial-statement'],
      outputTypes: ['covenant-compliance-report', 'breach-alert', 'waiver-request'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['waiver-request'],
      maxTokenBudget: 60000,
      maxCostUsdBudget: 2.5,
    },
    persona: {
      systemPromptAddition: 'You are a treasury compliance specialist. Monitor covenant ratios continuously and provide early warning of potential breaches.',
      specialInstructions: ['Test covenants quarterly and on material transactions', 'Provide 60-day advance warning of projected breaches'],
    },
    icon: 'Lock',
    color: '#BE123C',
  },
  {
    agentTypeId: 'accounting.expense-benchmark',
    displayName: 'Expense Benchmarking Agent',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Researcher,
    description: 'Compares company spending patterns against industry benchmarks and peer companies to identify areas of over or under-spending.',
    capabilities: {
      tools: ['analyze_expenses', 'get_account_balance', 'get_workspace_stats'],
      connectors: ['erp', 'market-data', 'benchmark-database'],
      inputTypes: ['expense-data', 'industry-benchmark', 'company-profile'],
      outputTypes: ['benchmark-report', 'savings-opportunity', 'peer-comparison'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You are a cost benchmarking analyst. Compare spending to relevant peers and identify actionable savings opportunities.',
      specialInstructions: ['Normalize by revenue or headcount for fair comparison', 'Focus on top 10 expense categories by dollar value'],
    },
    icon: 'Scale',
    color: '#0891B2',
  },
  {
    agentTypeId: 'accounting.project-cost-tracker',
    displayName: 'Project Cost Tracker',
    domain: AgentDomain.Accounting,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Tracks project-level costs including labor, materials, and overhead, comparing actual costs to budgets and estimating costs at completion.',
    capabilities: {
      tools: ['analyze_expenses', 'get_account_balance', 'get_upcoming_deadlines', 'get_workspace_stats'],
      connectors: ['erp', 'project-management', 'timesheet-system'],
      inputTypes: ['project-budget', 'timesheet', 'purchase-order', 'expense-report'],
      outputTypes: ['project-cost-report', 'eac-estimate', 'budget-alert'],
      domains: ['accounting'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You are a project cost accountant. Provide real-time cost visibility and early warning when projects trend over budget.',
      specialInstructions: ['Calculate EAC using both CPI and SPI methods', 'Highlight earned value variances weekly'],
    },
    icon: 'FolderKanban',
    color: '#7C3AED',
  },
]
