import { AgentDomain, AgentCategory, AgentType, CostTier, LatencyProfile } from '../../types'
import type { AgentCapabilityManifest } from '../../types'

export const AGENTS: AgentCapabilityManifest[] = [
  {
    agentTypeId: 'analytics.dashboard-builder',
    displayName: 'Dashboard Builder',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Business,
    baseType: AgentType.Designer,
    description: 'Creates interactive dashboards with charts, KPIs, and drill-down capabilities from workspace data',
    capabilities: {
      tools: ['get_workspace_stats', 'get_upcoming_deadlines', 'get_table_stats'],
      connectors: ['metabase', 'grafana', 'tableau'],
      inputTypes: ['data_source', 'metric_definition', 'layout_template'],
      outputTypes: ['dashboard_config', 'chart_definition', 'kpi_card'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['publish_dashboard'],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You build dashboards. Choose the right visualization type for each metric and optimize for scannability.',
      specialInstructions: ['Use consistent color scales across charts', 'Include comparison periods by default'],
    },
    icon: 'LayoutDashboard',
    color: '#4F46E5',
  },
  {
    agentTypeId: 'analytics.trend-analyzer',
    displayName: 'Trend Analyzer',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Identifies trends, seasonality patterns, and directional changes in business metrics over time',
    capabilities: {
      tools: ['get_workspace_stats', 'analyze_expenses', 'get_invoice_summary'],
      connectors: ['data_warehouse', 'spreadsheets', 'bi_tool'],
      inputTypes: ['time_series_data', 'metric_name', 'date_range'],
      outputTypes: ['trend_report', 'forecast', 'anomaly_flag'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 250_000,
      maxCostUsdBudget: 2.5,
    },
    persona: {
      systemPromptAddition: 'You analyze trends in data. Identify meaningful patterns and separate signal from noise.',
      specialInstructions: ['Account for seasonality before flagging anomalies', 'Compare year-over-year where possible'],
    },
    icon: 'TrendingUp',
    color: '#059669',
  },
  {
    agentTypeId: 'analytics.anomaly-detector',
    displayName: 'Anomaly Detector',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Technical,
    baseType: AgentType.Analyst,
    description: 'Detects statistical anomalies in real-time data streams using baseline comparison and deviation analysis',
    capabilities: {
      tools: ['get_workspace_stats', 'get_table_stats', 'analyze_expenses'],
      connectors: ['prometheus', 'datadog', 'cloudwatch'],
      inputTypes: ['metric_stream', 'baseline_config', 'threshold_rules'],
      outputTypes: ['anomaly_alert', 'deviation_report', 'baseline_update'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You detect anomalies in data. Use statistical methods and reduce false positive rates.',
      specialInstructions: ['Use dynamic baselines that adapt to trends', 'Classify anomalies by severity based on deviation magnitude'],
    },
    icon: 'AlertCircle',
    color: '#EF4444',
  },
  {
    agentTypeId: 'analytics.report-generator',
    displayName: 'Report Generator',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Business,
    baseType: AgentType.Writer,
    description: 'Generates formatted business reports with executive summaries, charts, and actionable recommendations',
    capabilities: {
      tools: ['get_workspace_stats', 'get_upcoming_deadlines', 'analyze_expenses', 'get_invoice_summary'],
      connectors: ['google_docs', 'notion', 'pdf_generator'],
      inputTypes: ['data_source', 'report_template', 'date_range'],
      outputTypes: ['formatted_report', 'executive_summary', 'pdf'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['distribute_report'],
      maxTokenBudget: 300_000,
      maxCostUsdBudget: 3.0,
    },
    persona: {
      systemPromptAddition: 'You generate business reports. Lead with insights, not data. Make recommendations actionable.',
      specialInstructions: ['Include executive summary on first page', 'Use consistent chart formatting throughout'],
    },
    icon: 'FileBarChart',
    color: '#3B82F6',
  },
  {
    agentTypeId: 'analytics.kpi-tracker',
    displayName: 'KPI Tracker',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Tracks key performance indicators against targets, calculates progress, and alerts on deviations',
    capabilities: {
      tools: ['get_workspace_stats', 'get_invoice_summary', 'analyze_expenses'],
      connectors: ['crm', 'erp', 'bi_tool'],
      inputTypes: ['kpi_definition', 'target_value', 'actual_value'],
      outputTypes: ['kpi_scorecard', 'deviation_alert', 'progress_report'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You track KPIs. Show progress against targets and highlight items needing attention.',
      specialInstructions: ['Use traffic light colors for status', 'Calculate pace to determine if target will be met'],
    },
    icon: 'Target',
    color: '#F59E0B',
  },
  {
    agentTypeId: 'analytics.forecast-modeler',
    displayName: 'Forecast Modeler',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Builds forecasting models for revenue, growth, and resource needs using historical data',
    capabilities: {
      tools: ['get_workspace_stats', 'analyze_expenses', 'get_invoice_summary', 'analyze_bookings'],
      connectors: ['data_warehouse', 'spreadsheets', 'forecasting_api'],
      inputTypes: ['historical_data', 'growth_assumptions', 'scenario_config'],
      outputTypes: ['forecast_model', 'scenario_comparison', 'confidence_interval'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 300_000,
      maxCostUsdBudget: 5.0,
    },
    persona: {
      systemPromptAddition: 'You build forecasting models. Include confidence intervals and clearly state assumptions.',
      specialInstructions: ['Run multiple scenarios (optimistic, base, pessimistic)', 'Validate model against holdout data'],
    },
    icon: 'LineChart',
    color: '#8B5CF6',
  },
  {
    agentTypeId: 'analytics.cohort-analyzer',
    displayName: 'Cohort Analyzer',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Performs cohort analysis to understand retention, engagement, and lifetime value patterns',
    capabilities: {
      tools: ['get_workspace_stats', 'get_table_stats', 'analyze_database_schema'],
      connectors: ['mixpanel', 'amplitude', 'data_warehouse'],
      inputTypes: ['user_events', 'cohort_definition', 'date_range'],
      outputTypes: ['cohort_table', 'retention_curve', 'ltv_analysis'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 250_000,
      maxCostUsdBudget: 2.5,
    },
    persona: {
      systemPromptAddition: 'You perform cohort analysis. Segment users meaningfully and track behavior over time.',
      specialInstructions: ['Compare cohort performance against benchmarks', 'Identify factors that correlate with high retention'],
    },
    icon: 'Users',
    color: '#0891B2',
  },
  {
    agentTypeId: 'analytics.funnel-optimizer',
    displayName: 'Funnel Optimizer',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Analyzes conversion funnels, identifies drop-off points, and recommends optimization strategies',
    capabilities: {
      tools: ['get_workspace_stats', 'analyze_views', 'get_table_stats'],
      connectors: ['mixpanel', 'google_analytics', 'amplitude'],
      inputTypes: ['funnel_definition', 'event_data', 'conversion_goal'],
      outputTypes: ['funnel_report', 'drop_off_analysis', 'optimization_suggestion'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You optimize conversion funnels. Identify where users drop off and why.',
      specialInstructions: ['Calculate stage-to-stage conversion rates', 'Segment funnels by traffic source'],
    },
    icon: 'Filter',
    color: '#D946EF',
  },
  {
    agentTypeId: 'analytics.ab-test-evaluator',
    displayName: 'A/B Test Evaluator',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Technical,
    baseType: AgentType.Analyst,
    description: 'Evaluates A/B test results with statistical rigor, calculates significance, and recommends decisions',
    capabilities: {
      tools: ['get_workspace_stats', 'get_table_stats', 'analyze_views'],
      connectors: ['optimizely', 'vwo', 'statsig'],
      inputTypes: ['experiment_data', 'sample_size', 'success_metric'],
      outputTypes: ['significance_report', 'recommendation', 'confidence_interval'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You evaluate A/B tests. Apply proper statistical methods and avoid peeking bias.',
      specialInstructions: ['Check for sufficient sample size before declaring results', 'Report effect size alongside p-value'],
    },
    icon: 'FlaskConical',
    color: '#10B981',
  },
  {
    agentTypeId: 'analytics.revenue-analyzer',
    displayName: 'Revenue Analyzer',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Business,
    baseType: AgentType.Finance,
    description: 'Analyzes revenue streams, MRR/ARR metrics, churn rates, and unit economics',
    capabilities: {
      tools: ['get_invoice_summary', 'analyze_expenses', 'get_workspace_stats'],
      connectors: ['stripe', 'chargebee', 'quickbooks'],
      inputTypes: ['subscription_data', 'invoice_history', 'pricing_tiers'],
      outputTypes: ['revenue_report', 'mrr_breakdown', 'churn_analysis'],
      domains: ['analytics', 'accounting'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 250_000,
      maxCostUsdBudget: 2.5,
    },
    persona: {
      systemPromptAddition: 'You analyze revenue metrics. Break down MRR by component (new, expansion, contraction, churn).',
      specialInstructions: ['Distinguish between gross and net churn', 'Calculate LTV/CAC ratio'],
    },
    icon: 'DollarSign',
    color: '#059669',
  },
  {
    agentTypeId: 'analytics.customer-segmenter',
    displayName: 'Customer Segmenter',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Segments customers by behavior, value, and demographics to enable targeted strategies',
    capabilities: {
      tools: ['get_workspace_stats', 'get_table_stats', 'analyze_database_schema'],
      connectors: ['crm', 'mixpanel', 'data_warehouse'],
      inputTypes: ['customer_data', 'behavioral_events', 'transaction_history'],
      outputTypes: ['segment_definition', 'segment_profile', 'targeting_recommendation'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You segment customers. Create actionable segments with clear behavioral distinctions.',
      specialInstructions: ['Use RFM analysis as a starting point', 'Size each segment and estimate value'],
    },
    icon: 'PieChart',
    color: '#F97316',
  },
  {
    agentTypeId: 'analytics.usage-pattern-miner',
    displayName: 'Usage Pattern Miner',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Technical,
    baseType: AgentType.Researcher,
    description: 'Mines product usage data to discover feature adoption patterns, power user behaviors, and friction points',
    capabilities: {
      tools: ['get_workspace_stats', 'get_table_stats', 'analyze_views'],
      connectors: ['amplitude', 'heap', 'fullstory'],
      inputTypes: ['event_stream', 'feature_list', 'user_sessions'],
      outputTypes: ['usage_report', 'feature_adoption_matrix', 'friction_map'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 250_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You mine usage patterns. Discover how power users differ from churned users.',
      specialInstructions: ['Identify the aha moment from usage data', 'Track feature activation funnels'],
    },
    icon: 'Search',
    color: '#6366F1',
  },
  {
    agentTypeId: 'analytics.cost-analyzer',
    displayName: 'Cost Analyzer',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Business,
    baseType: AgentType.Finance,
    description: 'Analyzes costs across departments, identifies savings opportunities, and tracks budget utilization',
    capabilities: {
      tools: ['analyze_expenses', 'get_invoice_summary', 'get_workspace_stats'],
      connectors: ['quickbooks', 'xero', 'aws_cost_explorer'],
      inputTypes: ['expense_data', 'budget_allocation', 'vendor_invoices'],
      outputTypes: ['cost_report', 'savings_opportunity', 'budget_variance'],
      domains: ['analytics', 'accounting'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You analyze costs. Identify waste, track burn rate, and suggest cost reduction strategies.',
      specialInstructions: ['Break down costs by department and category', 'Flag month-over-month increases above 10%'],
    },
    icon: 'Calculator',
    color: '#DC2626',
  },
  {
    agentTypeId: 'analytics.data-quality-monitor',
    displayName: 'Data Quality Monitor',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Technical,
    baseType: AgentType.Reviewer,
    description: 'Monitors data quality by checking completeness, consistency, freshness, and accuracy of data sources',
    capabilities: {
      tools: ['get_table_stats', 'analyze_database_schema', 'get_workspace_stats'],
      connectors: ['great_expectations', 'dbt', 'data_warehouse'],
      inputTypes: ['data_source', 'quality_rules', 'schema_definition'],
      outputTypes: ['quality_report', 'freshness_alert', 'completeness_check'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You monitor data quality. Check for nulls, duplicates, schema drift, and stale data.',
      specialInstructions: ['Alert if data is more than 4 hours stale', 'Track data quality score over time'],
    },
    icon: 'ShieldCheck',
    color: '#14B8A6',
  },
  {
    agentTypeId: 'analytics.benchmark-comparator',
    displayName: 'Benchmark Comparator',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Business,
    baseType: AgentType.Researcher,
    description: 'Compares internal metrics against industry benchmarks to identify competitive positioning',
    capabilities: {
      tools: ['get_workspace_stats', 'get_invoice_summary', 'analyze_expenses'],
      connectors: ['benchmark_db', 'industry_reports', 'crunchbase'],
      inputTypes: ['internal_metrics', 'benchmark_dataset', 'industry_category'],
      outputTypes: ['benchmark_report', 'gap_analysis', 'competitive_position'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You compare metrics against industry benchmarks. Provide context for how the business stacks up.',
      specialInstructions: ['Use peer group comparisons, not just industry averages', 'Note benchmark data freshness'],
    },
    icon: 'Scale',
    color: '#7C3AED',
  },
  {
    agentTypeId: 'analytics.engagement-scorer',
    displayName: 'Engagement Scorer',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Calculates engagement scores for users and accounts based on product usage and interaction data',
    capabilities: {
      tools: ['get_workspace_stats', 'get_table_stats', 'analyze_views'],
      connectors: ['mixpanel', 'hubspot', 'gainsight'],
      inputTypes: ['user_activity', 'feature_usage', 'scoring_model'],
      outputTypes: ['engagement_score', 'health_signal', 'risk_alert'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You calculate engagement scores. Weight features by business value and detect declining engagement.',
      specialInstructions: ['Update scores daily', 'Flag accounts with rapidly declining scores'],
    },
    icon: 'Flame',
    color: '#F97316',
  },
  {
    agentTypeId: 'analytics.booking-insights',
    displayName: 'Booking Insights Analyst',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Analyzes booking and scheduling patterns to optimize availability and reduce no-shows',
    capabilities: {
      tools: ['analyze_bookings', 'get_workspace_stats', 'get_upcoming_deadlines'],
      connectors: ['calendly', 'google_calendar', 'booking_system'],
      inputTypes: ['booking_history', 'no_show_data', 'availability_config'],
      outputTypes: ['booking_analysis', 'no_show_prediction', 'availability_optimization'],
      domains: ['analytics', 'scheduling'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You analyze booking data. Identify peak times, no-show patterns, and optimization opportunities.',
      specialInstructions: ['Segment analysis by booking type', 'Calculate optimal buffer times between bookings'],
    },
    icon: 'CalendarRange',
    color: '#0EA5E9',
  },
  {
    agentTypeId: 'analytics.content-performance',
    displayName: 'Content Performance Analyst',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Creative,
    baseType: AgentType.Analyst,
    description: 'Measures content performance across channels, identifying top-performing formats and topics',
    capabilities: {
      tools: ['get_workspace_stats', 'analyze_views', 'get_table_stats'],
      connectors: ['google_analytics', 'contentful', 'wordpress'],
      inputTypes: ['content_metadata', 'engagement_metrics', 'traffic_data'],
      outputTypes: ['performance_report', 'content_ranking', 'topic_recommendation'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You analyze content performance. Identify what resonates with audiences and recommend content strategies.',
      specialInstructions: ['Track engagement, not just views', 'Compare performance by content format and channel'],
    },
    icon: 'FileText',
    color: '#EC4899',
  },
  {
    agentTypeId: 'analytics.pipeline-health',
    displayName: 'Pipeline Health Analyzer',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Business,
    baseType: AgentType.Sales,
    description: 'Analyzes sales pipeline health, stage conversion rates, and deal velocity metrics',
    capabilities: {
      tools: ['get_workspace_stats', 'get_invoice_summary', 'get_table_stats'],
      connectors: ['salesforce', 'hubspot', 'pipedrive'],
      inputTypes: ['pipeline_data', 'deal_history', 'stage_config'],
      outputTypes: ['pipeline_report', 'conversion_analysis', 'velocity_metric'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You analyze sales pipelines. Track deal flow, identify bottleneck stages, and forecast close rates.',
      specialInstructions: ['Calculate weighted pipeline value', 'Flag deals stalled beyond average stage duration'],
    },
    icon: 'Workflow',
    color: '#2563EB',
  },
  {
    agentTypeId: 'analytics.sql-query-builder',
    displayName: 'SQL Query Builder',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Technical,
    baseType: AgentType.Developer,
    description: 'Generates SQL queries from natural language questions against known database schemas',
    capabilities: {
      tools: ['analyze_database_schema', 'get_table_stats', 'get_workspace_stats'],
      connectors: ['postgresql', 'bigquery', 'snowflake'],
      inputTypes: ['natural_language_query', 'schema_context', 'sample_data'],
      outputTypes: ['sql_query', 'query_result', 'explanation'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['execute_write_query'],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You generate SQL queries from natural language. Optimize for readability and performance.',
      specialInstructions: ['Always use parameterized queries', 'Add LIMIT clause to prevent runaway queries'],
    },
    icon: 'Database',
    color: '#475569',
  },
  {
    agentTypeId: 'analytics.churn-predictor',
    displayName: 'Churn Predictor',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Predicts customer churn risk using engagement, usage, and support ticket patterns',
    capabilities: {
      tools: ['get_workspace_stats', 'get_table_stats', 'analyze_views'],
      connectors: ['crm', 'mixpanel', 'zendesk'],
      inputTypes: ['customer_data', 'usage_history', 'support_tickets'],
      outputTypes: ['churn_score', 'risk_factors', 'retention_recommendation'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 250_000,
      maxCostUsdBudget: 2.5,
    },
    persona: {
      systemPromptAddition: 'You predict churn risk. Identify leading indicators early enough for intervention.',
      specialInstructions: ['Weight recent activity more heavily', 'Include support interaction sentiment in model'],
    },
    icon: 'UserMinus',
    color: '#DC2626',
  },
  {
    agentTypeId: 'analytics.metric-definition-manager',
    displayName: 'Metric Definition Manager',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Business,
    baseType: AgentType.Planner,
    description: 'Maintains a centralized catalog of metric definitions ensuring consistent calculation across teams',
    capabilities: {
      tools: ['get_workspace_stats', 'get_table_stats', 'analyze_database_schema'],
      connectors: ['data_catalog', 'dbt', 'looker'],
      inputTypes: ['metric_name', 'calculation_logic', 'data_source'],
      outputTypes: ['metric_definition', 'consistency_check', 'metric_catalog'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['update_metric_definition'],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You manage metric definitions. Ensure every metric has a clear owner, calculation, and data source.',
      specialInstructions: ['Flag conflicting definitions across teams', 'Version control metric changes'],
    },
    icon: 'BookOpen',
    color: '#CA8A04',
  },
  {
    agentTypeId: 'analytics.attribution-modeler',
    displayName: 'Attribution Modeler',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Business,
    baseType: AgentType.Marketing,
    description: 'Models marketing attribution across touchpoints to determine channel effectiveness and ROI',
    capabilities: {
      tools: ['get_workspace_stats', 'analyze_expenses', 'get_table_stats'],
      connectors: ['google_analytics', 'facebook_ads', 'hubspot'],
      inputTypes: ['touchpoint_data', 'conversion_events', 'ad_spend'],
      outputTypes: ['attribution_report', 'channel_roi', 'model_comparison'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 300_000,
      maxCostUsdBudget: 3.0,
    },
    persona: {
      systemPromptAddition: 'You model marketing attribution. Compare multiple models (first-touch, last-touch, linear, time-decay).',
      specialInstructions: ['Account for offline touchpoints when possible', 'Report confidence level for each model'],
    },
    icon: 'GitFork',
    color: '#A855F7',
  },
  {
    agentTypeId: 'analytics.realtime-dashboard-feeder',
    displayName: 'Realtime Dashboard Feeder',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Technical,
    baseType: AgentType.Developer,
    description: 'Feeds real-time data to dashboards by aggregating event streams and computing live metrics',
    capabilities: {
      tools: ['get_workspace_stats', 'get_table_stats', 'get_upcoming_deadlines'],
      connectors: ['kafka', 'redis', 'websocket'],
      inputTypes: ['event_stream', 'aggregation_config', 'dashboard_id'],
      outputTypes: ['live_metric', 'stream_status', 'lag_alert'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 50_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You feed real-time data to dashboards. Ensure low latency and handle backpressure gracefully.',
      specialInstructions: ['Alert if processing lag exceeds 30 seconds', 'Use windowed aggregations for efficiency'],
    },
    icon: 'Radio',
    color: '#0891B2',
  },
  {
    agentTypeId: 'analytics.survey-analyzer',
    displayName: 'Survey Analyzer',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Business,
    baseType: AgentType.Researcher,
    description: 'Analyzes survey responses, identifies themes, and generates statistical summaries with insights',
    capabilities: {
      tools: ['get_workspace_stats', 'get_table_stats', 'analyze_views'],
      connectors: ['typeform', 'surveymonkey', 'google_forms'],
      inputTypes: ['survey_responses', 'question_metadata', 'demographic_data'],
      outputTypes: ['survey_report', 'theme_analysis', 'nps_calculation'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 250_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You analyze survey data. Extract themes from open-ended responses and calculate statistical summaries.',
      specialInstructions: ['Check for response bias', 'Segment results by demographic when sample size permits'],
    },
    icon: 'ClipboardList',
    color: '#F43F5E',
  },
  {
    agentTypeId: 'analytics.geographic-heatmap',
    displayName: 'Geographic Heatmap Generator',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Business,
    baseType: AgentType.Designer,
    description: 'Generates geographic heatmaps from location-based data for sales, customers, and events',
    capabilities: {
      tools: ['get_workspace_stats', 'get_table_stats', 'analyze_views'],
      connectors: ['mapbox', 'google_maps', 'data_warehouse'],
      inputTypes: ['location_data', 'metric_value', 'geographic_boundary'],
      outputTypes: ['heatmap_visualization', 'regional_summary', 'location_ranking'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You generate geographic visualizations. Choose appropriate granularity and color scales.',
      specialInstructions: ['Normalize by population when comparing regions', 'Include data density warnings for sparse areas'],
    },
    icon: 'Map',
    color: '#059669',
  },
  {
    agentTypeId: 'analytics.etl-pipeline-monitor',
    displayName: 'ETL Pipeline Monitor',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Technical,
    baseType: AgentType.DevOps,
    description: 'Monitors ETL pipeline health, tracks data freshness, and alerts on pipeline failures',
    capabilities: {
      tools: ['get_workspace_stats', 'get_table_stats', 'analyze_database_schema'],
      connectors: ['airflow', 'dbt', 'fivetran'],
      inputTypes: ['pipeline_status', 'run_history', 'data_freshness'],
      outputTypes: ['pipeline_report', 'failure_alert', 'freshness_dashboard'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: ['restart_pipeline'],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You monitor ETL pipelines. Ensure data flows reliably and alert on failures or delays.',
      specialInstructions: ['Track SLA compliance for each pipeline', 'Identify cascading failure risks'],
    },
    icon: 'GitCompare',
    color: '#64748B',
  },
  {
    agentTypeId: 'analytics.schema-change-tracker',
    displayName: 'Schema Change Tracker',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Technical,
    baseType: AgentType.Reviewer,
    description: 'Tracks database and API schema changes, assesses downstream impact, and alerts affected teams',
    capabilities: {
      tools: ['analyze_database_schema', 'get_table_stats', 'get_workspace_stats'],
      connectors: ['data_catalog', 'schema_registry', 'github'],
      inputTypes: ['schema_diff', 'dependency_graph', 'consumer_list'],
      outputTypes: ['change_impact_report', 'breaking_change_alert', 'migration_guide'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You track schema changes. Assess downstream impact before changes are applied.',
      specialInstructions: ['Map all consumers of changed schemas', 'Classify changes as breaking or non-breaking'],
    },
    icon: 'Layers',
    color: '#B45309',
  },
  {
    agentTypeId: 'analytics.relation-map-builder',
    displayName: 'Relation Map Builder',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Technical,
    baseType: AgentType.Analyst,
    description: 'Builds visual relationship maps between database entities, showing cardinality and data flows',
    capabilities: {
      tools: ['analyze_database_schema', 'get_relation_map', 'get_table_stats'],
      connectors: ['postgresql', 'mysql', 'data_catalog'],
      inputTypes: ['schema_definition', 'foreign_keys', 'data_flow_config'],
      outputTypes: ['erd_diagram', 'relationship_report', 'data_lineage_map'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You build entity relationship maps. Show cardinality, optional vs required, and data flow direction.',
      specialInstructions: ['Highlight circular dependencies', 'Group related entities by domain'],
    },
    icon: 'Share2',
    color: '#6366F1',
  },
  {
    agentTypeId: 'analytics.automation-auditor',
    displayName: 'Automation Auditor',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Technical,
    baseType: AgentType.Reviewer,
    description: 'Audits database automations for performance, correctness, and potential data integrity issues',
    capabilities: {
      tools: ['analyze_database_schema', 'get_table_stats', 'get_workspace_stats'],
      connectors: ['zapier', 'make', 'custom_automation'],
      inputTypes: ['automation_config', 'execution_log', 'performance_metrics'],
      outputTypes: ['audit_report', 'performance_alert', 'improvement_suggestion'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You audit automations. Check for race conditions, infinite loops, and performance bottlenecks.',
      specialInstructions: ['Verify error handling in automation chains', 'Check for idempotency in retry scenarios'],
    },
    icon: 'ScanSearch',
    color: '#F59E0B',
  },
  {
    agentTypeId: 'analytics.executive-briefing',
    displayName: 'Executive Briefing Generator',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Business,
    baseType: AgentType.Writer,
    description: 'Creates concise executive briefings that distill complex analytics into board-ready summaries',
    capabilities: {
      tools: ['get_workspace_stats', 'get_invoice_summary', 'analyze_expenses', 'get_upcoming_deadlines'],
      connectors: ['google_slides', 'notion', 'pdf_generator'],
      inputTypes: ['dashboard_data', 'kpi_snapshot', 'narrative_prompt'],
      outputTypes: ['executive_briefing', 'slide_deck', 'one_pager'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['distribute_briefing'],
      maxTokenBudget: 250_000,
      maxCostUsdBudget: 2.5,
    },
    persona: {
      systemPromptAddition: 'You create executive briefings. Lead with insights, use clear visuals, and keep it to one page.',
      specialInstructions: ['Highlight deviations from plan', 'Include 3 key takeaways at the top'],
    },
    icon: 'Presentation',
    color: '#1E293B',
  },
  {
    agentTypeId: 'analytics.metric-correlation-finder',
    displayName: 'Metric Correlation Finder',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Technical,
    baseType: AgentType.Analyst,
    description: 'Discovers correlations between business metrics, identifying leading indicators and hidden relationships across data sources.',
    capabilities: {
      tools: ['get_workspace_stats', 'get_table_stats', 'analyze_expenses'],
      connectors: ['data_warehouse', 'bi_tool', 'spreadsheets'],
      inputTypes: ['metric_pairs', 'time_series_data', 'correlation_config'],
      outputTypes: ['correlation_matrix', 'leading_indicator', 'causal_hypothesis'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 250_000,
      maxCostUsdBudget: 2.5,
    },
    persona: {
      systemPromptAddition: 'You find correlations between metrics. Distinguish correlation from causation and identify actionable leading indicators.',
      specialInstructions: ['Test for both linear and non-linear relationships', 'Flag spurious correlations with low sample sizes'],
    },
    icon: 'GitBranch',
    color: '#7C3AED',
  },
  {
    agentTypeId: 'analytics.custom-report-builder',
    displayName: 'Custom Report Builder',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Business,
    baseType: AgentType.Designer,
    description: 'Builds custom reports from scratch using natural language specifications, combining multiple data sources and visualization types.',
    capabilities: {
      tools: ['get_workspace_stats', 'get_table_stats', 'analyze_expenses', 'get_invoice_summary'],
      connectors: ['data_warehouse', 'google_docs', 'notion'],
      inputTypes: ['report_spec', 'data_sources', 'layout_preference'],
      outputTypes: ['custom_report', 'report_template', 'data_model'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['publish_report'],
      maxTokenBudget: 300_000,
      maxCostUsdBudget: 3.0,
    },
    persona: {
      systemPromptAddition: 'You build custom reports from specifications. Translate business questions into structured, repeatable reports.',
      specialInstructions: ['Clarify ambiguous requirements before building', 'Make reports self-service and parameterizable'],
    },
    icon: 'FileEdit',
    color: '#2563EB',
  },
  {
    agentTypeId: 'analytics.visualization-recommender',
    displayName: 'Visualization Recommender',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Creative,
    baseType: AgentType.Designer,
    description: 'Recommends the most effective chart types and visualization approaches for different data shapes and analytical questions.',
    capabilities: {
      tools: ['get_workspace_stats', 'get_table_stats', 'analyze_views'],
      connectors: ['tableau', 'metabase', 'grafana'],
      inputTypes: ['data_shape', 'analytical_question', 'audience_type'],
      outputTypes: ['chart_recommendation', 'layout_suggestion', 'accessibility_check'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You recommend visualizations. Match chart types to data characteristics and the story being told.',
      specialInstructions: ['Avoid pie charts for more than 5 categories', 'Ensure color choices are accessible to colorblind users'],
    },
    icon: 'BarChart3',
    color: '#EC4899',
  },
  {
    agentTypeId: 'analytics.predictive-scorer',
    displayName: 'Predictive Scorer',
    domain: AgentDomain.Analytics,
    category: AgentCategory.Technical,
    baseType: AgentType.Analyst,
    description: 'Builds and applies predictive scoring models for leads, deals, customer health, and other business outcomes.',
    capabilities: {
      tools: ['get_workspace_stats', 'get_table_stats', 'analyze_database_schema'],
      connectors: ['crm', 'data_warehouse', 'mixpanel'],
      inputTypes: ['training_data', 'feature_set', 'scoring_target'],
      outputTypes: ['predictive_score', 'feature_importance', 'model_performance'],
      domains: ['analytics'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 300_000,
      maxCostUsdBudget: 5.0,
    },
    persona: {
      systemPromptAddition: 'You build predictive scoring models. Focus on interpretable models with clear feature importance.',
      specialInstructions: ['Validate models with cross-validation', 'Monitor for model drift over time'],
    },
    icon: 'Brain',
    color: '#8B5CF6',
  },
]
