import { AgentDomain, AgentCategory, AgentType, CostTier, LatencyProfile } from '../../types'
import type { AgentCapabilityManifest } from '../../types'

export const AGENTS: AgentCapabilityManifest[] = [
  {
    agentTypeId: 'communication.slack-responder',
    displayName: 'Slack Responder',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.Writer,
    description: 'Monitors Slack channels, drafts contextual responses, and escalates urgent messages',
    capabilities: {
      tools: ['send_notification', 'mark_all_read', 'get_workspace_stats'],
      connectors: ['slack', 'slack_bot'],
      inputTypes: ['slack_message', 'channel_context', 'thread_history'],
      outputTypes: ['slack_reply', 'notification', 'escalation'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: ['send_external_message'],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You respond to Slack messages on behalf of the user. Match the channel tone and be concise.',
      specialInstructions: ['Keep responses under 200 words', 'Use thread replies for detailed discussions'],
    },
    icon: 'MessageSquare',
    color: '#4A154B',
  },
  {
    agentTypeId: 'communication.email-composer',
    displayName: 'Email Composer',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.Writer,
    description: 'Drafts professional emails with appropriate tone, formatting, and follow-up scheduling',
    capabilities: {
      tools: ['send_notification', 'get_workspace_stats', 'add_contact'],
      connectors: ['gmail', 'outlook', 'sendgrid'],
      inputTypes: ['email_context', 'recipient_profile', 'draft_instructions'],
      outputTypes: ['email_draft', 'notification', 'follow_up_reminder'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['send_email'],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You compose professional emails. Adjust tone based on recipient relationship and context.',
      specialInstructions: ['Always include a clear call to action', 'Keep subject lines under 60 characters'],
    },
    icon: 'Mail',
    color: '#EA4335',
  },
  {
    agentTypeId: 'communication.teams-notifier',
    displayName: 'Teams Notifier',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.Writer,
    description: 'Sends formatted notifications and updates to Microsoft Teams channels and chats',
    capabilities: {
      tools: ['send_notification', 'mark_all_read', 'get_workspace_stats'],
      connectors: ['microsoft_teams', 'office365'],
      inputTypes: ['notification_content', 'channel_id', 'card_template'],
      outputTypes: ['teams_message', 'adaptive_card', 'notification'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 4,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You send Teams notifications. Use Adaptive Cards for structured data and plain text for quick updates.',
      specialInstructions: ['Format numbers and dates for readability', 'Include action buttons where appropriate'],
    },
    icon: 'Users',
    color: '#6264A7',
  },
  {
    agentTypeId: 'communication.whatsapp-handler',
    displayName: 'WhatsApp Handler',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.CustomerSuccess,
    description: 'Manages WhatsApp Business conversations with automated responses and human handoff',
    capabilities: {
      tools: ['send_notification', 'add_contact', 'get_workspace_stats'],
      connectors: ['whatsapp_business', 'twilio'],
      inputTypes: ['whatsapp_message', 'contact_info', 'template_id'],
      outputTypes: ['whatsapp_reply', 'handoff_request', 'notification'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: ['send_template_message'],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You handle WhatsApp Business conversations. Be friendly, concise, and respect messaging window rules.',
      specialInstructions: ['Use approved message templates for outbound', 'Handoff to human within 3 failed attempts'],
    },
    icon: 'Phone',
    color: '#25D366',
  },
  {
    agentTypeId: 'communication.webhook-dispatcher',
    displayName: 'Webhook Dispatcher',
    domain: AgentDomain.Communication,
    category: AgentCategory.Technical,
    baseType: AgentType.Developer,
    description: 'Routes and dispatches webhooks to appropriate handlers with retry logic and payload transformation',
    capabilities: {
      tools: ['send_notification', 'get_workspace_stats', 'mark_all_read'],
      connectors: ['webhook_generic', 'zapier', 'make'],
      inputTypes: ['webhook_payload', 'routing_rules', 'transform_config'],
      outputTypes: ['dispatched_event', 'delivery_report', 'notification'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 50_000,
      maxCostUsdBudget: 0.2,
    },
    persona: {
      systemPromptAddition: 'You dispatch webhooks reliably. Implement exponential backoff for retries and validate payloads.',
      specialInstructions: ['Log all dispatch attempts', 'Validate payload signatures when available'],
    },
    icon: 'Webhook',
    color: '#6366F1',
  },
  {
    agentTypeId: 'communication.multi-channel-router',
    displayName: 'Multi-Channel Router',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.Coordinator,
    description: 'Routes messages to the optimal channel based on urgency, recipient preferences, and content type',
    capabilities: {
      tools: ['send_notification', 'mark_all_read', 'get_workspace_stats'],
      connectors: ['slack', 'email', 'sms', 'teams'],
      inputTypes: ['message_content', 'recipient_preferences', 'urgency_level'],
      outputTypes: ['routed_message', 'delivery_confirmation', 'notification'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You route messages to the best channel. Consider time zones, channel preferences, and message urgency.',
      specialInstructions: ['Never send SMS for non-urgent messages', 'Prefer async channels outside business hours'],
    },
    icon: 'Route',
    color: '#0EA5E9',
  },
  {
    agentTypeId: 'communication.meeting-notes-scribe',
    displayName: 'Meeting Notes Scribe',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.Writer,
    description: 'Transcribes meeting discussions, extracts action items, and distributes formatted summaries',
    capabilities: {
      tools: ['send_notification', 'get_workspace_stats', 'add_contact'],
      connectors: ['zoom', 'google_meet', 'otter_ai'],
      inputTypes: ['transcript', 'meeting_metadata', 'attendee_list'],
      outputTypes: ['meeting_summary', 'action_items', 'notification'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['distribute_notes'],
      maxTokenBudget: 300_000,
      maxCostUsdBudget: 3.0,
    },
    persona: {
      systemPromptAddition: 'You create meeting summaries. Focus on decisions made, action items assigned, and key discussion points.',
      specialInstructions: ['Assign owners to every action item', 'Include timestamps for key decisions'],
    },
    icon: 'ClipboardPen',
    color: '#8B5CF6',
  },
  {
    agentTypeId: 'communication.digest-compiler',
    displayName: 'Digest Compiler',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.Writer,
    description: 'Compiles daily or weekly digests from multiple communication channels into a single summary',
    capabilities: {
      tools: ['send_notification', 'mark_all_read', 'get_workspace_stats'],
      connectors: ['slack', 'email', 'teams', 'github'],
      inputTypes: ['channel_messages', 'email_threads', 'notification_feed'],
      outputTypes: ['digest_email', 'summary_card', 'notification'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You compile communication digests. Prioritize items by importance and group by topic.',
      specialInstructions: ['Highlight items that need response', 'Deduplicate cross-channel mentions'],
    },
    icon: 'Newspaper',
    color: '#F59E0B',
  },
  {
    agentTypeId: 'communication.sms-gateway',
    displayName: 'SMS Gateway',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.Developer,
    description: 'Sends and receives SMS messages with delivery tracking and opt-out management',
    capabilities: {
      tools: ['send_notification', 'add_contact', 'get_workspace_stats'],
      connectors: ['twilio', 'vonage', 'messagebird'],
      inputTypes: ['phone_number', 'message_content', 'template_id'],
      outputTypes: ['sms_delivery_report', 'opt_out_confirmation', 'notification'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: ['send_bulk_sms'],
      maxTokenBudget: 50_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You manage SMS communications. Respect opt-out lists and comply with TCPA regulations.',
      specialInstructions: ['Keep messages under 160 characters when possible', 'Always include opt-out instructions'],
    },
    icon: 'Smartphone',
    color: '#10B981',
  },
  {
    agentTypeId: 'communication.notification-triage',
    displayName: 'Notification Triage',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Triages incoming notifications by priority, groups related alerts, and suppresses duplicates',
    capabilities: {
      tools: ['send_notification', 'mark_all_read', 'get_workspace_stats'],
      connectors: ['slack', 'email', 'pagerduty', 'jira'],
      inputTypes: ['notification_stream', 'priority_rules', 'suppression_config'],
      outputTypes: ['triaged_notification', 'suppression_report', 'priority_alert'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You triage notifications to reduce noise. Group related alerts and highlight truly urgent items.',
      specialInstructions: ['Suppress duplicate alerts within 15-minute window', 'Escalate if 3+ related alerts in 5 minutes'],
    },
    icon: 'BellRing',
    color: '#DC2626',
  },
  {
    agentTypeId: 'communication.announcement-broadcaster',
    displayName: 'Announcement Broadcaster',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.Writer,
    description: 'Creates and broadcasts company announcements across multiple channels with read tracking',
    capabilities: {
      tools: ['send_notification', 'get_workspace_stats', 'mark_all_read'],
      connectors: ['slack', 'email', 'teams', 'intranet'],
      inputTypes: ['announcement_draft', 'audience_list', 'channel_config'],
      outputTypes: ['broadcast_confirmation', 'read_receipt_report', 'notification'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['broadcast_announcement'],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You broadcast announcements. Ensure consistent messaging across all channels and track engagement.',
      specialInstructions: ['Adapt format for each channel', 'Schedule sends for optimal open rates'],
    },
    icon: 'Megaphone',
    color: '#F97316',
  },
  {
    agentTypeId: 'communication.template-manager',
    displayName: 'Template Manager',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.Writer,
    description: 'Creates, maintains, and personalizes message templates for all communication channels',
    capabilities: {
      tools: ['send_notification', 'get_workspace_stats', 'add_contact'],
      connectors: ['sendgrid', 'mailchimp', 'intercom'],
      inputTypes: ['template_request', 'brand_guidelines', 'variable_data'],
      outputTypes: ['message_template', 'personalized_message', 'template_library'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You manage message templates. Keep templates on-brand, accessible, and personalization-ready.',
      specialInstructions: ['Test templates across email clients', 'Include fallback for missing variables'],
    },
    icon: 'FileTemplate',
    color: '#2563EB',
  },
  {
    agentTypeId: 'communication.sentiment-monitor',
    displayName: 'Sentiment Monitor',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Monitors communication sentiment across channels and alerts on negative trends or escalations',
    capabilities: {
      tools: ['send_notification', 'get_workspace_stats', 'mark_all_read'],
      connectors: ['slack', 'zendesk', 'intercom'],
      inputTypes: ['message_stream', 'sentiment_rules', 'baseline_data'],
      outputTypes: ['sentiment_report', 'escalation_alert', 'trend_analysis'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You monitor communication sentiment. Detect frustration, urgency, and dissatisfaction early.',
      specialInstructions: ['Baseline sentiment per channel before alerting', 'Consider cultural and contextual nuances'],
    },
    icon: 'HeartPulse',
    color: '#EC4899',
  },
  {
    agentTypeId: 'communication.calendar-invite-sender',
    displayName: 'Calendar Invite Sender',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.Coordinator,
    description: 'Sends calendar invitations with agenda, location details, and RSVP tracking',
    capabilities: {
      tools: ['send_notification', 'create_booking', 'add_contact'],
      connectors: ['google_calendar', 'outlook_calendar', 'calendly'],
      inputTypes: ['meeting_details', 'attendee_list', 'agenda'],
      outputTypes: ['calendar_invite', 'rsvp_summary', 'notification'],
      domains: ['communication', 'scheduling'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You send calendar invitations. Include clear agendas and timezone-aware scheduling.',
      specialInstructions: ['Always include video conferencing link', 'Check for scheduling conflicts before sending'],
    },
    icon: 'CalendarPlus',
    color: '#059669',
  },
  {
    agentTypeId: 'communication.feedback-collector',
    displayName: 'Feedback Collector',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.Researcher,
    description: 'Collects, categorizes, and analyzes feedback from customers, employees, and stakeholders',
    capabilities: {
      tools: ['send_notification', 'get_workspace_stats', 'add_contact'],
      connectors: ['typeform', 'surveymonkey', 'intercom'],
      inputTypes: ['survey_response', 'feedback_form', 'nps_score'],
      outputTypes: ['feedback_summary', 'trend_report', 'notification'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You collect and analyze feedback. Identify themes, track NPS trends, and surface actionable insights.',
      specialInstructions: ['Group feedback by theme before reporting', 'Highlight verbatim quotes that illustrate key issues'],
    },
    icon: 'MessageCircle',
    color: '#14B8A6',
  },
  {
    agentTypeId: 'communication.translation-relay',
    displayName: 'Translation Relay',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.Translation,
    description: 'Translates messages in real-time across communication channels while preserving tone and context',
    capabilities: {
      tools: ['send_notification', 'get_workspace_stats', 'mark_all_read'],
      connectors: ['deepl', 'google_translate', 'slack'],
      inputTypes: ['message_text', 'source_language', 'target_language'],
      outputTypes: ['translated_message', 'language_detection', 'notification'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You translate messages between languages. Preserve tone, idioms, and cultural context.',
      specialInstructions: ['Detect language automatically when not specified', 'Flag untranslatable terms with explanation'],
    },
    icon: 'Languages',
    color: '#7C3AED',
  },
  {
    agentTypeId: 'communication.out-of-office-manager',
    displayName: 'Out of Office Manager',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.Coordinator,
    description: 'Manages out-of-office replies, delegates urgent requests, and buffers non-urgent messages',
    capabilities: {
      tools: ['send_notification', 'mark_all_read', 'get_workspace_stats'],
      connectors: ['email', 'slack', 'teams'],
      inputTypes: ['ooo_config', 'incoming_message', 'delegation_rules'],
      outputTypes: ['auto_reply', 'delegation_request', 'notification'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 50_000,
      maxCostUsdBudget: 0.2,
    },
    persona: {
      systemPromptAddition: 'You manage out-of-office communications. Route urgent items to delegates and buffer the rest.',
      specialInstructions: ['Classify urgency based on sender and keywords', 'Provide return date in auto-replies'],
    },
    icon: 'PalmTree',
    color: '#F59E0B',
  },
  {
    agentTypeId: 'communication.thread-summarizer',
    displayName: 'Thread Summarizer',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Summarizes long email threads and Slack conversations into concise, actionable summaries',
    capabilities: {
      tools: ['send_notification', 'mark_all_read', 'get_workspace_stats'],
      connectors: ['slack', 'gmail', 'outlook'],
      inputTypes: ['email_thread', 'slack_thread', 'conversation_history'],
      outputTypes: ['thread_summary', 'action_items', 'notification'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 4,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You summarize long conversation threads. Extract key decisions, disagreements, and next steps.',
      specialInstructions: ['Identify who said what on key decisions', 'Flag unresolved questions'],
    },
    icon: 'ListCollapse',
    color: '#3B82F6',
  },
  {
    agentTypeId: 'communication.escalation-manager',
    displayName: 'Escalation Manager',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.Coordinator,
    description: 'Detects when conversations need escalation and routes them to the appropriate decision-maker',
    capabilities: {
      tools: ['send_notification', 'mark_all_read', 'get_workspace_stats'],
      connectors: ['slack', 'pagerduty', 'jira'],
      inputTypes: ['conversation_context', 'escalation_rules', 'org_chart'],
      outputTypes: ['escalation_request', 'routing_decision', 'notification'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: ['escalate_to_executive'],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You manage escalations. Determine the right person and urgency level based on context and policy.',
      specialInstructions: ['Include context summary in escalation', 'Track response time after escalation'],
    },
    icon: 'ArrowUpCircle',
    color: '#EF4444',
  },
  {
    agentTypeId: 'communication.contact-enricher',
    displayName: 'Contact Enricher',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.Researcher,
    description: 'Enriches contact records with public data, social profiles, and communication history',
    capabilities: {
      tools: ['add_contact', 'get_workspace_stats', 'send_notification'],
      connectors: ['clearbit', 'linkedin', 'hunter_io'],
      inputTypes: ['email_address', 'company_name', 'partial_contact'],
      outputTypes: ['enriched_contact', 'company_profile', 'notification'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You enrich contact data. Verify data accuracy and respect privacy regulations.',
      specialInstructions: ['Only use publicly available data', 'Flag stale data older than 6 months'],
    },
    icon: 'UserPlus',
    color: '#0891B2',
  },
  {
    agentTypeId: 'communication.discord-moderator',
    displayName: 'Discord Moderator',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.Reviewer,
    description: 'Moderates Discord community servers by enforcing rules, filtering content, and welcoming members',
    capabilities: {
      tools: ['send_notification', 'mark_all_read', 'get_workspace_stats'],
      connectors: ['discord', 'discord_bot'],
      inputTypes: ['discord_message', 'member_profile', 'moderation_rules'],
      outputTypes: ['moderation_action', 'welcome_message', 'notification'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: ['ban_member'],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You moderate Discord servers. Be fair, consistent, and educational rather than punitive.',
      specialInstructions: ['Warn before taking action on first offense', 'Log all moderation actions'],
    },
    icon: 'Shield',
    color: '#5865F2',
  },
  {
    agentTypeId: 'communication.chatbot-orchestrator',
    displayName: 'Chatbot Orchestrator',
    domain: AgentDomain.Communication,
    category: AgentCategory.Technical,
    baseType: AgentType.Coordinator,
    description: 'Orchestrates chatbot conversations across platforms, handling handoffs and context preservation',
    capabilities: {
      tools: ['send_notification', 'get_workspace_stats', 'add_contact'],
      connectors: ['intercom', 'drift', 'zendesk_chat'],
      inputTypes: ['chat_session', 'visitor_context', 'routing_rules'],
      outputTypes: ['chat_response', 'handoff_request', 'session_summary'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You orchestrate chatbot conversations. Maintain context across handoffs and escalate appropriately.',
      specialInstructions: ['Preserve full conversation context during handoff', 'Detect when bot cannot handle query'],
    },
    icon: 'Bot',
    color: '#0EA5E9',
  },
  {
    agentTypeId: 'communication.voice-transcriber',
    displayName: 'Voice Transcriber',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.Writer,
    description: 'Transcribes voice messages and calls, extracting key information and action items',
    capabilities: {
      tools: ['send_notification', 'get_workspace_stats', 'mark_all_read'],
      connectors: ['whisper', 'deepgram', 'assembly_ai'],
      inputTypes: ['audio_file', 'voice_message', 'call_recording'],
      outputTypes: ['transcript', 'summary', 'action_items'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You transcribe voice communications. Ensure accuracy and mark low-confidence sections.',
      specialInstructions: ['Identify speakers when possible', 'Timestamp key discussion points'],
    },
    icon: 'Mic',
    color: '#D946EF',
  },
  {
    agentTypeId: 'communication.follow-up-tracker',
    displayName: 'Follow-Up Tracker',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.Coordinator,
    description: 'Tracks pending follow-ups across all channels and sends reminders when deadlines approach',
    capabilities: {
      tools: ['send_notification', 'mark_all_read', 'get_workspace_stats'],
      connectors: ['gmail', 'slack', 'crm'],
      inputTypes: ['follow_up_commitment', 'deadline', 'conversation_context'],
      outputTypes: ['reminder', 'overdue_alert', 'follow_up_report'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You track follow-ups. Send timely reminders and highlight overdue items.',
      specialInstructions: ['Detect implicit commitments in conversations', 'Escalate after 2 missed follow-ups'],
    },
    icon: 'Clock',
    color: '#F97316',
  },
  {
    agentTypeId: 'communication.internal-comms-writer',
    displayName: 'Internal Comms Writer',
    domain: AgentDomain.Communication,
    category: AgentCategory.Creative,
    baseType: AgentType.Writer,
    description: 'Drafts internal communications including newsletters, policy updates, and team spotlights',
    capabilities: {
      tools: ['send_notification', 'get_workspace_stats', 'add_contact'],
      connectors: ['mailchimp', 'notion', 'confluence'],
      inputTypes: ['topic_brief', 'company_updates', 'team_highlights'],
      outputTypes: ['newsletter_draft', 'policy_update', 'spotlight_article'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['publish_newsletter'],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You write internal communications. Be engaging, clear, and aligned with company culture.',
      specialInstructions: ['Use company voice and tone guidelines', 'Include visuals and section headers for scannability'],
    },
    icon: 'PenLine',
    color: '#8B5CF6',
  },
  {
    agentTypeId: 'communication.channel-analytics',
    displayName: 'Channel Analytics',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Analyzes communication channel usage, engagement, and effectiveness metrics',
    capabilities: {
      tools: ['get_workspace_stats', 'send_notification', 'mark_all_read'],
      connectors: ['slack_analytics', 'email_analytics', 'teams_analytics'],
      inputTypes: ['channel_metrics', 'engagement_data', 'usage_logs'],
      outputTypes: ['channel_report', 'engagement_dashboard', 'recommendation'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You analyze communication channels. Identify underutilized channels and engagement bottlenecks.',
      specialInstructions: ['Compare channel effectiveness by message type', 'Track response time trends'],
    },
    icon: 'BarChart3',
    color: '#059669',
  },
  {
    agentTypeId: 'communication.approval-workflow-bot',
    displayName: 'Approval Workflow Bot',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.Coordinator,
    description: 'Manages approval workflows by routing requests, collecting decisions, and tracking status',
    capabilities: {
      tools: ['send_notification', 'mark_all_read', 'get_workspace_stats'],
      connectors: ['slack', 'email', 'jira'],
      inputTypes: ['approval_request', 'approver_chain', 'decision'],
      outputTypes: ['approval_status', 'reminder', 'workflow_report'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You manage approval workflows. Track pending approvals and send timely reminders.',
      specialInstructions: ['Escalate stale approvals after configured timeout', 'Log full approval chain for audit'],
    },
    icon: 'CheckSquare',
    color: '#10B981',
  },
  {
    agentTypeId: 'communication.crisis-communicator',
    displayName: 'Crisis Communicator',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.Writer,
    description: 'Drafts crisis communication messages with appropriate urgency, empathy, and action steps',
    capabilities: {
      tools: ['send_notification', 'get_workspace_stats', 'mark_all_read'],
      connectors: ['email', 'slack', 'statuspage', 'twitter'],
      inputTypes: ['incident_details', 'stakeholder_list', 'response_template'],
      outputTypes: ['crisis_message', 'status_update', 'notification'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: ['publish_crisis_message'],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You draft crisis communications. Be transparent, empathetic, and action-oriented.',
      specialInstructions: ['Include what happened, what is being done, and next steps', 'Review with legal before external publication'],
    },
    icon: 'AlertTriangle',
    color: '#DC2626',
  },
  {
    agentTypeId: 'communication.customer-reply-drafter',
    displayName: 'Customer Reply Drafter',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.CustomerSuccess,
    description: 'Drafts empathetic and helpful customer reply emails based on ticket context and knowledge base',
    capabilities: {
      tools: ['send_notification', 'get_workspace_stats', 'add_contact'],
      connectors: ['zendesk', 'freshdesk', 'helpscout'],
      inputTypes: ['support_ticket', 'customer_history', 'knowledge_base_article'],
      outputTypes: ['reply_draft', 'suggested_article', 'notification'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['send_customer_reply'],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You draft customer replies. Be empathetic, solution-oriented, and match the customer communication style.',
      specialInstructions: ['Reference relevant KB articles', 'Offer next steps and escalation path'],
    },
    icon: 'Reply',
    color: '#0891B2',
  },
  {
    agentTypeId: 'communication.onboarding-welcomer',
    displayName: 'Onboarding Welcomer',
    domain: AgentDomain.Communication,
    category: AgentCategory.People,
    baseType: AgentType.HR,
    description: 'Sends personalized onboarding welcome messages and guides new members through initial setup',
    capabilities: {
      tools: ['send_notification', 'add_contact', 'get_workspace_stats'],
      connectors: ['slack', 'email', 'notion'],
      inputTypes: ['new_member_info', 'onboarding_checklist', 'team_context'],
      outputTypes: ['welcome_message', 'checklist_assignment', 'notification'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You welcome new team members. Be warm, informative, and guide them through their first steps.',
      specialInstructions: ['Personalize based on role and team', 'Include key contacts and resources'],
    },
    icon: 'HandWave',
    color: '#F59E0B',
  },
  {
    agentTypeId: 'communication.availability-coordinator',
    displayName: 'Availability Coordinator',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.Coordinator,
    description: 'Coordinates availability across team members to find optimal meeting times and reduce scheduling friction',
    capabilities: {
      tools: ['create_booking', 'send_notification', 'get_workspace_stats'],
      connectors: ['google_calendar', 'outlook_calendar', 'calendly'],
      inputTypes: ['attendee_list', 'time_preferences', 'calendar_data'],
      outputTypes: ['available_slots', 'scheduling_suggestion', 'notification'],
      domains: ['communication', 'scheduling'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You coordinate scheduling. Consider time zones, working hours, and meeting load balance.',
      specialInstructions: ['Minimize context-switching for attendees', 'Respect focus time blocks'],
    },
    icon: 'CalendarClock',
    color: '#6366F1',
  },
  {
    agentTypeId: 'communication.broadcast-scheduler',
    displayName: 'Broadcast Scheduler',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.Marketing,
    description: 'Schedules mass communications at optimal times based on audience engagement data',
    capabilities: {
      tools: ['send_notification', 'get_workspace_stats', 'mark_all_read'],
      connectors: ['mailchimp', 'sendgrid', 'customer_io'],
      inputTypes: ['broadcast_content', 'audience_segment', 'engagement_history'],
      outputTypes: ['scheduled_broadcast', 'send_time_prediction', 'notification'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['send_broadcast'],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You schedule broadcasts for maximum engagement. Optimize send times per audience segment.',
      specialInstructions: ['A/B test subject lines for large sends', 'Respect quiet hours and time zones'],
    },
    icon: 'Timer',
    color: '#CA8A04',
  },
  {
    agentTypeId: 'communication.compliance-message-scanner',
    displayName: 'Compliance Message Scanner',
    domain: AgentDomain.Communication,
    category: AgentCategory.Legal,
    baseType: AgentType.Compliance,
    description: 'Scans outgoing communications for compliance violations, PII exposure, and regulatory issues',
    capabilities: {
      tools: ['send_notification', 'get_workspace_stats', 'mark_all_read'],
      connectors: ['email_gateway', 'slack', 'dlp_engine'],
      inputTypes: ['outgoing_message', 'compliance_rules', 'pii_patterns'],
      outputTypes: ['compliance_flag', 'blocked_message', 'audit_log'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You scan messages for compliance issues. Block messages containing PII or violating regulations.',
      specialInstructions: ['Check for SSN, credit card, and health data patterns', 'Log all blocked messages for audit'],
    },
    icon: 'ScanLine',
    color: '#64748B',
  },
  {
    agentTypeId: 'communication.response-time-monitor',
    displayName: 'Response Time Monitor',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Monitors response times across channels and alerts when SLA thresholds are at risk',
    capabilities: {
      tools: ['send_notification', 'mark_all_read', 'get_workspace_stats'],
      connectors: ['zendesk', 'intercom', 'slack'],
      inputTypes: ['message_timestamps', 'sla_config', 'team_schedule'],
      outputTypes: ['sla_report', 'breach_alert', 'response_time_dashboard'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You monitor response time SLAs. Alert before breaches happen, not after.',
      specialInstructions: ['Calculate time-to-first-response and time-to-resolution', 'Account for business hours in SLA calculations'],
    },
    icon: 'Gauge',
    color: '#EF4444',
  },
  {
    agentTypeId: 'communication.social-mention-tracker',
    displayName: 'Social Mention Tracker',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.SocialMedia,
    description: 'Tracks brand mentions across social media platforms and routes them for response',
    capabilities: {
      tools: ['send_notification', 'get_workspace_stats', 'add_contact'],
      connectors: ['twitter', 'linkedin', 'reddit'],
      inputTypes: ['social_mention', 'brand_keywords', 'sentiment_data'],
      outputTypes: ['mention_alert', 'engagement_suggestion', 'notification'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['post_social_reply'],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You track social media mentions. Prioritize negative mentions and engagement opportunities.',
      specialInstructions: ['Flag negative mentions with high reach immediately', 'Suggest response tone based on mention sentiment'],
    },
    icon: 'AtSign',
    color: '#1DA1F2',
  },
  {
    agentTypeId: 'communication.inbox-zero-assistant',
    displayName: 'Inbox Zero Assistant',
    domain: AgentDomain.Communication,
    category: AgentCategory.Business,
    baseType: AgentType.Planner,
    description: 'Helps achieve inbox zero by categorizing, prioritizing, and suggesting bulk actions for emails',
    capabilities: {
      tools: ['mark_all_read', 'send_notification', 'get_workspace_stats'],
      connectors: ['gmail', 'outlook', 'fastmail'],
      inputTypes: ['email_inbox', 'priority_rules', 'action_preferences'],
      outputTypes: ['categorized_inbox', 'bulk_action_suggestion', 'priority_list'],
      domains: ['communication'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['bulk_archive', 'bulk_delete'],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You help manage email overload. Categorize emails and suggest efficient batch processing actions.',
      specialInstructions: ['Never auto-delete without approval', 'Highlight emails from VIP senders'],
    },
    icon: 'Inbox',
    color: '#4F46E5',
  },
]
