import { AgentDomain, AgentCategory, AgentType, CostTier, LatencyProfile } from '../../types'
import type { AgentCapabilityManifest } from '../../types'

export const AGENTS: AgentCapabilityManifest[] = [
  {
    agentTypeId: 'cross-module.deadline-aggregator',
    displayName: 'Deadline Aggregator',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Core,
    baseType: AgentType.Coordinator,
    description: 'Aggregates deadlines from projects, bookings, invoices, and tasks into a unified timeline view',
    capabilities: {
      tools: ['get_upcoming_deadlines', 'list_issues', 'list_bookings', 'get_invoice_summary'],
      connectors: ['google_calendar', 'jira', 'asana'],
      inputTypes: ['deadline_source', 'date_range', 'priority_filter'],
      outputTypes: ['unified_timeline', 'deadline_alert', 'priority_list'],
      domains: ['cross-module', 'projects', 'scheduling', 'accounting'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You aggregate deadlines across all modules. Surface conflicts and approaching deadlines proactively.',
      specialInstructions: ['Highlight overlapping deadlines', 'Show buffer time between consecutive deadlines'],
    },
    icon: 'CalendarClock',
    color: '#EF4444',
  },
  {
    agentTypeId: 'cross-module.cross-module-linker',
    displayName: 'Cross-Module Linker',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Core,
    baseType: AgentType.Coordinator,
    description: 'Creates and maintains bidirectional links between related items across different modules',
    capabilities: {
      tools: ['get_workspace_stats', 'list_issues', 'search_pages', 'get_invoice_summary'],
      connectors: ['notion', 'linear', 'quickbooks'],
      inputTypes: ['source_item', 'target_module', 'relationship_type'],
      outputTypes: ['link_record', 'related_items', 'link_graph'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You create cross-module links. Keep the relationship graph accurate and bidirectional.',
      specialInstructions: ['Suggest links based on content similarity', 'Clean up orphaned links periodically'],
    },
    icon: 'Link',
    color: '#6366F1',
  },
  {
    agentTypeId: 'cross-module.workflow-orchestrator',
    displayName: 'Workflow Orchestrator',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Core,
    baseType: AgentType.Coordinator,
    description: 'Orchestrates multi-step workflows that span multiple modules, handling data passing and error recovery',
    capabilities: {
      tools: ['get_workspace_stats', 'list_issues', 'list_bookings', 'get_invoice_summary'],
      connectors: ['zapier', 'make', 'n8n'],
      inputTypes: ['workflow_definition', 'trigger_event', 'context_data'],
      outputTypes: ['workflow_status', 'step_result', 'error_recovery_plan'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['execute_destructive_step'],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You orchestrate cross-module workflows. Handle failures gracefully and ensure data consistency.',
      specialInstructions: ['Implement compensation logic for failed steps', 'Log all state transitions'],
    },
    icon: 'Workflow',
    color: '#4F46E5',
  },
  {
    agentTypeId: 'cross-module.context-summarizer',
    displayName: 'Context Summarizer',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Core,
    baseType: AgentType.Writer,
    description: 'Summarizes context from multiple modules to provide a holistic view of a project, client, or initiative',
    capabilities: {
      tools: ['get_workspace_stats', 'search_pages', 'list_issues', 'get_invoice_summary'],
      connectors: ['notion', 'linear', 'crm'],
      inputTypes: ['entity_id', 'module_list', 'summary_depth'],
      outputTypes: ['context_summary', 'activity_timeline', 'key_metrics'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 250_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You summarize context across modules. Provide a 360-degree view with key highlights.',
      specialInstructions: ['Include recent activity from each module', 'Highlight items needing attention'],
    },
    icon: 'FileText',
    color: '#3B82F6',
  },
  {
    agentTypeId: 'cross-module.priority-router',
    displayName: 'Priority Router',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Core,
    baseType: AgentType.Planner,
    description: 'Routes and prioritizes work items across modules based on urgency, dependencies, and resource availability',
    capabilities: {
      tools: ['get_upcoming_deadlines', 'list_issues', 'get_workspace_stats', 'list_bookings'],
      connectors: ['linear', 'asana', 'jira'],
      inputTypes: ['work_item', 'priority_criteria', 'resource_availability'],
      outputTypes: ['priority_queue', 'routing_decision', 'workload_balance'],
      domains: ['cross-module', 'projects'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You route and prioritize work. Balance urgency with importance and consider team capacity.',
      specialInstructions: ['Factor in dependencies when prioritizing', 'Redistribute when team members are overloaded'],
    },
    icon: 'ArrowUpDown',
    color: '#F59E0B',
  },
  {
    agentTypeId: 'cross-module.daily-standup-compiler',
    displayName: 'Daily Standup Compiler',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Core,
    baseType: AgentType.Writer,
    description: 'Compiles daily standup reports by aggregating activity from all modules for each team member',
    capabilities: {
      tools: ['get_workspace_stats', 'list_issues', 'get_upcoming_deadlines', 'list_bookings'],
      connectors: ['slack', 'linear', 'github'],
      inputTypes: ['team_roster', 'date_range', 'activity_feed'],
      outputTypes: ['standup_report', 'blocker_list', 'progress_summary'],
      domains: ['cross-module', 'projects'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You compile daily standups. Focus on what was done, what is planned, and blockers.',
      specialInstructions: ['Auto-detect blockers from stale items', 'Keep per-person summary under 5 bullet points'],
    },
    icon: 'Sun',
    color: '#F97316',
  },
  {
    agentTypeId: 'cross-module.resource-allocator',
    displayName: 'Resource Allocator',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Business,
    baseType: AgentType.Planner,
    description: 'Optimizes resource allocation across projects, considering skills, availability, and project priorities',
    capabilities: {
      tools: ['list_issues', 'list_bookings', 'get_workspace_stats', 'get_upcoming_deadlines'],
      connectors: ['resource_planner', 'hr_system', 'project_tool'],
      inputTypes: ['resource_pool', 'project_demands', 'skill_matrix'],
      outputTypes: ['allocation_plan', 'utilization_report', 'conflict_resolution'],
      domains: ['cross-module', 'projects', 'scheduling'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['reassign_resource'],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You allocate resources across projects. Balance workload and match skills to requirements.',
      specialInstructions: ['Avoid over-allocating individuals above 80%', 'Consider ramp-up time for context switching'],
    },
    icon: 'Users',
    color: '#0891B2',
  },
  {
    agentTypeId: 'cross-module.search-orchestrator',
    displayName: 'Search Orchestrator',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Core,
    baseType: AgentType.Researcher,
    description: 'Orchestrates federated search across all modules, ranking results by relevance and recency',
    capabilities: {
      tools: ['search_pages', 'list_issues', 'get_workspace_stats', 'list_bookings'],
      connectors: ['elasticsearch', 'algolia', 'typesense'],
      inputTypes: ['search_query', 'module_filter', 'date_filter'],
      outputTypes: ['search_results', 'result_ranking', 'suggestion'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You orchestrate cross-module search. Rank results by relevance and respect access permissions.',
      specialInstructions: ['Boost recent results', 'Include result type and module in response'],
    },
    icon: 'Search',
    color: '#8B5CF6',
  },
  {
    agentTypeId: 'cross-module.notification-aggregator',
    displayName: 'Notification Aggregator',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Core,
    baseType: AgentType.Coordinator,
    description: 'Aggregates notifications from all modules, deduplicates, prioritizes, and batches delivery',
    capabilities: {
      tools: ['get_workspace_stats', 'get_upcoming_deadlines', 'list_issues'],
      connectors: ['notification_service', 'push_gateway', 'email'],
      inputTypes: ['notification_event', 'preference_config', 'batch_rules'],
      outputTypes: ['batched_notification', 'priority_alert', 'digest'],
      domains: ['cross-module', 'communication'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 50_000,
      maxCostUsdBudget: 0.2,
    },
    persona: {
      systemPromptAddition: 'You aggregate notifications. Reduce noise by batching and deduplicating while preserving urgency.',
      specialInstructions: ['Never batch critical alerts', 'Group related notifications within 5-minute windows'],
    },
    icon: 'Bell',
    color: '#DC2626',
  },
  {
    agentTypeId: 'cross-module.onboarding-guide',
    displayName: 'Onboarding Guide',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.People,
    baseType: AgentType.HR,
    description: 'Guides new users through workspace setup by configuring relevant modules and creating starter content',
    capabilities: {
      tools: ['get_workspace_stats', 'search_pages', 'list_issues', 'list_bookings'],
      connectors: ['notion', 'slack', 'email'],
      inputTypes: ['user_role', 'team_config', 'onboarding_template'],
      outputTypes: ['setup_checklist', 'welcome_content', 'progress_tracker'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You guide new users through onboarding. Make setup feel effortless and personalized.',
      specialInstructions: ['Customize steps based on role', 'Track completion and nudge on stalled steps'],
    },
    icon: 'Compass',
    color: '#059669',
  },
  {
    agentTypeId: 'cross-module.weekly-digest-creator',
    displayName: 'Weekly Digest Creator',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Business,
    baseType: AgentType.Writer,
    description: 'Creates weekly workspace digests summarizing progress, highlights, and upcoming deadlines across all modules',
    capabilities: {
      tools: ['get_workspace_stats', 'get_upcoming_deadlines', 'list_issues', 'analyze_expenses'],
      connectors: ['email', 'slack', 'notion'],
      inputTypes: ['date_range', 'team_filter', 'highlight_criteria'],
      outputTypes: ['weekly_digest', 'highlight_reel', 'deadline_summary'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['distribute_digest'],
      maxTokenBudget: 250_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You create weekly digests. Highlight wins, flag risks, and preview the week ahead.',
      specialInstructions: ['Include team shoutouts when milestones are hit', 'Keep the digest scannable in under 3 minutes'],
    },
    icon: 'Newspaper',
    color: '#4F46E5',
  },
  {
    agentTypeId: 'cross-module.dependency-tracker',
    displayName: 'Dependency Tracker',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Tracks dependencies between items across modules and alerts when blockers affect downstream work',
    capabilities: {
      tools: ['list_issues', 'get_upcoming_deadlines', 'get_workspace_stats', 'list_bookings'],
      connectors: ['linear', 'jira', 'asana'],
      inputTypes: ['dependency_definition', 'status_change', 'blocker_event'],
      outputTypes: ['dependency_graph', 'blocker_alert', 'impact_analysis'],
      domains: ['cross-module', 'projects'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You track cross-module dependencies. Alert immediately when a blocker impacts downstream work.',
      specialInstructions: ['Calculate critical path through dependency chains', 'Estimate delay propagation'],
    },
    icon: 'GitBranch',
    color: '#F43F5E',
  },
  {
    agentTypeId: 'cross-module.capacity-planner',
    displayName: 'Capacity Planner',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Business,
    baseType: AgentType.Planner,
    description: 'Plans team capacity by analyzing workload across projects, meetings, and recurring commitments',
    capabilities: {
      tools: ['list_issues', 'list_bookings', 'get_upcoming_deadlines', 'get_workspace_stats'],
      connectors: ['resource_planner', 'google_calendar', 'linear'],
      inputTypes: ['team_roster', 'workload_data', 'calendar_events'],
      outputTypes: ['capacity_report', 'overload_alert', 'rebalance_suggestion'],
      domains: ['cross-module', 'projects', 'scheduling'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You plan team capacity. Account for meetings, focus time, and sprint commitments.',
      specialInstructions: ['Subtract meeting hours from available capacity', 'Flag individuals above 90% utilization'],
    },
    icon: 'BarChart3',
    color: '#0EA5E9',
  },
  {
    agentTypeId: 'cross-module.audit-trail-builder',
    displayName: 'Audit Trail Builder',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Legal,
    baseType: AgentType.Compliance,
    description: 'Builds comprehensive audit trails by correlating actions across modules into a unified event log',
    capabilities: {
      tools: ['get_workspace_stats', 'list_issues', 'search_pages', 'get_invoice_summary'],
      connectors: ['audit_log', 'event_store', 'compliance_platform'],
      inputTypes: ['event_source', 'entity_id', 'date_range'],
      outputTypes: ['audit_trail', 'compliance_report', 'event_timeline'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You build audit trails. Ensure every action is traceable with who, what, when, and why.',
      specialInstructions: ['Correlate events by entity across modules', 'Ensure immutability of audit records'],
    },
    icon: 'ScrollText',
    color: '#475569',
  },
  {
    agentTypeId: 'cross-module.data-sync-monitor',
    displayName: 'Data Sync Monitor',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Technical,
    baseType: AgentType.DevOps,
    description: 'Monitors data synchronization between modules and external systems, detecting drift and conflicts',
    capabilities: {
      tools: ['get_workspace_stats', 'list_issues', 'get_invoice_summary'],
      connectors: ['sync_engine', 'event_bus', 'database'],
      inputTypes: ['sync_config', 'data_source', 'conflict_log'],
      outputTypes: ['sync_status', 'drift_alert', 'conflict_resolution'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: ['force_sync'],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You monitor data sync. Detect drift between modules and resolve conflicts deterministically.',
      specialInstructions: ['Use last-write-wins as default conflict resolution', 'Alert on sync lag exceeding 5 minutes'],
    },
    icon: 'RefreshCcw',
    color: '#10B981',
  },
  {
    agentTypeId: 'cross-module.impact-analyzer',
    displayName: 'Impact Analyzer',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Analyzes the cross-module impact of changes, showing how modifications in one area affect others',
    capabilities: {
      tools: ['get_workspace_stats', 'list_issues', 'search_pages', 'get_upcoming_deadlines'],
      connectors: ['dependency_graph', 'event_bus', 'notification_service'],
      inputTypes: ['change_event', 'entity_graph', 'module_config'],
      outputTypes: ['impact_report', 'affected_items', 'risk_assessment'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You analyze cross-module impact. Trace how changes propagate and identify unintended consequences.',
      specialInstructions: ['Show direct and indirect impacts', 'Rate impact severity for each affected item'],
    },
    icon: 'Ripple',
    color: '#7C3AED',
  },
  {
    agentTypeId: 'cross-module.template-provisioner',
    displayName: 'Template Provisioner',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Core,
    baseType: AgentType.Planner,
    description: 'Provisions complete project setups from templates, creating linked items across multiple modules',
    capabilities: {
      tools: ['search_pages', 'list_issues', 'get_workspace_stats', 'list_bookings'],
      connectors: ['notion', 'linear', 'google_calendar'],
      inputTypes: ['template_id', 'project_config', 'team_roster'],
      outputTypes: ['provisioned_workspace', 'setup_report', 'linked_items'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['provision_production_template'],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You provision workspaces from templates. Ensure all cross-module links are correctly established.',
      specialInstructions: ['Validate template completeness before provisioning', 'Create items in dependency order'],
    },
    icon: 'LayoutTemplate',
    color: '#2563EB',
  },
  {
    agentTypeId: 'cross-module.health-check-runner',
    displayName: 'Health Check Runner',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Technical,
    baseType: AgentType.DevOps,
    description: 'Runs health checks across all modules, verifying connectivity, data integrity, and feature availability',
    capabilities: {
      tools: ['get_workspace_stats', 'list_issues', 'get_invoice_summary', 'list_bookings'],
      connectors: ['health_check_api', 'monitoring_service', 'status_page'],
      inputTypes: ['check_suite', 'module_list', 'threshold_config'],
      outputTypes: ['health_report', 'degradation_alert', 'status_dashboard'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 50_000,
      maxCostUsdBudget: 0.2,
    },
    persona: {
      systemPromptAddition: 'You run health checks across the platform. Report module status and identify degraded services.',
      specialInstructions: ['Run checks every 60 seconds', 'Distinguish between degraded and down states'],
    },
    icon: 'HeartPulse',
    color: '#EF4444',
  },
  {
    agentTypeId: 'cross-module.migration-coordinator',
    displayName: 'Migration Coordinator',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Technical,
    baseType: AgentType.Coordinator,
    description: 'Coordinates data migrations between modules, ensuring referential integrity and zero data loss',
    capabilities: {
      tools: ['get_workspace_stats', 'search_pages', 'list_issues', 'get_invoice_summary'],
      connectors: ['migration_tool', 'database', 'event_bus'],
      inputTypes: ['migration_plan', 'source_data', 'target_schema'],
      outputTypes: ['migration_status', 'validation_report', 'rollback_plan'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['execute_migration', 'rollback_migration'],
      maxTokenBudget: 300_000,
      maxCostUsdBudget: 5.0,
    },
    persona: {
      systemPromptAddition: 'You coordinate data migrations. Ensure zero data loss and maintain referential integrity.',
      specialInstructions: ['Validate row counts before and after', 'Run migration on staging before production'],
    },
    icon: 'ArrowRightLeft',
    color: '#D946EF',
  },
  {
    agentTypeId: 'cross-module.permission-sync',
    displayName: 'Permission Synchronizer',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Technical,
    baseType: AgentType.Security,
    description: 'Synchronizes user permissions across modules to ensure consistent access control',
    capabilities: {
      tools: ['get_workspace_stats', 'list_issues', 'search_pages'],
      connectors: ['auth_service', 'rbac_engine', 'directory'],
      inputTypes: ['permission_change', 'role_definition', 'user_group'],
      outputTypes: ['sync_report', 'permission_diff', 'conflict_alert'],
      domains: ['cross-module', 'security'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['grant_admin_access'],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You synchronize permissions across modules. Ensure consistency and apply least-privilege.',
      specialInstructions: ['Propagate permission changes within 30 seconds', 'Log all permission modifications'],
    },
    icon: 'Lock',
    color: '#64748B',
  },
  {
    agentTypeId: 'cross-module.activity-feed-curator',
    displayName: 'Activity Feed Curator',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Core,
    baseType: AgentType.Writer,
    description: 'Curates a personalized activity feed from all modules, filtering noise and highlighting relevant updates',
    capabilities: {
      tools: ['get_workspace_stats', 'list_issues', 'get_upcoming_deadlines', 'search_pages'],
      connectors: ['activity_stream', 'preference_service', 'recommendation_engine'],
      inputTypes: ['activity_event', 'user_preferences', 'relevance_model'],
      outputTypes: ['curated_feed', 'highlight', 'muted_list'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You curate activity feeds. Surface what matters and suppress noise.',
      specialInstructions: ['Learn from user muting patterns', 'Boost items from direct collaborators'],
    },
    icon: 'Rss',
    color: '#F59E0B',
  },
  {
    agentTypeId: 'cross-module.goal-tracker',
    displayName: 'Goal Tracker',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Tracks OKRs and goals by aggregating progress signals from issues, bookings, invoices, and pages',
    capabilities: {
      tools: ['get_workspace_stats', 'list_issues', 'get_invoice_summary', 'get_upcoming_deadlines'],
      connectors: ['okr_tool', 'linear', 'notion'],
      inputTypes: ['goal_definition', 'key_result', 'progress_signal'],
      outputTypes: ['goal_progress', 'confidence_score', 'risk_alert'],
      domains: ['cross-module', 'projects'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You track goals and OKRs. Calculate progress from real data, not manual updates.',
      specialInstructions: ['Update confidence scores based on pace', 'Flag goals at risk of missing target'],
    },
    icon: 'Target',
    color: '#059669',
  },
  {
    agentTypeId: 'cross-module.automation-suggester',
    displayName: 'Automation Suggester',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Core,
    baseType: AgentType.Planner,
    description: 'Identifies repetitive manual processes across modules and suggests automation opportunities',
    capabilities: {
      tools: ['get_workspace_stats', 'list_issues', 'search_pages', 'list_bookings'],
      connectors: ['workflow_engine', 'zapier', 'make'],
      inputTypes: ['activity_pattern', 'process_log', 'frequency_data'],
      outputTypes: ['automation_suggestion', 'roi_estimate', 'workflow_template'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You identify automation opportunities. Calculate time savings and suggest specific workflow implementations.',
      specialInstructions: ['Estimate hours saved per month', 'Rank suggestions by ROI'],
    },
    icon: 'Sparkles',
    color: '#A855F7',
  },
  {
    agentTypeId: 'cross-module.billing-reconciler',
    displayName: 'Billing Reconciler',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Business,
    baseType: AgentType.Finance,
    description: 'Reconciles billing data across invoices, expenses, and project deliverables to ensure accuracy',
    capabilities: {
      tools: ['get_invoice_summary', 'analyze_expenses', 'list_issues', 'get_workspace_stats'],
      connectors: ['stripe', 'quickbooks', 'project_tool'],
      inputTypes: ['invoice_data', 'expense_report', 'deliverable_log'],
      outputTypes: ['reconciliation_report', 'discrepancy_alert', 'billing_summary'],
      domains: ['cross-module', 'accounting'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['adjust_invoice'],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You reconcile billing across modules. Match deliverables to invoices and flag discrepancies.',
      specialInstructions: ['Cross-reference project hours with billed amounts', 'Flag discrepancies above $100'],
    },
    icon: 'Receipt',
    color: '#059669',
  },
  {
    agentTypeId: 'cross-module.report-scheduler',
    displayName: 'Report Scheduler',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Business,
    baseType: AgentType.Coordinator,
    description: 'Schedules and distributes recurring reports from any module to configured recipients',
    capabilities: {
      tools: ['get_workspace_stats', 'get_upcoming_deadlines', 'get_invoice_summary', 'analyze_expenses'],
      connectors: ['email', 'slack', 'google_drive'],
      inputTypes: ['report_config', 'schedule_cron', 'recipient_list'],
      outputTypes: ['scheduled_report', 'delivery_confirmation', 'schedule_status'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You schedule report delivery. Ensure reports arrive on time and in the preferred format.',
      specialInstructions: ['Respect recipient time zones', 'Retry delivery on transient failures'],
    },
    icon: 'Clock',
    color: '#CA8A04',
  },
  {
    agentTypeId: 'cross-module.risk-assessor',
    displayName: 'Risk Assessor',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Assesses organizational risk by analyzing signals from projects, finances, compliance, and operations',
    capabilities: {
      tools: ['get_workspace_stats', 'list_issues', 'analyze_expenses', 'get_upcoming_deadlines'],
      connectors: ['risk_register', 'compliance_tool', 'financial_system'],
      inputTypes: ['risk_signal', 'historical_incidents', 'threshold_config'],
      outputTypes: ['risk_matrix', 'mitigation_plan', 'risk_score'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 250_000,
      maxCostUsdBudget: 2.5,
    },
    persona: {
      systemPromptAddition: 'You assess organizational risk. Combine signals from multiple domains to paint the full picture.',
      specialInstructions: ['Rate risks by likelihood and impact', 'Suggest mitigation actions for top risks'],
    },
    icon: 'AlertTriangle',
    color: '#DC2626',
  },
  {
    agentTypeId: 'cross-module.handoff-coordinator',
    displayName: 'Handoff Coordinator',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Core,
    baseType: AgentType.Coordinator,
    description: 'Manages work handoffs between teams and modules, ensuring context is transferred completely',
    capabilities: {
      tools: ['list_issues', 'search_pages', 'get_workspace_stats', 'get_upcoming_deadlines'],
      connectors: ['linear', 'notion', 'slack'],
      inputTypes: ['handoff_request', 'context_bundle', 'recipient_team'],
      outputTypes: ['handoff_package', 'acknowledgement', 'context_summary'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You coordinate handoffs. Ensure receiving teams have full context and clear expectations.',
      specialInstructions: ['Include decision history in handoff package', 'Verify recipient acknowledgement'],
    },
    icon: 'HandShake',
    color: '#F97316',
  },
  {
    agentTypeId: 'cross-module.workspace-analytics',
    displayName: 'Workspace Analytics',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Provides holistic workspace analytics by correlating metrics across all modules',
    capabilities: {
      tools: ['get_workspace_stats', 'get_upcoming_deadlines', 'analyze_expenses', 'get_invoice_summary'],
      connectors: ['bi_tool', 'data_warehouse', 'dashboard'],
      inputTypes: ['module_metrics', 'date_range', 'dimension_filter'],
      outputTypes: ['workspace_dashboard', 'cross_module_insight', 'health_score'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 250_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You provide workspace-wide analytics. Correlate metrics across modules to surface cross-cutting insights.',
      specialInstructions: ['Calculate overall workspace health score', 'Identify correlations between module metrics'],
    },
    icon: 'BarChart3',
    color: '#3B82F6',
  },
  {
    agentTypeId: 'cross-module.duplicate-detector',
    displayName: 'Duplicate Detector',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Detects duplicate or near-duplicate content across pages, issues, and contacts to reduce redundancy',
    capabilities: {
      tools: ['search_pages', 'list_issues', 'get_workspace_stats'],
      connectors: ['search_index', 'similarity_engine', 'dedup_service'],
      inputTypes: ['content_item', 'similarity_threshold', 'module_scope'],
      outputTypes: ['duplicate_pair', 'merge_suggestion', 'dedup_report'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['merge_duplicates'],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You detect duplicates across the workspace. Use fuzzy matching and content similarity.',
      specialInstructions: ['Present duplicates as suggestions, not automatic merges', 'Show side-by-side comparison'],
    },
    icon: 'Copy',
    color: '#8B5CF6',
  },
  {
    agentTypeId: 'cross-module.sla-monitor',
    displayName: 'SLA Monitor',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Monitors service level agreements across modules by tracking response times, delivery dates, and quality metrics',
    capabilities: {
      tools: ['get_upcoming_deadlines', 'list_issues', 'get_workspace_stats', 'list_bookings'],
      connectors: ['ticketing_system', 'monitoring_service', 'crm'],
      inputTypes: ['sla_definition', 'performance_data', 'breach_threshold'],
      outputTypes: ['sla_dashboard', 'breach_alert', 'compliance_report'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You monitor SLAs. Alert before breaches happen and track compliance over time.',
      specialInstructions: ['Calculate remaining time before breach', 'Distinguish internal vs external SLAs'],
    },
    icon: 'Timer',
    color: '#EF4444',
  },
  {
    agentTypeId: 'cross-module.retrospective-analyzer',
    displayName: 'Retrospective Analyzer',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Business,
    baseType: AgentType.Researcher,
    description: 'Analyzes past sprints and projects across modules to extract lessons learned and improvement areas',
    capabilities: {
      tools: ['list_issues', 'get_workspace_stats', 'search_pages', 'get_upcoming_deadlines'],
      connectors: ['linear', 'notion', 'confluence'],
      inputTypes: ['sprint_data', 'project_history', 'team_feedback'],
      outputTypes: ['retrospective_report', 'improvement_action', 'pattern_analysis'],
      domains: ['cross-module', 'projects'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 250_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You analyze retrospective data. Identify recurring issues and track improvement over time.',
      specialInstructions: ['Look for patterns across multiple sprints', 'Measure if past action items were effective'],
    },
    icon: 'History',
    color: '#6366F1',
  },
  {
    agentTypeId: 'cross-module.compliance-aggregator',
    displayName: 'Compliance Aggregator',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Legal,
    baseType: AgentType.Compliance,
    description: 'Aggregates compliance status across all modules for unified regulatory reporting',
    capabilities: {
      tools: ['get_workspace_stats', 'list_issues', 'get_invoice_summary', 'analyze_expenses'],
      connectors: ['vanta', 'drata', 'compliance_registry'],
      inputTypes: ['compliance_framework', 'control_evidence', 'module_status'],
      outputTypes: ['compliance_dashboard', 'gap_report', 'evidence_package'],
      domains: ['cross-module', 'security'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 250_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You aggregate compliance status. Map controls to evidence across all modules.',
      specialInstructions: ['Track evidence freshness', 'Flag controls without recent evidence'],
    },
    icon: 'ShieldCheck',
    color: '#059669',
  },
  {
    agentTypeId: 'cross-module.expense-project-mapper',
    displayName: 'Expense-Project Mapper',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Business,
    baseType: AgentType.Finance,
    description: 'Maps expenses to projects and cost centers, enabling accurate project profitability tracking',
    capabilities: {
      tools: ['analyze_expenses', 'list_issues', 'get_invoice_summary', 'get_workspace_stats'],
      connectors: ['quickbooks', 'xero', 'project_tool'],
      inputTypes: ['expense_record', 'project_list', 'allocation_rules'],
      outputTypes: ['expense_allocation', 'profitability_report', 'cost_center_summary'],
      domains: ['cross-module', 'accounting'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You map expenses to projects. Enable accurate cost tracking and profitability analysis.',
      specialInstructions: ['Use allocation rules for shared costs', 'Flag unallocated expenses for review'],
    },
    icon: 'ArrowLeftRight',
    color: '#CA8A04',
  },
  {
    agentTypeId: 'cross-module.client-360-builder',
    displayName: 'Client 360 Builder',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Business,
    baseType: AgentType.CustomerSuccess,
    description: 'Builds a 360-degree client view by aggregating data from projects, invoices, bookings, and communications',
    capabilities: {
      tools: ['get_workspace_stats', 'list_issues', 'get_invoice_summary', 'list_bookings'],
      connectors: ['crm', 'project_tool', 'billing_system'],
      inputTypes: ['client_id', 'module_data', 'interaction_history'],
      outputTypes: ['client_profile', 'health_score', 'engagement_timeline'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You build client profiles. Aggregate data from all touchpoints for a complete view.',
      specialInstructions: ['Calculate client health score from multi-module signals', 'Highlight recent interactions and open items'],
    },
    icon: 'UserCircle',
    color: '#0891B2',
  },
  {
    agentTypeId: 'cross-module.changelog-publisher',
    displayName: 'Changelog Publisher',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Core,
    baseType: AgentType.Writer,
    description: 'Publishes changelogs by aggregating completed items across projects, releases, and feature flags',
    capabilities: {
      tools: ['list_issues', 'search_pages', 'get_workspace_stats'],
      connectors: ['github', 'linear', 'notion'],
      inputTypes: ['completed_issues', 'release_notes', 'feature_flags'],
      outputTypes: ['changelog_entry', 'release_announcement', 'version_summary'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['publish_changelog'],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You publish changelogs. Write for end users, not developers. Highlight user-facing improvements.',
      specialInstructions: ['Group changes by category (features, fixes, improvements)', 'Include screenshots or GIFs for visual changes'],
    },
    icon: 'NotebookPen',
    color: '#4F46E5',
  },
  {
    agentTypeId: 'cross-module.knowledge-linker',
    displayName: 'Knowledge Linker',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Core,
    baseType: AgentType.Researcher,
    description: 'Creates knowledge graph connections between pages, issues, and data records across modules',
    capabilities: {
      tools: ['search_pages', 'list_issues', 'get_workspace_stats', 'get_upcoming_deadlines'],
      connectors: ['notion', 'confluence', 'knowledge_graph'],
      inputTypes: ['content_item', 'entity_extraction', 'relationship_type'],
      outputTypes: ['knowledge_link', 'entity_graph', 'suggestion'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You build knowledge graphs. Extract entities, identify relationships, and surface connections.',
      specialInstructions: ['Use NER to extract key entities', 'Suggest links based on semantic similarity'],
    },
    icon: 'Brain',
    color: '#D946EF',
  },
  {
    agentTypeId: 'cross-module.global-search-agent',
    displayName: 'Global Search Agent',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Core,
    baseType: AgentType.Researcher,
    description: 'Provides unified search across all modules with intelligent ranking, filtering, and contextual result grouping.',
    capabilities: {
      tools: ['search_pages', 'list_issues', 'get_bookings', 'get_workspace_stats'],
      connectors: ['elasticsearch', 'algolia', 'typesense'],
      inputTypes: ['search_query', 'module_filter', 'date_range'],
      outputTypes: ['ranked_results', 'faceted_groups', 'search_suggestions'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 50_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You search across all modules. Rank results by relevance and recency, grouping by module for easy scanning.',
      specialInstructions: ['Boost recent items and frequently accessed content', 'Support fuzzy matching for typo tolerance'],
    },
    icon: 'Search',
    color: '#F59E0B',
  },
  {
    agentTypeId: 'cross-module.notification-consolidator',
    displayName: 'Notification Consolidator',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Core,
    baseType: AgentType.Coordinator,
    description: 'Consolidates notifications from all modules into intelligent digests, reducing alert fatigue while preserving critical alerts.',
    capabilities: {
      tools: ['get_workspace_stats', 'get_upcoming_deadlines', 'send_notification'],
      connectors: ['slack', 'email', 'push_notifications'],
      inputTypes: ['notification_stream', 'consolidation_rules', 'user_preferences'],
      outputTypes: ['consolidated_digest', 'priority_alert', 'noise_reduction_report'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You consolidate notifications across modules. Batch low-priority items and surface critical ones immediately.',
      specialInstructions: ['Group related notifications from the same event', 'Respect quiet hours except for critical alerts'],
    },
    icon: 'BellDot',
    color: '#EF4444',
  },
  {
    agentTypeId: 'cross-module.status-dashboard-builder',
    displayName: 'Status Dashboard Builder',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Business,
    baseType: AgentType.Designer,
    description: 'Creates unified status dashboards pulling metrics from all modules into a single executive-level view.',
    capabilities: {
      tools: ['get_workspace_stats', 'list_issues', 'get_invoice_summary', 'get_bookings'],
      connectors: ['metabase', 'grafana', 'notion'],
      inputTypes: ['module_metrics', 'dashboard_layout', 'refresh_interval'],
      outputTypes: ['unified_dashboard', 'status_summary', 'health_indicators'],
      domains: ['cross-module', 'analytics'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['publish_dashboard'],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You build cross-module status dashboards. Show the big picture with drill-down capability into each module.',
      specialInstructions: ['Use traffic light indicators for quick scanning', 'Include trend sparklines for key metrics'],
    },
    icon: 'LayoutDashboard',
    color: '#3B82F6',
  },
  {
    agentTypeId: 'cross-module.cross-reference-validator',
    displayName: 'Cross-Reference Validator',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Technical,
    baseType: AgentType.Reviewer,
    description: 'Validates data consistency across modules by cross-referencing records, detecting orphaned links, and flagging discrepancies.',
    capabilities: {
      tools: ['get_workspace_stats', 'list_issues', 'get_invoice_summary', 'search_pages'],
      connectors: ['data_warehouse', 'erp'],
      inputTypes: ['reference_pairs', 'validation_rules', 'module_scope'],
      outputTypes: ['validation_report', 'discrepancy_list', 'repair_suggestion'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You validate cross-module data consistency. Find orphaned references and mismatched records across systems.',
      specialInstructions: ['Check bidirectional link integrity', 'Flag stale references to deleted items'],
    },
    icon: 'CheckCheck',
    color: '#059669',
  },
  {
    agentTypeId: 'cross-module.unified-timeline-builder',
    displayName: 'Unified Timeline Builder',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Business,
    baseType: AgentType.Designer,
    description: 'Builds chronological timelines combining events from projects, scheduling, documents, and accounting into a single narrative view.',
    capabilities: {
      tools: ['get_workspace_stats', 'list_issues', 'get_bookings', 'get_upcoming_deadlines'],
      connectors: ['google_calendar', 'jira', 'notion'],
      inputTypes: ['date_range', 'module_filter', 'entity_filter'],
      outputTypes: ['unified_timeline', 'milestone_view', 'activity_stream'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You build unified timelines. Weave events from all modules into a coherent chronological narrative.',
      specialInstructions: ['Highlight milestone events with visual emphasis', 'Allow filtering by module and entity type'],
    },
    icon: 'GitCommitHorizontal',
    color: '#6366F1',
  },
  {
    agentTypeId: 'cross-module.bottleneck-detector',
    displayName: 'Bottleneck Detector',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Identifies process bottlenecks across modules by analyzing wait times, queue depths, and throughput at each stage of cross-module workflows.',
    capabilities: {
      tools: ['get_workspace_stats', 'list_issues', 'get_bookings', 'analyze_expenses'],
      connectors: ['analytics', 'process_mining'],
      inputTypes: ['workflow_data', 'stage_metrics', 'throughput_data'],
      outputTypes: ['bottleneck_report', 'wait_time_analysis', 'optimization_recommendation'],
      domains: ['cross-module', 'projects'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You detect process bottlenecks. Identify where work stalls across module boundaries and recommend fixes.',
      specialInstructions: ['Measure cycle time at each handoff point', 'Distinguish capacity bottlenecks from dependency bottlenecks'],
    },
    icon: 'AlertTriangle',
    color: '#D97706',
  },
  {
    agentTypeId: 'cross-module.change-propagator',
    displayName: 'Change Propagator',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Technical,
    baseType: AgentType.Developer,
    description: 'Propagates changes across modules when updates in one system require corresponding updates in others, maintaining data consistency.',
    capabilities: {
      tools: ['get_workspace_stats', 'list_issues', 'create_page', 'create_issue'],
      connectors: ['webhooks', 'event_bus', 'api_gateway'],
      inputTypes: ['change_event', 'propagation_rules', 'dependency_map'],
      outputTypes: ['propagation_log', 'conflict_alert', 'consistency_report'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: ['propagate-destructive-change'],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You propagate changes across modules. Ensure updates cascade correctly without creating inconsistencies.',
      specialInstructions: ['Use idempotent operations for retry safety', 'Log all propagation events for audit trail'],
    },
    icon: 'Share2',
    color: '#8B5CF6',
  },
  {
    agentTypeId: 'cross-module.conflict-resolver',
    displayName: 'Conflict Resolver',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Core,
    baseType: AgentType.Coordinator,
    description: 'Resolves data and scheduling conflicts that span multiple modules, mediating between competing priorities and constraints.',
    capabilities: {
      tools: ['get_workspace_stats', 'list_issues', 'get_bookings', 'get_upcoming_deadlines'],
      connectors: ['slack', 'email'],
      inputTypes: ['conflict_description', 'stakeholder_list', 'constraint_set'],
      outputTypes: ['resolution_proposal', 'impact_analysis', 'stakeholder_notification'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['apply-resolution'],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You resolve cross-module conflicts. Find solutions that satisfy the most critical constraints across all systems.',
      specialInstructions: ['Present trade-offs clearly to decision makers', 'Prioritize by business impact, not module ownership'],
    },
    icon: 'Swords',
    color: '#EF4444',
  },
  {
    agentTypeId: 'cross-module.integration-health-checker',
    displayName: 'Integration Health Checker',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Technical,
    baseType: AgentType.DevOps,
    description: 'Monitors the health of integrations between modules and external services, detecting failures, latency spikes, and data flow issues.',
    capabilities: {
      tools: ['get_workspace_stats', 'get_table_stats'],
      connectors: ['datadog', 'pagerduty', 'statuspage'],
      inputTypes: ['integration_endpoints', 'health_thresholds', 'monitoring_config'],
      outputTypes: ['health_report', 'incident_alert', 'latency_dashboard'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You monitor integration health. Detect failures before they cascade and alert the right teams.',
      specialInstructions: ['Check endpoint health every 60 seconds', 'Identify cascading failure patterns across integrations'],
    },
    icon: 'HeartPulse',
    color: '#10B981',
  },
  {
    agentTypeId: 'cross-module.template-propagator',
    displayName: 'Template Propagator',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Business,
    baseType: AgentType.Coordinator,
    description: 'Propagates template updates across all modules that use shared templates, ensuring consistency in forms, reports, and workflows.',
    capabilities: {
      tools: ['get_workspace_stats', 'search_pages', 'create_page'],
      connectors: ['notion', 'google_docs'],
      inputTypes: ['template_update', 'usage_registry', 'propagation_scope'],
      outputTypes: ['propagation_report', 'affected_instances', 'rollback_plan'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['propagate-to-production'],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You propagate template changes. Update all instances while preserving local customizations.',
      specialInstructions: ['Track which instances have local overrides', 'Provide rollback capability for each propagation'],
    },
    icon: 'Copy',
    color: '#0891B2',
  },
  {
    agentTypeId: 'cross-module.batch-processor',
    displayName: 'Batch Processor',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Technical,
    baseType: AgentType.Developer,
    description: 'Executes batch operations across multiple modules simultaneously, handling retries, partial failures, and rollback scenarios.',
    capabilities: {
      tools: ['get_workspace_stats', 'create_issue', 'create_page', 'create_booking'],
      connectors: ['task_queue', 'event_bus'],
      inputTypes: ['batch_definition', 'operation_list', 'error_policy'],
      outputTypes: ['batch_result', 'failure_report', 'rollback_manifest'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['execute-destructive-batch'],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You execute cross-module batch operations. Handle partial failures gracefully with clear reporting.',
      specialInstructions: ['Use transactions where possible', 'Report progress percentage during long-running batches'],
    },
    icon: 'Boxes',
    color: '#64748B',
  },
  {
    agentTypeId: 'cross-module.compliance-checker',
    displayName: 'Compliance Checker',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Legal,
    baseType: AgentType.Compliance,
    description: 'Checks compliance requirements across all modules including data retention, access controls, audit trails, and regulatory requirements.',
    capabilities: {
      tools: ['get_workspace_stats', 'get_table_stats', 'analyze_expenses'],
      connectors: ['compliance_db', 'audit_log'],
      inputTypes: ['compliance_framework', 'audit_scope', 'regulation_requirements'],
      outputTypes: ['compliance_report', 'violation_list', 'remediation_plan'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 300_000,
      maxCostUsdBudget: 5.0,
    },
    persona: {
      systemPromptAddition: 'You check compliance across all modules. Apply regulatory frameworks systematically and document findings.',
      specialInstructions: ['Map controls to specific regulatory requirements', 'Prioritize findings by risk severity'],
    },
    icon: 'Scale',
    color: '#B91C1C',
  },
  {
    agentTypeId: 'cross-module.budget-consolidator',
    displayName: 'Budget Consolidator',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Business,
    baseType: AgentType.Finance,
    description: 'Consolidates budget data from projects, accounting, and scheduling modules into a unified financial view with variance analysis.',
    capabilities: {
      tools: ['get_workspace_stats', 'analyze_expenses', 'get_invoice_summary', 'list_issues'],
      connectors: ['quickbooks', 'xero', 'erp'],
      inputTypes: ['budget_sources', 'consolidation_rules', 'reporting_period'],
      outputTypes: ['consolidated_budget', 'variance_report', 'forecast_update'],
      domains: ['cross-module', 'accounting'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You consolidate budgets across modules. Reconcile project costs, schedule resources, and accounting data into one view.',
      specialInstructions: ['Eliminate double-counting across modules', 'Highlight unfunded commitments'],
    },
    icon: 'Wallet',
    color: '#CA8A04',
  },
  {
    agentTypeId: 'cross-module.knowledge-graph-builder',
    displayName: 'Knowledge Graph Builder',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Technical,
    baseType: AgentType.Researcher,
    description: 'Builds and maintains a knowledge graph connecting entities, concepts, and relationships across all workspace modules.',
    capabilities: {
      tools: ['search_pages', 'get_workspace_stats', 'list_issues', 'get_table_stats'],
      connectors: ['neo4j', 'data_catalog'],
      inputTypes: ['content_corpus', 'entity_types', 'relationship_rules'],
      outputTypes: ['knowledge_graph', 'entity_map', 'relationship_discovery'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 300_000,
      maxCostUsdBudget: 5.0,
    },
    persona: {
      systemPromptAddition: 'You build knowledge graphs. Extract entities and relationships from all modules to create a connected intelligence layer.',
      specialInstructions: ['Use NER to extract entities consistently', 'Resolve entity duplicates across modules'],
    },
    icon: 'Orbit',
    color: '#D946EF',
  },
  {
    agentTypeId: 'cross-module.entity-resolver',
    displayName: 'Entity Resolver',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Technical,
    baseType: AgentType.Analyst,
    description: 'Resolves entity references across modules, matching people, companies, and projects that appear under different names or IDs.',
    capabilities: {
      tools: ['get_workspace_stats', 'search_pages', 'list_issues'],
      connectors: ['data_warehouse', 'crm', 'erp'],
      inputTypes: ['entity_references', 'matching_rules', 'confidence_threshold'],
      outputTypes: ['resolved_entities', 'match_candidates', 'dedup_report'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['merge-entities'],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You resolve entity references across modules. Match records that refer to the same real-world entity.',
      specialInstructions: ['Use fuzzy matching for name variations', 'Present uncertain matches for human review'],
    },
    icon: 'Fingerprint',
    color: '#475569',
  },
  {
    agentTypeId: 'cross-module.smart-routing-engine',
    displayName: 'Smart Routing Engine',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Core,
    baseType: AgentType.Coordinator,
    description: 'Routes work items, requests, and notifications to the right module and person based on content analysis and organizational rules.',
    capabilities: {
      tools: ['get_workspace_stats', 'list_issues', 'search_pages', 'get_bookings'],
      connectors: ['slack', 'email', 'webhooks'],
      inputTypes: ['work_item', 'routing_rules', 'team_capacity'],
      outputTypes: ['routing_decision', 'assignment_record', 'escalation_trigger'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You route work items across modules. Get every request to the right place and person on the first try.',
      specialInstructions: ['Consider team capacity and expertise in routing decisions', 'Learn from re-routing patterns to improve accuracy'],
    },
    icon: 'Route',
    color: '#F97316',
  },
  {
    agentTypeId: 'cross-module.fallback-handler',
    displayName: 'Fallback Handler',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Technical,
    baseType: AgentType.DevOps,
    description: 'Handles failures in cross-module operations with graceful degradation, retry logic, and fallback strategies to maintain service continuity.',
    capabilities: {
      tools: ['get_workspace_stats'],
      connectors: ['pagerduty', 'statuspage', 'event_bus'],
      inputTypes: ['failure_event', 'fallback_config', 'retry_policy'],
      outputTypes: ['fallback_action', 'recovery_report', 'degradation_notice'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 50_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You handle cross-module failures. Implement graceful degradation and recovery strategies to minimize user impact.',
      specialInstructions: ['Use exponential backoff for retries', 'Cache last-known-good state for fallback responses'],
    },
    icon: 'LifeBuoy',
    color: '#DC2626',
  },
  {
    agentTypeId: 'cross-module.recovery-orchestrator',
    displayName: 'Recovery Orchestrator',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Technical,
    baseType: AgentType.DevOps,
    description: 'Orchestrates recovery procedures after cross-module incidents, coordinating data reconciliation, service restoration, and post-incident review.',
    capabilities: {
      tools: ['get_workspace_stats', 'get_table_stats'],
      connectors: ['pagerduty', 'jira', 'statuspage'],
      inputTypes: ['incident_record', 'recovery_playbook', 'affected_modules'],
      outputTypes: ['recovery_plan', 'reconciliation_report', 'post_mortem'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['execute-recovery-plan'],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You orchestrate incident recovery. Coordinate across modules to restore service and reconcile data.',
      specialInstructions: ['Follow runbook procedures step by step', 'Verify data consistency after recovery'],
    },
    icon: 'ShieldCheck',
    color: '#059669',
  },
  {
    agentTypeId: 'cross-module.feature-flag-manager',
    displayName: 'Feature Flag Manager',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.Technical,
    baseType: AgentType.Developer,
    description: 'Manages feature flags across all modules, enabling gradual rollouts, A/B testing, and instant rollbacks of cross-module features.',
    capabilities: {
      tools: ['get_workspace_stats'],
      connectors: ['launchdarkly', 'statsig', 'custom_flags'],
      inputTypes: ['flag_definition', 'targeting_rules', 'rollout_plan'],
      outputTypes: ['flag_status', 'rollout_report', 'impact_analysis'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['enable-flag-production'],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You manage feature flags across modules. Enable safe, gradual feature rollouts with instant rollback capability.',
      specialInstructions: ['Start with 1% rollout for new features', 'Monitor error rates after each rollout increment'],
    },
    icon: 'ToggleRight',
    color: '#7C3AED',
  },
  {
    agentTypeId: 'cross-module.feedback-loop-processor',
    displayName: 'Feedback Loop Processor',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.People,
    baseType: AgentType.Analyst,
    description: 'Processes user feedback from all modules, identifies patterns, routes to product teams, and tracks resolution of reported issues.',
    capabilities: {
      tools: ['get_workspace_stats', 'create_issue', 'search_pages'],
      connectors: ['intercom', 'zendesk', 'productboard'],
      inputTypes: ['feedback_item', 'sentiment_data', 'source_module'],
      outputTypes: ['feedback_analysis', 'pattern_report', 'routing_recommendation'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You process feedback across modules. Identify themes, quantify impact, and route insights to the right teams.',
      specialInstructions: ['Deduplicate feedback about the same issue', 'Weight feedback by user segment and business value'],
    },
    icon: 'MessageCircle',
    color: '#0EA5E9',
  },
  {
    agentTypeId: 'cross-module.onboarding-orchestrator',
    displayName: 'Onboarding Orchestrator',
    domain: AgentDomain.CrossModule,
    category: AgentCategory.People,
    baseType: AgentType.Coordinator,
    description: 'Orchestrates user onboarding across all modules, guiding new users through setup, configuration, and first-use experiences.',
    capabilities: {
      tools: ['get_workspace_stats', 'create_page', 'create_booking'],
      connectors: ['intercom', 'email', 'in_app_messaging'],
      inputTypes: ['user_profile', 'onboarding_plan', 'progress_data'],
      outputTypes: ['onboarding_checklist', 'guided_tour', 'completion_report'],
      domains: ['cross-module'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You orchestrate user onboarding. Guide users through each module in the right order with contextual help.',
      specialInstructions: ['Adapt onboarding path based on user role', 'Celebrate milestones to maintain motivation'],
    },
    icon: 'Rocket',
    color: '#F59E0B',
  },

]
