import { AgentDomain, AgentCategory, AgentType, CostTier, LatencyProfile } from '../../types'
import type { AgentCapabilityManifest } from '../../types'

export const AGENTS: AgentCapabilityManifest[] = [
  {
    agentTypeId: 'databases.schema-designer',
    displayName: 'Schema Designer',
    domain: AgentDomain.Databases,
    category: AgentCategory.Technical,
    baseType: AgentType.Designer,
    description: 'Designs optimal database schemas with proper field types, relations, and constraints based on natural language descriptions of your data model.',
    capabilities: {
      tools: ['create_database', 'add_table', 'analyze_database_schema', 'get_relation_map'],
      connectors: ['origina-databases'],
      inputTypes: ['text', 'schema-description', 'erd-diagram'],
      outputTypes: ['database-schema', 'migration-plan', 'erd-diagram'],
      domains: ['schema', 'design', 'modeling', 'relational', 'tables'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['create_database'],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 0.50,
    },
    persona: {
      systemPromptAddition: 'You are an expert database architect. Design clean, normalized schemas with clear naming conventions and proper relations.',
      specialInstructions: [
        'Always suggest primary keys and unique constraints',
        'Recommend indexes for frequently queried fields',
        'Prefer normalized schemas unless denormalization is justified',
      ],
    },
    icon: 'database',
    color: '#6366F1',
  },
  {
    agentTypeId: 'databases.data-validator',
    displayName: 'Data Validator',
    domain: AgentDomain.Databases,
    category: AgentCategory.Technical,
    baseType: AgentType.Reviewer,
    description: 'Validates data integrity across tables by checking for orphaned records, type mismatches, duplicate entries, and constraint violations.',
    capabilities: {
      tools: ['analyze_database_schema', 'get_table_stats', 'get_relation_map'],
      connectors: ['origina-databases'],
      inputTypes: ['database-id', 'table-id', 'validation-rules'],
      outputTypes: ['validation-report', 'error-list', 'fix-suggestions'],
      domains: ['validation', 'integrity', 'quality', 'consistency'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 0.25,
    },
    persona: {
      systemPromptAddition: 'You are a meticulous data quality analyst. Find every inconsistency, orphan, and violation in the dataset.',
      specialInstructions: [
        'Check referential integrity across all relations',
        'Flag potential duplicate records using fuzzy matching',
        'Report severity levels for each issue found',
      ],
    },
    icon: 'shield-check',
    color: '#10B981',
  },
  {
    agentTypeId: 'databases.import-manager',
    displayName: 'Import Manager',
    domain: AgentDomain.Databases,
    category: AgentCategory.Technical,
    baseType: AgentType.Developer,
    description: 'Handles bulk data imports from CSV, JSON, and Excel files with automatic column mapping, type detection, and error handling.',
    capabilities: {
      tools: ['create_database', 'add_table', 'add_row', 'analyze_database_schema'],
      connectors: ['origina-databases', 'file-storage'],
      inputTypes: ['csv', 'json', 'xlsx', 'file-upload'],
      outputTypes: ['import-report', 'error-log', 'row-count'],
      domains: ['import', 'csv', 'migration', 'bulk-load', 'etl'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['add_row'],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 0.40,
    },
    persona: {
      systemPromptAddition: 'You are a data migration specialist. Map source columns to target fields accurately and handle edge cases gracefully.',
      specialInstructions: [
        'Auto-detect column types from sample data',
        'Preview first 10 rows before committing import',
        'Create rollback plan for large imports',
      ],
    },
    icon: 'upload',
    color: '#3B82F6',
  },
  {
    agentTypeId: 'databases.export-manager',
    displayName: 'Export Manager',
    domain: AgentDomain.Databases,
    category: AgentCategory.Technical,
    baseType: AgentType.Developer,
    description: 'Exports database views and filtered datasets to CSV, JSON, or Excel formats with configurable column selection and formatting.',
    capabilities: {
      tools: ['analyze_database_schema', 'get_table_stats', 'analyze_views'],
      connectors: ['origina-databases', 'file-storage'],
      inputTypes: ['database-id', 'view-id', 'filter-criteria', 'export-config'],
      outputTypes: ['csv', 'json', 'xlsx', 'export-report'],
      domains: ['export', 'download', 'report', 'extract'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.20,
    },
    persona: {
      systemPromptAddition: 'You are a data export specialist. Format exports cleanly with proper headers, date formats, and encoding.',
      specialInstructions: [
        'Respect view filters and sort orders in exports',
        'Handle large datasets with pagination',
        'Include metadata sheet for Excel exports',
      ],
    },
    icon: 'download',
    color: '#8B5CF6',
  },
  {
    agentTypeId: 'databases.automation-builder',
    displayName: 'Automation Builder',
    domain: AgentDomain.Databases,
    category: AgentCategory.Technical,
    baseType: AgentType.Developer,
    description: 'Creates and manages database automations triggered by row changes, schedules, or external events with conditional logic and multi-step actions.',
    capabilities: {
      tools: ['review_database_automations', 'analyze_database_schema', 'get_table_stats'],
      connectors: ['origina-databases', 'origina-workflows'],
      inputTypes: ['automation-description', 'trigger-config', 'action-config'],
      outputTypes: ['automation-definition', 'test-results', 'execution-log'],
      domains: ['automation', 'trigger', 'workflow', 'rules', 'actions'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['review_database_automations'],
      maxTokenBudget: 45000,
      maxCostUsdBudget: 0.45,
    },
    persona: {
      systemPromptAddition: 'You are an automation engineer. Build reliable, efficient automations with proper error handling and clear trigger conditions.',
      specialInstructions: [
        'Always include error handling steps in automations',
        'Suggest rate limiting for high-frequency triggers',
        'Test automations with sample data before activation',
      ],
    },
    icon: 'zap',
    color: '#F59E0B',
  },
  {
    agentTypeId: 'databases.view-optimizer',
    displayName: 'View Optimizer',
    domain: AgentDomain.Databases,
    category: AgentCategory.Technical,
    baseType: AgentType.Analyst,
    description: 'Analyzes and optimizes database views for performance, suggesting better filters, sort orders, groupings, and field selections.',
    capabilities: {
      tools: ['analyze_views', 'get_table_stats', 'analyze_database_schema'],
      connectors: ['origina-databases'],
      inputTypes: ['view-id', 'performance-complaint', 'usage-pattern'],
      outputTypes: ['optimization-report', 'view-config', 'performance-metrics'],
      domains: ['views', 'performance', 'optimization', 'filters', 'sorting'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 0.25,
    },
    persona: {
      systemPromptAddition: 'You are a database performance tuner. Optimize views for speed and usability without sacrificing data completeness.',
      specialInstructions: [
        'Identify unused columns that slow rendering',
        'Suggest computed fields to replace complex formulas',
        'Recommend view splitting for tables with 50+ columns',
      ],
    },
    icon: 'eye',
    color: '#14B8A6',
  },
  {
    agentTypeId: 'databases.relation-mapper',
    displayName: 'Relation Mapper',
    domain: AgentDomain.Databases,
    category: AgentCategory.Technical,
    baseType: AgentType.Analyst,
    description: 'Maps and visualizes relationships between database tables, identifies missing links, and suggests new relations to improve data connectivity.',
    capabilities: {
      tools: ['get_relation_map', 'analyze_database_schema', 'add_table'],
      connectors: ['origina-databases'],
      inputTypes: ['database-id', 'table-list', 'relation-question'],
      outputTypes: ['relation-diagram', 'missing-links-report', 'relation-suggestions'],
      domains: ['relations', 'links', 'foreign-keys', 'graph', 'connections'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['add_table'],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 0.40,
    },
    persona: {
      systemPromptAddition: 'You are a data relationship expert. Map connections between entities and identify opportunities for better data linking.',
      specialInstructions: [
        'Detect implicit relations from naming patterns',
        'Flag circular dependencies that may cause issues',
        'Suggest junction tables for many-to-many relationships',
      ],
    },
    icon: 'git-branch',
    color: '#EC4899',
  },
  {
    agentTypeId: 'databases.field-type-advisor',
    displayName: 'Field Type Advisor',
    domain: AgentDomain.Databases,
    category: AgentCategory.Technical,
    baseType: AgentType.Reviewer,
    description: 'Analyzes existing field types and recommends optimal types based on actual data patterns, improving storage efficiency and query performance.',
    capabilities: {
      tools: ['analyze_database_schema', 'get_table_stats'],
      connectors: ['origina-databases'],
      inputTypes: ['table-id', 'field-list', 'data-sample'],
      outputTypes: ['type-recommendations', 'migration-plan'],
      domains: ['field-types', 'columns', 'data-types', 'schema'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.20,
    },
    persona: {
      systemPromptAddition: 'You are a data typing specialist. Recommend the most appropriate field types based on actual data patterns and usage.',
      specialInstructions: [
        'Detect date strings stored as text fields',
        'Identify numeric fields that should be currency type',
        'Suggest select/enum types for low-cardinality text fields',
      ],
    },
    icon: 'type',
    color: '#78716C',
  },
  {
    agentTypeId: 'databases.template-creator',
    displayName: 'Template Creator',
    domain: AgentDomain.Databases,
    category: AgentCategory.Creative,
    baseType: AgentType.Designer,
    description: 'Creates reusable database templates for common use cases like CRM, inventory, project tracking, and content management.',
    capabilities: {
      tools: ['create_database', 'add_table', 'analyze_database_schema'],
      connectors: ['origina-databases'],
      inputTypes: ['use-case-description', 'industry', 'requirements'],
      outputTypes: ['database-template', 'setup-guide', 'sample-data'],
      domains: ['templates', 'starter', 'boilerplate', 'use-case'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['create_database'],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 0.50,
    },
    persona: {
      systemPromptAddition: 'You are a database template designer. Create well-structured starter databases that users can customize for their needs.',
      specialInstructions: [
        'Include sample data rows to demonstrate usage',
        'Create multiple views for each template (grid, kanban, calendar)',
        'Add helpful field descriptions and placeholder text',
      ],
    },
    icon: 'layout-template',
    color: '#A855F7',
  },
  {
    agentTypeId: 'databases.formula-writer',
    displayName: 'Formula Writer',
    domain: AgentDomain.Databases,
    category: AgentCategory.Technical,
    baseType: AgentType.Developer,
    description: 'Writes and debugs computed field formulas for rollups, lookups, conditional formatting, and derived calculations.',
    capabilities: {
      tools: ['analyze_database_schema', 'get_table_stats', 'analyze_views'],
      connectors: ['origina-databases'],
      inputTypes: ['formula-request', 'field-context', 'error-message'],
      outputTypes: ['formula-expression', 'explanation', 'test-results'],
      domains: ['formulas', 'computed', 'calculations', 'rollups', 'lookups'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.15,
    },
    persona: {
      systemPromptAddition: 'You are a formula expert. Write clean, efficient formulas and explain the logic step by step.',
      specialInstructions: [
        'Break complex formulas into intermediate computed fields',
        'Always handle null/empty values in formulas',
        'Provide examples with sample data for each formula',
      ],
    },
    icon: 'function-square',
    color: '#0EA5E9',
  },
  {
    agentTypeId: 'databases.kanban-configurator',
    displayName: 'Kanban Configurator',
    domain: AgentDomain.Databases,
    category: AgentCategory.Creative,
    baseType: AgentType.Designer,
    description: 'Configures kanban board views with optimal column groupings, card layouts, color coding, and swimlanes for project tracking.',
    capabilities: {
      tools: ['analyze_views', 'analyze_database_schema', 'get_table_stats'],
      connectors: ['origina-databases'],
      inputTypes: ['table-id', 'workflow-description', 'status-fields'],
      outputTypes: ['kanban-config', 'column-definitions', 'card-layout'],
      domains: ['kanban', 'board', 'status', 'workflow', 'cards'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.20,
    },
    persona: {
      systemPromptAddition: 'You are a visual workflow expert. Design kanban boards that make project status instantly understandable.',
      specialInstructions: [
        'Suggest meaningful color coding for status columns',
        'Recommend WIP limits based on team size',
        'Configure card previews to show most relevant fields',
      ],
    },
    icon: 'kanban',
    color: '#F97316',
  },
  {
    agentTypeId: 'databases.calendar-view-builder',
    displayName: 'Calendar View Builder',
    domain: AgentDomain.Databases,
    category: AgentCategory.Creative,
    baseType: AgentType.Designer,
    description: 'Creates calendar views from date fields in database tables with event styling, duration handling, and recurring event support.',
    capabilities: {
      tools: ['analyze_views', 'analyze_database_schema', 'get_table_stats'],
      connectors: ['origina-databases'],
      inputTypes: ['table-id', 'date-fields', 'display-preferences'],
      outputTypes: ['calendar-config', 'event-mappings', 'color-rules'],
      domains: ['calendar', 'dates', 'events', 'timeline', 'schedule'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.20,
    },
    persona: {
      systemPromptAddition: 'You are a calendar visualization specialist. Configure date-driven views that surface deadlines and milestones clearly.',
      specialInstructions: [
        'Auto-detect start/end date field pairs for duration events',
        'Suggest color coding based on status or category fields',
        'Handle timezone considerations for distributed teams',
      ],
    },
    icon: 'calendar',
    color: '#EF4444',
  },
  {
    agentTypeId: 'databases.gallery-view-builder',
    displayName: 'Gallery View Builder',
    domain: AgentDomain.Databases,
    category: AgentCategory.Creative,
    baseType: AgentType.Designer,
    description: 'Configures gallery/card views for visual databases with image thumbnails, cover photos, and rich card layouts.',
    capabilities: {
      tools: ['analyze_views', 'analyze_database_schema', 'get_table_stats'],
      connectors: ['origina-databases'],
      inputTypes: ['table-id', 'image-fields', 'card-layout-preferences'],
      outputTypes: ['gallery-config', 'card-template', 'filter-presets'],
      domains: ['gallery', 'cards', 'images', 'visual', 'thumbnails'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.15,
    },
    persona: {
      systemPromptAddition: 'You are a visual design expert for data views. Create stunning gallery layouts that make data browsing engaging.',
      specialInstructions: [
        'Prioritize image fields for card covers',
        'Suggest compact field selections for card bodies',
        'Configure hover previews for detailed information',
      ],
    },
    icon: 'layout-grid',
    color: '#D946EF',
  },
  {
    agentTypeId: 'databases.form-builder',
    displayName: 'Form Builder',
    domain: AgentDomain.Databases,
    category: AgentCategory.Creative,
    baseType: AgentType.Designer,
    description: 'Creates data entry forms linked to database tables with field ordering, validation rules, conditional sections, and submission workflows.',
    capabilities: {
      tools: ['analyze_database_schema', 'add_table', 'get_table_stats'],
      connectors: ['origina-databases', 'origina-forms'],
      inputTypes: ['table-id', 'form-requirements', 'field-order'],
      outputTypes: ['form-config', 'validation-rules', 'submission-workflow'],
      domains: ['forms', 'input', 'data-entry', 'surveys', 'submissions'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['add_table'],
      maxTokenBudget: 35000,
      maxCostUsdBudget: 0.35,
    },
    persona: {
      systemPromptAddition: 'You are a form design specialist. Build intuitive data entry forms that minimize friction and maximize completion rates.',
      specialInstructions: [
        'Group related fields into logical sections',
        'Add helpful placeholder text and field descriptions',
        'Implement conditional visibility for complex forms',
      ],
    },
    icon: 'clipboard-list',
    color: '#06B6D4',
  },
  {
    agentTypeId: 'databases.data-deduplicator',
    displayName: 'Data Deduplicator',
    domain: AgentDomain.Databases,
    category: AgentCategory.Technical,
    baseType: AgentType.Analyst,
    description: 'Identifies and merges duplicate records using fuzzy matching on names, emails, addresses, and other fields with configurable thresholds.',
    capabilities: {
      tools: ['get_table_stats', 'analyze_database_schema', 'add_row'],
      connectors: ['origina-databases'],
      inputTypes: ['table-id', 'match-fields', 'threshold-config'],
      outputTypes: ['duplicate-report', 'merge-candidates', 'merge-results'],
      domains: ['duplicates', 'dedup', 'merge', 'cleanup', 'matching'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['add_row'],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 0.40,
    },
    persona: {
      systemPromptAddition: 'You are a data deduplication expert. Find duplicates accurately while minimizing false positives.',
      specialInstructions: [
        'Use multiple fields for matching confidence scoring',
        'Present merge candidates for user review before acting',
        'Preserve the most complete record as the survivor',
      ],
    },
    icon: 'copy-minus',
    color: '#DC2626',
  },
  {
    agentTypeId: 'databases.stats-reporter',
    displayName: 'Stats Reporter',
    domain: AgentDomain.Databases,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Generates statistical summaries of database tables including row counts, field distributions, null rates, and trend analysis.',
    capabilities: {
      tools: ['get_table_stats', 'analyze_database_schema', 'analyze_views', 'get_workspace_stats'],
      connectors: ['origina-databases'],
      inputTypes: ['database-id', 'table-id', 'date-range'],
      outputTypes: ['stats-report', 'distribution-chart', 'trend-analysis'],
      domains: ['statistics', 'analytics', 'reports', 'metrics', 'trends'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 0.25,
    },
    persona: {
      systemPromptAddition: 'You are a data analytics expert. Present clear, actionable statistics that help users understand their data.',
      specialInstructions: [
        'Always include row counts and null percentages',
        'Highlight outliers and anomalies in distributions',
        'Compare current stats to historical baselines when available',
      ],
    },
    icon: 'bar-chart-3',
    color: '#2563EB',
  },
  {
    agentTypeId: 'databases.migration-planner',
    displayName: 'Migration Planner',
    domain: AgentDomain.Databases,
    category: AgentCategory.Technical,
    baseType: AgentType.Planner,
    description: 'Plans database schema migrations with step-by-step instructions, data transformation rules, and rollback strategies.',
    capabilities: {
      tools: ['analyze_database_schema', 'get_table_stats', 'get_relation_map'],
      connectors: ['origina-databases'],
      inputTypes: ['current-schema', 'target-schema', 'migration-requirements'],
      outputTypes: ['migration-plan', 'transformation-rules', 'rollback-plan'],
      domains: ['migration', 'schema-change', 'upgrade', 'transformation'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['analyze_database_schema'],
      maxTokenBudget: 60000,
      maxCostUsdBudget: 0.60,
    },
    persona: {
      systemPromptAddition: 'You are a database migration architect. Plan safe, reversible migrations that minimize downtime and data loss risk.',
      specialInstructions: [
        'Break large migrations into incremental steps',
        'Include data validation checks between steps',
        'Always provide a tested rollback procedure',
      ],
    },
    icon: 'route',
    color: '#7C3AED',
  },
  {
    agentTypeId: 'databases.access-control-manager',
    displayName: 'Access Control Manager',
    domain: AgentDomain.Databases,
    category: AgentCategory.Technical,
    baseType: AgentType.Security,
    description: 'Manages field-level and row-level access permissions for database tables, ensuring proper data visibility across teams and roles.',
    capabilities: {
      tools: ['analyze_database_schema', 'get_table_stats', 'analyze_views'],
      connectors: ['origina-databases', 'origina-auth'],
      inputTypes: ['access-requirements', 'role-list', 'sensitivity-levels'],
      outputTypes: ['permission-matrix', 'access-policy', 'audit-report'],
      domains: ['permissions', 'access', 'security', 'roles', 'visibility'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['analyze_database_schema'],
      maxTokenBudget: 35000,
      maxCostUsdBudget: 0.35,
    },
    persona: {
      systemPromptAddition: 'You are a data security specialist. Configure access controls that balance usability with data protection.',
      specialInstructions: [
        'Apply principle of least privilege by default',
        'Flag sensitive fields like PII and financial data',
        'Create role-based view presets for common access patterns',
      ],
    },
    icon: 'lock',
    color: '#991B1B',
  },
  {
    agentTypeId: 'databases.api-connector',
    displayName: 'API Connector',
    domain: AgentDomain.Databases,
    category: AgentCategory.Technical,
    baseType: AgentType.Developer,
    description: 'Connects external APIs to database tables for automatic data sync, webhook-driven updates, and scheduled pulls.',
    capabilities: {
      tools: ['add_row', 'add_table', 'analyze_database_schema', 'review_database_automations'],
      connectors: ['origina-databases', 'external-api'],
      inputTypes: ['api-endpoint', 'mapping-config', 'sync-schedule'],
      outputTypes: ['sync-report', 'error-log', 'mapping-preview'],
      domains: ['api', 'sync', 'integration', 'webhook', 'connector'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['add_row', 'add_table'],
      maxTokenBudget: 45000,
      maxCostUsdBudget: 0.45,
    },
    persona: {
      systemPromptAddition: 'You are an API integration specialist. Build reliable data pipelines between external services and OriginA databases.',
      specialInstructions: [
        'Handle pagination for large API responses',
        'Implement idempotent sync to prevent duplicates',
        'Set up error alerting for failed sync operations',
      ],
    },
    icon: 'plug',
    color: '#059669',
  },
  {
    agentTypeId: 'databases.data-enricher',
    displayName: 'Data Enricher',
    domain: AgentDomain.Databases,
    category: AgentCategory.Business,
    baseType: AgentType.Researcher,
    description: 'Enriches database records with additional information by looking up company data, geocoding addresses, and filling in missing fields.',
    capabilities: {
      tools: ['add_row', 'get_table_stats', 'analyze_database_schema'],
      connectors: ['origina-databases', 'enrichment-api'],
      inputTypes: ['table-id', 'enrichment-fields', 'lookup-config'],
      outputTypes: ['enrichment-report', 'updated-records', 'match-quality'],
      domains: ['enrichment', 'lookup', 'augment', 'company-data', 'geocoding'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['add_row'],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 0.60,
    },
    persona: {
      systemPromptAddition: 'You are a data enrichment specialist. Fill gaps in records with accurate, up-to-date information from reliable sources.',
      specialInstructions: [
        'Validate enriched data against existing fields for consistency',
        'Track enrichment confidence scores for each field',
        'Batch enrichment requests to minimize API costs',
      ],
    },
    icon: 'sparkles',
    color: '#F59E0B',
  },
  {
    agentTypeId: 'databases.backup-manager',
    displayName: 'Backup Manager',
    domain: AgentDomain.Databases,
    category: AgentCategory.Technical,
    baseType: AgentType.DevOps,
    description: 'Manages database backups with scheduled snapshots, point-in-time recovery, and cross-workspace replication for disaster recovery.',
    capabilities: {
      tools: ['analyze_database_schema', 'get_table_stats', 'get_workspace_stats'],
      connectors: ['origina-databases', 'backup-storage'],
      inputTypes: ['backup-schedule', 'retention-policy', 'recovery-point'],
      outputTypes: ['backup-report', 'recovery-plan', 'backup-manifest'],
      domains: ['backup', 'recovery', 'snapshot', 'replication', 'disaster-recovery'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['get_workspace_stats'],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 0.30,
    },
    persona: {
      systemPromptAddition: 'You are a database reliability engineer. Ensure data is always recoverable with tested backup and restore procedures.',
      specialInstructions: [
        'Verify backup integrity after each snapshot',
        'Test restore procedures on a regular schedule',
        'Alert on backup failures immediately',
      ],
    },
    icon: 'hard-drive',
    color: '#64748B',
  },
  {
    agentTypeId: 'databases.query-assistant',
    displayName: 'Query Assistant',
    domain: AgentDomain.Databases,
    category: AgentCategory.Technical,
    baseType: AgentType.Developer,
    description: 'Translates natural language questions into database queries, helping users find specific records and generate filtered views.',
    capabilities: {
      tools: ['analyze_database_schema', 'get_table_stats', 'analyze_views'],
      connectors: ['origina-databases'],
      inputTypes: ['natural-language-query', 'table-context', 'filter-request'],
      outputTypes: ['query-result', 'filter-config', 'view-definition'],
      domains: ['query', 'search', 'filter', 'find', 'lookup'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.10,
    },
    persona: {
      systemPromptAddition: 'You are a natural language query interpreter. Convert user questions into precise database filters and queries.',
      specialInstructions: [
        'Clarify ambiguous queries before executing',
        'Suggest related queries that might be useful',
        'Show query logic so users can learn filter syntax',
      ],
    },
    icon: 'search',
    color: '#0891B2',
  },
  {
    agentTypeId: 'databases.changelog-tracker',
    displayName: 'Changelog Tracker',
    domain: AgentDomain.Databases,
    category: AgentCategory.Technical,
    baseType: AgentType.Reviewer,
    description: 'Tracks and reports all changes to database records including who changed what, when, and provides diff views for audit compliance.',
    capabilities: {
      tools: ['get_table_stats', 'analyze_database_schema', 'get_workspace_stats'],
      connectors: ['origina-databases'],
      inputTypes: ['table-id', 'date-range', 'user-filter'],
      outputTypes: ['changelog-report', 'diff-view', 'audit-summary'],
      domains: ['changelog', 'audit', 'history', 'tracking', 'diff'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.20,
    },
    persona: {
      systemPromptAddition: 'You are a data audit specialist. Track every change with precision and present clear, chronological change histories.',
      specialInstructions: [
        'Group related changes into logical changesets',
        'Highlight bulk operations distinctly from individual edits',
        'Flag unusual patterns like mass deletions or after-hours changes',
      ],
    },
    icon: 'history',
    color: '#475569',
  },
  {
    agentTypeId: 'databases.pivot-table-builder',
    displayName: 'Pivot Table Builder',
    domain: AgentDomain.Databases,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Creates pivot table summaries from database tables with configurable row groupings, column groupings, and aggregation functions.',
    capabilities: {
      tools: ['get_table_stats', 'analyze_database_schema', 'analyze_views'],
      connectors: ['origina-databases'],
      inputTypes: ['table-id', 'row-fields', 'column-fields', 'value-fields'],
      outputTypes: ['pivot-table', 'summary-chart', 'aggregate-data'],
      domains: ['pivot', 'summary', 'aggregation', 'grouping', 'cross-tab'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.20,
    },
    persona: {
      systemPromptAddition: 'You are a data summarization expert. Build meaningful pivot tables that reveal patterns and insights in your data.',
      specialInstructions: [
        'Suggest meaningful default aggregations for each field type',
        'Include subtotals and grand totals by default',
        'Recommend charts that complement the pivot table',
      ],
    },
    icon: 'table-2',
    color: '#7C3AED',
  },
  {
    agentTypeId: 'databases.data-classifier',
    displayName: 'Data Classifier',
    domain: AgentDomain.Databases,
    category: AgentCategory.Technical,
    baseType: AgentType.Analyst,
    description: 'Automatically categorizes and tags database records using pattern recognition, keyword analysis, and ML-based classification.',
    capabilities: {
      tools: ['get_table_stats', 'add_row', 'analyze_database_schema'],
      connectors: ['origina-databases'],
      inputTypes: ['table-id', 'classification-rules', 'training-examples'],
      outputTypes: ['classification-results', 'confidence-scores', 'category-distribution'],
      domains: ['classification', 'tagging', 'categorization', 'labeling', 'sorting'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['add_row'],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 0.40,
    },
    persona: {
      systemPromptAddition: 'You are a data classification specialist. Apply consistent, accurate labels to records based on their content and context.',
      specialInstructions: [
        'Explain classification reasoning for transparency',
        'Flag low-confidence classifications for human review',
        'Learn from user corrections to improve accuracy',
      ],
    },
    icon: 'tags',
    color: '#16A34A',
  },
  {
    agentTypeId: 'databases.dependency-analyzer',
    displayName: 'Dependency Analyzer',
    domain: AgentDomain.Databases,
    category: AgentCategory.Technical,
    baseType: AgentType.Analyst,
    description: 'Analyzes cross-table dependencies to identify cascade effects, breaking changes, and safe deletion paths for records and fields.',
    capabilities: {
      tools: ['get_relation_map', 'analyze_database_schema', 'get_table_stats'],
      connectors: ['origina-databases'],
      inputTypes: ['table-id', 'field-id', 'record-id', 'change-proposal'],
      outputTypes: ['dependency-tree', 'impact-analysis', 'safe-path-report'],
      domains: ['dependencies', 'cascade', 'impact', 'breaking-changes', 'references'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 35000,
      maxCostUsdBudget: 0.35,
    },
    persona: {
      systemPromptAddition: 'You are a dependency analysis expert. Map every ripple effect before changes are made to protect data integrity.',
      specialInstructions: [
        'Trace dependencies to the deepest level',
        'Quantify the impact scope (number of affected records)',
        'Suggest safe alternatives to destructive changes',
      ],
    },
    icon: 'network',
    color: '#B91C1C',
  },
  {
    agentTypeId: 'databases.notification-configurator',
    displayName: 'Notification Configurator',
    domain: AgentDomain.Databases,
    category: AgentCategory.Technical,
    baseType: AgentType.Developer,
    description: 'Sets up database change notifications with configurable triggers, recipient rules, and delivery channels for real-time data monitoring.',
    capabilities: {
      tools: ['review_database_automations', 'analyze_database_schema', 'get_table_stats'],
      connectors: ['origina-databases', 'origina-notifications'],
      inputTypes: ['trigger-conditions', 'recipient-rules', 'channel-preferences'],
      outputTypes: ['notification-config', 'trigger-summary', 'delivery-report'],
      domains: ['notifications', 'alerts', 'triggers', 'monitoring', 'subscriptions'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['review_database_automations'],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.20,
    },
    persona: {
      systemPromptAddition: 'You are a notification design specialist. Configure smart alerts that inform without overwhelming users.',
      specialInstructions: [
        'Suggest digest mode for high-frequency changes',
        'Include relevant context in notification messages',
        'Implement quiet hours and batching to reduce noise',
      ],
    },
    icon: 'bell',
    color: '#EA580C',
  },
  {
    agentTypeId: 'databases.timeline-view-builder',
    displayName: 'Timeline View Builder',
    domain: AgentDomain.Databases,
    category: AgentCategory.Creative,
    baseType: AgentType.Designer,
    description: 'Creates timeline/Gantt views from database tables with date ranges, milestones, dependencies, and critical path highlighting.',
    capabilities: {
      tools: ['analyze_views', 'analyze_database_schema', 'get_table_stats'],
      connectors: ['origina-databases'],
      inputTypes: ['table-id', 'date-range-fields', 'dependency-fields'],
      outputTypes: ['timeline-config', 'milestone-markers', 'critical-path'],
      domains: ['timeline', 'gantt', 'milestones', 'schedule', 'project-plan'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.20,
    },
    persona: {
      systemPromptAddition: 'You are a timeline visualization expert. Build clear, informative Gantt views that show project progress at a glance.',
      specialInstructions: [
        'Highlight overdue items prominently',
        'Show dependency arrows between related items',
        'Color-code bars by status, assignee, or priority',
      ],
    },
    icon: 'gantt-chart',
    color: '#4338CA',
  },
  {
    agentTypeId: 'databases.data-generator',
    displayName: 'Data Generator',
    domain: AgentDomain.Databases,
    category: AgentCategory.Technical,
    baseType: AgentType.Developer,
    description: 'Generates realistic sample data for database tables based on field types, constraints, and relationship patterns for testing and demos.',
    capabilities: {
      tools: ['add_row', 'analyze_database_schema', 'get_relation_map'],
      connectors: ['origina-databases'],
      inputTypes: ['table-id', 'row-count', 'data-profile', 'seed-config'],
      outputTypes: ['generated-rows', 'generation-report', 'data-preview'],
      domains: ['seed-data', 'testing', 'demo', 'sample', 'mock-data'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['add_row'],
      maxTokenBudget: 35000,
      maxCostUsdBudget: 0.35,
    },
    persona: {
      systemPromptAddition: 'You are a test data specialist. Generate realistic, diverse data that exercises all edge cases and field variations.',
      specialInstructions: [
        'Respect field constraints and relation integrity',
        'Include edge cases like empty strings, long values, and special characters',
        'Generate deterministic data with configurable seeds for reproducibility',
      ],
    },
    icon: 'dice-5',
    color: '#22D3EE',
  },
  {
    agentTypeId: 'databases.crm-builder',
    displayName: 'CRM Builder',
    domain: AgentDomain.Databases,
    category: AgentCategory.Business,
    baseType: AgentType.Sales,
    description: 'Builds custom CRM databases with contact management, deal pipelines, activity tracking, and sales funnel views.',
    capabilities: {
      tools: ['create_database', 'add_table', 'analyze_database_schema', 'get_table_stats'],
      connectors: ['origina-databases'],
      inputTypes: ['crm-requirements', 'pipeline-stages', 'contact-fields'],
      outputTypes: ['crm-database', 'pipeline-view', 'dashboard-config'],
      domains: ['crm', 'sales', 'contacts', 'deals', 'pipeline'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['create_database', 'add_table'],
      maxTokenBudget: 60000,
      maxCostUsdBudget: 0.60,
    },
    persona: {
      systemPromptAddition: 'You are a CRM architect. Design sales databases that track every customer interaction and optimize deal flow.',
      specialInstructions: [
        'Include standard CRM fields (company, contact, deal, activity)',
        'Create kanban views for deal pipeline stages',
        'Add automation for stage transition notifications',
      ],
    },
    icon: 'users',
    color: '#2563EB',
  },
  {
    agentTypeId: 'databases.inventory-builder',
    displayName: 'Inventory Builder',
    domain: AgentDomain.Databases,
    category: AgentCategory.Business,
    baseType: AgentType.Planner,
    description: 'Creates inventory management databases with stock tracking, reorder points, supplier relations, and warehouse location mapping.',
    capabilities: {
      tools: ['create_database', 'add_table', 'analyze_database_schema', 'get_relation_map'],
      connectors: ['origina-databases'],
      inputTypes: ['inventory-requirements', 'product-categories', 'warehouse-info'],
      outputTypes: ['inventory-database', 'reorder-rules', 'stock-dashboard'],
      domains: ['inventory', 'stock', 'warehouse', 'products', 'supply-chain'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['create_database', 'add_table'],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 0.50,
    },
    persona: {
      systemPromptAddition: 'You are an inventory systems expert. Design databases that keep stock levels accurate and prevent stockouts.',
      specialInstructions: [
        'Include reorder point calculations and alerts',
        'Track stock movements with audit trail',
        'Support multi-warehouse and multi-location setups',
      ],
    },
    icon: 'package',
    color: '#CA8A04',
  },
  {
    agentTypeId: 'databases.content-calendar-builder',
    displayName: 'Content Calendar Builder',
    domain: AgentDomain.Databases,
    category: AgentCategory.Creative,
    baseType: AgentType.Marketing,
    description: 'Creates content calendar databases with editorial workflows, publishing schedules, channel management, and content status tracking.',
    capabilities: {
      tools: ['create_database', 'add_table', 'analyze_database_schema', 'analyze_views'],
      connectors: ['origina-databases'],
      inputTypes: ['content-types', 'channels', 'team-roles', 'publishing-cadence'],
      outputTypes: ['content-database', 'editorial-calendar', 'workflow-config'],
      domains: ['content', 'editorial', 'publishing', 'social-media', 'marketing'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['create_database'],
      maxTokenBudget: 45000,
      maxCostUsdBudget: 0.45,
    },
    persona: {
      systemPromptAddition: 'You are a content operations expert. Design editorial databases that keep publishing on schedule across all channels.',
      specialInstructions: [
        'Create status workflow (idea, draft, review, scheduled, published)',
        'Include calendar and kanban views by default',
        'Add fields for SEO metadata and social media variants',
      ],
    },
    icon: 'newspaper',
    color: '#E11D48',
  },
  {
    agentTypeId: 'databases.workspace-usage-analyst',
    displayName: 'Workspace Usage Analyst',
    domain: AgentDomain.Databases,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Analyzes database usage patterns across the workspace including most active tables, least used views, and growth projections.',
    capabilities: {
      tools: ['get_workspace_stats', 'get_table_stats', 'analyze_views', 'analyze_database_schema'],
      connectors: ['origina-databases'],
      inputTypes: ['workspace-id', 'date-range', 'usage-type'],
      outputTypes: ['usage-report', 'growth-forecast', 'optimization-suggestions'],
      domains: ['usage', 'analytics', 'growth', 'adoption', 'workspace'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 0.25,
    },
    persona: {
      systemPromptAddition: 'You are a workspace analytics expert. Identify usage patterns and recommend optimizations to improve data management.',
      specialInstructions: [
        'Rank tables by activity level and growth rate',
        'Identify abandoned databases for cleanup',
        'Recommend consolidation of similar databases',
      ],
    },
    icon: 'activity',
    color: '#0D9488',
  },
  {
    agentTypeId: 'databases.row-link-resolver',
    displayName: 'Row Link Resolver',
    domain: AgentDomain.Databases,
    category: AgentCategory.Technical,
    baseType: AgentType.Developer,
    description: 'Resolves broken row links and orphaned references across related tables, rebuilding relational integrity after bulk operations.',
    capabilities: {
      tools: ['get_relation_map', 'get_table_stats', 'add_row', 'analyze_database_schema'],
      connectors: ['origina-databases'],
      inputTypes: ['table-id', 'broken-links-report', 'resolution-strategy'],
      outputTypes: ['repair-report', 'resolved-links', 'orphan-list'],
      domains: ['links', 'references', 'orphans', 'integrity', 'repair'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['add_row'],
      maxTokenBudget: 35000,
      maxCostUsdBudget: 0.35,
    },
    persona: {
      systemPromptAddition: 'You are a data integrity specialist. Find and fix broken links between records to restore relational consistency.',
      specialInstructions: [
        'Scan all relation fields for dangling references',
        'Suggest matching records for orphaned links',
        'Create repair report with before/after comparisons',
      ],
    },
    icon: 'link-2',
    color: '#6D28D9',
  },
  {
    agentTypeId: 'databases.schema-documenter',
    displayName: 'Schema Documenter',
    domain: AgentDomain.Databases,
    category: AgentCategory.Technical,
    baseType: AgentType.Writer,
    description: 'Generates comprehensive documentation for database schemas including field descriptions, relation maps, and usage guides.',
    capabilities: {
      tools: ['analyze_database_schema', 'get_relation_map', 'get_table_stats'],
      connectors: ['origina-databases'],
      inputTypes: ['database-id', 'documentation-style', 'audience'],
      outputTypes: ['schema-docs', 'data-dictionary', 'erd-diagram'],
      domains: ['documentation', 'data-dictionary', 'schema-docs', 'reference'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 0.40,
    },
    persona: {
      systemPromptAddition: 'You are a technical documentation writer for databases. Create clear, comprehensive data dictionaries that any team member can understand.',
      specialInstructions: [
        'Include field-level descriptions with example values',
        'Document all relations with cardinality notation',
        'Add usage guidelines and common query patterns',
      ],
    },
    icon: 'book-open',
    color: '#334155',
  },
]
