import { AgentDomain, AgentCategory, AgentType, CostTier, LatencyProfile } from '../../types'
import type { AgentCapabilityManifest } from '../../types'

export const AGENTS: AgentCapabilityManifest[] = [
  {
    agentTypeId: 'developer.code-reviewer',
    displayName: 'Code Reviewer',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.Reviewer,
    description: 'Reviews pull requests for code quality, security vulnerabilities, and adherence to team standards',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'create_page'],
      connectors: ['github', 'gitlab', 'bitbucket'],
      inputTypes: ['pull_request', 'code_diff', 'file_tree'],
      outputTypes: ['review_comment', 'issue', 'approval'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You are a senior code reviewer. Focus on correctness, readability, and maintainability. Flag security issues as high priority.',
      specialInstructions: ['Always explain why a change is suggested', 'Reference team style guide when applicable'],
    },
    icon: 'GitPullRequest',
    color: '#8B5CF6',
  },
  {
    agentTypeId: 'developer.api-monitor',
    displayName: 'API Monitor',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.Analyst,
    description: 'Monitors API health, response times, and error rates across all endpoints',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'get_workspace_stats'],
      connectors: ['datadog', 'new_relic', 'pagerduty'],
      inputTypes: ['api_metrics', 'error_log', 'latency_data'],
      outputTypes: ['alert', 'issue', 'health_report'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You monitor API endpoints continuously. Prioritize uptime and latency. Escalate P0 incidents immediately.',
      specialInstructions: ['Alert on 5xx spike above 1%', 'Track p99 latency trends'],
    },
    icon: 'Activity',
    color: '#EF4444',
  },
  {
    agentTypeId: 'developer.sandbox-manager',
    displayName: 'Sandbox Manager',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.DevOps,
    description: 'Provisions, configures, and tears down ephemeral sandbox environments for feature testing',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'get_workspace_stats'],
      connectors: ['docker', 'kubernetes', 'terraform'],
      inputTypes: ['branch_name', 'config_file', 'resource_spec'],
      outputTypes: ['environment_url', 'status_report', 'teardown_confirmation'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['provision_environment', 'teardown_environment'],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 5.0,
    },
    persona: {
      systemPromptAddition: 'You manage sandbox environments. Ensure isolation between environments and clean up resources after TTL expires.',
      specialInstructions: ['Always set a TTL on provisioned environments', 'Verify resource limits before provisioning'],
    },
    icon: 'Box',
    color: '#F59E0B',
  },
  {
    agentTypeId: 'developer.log-analyzer',
    displayName: 'Log Analyzer',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.Analyst,
    description: 'Parses application logs to identify errors, anomalies, and performance bottlenecks',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'get_workspace_stats'],
      connectors: ['elasticsearch', 'splunk', 'cloudwatch'],
      inputTypes: ['log_stream', 'error_trace', 'query_pattern'],
      outputTypes: ['anomaly_report', 'issue', 'root_cause_analysis'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 300_000,
      maxCostUsdBudget: 3.0,
    },
    persona: {
      systemPromptAddition: 'You analyze application logs for patterns. Correlate errors across services to identify root causes.',
      specialInstructions: ['Group related errors by trace ID', 'Highlight recurring patterns across time windows'],
    },
    icon: 'FileText',
    color: '#06B6D4',
  },
  {
    agentTypeId: 'developer.performance-profiler',
    displayName: 'Performance Profiler',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.Analyst,
    description: 'Profiles application performance, identifies bottlenecks, and recommends optimizations',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'create_page'],
      connectors: ['lighthouse', 'web_vitals', 'flame_graph'],
      inputTypes: ['performance_trace', 'bundle_analysis', 'runtime_metrics'],
      outputTypes: ['optimization_report', 'issue', 'benchmark_comparison'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You profile application performance. Focus on real-world user impact metrics like LCP, FID, and CLS.',
      specialInstructions: ['Compare against previous benchmarks', 'Prioritize fixes by user impact'],
    },
    icon: 'Gauge',
    color: '#10B981',
  },
  {
    agentTypeId: 'developer.documentation-generator',
    displayName: 'Documentation Generator',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.Writer,
    description: 'Generates and maintains API documentation, code comments, and developer guides from source code',
    capabilities: {
      tools: ['create_page', 'create_issue', 'get_workspace_stats'],
      connectors: ['github', 'notion', 'confluence'],
      inputTypes: ['source_code', 'api_schema', 'changelog'],
      outputTypes: ['documentation_page', 'api_reference', 'migration_guide'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['publish_documentation'],
      maxTokenBudget: 250_000,
      maxCostUsdBudget: 2.5,
    },
    persona: {
      systemPromptAddition: 'You generate clear, accurate technical documentation. Write for the target audience and include practical examples.',
      specialInstructions: ['Include code examples for every public API', 'Mark breaking changes prominently'],
    },
    icon: 'BookOpen',
    color: '#3B82F6',
  },
  {
    agentTypeId: 'developer.dependency-auditor',
    displayName: 'Dependency Auditor',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.Security,
    description: 'Scans project dependencies for known vulnerabilities, license conflicts, and outdated packages',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'get_workspace_stats'],
      connectors: ['npm', 'snyk', 'dependabot'],
      inputTypes: ['package_manifest', 'lockfile', 'vulnerability_db'],
      outputTypes: ['vulnerability_report', 'issue', 'upgrade_plan'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['auto_upgrade_dependency'],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You audit dependencies for security and compliance. Prioritize critical CVEs and license violations.',
      specialInstructions: ['Flag transitive dependency vulnerabilities', 'Check license compatibility with project license'],
    },
    icon: 'Shield',
    color: '#DC2626',
  },
  {
    agentTypeId: 'developer.test-generator',
    displayName: 'Test Generator',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.Developer,
    description: 'Generates unit tests, integration tests, and edge case coverage for new and existing code',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'create_page'],
      connectors: ['github', 'jest', 'vitest'],
      inputTypes: ['source_code', 'function_signature', 'test_coverage_report'],
      outputTypes: ['test_file', 'coverage_report', 'edge_case_list'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You generate comprehensive test suites. Cover happy paths, edge cases, and error scenarios.',
      specialInstructions: ['Use testing library best practices', 'Avoid testing implementation details'],
    },
    icon: 'TestTube',
    color: '#A855F7',
  },
  {
    agentTypeId: 'developer.migration-assistant',
    displayName: 'Migration Assistant',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.Developer,
    description: 'Assists with database migrations, framework upgrades, and API version transitions',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'create_page'],
      connectors: ['github', 'database', 'ci_cd'],
      inputTypes: ['schema_diff', 'migration_plan', 'breaking_changes'],
      outputTypes: ['migration_script', 'rollback_plan', 'compatibility_report'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['execute_migration', 'rollback_migration'],
      maxTokenBudget: 300_000,
      maxCostUsdBudget: 5.0,
    },
    persona: {
      systemPromptAddition: 'You handle migrations with extreme care. Always generate rollback plans and verify data integrity.',
      specialInstructions: ['Test migration on staging first', 'Create backup before execution'],
    },
    icon: 'ArrowRightLeft',
    color: '#F97316',
  },
  {
    agentTypeId: 'developer.ci-pipeline-optimizer',
    displayName: 'CI Pipeline Optimizer',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.DevOps,
    description: 'Analyzes CI/CD pipeline configurations to reduce build times and improve reliability',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'get_workspace_stats'],
      connectors: ['github_actions', 'circleci', 'jenkins'],
      inputTypes: ['pipeline_config', 'build_metrics', 'test_results'],
      outputTypes: ['optimization_report', 'pipeline_config', 'issue'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['modify_pipeline'],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You optimize CI/CD pipelines for speed and reliability. Focus on parallelization, caching, and flaky test detection.',
      specialInstructions: ['Identify the longest pipeline stages', 'Suggest caching strategies for dependencies'],
    },
    icon: 'Workflow',
    color: '#0EA5E9',
  },
  {
    agentTypeId: 'developer.incident-responder',
    displayName: 'Incident Responder',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.Coordinator,
    description: 'Coordinates incident response by triaging alerts, assembling responders, and tracking resolution',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'get_workspace_stats'],
      connectors: ['pagerduty', 'slack', 'statuspage'],
      inputTypes: ['alert', 'incident_report', 'runbook'],
      outputTypes: ['incident_timeline', 'status_update', 'postmortem'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: ['escalate_incident'],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You coordinate incident response. Stay calm, communicate clearly, and focus on mitigation before root cause analysis.',
      specialInstructions: ['Update status page within 5 minutes of detection', 'Log all actions in incident timeline'],
    },
    icon: 'Siren',
    color: '#EF4444',
  },
  {
    agentTypeId: 'developer.release-manager',
    displayName: 'Release Manager',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.Coordinator,
    description: 'Manages release cycles, generates changelogs, and coordinates deployment gates',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'create_page'],
      connectors: ['github', 'jira', 'slack'],
      inputTypes: ['commit_log', 'release_branch', 'deployment_config'],
      outputTypes: ['changelog', 'release_notes', 'deployment_approval'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['create_release', 'deploy_production'],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You manage software releases. Ensure all checks pass, changelogs are accurate, and stakeholders are notified.',
      specialInstructions: ['Verify all CI checks green before release', 'Include breaking changes in release notes header'],
    },
    icon: 'Rocket',
    color: '#8B5CF6',
  },
  {
    agentTypeId: 'developer.error-tracker',
    displayName: 'Error Tracker',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.Analyst,
    description: 'Aggregates, deduplicates, and prioritizes runtime errors from production environments',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'get_workspace_stats'],
      connectors: ['sentry', 'bugsnag', 'rollbar'],
      inputTypes: ['error_event', 'stack_trace', 'user_session'],
      outputTypes: ['error_group', 'issue', 'impact_assessment'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You track and prioritize production errors. Group related errors and assess user impact to determine priority.',
      specialInstructions: ['Deduplicate similar stack traces', 'Calculate affected user percentage'],
    },
    icon: 'Bug',
    color: '#F43F5E',
  },
  {
    agentTypeId: 'developer.schema-validator',
    displayName: 'Schema Validator',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.Reviewer,
    description: 'Validates API schemas, database schemas, and configuration files against defined contracts',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'create_page'],
      connectors: ['openapi', 'graphql', 'json_schema'],
      inputTypes: ['api_schema', 'database_schema', 'config_file'],
      outputTypes: ['validation_report', 'issue', 'compatibility_matrix'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 4,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You validate schemas for correctness and backward compatibility. Flag breaking changes immediately.',
      specialInstructions: ['Check for required field additions on existing types', 'Validate enum value consistency'],
    },
    icon: 'FileCheck',
    color: '#14B8A6',
  },
  {
    agentTypeId: 'developer.refactoring-advisor',
    displayName: 'Refactoring Advisor',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.Developer,
    description: 'Identifies code smells, suggests refactoring patterns, and estimates refactoring effort',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'create_page'],
      connectors: ['sonarqube', 'codeclimate', 'github'],
      inputTypes: ['source_code', 'complexity_report', 'dependency_graph'],
      outputTypes: ['refactoring_plan', 'issue', 'effort_estimate'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 250_000,
      maxCostUsdBudget: 2.5,
    },
    persona: {
      systemPromptAddition: 'You advise on code refactoring. Prioritize changes that reduce complexity and improve testability.',
      specialInstructions: ['Calculate cyclomatic complexity before and after', 'Suggest incremental refactoring steps'],
    },
    icon: 'Wrench',
    color: '#6366F1',
  },
  {
    agentTypeId: 'developer.database-optimizer',
    displayName: 'Database Optimizer',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.Analyst,
    description: 'Analyzes database queries, suggests index improvements, and identifies N+1 query problems',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'get_workspace_stats'],
      connectors: ['postgresql', 'mysql', 'mongodb'],
      inputTypes: ['query_log', 'explain_plan', 'schema_definition'],
      outputTypes: ['optimization_report', 'issue', 'index_suggestion'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['create_index', 'alter_table'],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You optimize database performance. Focus on query plans, indexing strategies, and connection pooling.',
      specialInstructions: ['Always check explain plans before suggesting changes', 'Consider read vs write ratio'],
    },
    icon: 'Database',
    color: '#0891B2',
  },
  {
    agentTypeId: 'developer.feature-flag-manager',
    displayName: 'Feature Flag Manager',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.DevOps,
    description: 'Manages feature flags, rollout percentages, and A/B test configurations',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'get_workspace_stats'],
      connectors: ['launchdarkly', 'split', 'flagsmith'],
      inputTypes: ['flag_config', 'rollout_plan', 'experiment_results'],
      outputTypes: ['flag_status', 'rollout_report', 'experiment_summary'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['full_rollout', 'kill_switch'],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You manage feature flags and progressive rollouts. Ensure clean flag lifecycle and prevent stale flags.',
      specialInstructions: ['Track flag age and schedule cleanup', 'Monitor error rates during rollout'],
    },
    icon: 'Flag',
    color: '#D946EF',
  },
  {
    agentTypeId: 'developer.infrastructure-scanner',
    displayName: 'Infrastructure Scanner',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.Security,
    description: 'Scans infrastructure-as-code for misconfigurations, security gaps, and cost optimization opportunities',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'get_workspace_stats'],
      connectors: ['terraform', 'aws', 'gcp'],
      inputTypes: ['iac_template', 'cloud_config', 'cost_report'],
      outputTypes: ['security_finding', 'issue', 'cost_optimization'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['modify_infrastructure'],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You scan infrastructure configurations. Flag publicly exposed resources, overly permissive IAM, and cost waste.',
      specialInstructions: ['Check for publicly accessible S3 buckets', 'Identify unused or oversized resources'],
    },
    icon: 'Server',
    color: '#64748B',
  },
  {
    agentTypeId: 'developer.git-workflow-enforcer',
    displayName: 'Git Workflow Enforcer',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.Reviewer,
    description: 'Enforces git workflow conventions including branch naming, commit messages, and merge policies',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'create_cycle'],
      connectors: ['github', 'gitlab', 'bitbucket'],
      inputTypes: ['branch_name', 'commit_message', 'merge_request'],
      outputTypes: ['policy_violation', 'issue', 'enforcement_report'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 50_000,
      maxCostUsdBudget: 0.2,
    },
    persona: {
      systemPromptAddition: 'You enforce git workflow standards. Be firm but educational when flagging violations.',
      specialInstructions: ['Check conventional commit format', 'Verify branch names match pattern'],
    },
    icon: 'GitBranch',
    color: '#F97316',
  },
  {
    agentTypeId: 'developer.api-design-reviewer',
    displayName: 'API Design Reviewer',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.Reviewer,
    description: 'Reviews API designs for RESTful best practices, naming consistency, and backward compatibility',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'create_page'],
      connectors: ['openapi', 'postman', 'swagger'],
      inputTypes: ['api_spec', 'endpoint_definition', 'schema_change'],
      outputTypes: ['review_comment', 'issue', 'design_guideline'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You review API designs for consistency and usability. Follow REST conventions and ensure backward compatibility.',
      specialInstructions: ['Check for consistent naming across endpoints', 'Verify pagination patterns are standard'],
    },
    icon: 'Network',
    color: '#2563EB',
  },
  {
    agentTypeId: 'developer.container-optimizer',
    displayName: 'Container Optimizer',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.DevOps,
    description: 'Optimizes Docker images for size, security, and build speed',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'get_workspace_stats'],
      connectors: ['docker', 'ecr', 'gcr'],
      inputTypes: ['dockerfile', 'image_manifest', 'layer_analysis'],
      outputTypes: ['optimization_report', 'issue', 'dockerfile_suggestion'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You optimize container images. Focus on multi-stage builds, layer caching, and minimal base images.',
      specialInstructions: ['Suggest multi-stage builds where applicable', 'Flag secrets in build layers'],
    },
    icon: 'Container',
    color: '#0284C7',
  },
  {
    agentTypeId: 'developer.accessibility-auditor',
    displayName: 'Accessibility Auditor',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.Reviewer,
    description: 'Audits web interfaces for WCAG compliance, keyboard navigation, and screen reader compatibility',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'create_page'],
      connectors: ['axe', 'lighthouse', 'wave'],
      inputTypes: ['html_snapshot', 'component_tree', 'aria_audit'],
      outputTypes: ['accessibility_report', 'issue', 'remediation_guide'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You audit for accessibility. Test with keyboard-only navigation and verify ARIA attributes are correct.',
      specialInstructions: ['Check color contrast ratios meet AA minimum', 'Verify all interactive elements are keyboard accessible'],
    },
    icon: 'Eye',
    color: '#059669',
  },
  {
    agentTypeId: 'developer.secret-scanner',
    displayName: 'Secret Scanner',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.Security,
    description: 'Scans code repositories for accidentally committed secrets, API keys, and credentials',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'get_workspace_stats'],
      connectors: ['github', 'trufflehog', 'gitleaks'],
      inputTypes: ['commit_diff', 'file_content', 'git_history'],
      outputTypes: ['secret_finding', 'issue', 'remediation_steps'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You scan for leaked secrets. Treat every finding as critical and provide immediate remediation steps.',
      specialInstructions: ['Check for patterns matching common API key formats', 'Scan git history, not just current files'],
    },
    icon: 'KeyRound',
    color: '#DC2626',
  },
  {
    agentTypeId: 'developer.load-tester',
    displayName: 'Load Tester',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.Analyst,
    description: 'Designs and executes load test scenarios to identify system capacity limits and bottlenecks',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'create_page'],
      connectors: ['k6', 'artillery', 'gatling'],
      inputTypes: ['test_scenario', 'endpoint_list', 'traffic_pattern'],
      outputTypes: ['load_test_report', 'issue', 'capacity_plan'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['execute_load_test'],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 3.0,
    },
    persona: {
      systemPromptAddition: 'You design and analyze load tests. Model realistic traffic patterns and identify the weakest link.',
      specialInstructions: ['Start with baseline tests before stress tests', 'Monitor resource utilization during tests'],
    },
    icon: 'Zap',
    color: '#EAB308',
  },
  {
    agentTypeId: 'developer.code-coverage-analyzer',
    displayName: 'Code Coverage Analyzer',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.Analyst,
    description: 'Analyzes test coverage, identifies untested code paths, and prioritizes coverage improvements',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'get_workspace_stats'],
      connectors: ['codecov', 'coveralls', 'istanbul'],
      inputTypes: ['coverage_report', 'source_map', 'test_results'],
      outputTypes: ['coverage_analysis', 'issue', 'priority_list'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You analyze test coverage. Focus on critical paths and high-risk code sections rather than chasing 100% coverage.',
      specialInstructions: ['Prioritize business-critical code paths', 'Flag decreasing coverage trends'],
    },
    icon: 'BarChart',
    color: '#7C3AED',
  },
  {
    agentTypeId: 'developer.environment-config-manager',
    displayName: 'Environment Config Manager',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.DevOps,
    description: 'Manages environment variables, configuration files, and secrets across staging and production',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'get_workspace_stats'],
      connectors: ['vault', 'aws_ssm', 'dotenv'],
      inputTypes: ['env_config', 'secret_reference', 'deployment_target'],
      outputTypes: ['config_diff', 'issue', 'sync_report'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['update_production_config'],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You manage environment configurations. Never log secret values and always use encrypted storage.',
      specialInstructions: ['Validate config changes against schema before apply', 'Detect config drift between environments'],
    },
    icon: 'Settings',
    color: '#475569',
  },
  {
    agentTypeId: 'developer.monorepo-navigator',
    displayName: 'Monorepo Navigator',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.Developer,
    description: 'Navigates monorepo structures, tracks cross-package dependencies, and suggests optimal build ordering',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'get_workspace_stats'],
      connectors: ['turborepo', 'nx', 'lerna'],
      inputTypes: ['package_graph', 'change_set', 'build_config'],
      outputTypes: ['dependency_graph', 'build_order', 'impact_analysis'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You navigate monorepo structures. Map dependencies accurately and minimize unnecessary rebuilds.',
      specialInstructions: ['Track transitive dependency changes', 'Suggest scope filters for CI runs'],
    },
    icon: 'FolderTree',
    color: '#CA8A04',
  },
  {
    agentTypeId: 'developer.api-mocking-generator',
    displayName: 'API Mocking Generator',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.Developer,
    description: 'Generates realistic mock APIs and fixtures from OpenAPI specs for local development and testing',
    capabilities: {
      tools: ['create_issue', 'create_page', 'list_issues'],
      connectors: ['openapi', 'msw', 'json_server'],
      inputTypes: ['api_spec', 'sample_data', 'response_schema'],
      outputTypes: ['mock_handler', 'fixture_data', 'msw_config'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You generate realistic API mocks. Create varied, edge-case-rich test data that exercises client code thoroughly.',
      specialInstructions: ['Include error response mocks', 'Generate realistic data distributions'],
    },
    icon: 'Plug',
    color: '#0D9488',
  },
  {
    agentTypeId: 'developer.tech-debt-tracker',
    displayName: 'Tech Debt Tracker',
    domain: AgentDomain.Developer,
    category: AgentCategory.Technical,
    baseType: AgentType.Planner,
    description: 'Catalogs technical debt, estimates paydown cost, and recommends prioritized remediation sprints',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'create_cycle'],
      connectors: ['sonarqube', 'github', 'jira'],
      inputTypes: ['codebase_metrics', 'todo_comments', 'dependency_age'],
      outputTypes: ['debt_inventory', 'sprint_plan', 'issue'],
      domains: ['developer'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You track and prioritize technical debt. Quantify debt in terms of developer time and risk to help with prioritization.',
      specialInstructions: ['Categorize debt by type: architecture, code quality, dependency, documentation', 'Estimate interest rate for each debt item'],
    },
    icon: 'ClipboardList',
    color: '#B45309',
  },
]
