import { AgentDomain, AgentCategory, AgentType, CostTier, LatencyProfile } from '../../types'
import type { AgentCapabilityManifest } from '../../types'

export const AGENTS: AgentCapabilityManifest[] = [
  {
    agentTypeId: 'documents.contract-analyzer',
    displayName: 'Contract Analyzer',
    domain: AgentDomain.Documents,
    category: AgentCategory.Legal,
    baseType: AgentType.Legal,
    description: 'Analyzes contracts for key clauses, obligations, deadlines, and risk areas with plain-language summaries of complex legal terms.',
    capabilities: {
      tools: ['search_pages', 'create_page', 'get_workspace_stats'],
      connectors: ['origina-documents'],
      inputTypes: ['contract-pdf', 'contract-text', 'analysis-request'],
      outputTypes: ['clause-summary', 'risk-report', 'obligation-list'],
      domains: ['contracts', 'legal', 'clauses', 'obligations', 'terms'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 80000,
      maxCostUsdBudget: 0.80,
    },
    persona: {
      systemPromptAddition: 'You are a contract analysis expert. Identify key terms, obligations, and risks in plain language that non-lawyers can understand.',
      specialInstructions: [
        'Highlight unusual or non-standard clauses',
        'Flag auto-renewal and termination provisions',
        'Summarize financial obligations with dates and amounts',
      ],
    },
    icon: 'file-search',
    color: '#4338CA',
  },
  {
    agentTypeId: 'documents.signature-workflow-manager',
    displayName: 'Signature Workflow Manager',
    domain: AgentDomain.Documents,
    category: AgentCategory.Business,
    baseType: AgentType.Coordinator,
    description: 'Orchestrates multi-party signature workflows with routing rules, sequential/parallel signing, reminders, and completion tracking.',
    capabilities: {
      tools: ['create_template', 'add_contact', 'search_pages', 'get_workspace_stats'],
      connectors: ['origina-documents', 'origina-notifications'],
      inputTypes: ['signer-list', 'routing-rules', 'deadline-config'],
      outputTypes: ['workflow-status', 'completion-report', 'reminder-schedule'],
      domains: ['signatures', 'signing', 'workflow', 'routing', 'approvals'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['create_template'],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 0.40,
    },
    persona: {
      systemPromptAddition: 'You are a signature workflow specialist. Design efficient signing flows that minimize turnaround time and maximize completion rates.',
      specialInstructions: [
        'Suggest optimal signing order based on signer roles',
        'Configure escalation paths for overdue signatures',
        'Track signing progress with real-time status updates',
      ],
    },
    icon: 'pen-tool',
    color: '#6366F1',
  },
  {
    agentTypeId: 'documents.field-placement-assistant',
    displayName: 'Field Placement Assistant',
    domain: AgentDomain.Documents,
    category: AgentCategory.Technical,
    baseType: AgentType.Designer,
    description: 'Automatically detects and places signature fields, date fields, initials, and text inputs on documents using layout analysis.',
    capabilities: {
      tools: ['create_template', 'search_pages'],
      connectors: ['origina-documents'],
      inputTypes: ['document-pdf', 'field-types', 'signer-assignments'],
      outputTypes: ['field-placement-map', 'annotated-document', 'placement-preview'],
      domains: ['fields', 'placement', 'layout', 'annotations', 'form-fields'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 35000,
      maxCostUsdBudget: 0.35,
    },
    persona: {
      systemPromptAddition: 'You are a document layout analyst. Place signature and form fields precisely where they belong on each document page.',
      specialInstructions: [
        'Detect signature lines and underscored areas automatically',
        'Place date fields adjacent to signature fields',
        'Assign fields to correct signers based on document context',
      ],
    },
    icon: 'crosshair',
    color: '#0EA5E9',
  },
  {
    agentTypeId: 'documents.audit-trail-generator',
    displayName: 'Audit Trail Generator',
    domain: AgentDomain.Documents,
    category: AgentCategory.Legal,
    baseType: AgentType.Compliance,
    description: 'Generates tamper-evident audit trails for document signing events including timestamps, IP addresses, and certificate of completion.',
    capabilities: {
      tools: ['search_pages', 'create_page', 'get_workspace_stats'],
      connectors: ['origina-documents'],
      inputTypes: ['document-id', 'event-log', 'compliance-requirements'],
      outputTypes: ['audit-trail', 'certificate-of-completion', 'compliance-report'],
      domains: ['audit', 'compliance', 'trail', 'certificate', 'evidence'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.20,
    },
    persona: {
      systemPromptAddition: 'You are a compliance documentation specialist. Generate legally defensible audit trails that satisfy regulatory requirements.',
      specialInstructions: [
        'Include all signing events with timestamps and identifiers',
        'Generate certificate of completion with document hash',
        'Format audit trails to meet eIDAS and ESIGN standards',
      ],
    },
    icon: 'shield',
    color: '#059669',
  },
  {
    agentTypeId: 'documents.template-populator',
    displayName: 'Template Populator',
    domain: AgentDomain.Documents,
    category: AgentCategory.Business,
    baseType: AgentType.Developer,
    description: 'Populates document templates with data from contacts, databases, and form responses, generating ready-to-send documents in bulk.',
    capabilities: {
      tools: ['create_template', 'add_contact', 'search_pages'],
      connectors: ['origina-documents', 'origina-databases'],
      inputTypes: ['template-id', 'data-source', 'merge-fields'],
      outputTypes: ['populated-document', 'merge-report', 'error-list'],
      domains: ['templates', 'merge', 'populate', 'bulk', 'mail-merge'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['create_template'],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 0.40,
    },
    persona: {
      systemPromptAddition: 'You are a document automation specialist. Populate templates accurately with data from multiple sources in bulk.',
      specialInstructions: [
        'Validate all merge fields before generating documents',
        'Handle missing data gracefully with configurable fallbacks',
        'Preview first document before processing entire batch',
      ],
    },
    icon: 'file-plus',
    color: '#3B82F6',
  },
  {
    agentTypeId: 'documents.template-designer',
    displayName: 'Template Designer',
    domain: AgentDomain.Documents,
    category: AgentCategory.Creative,
    baseType: AgentType.Designer,
    description: 'Creates professional document templates with branded headers, footers, merge fields, and conditional sections for various document types.',
    capabilities: {
      tools: ['create_template', 'search_pages', 'create_page'],
      connectors: ['origina-documents'],
      inputTypes: ['template-requirements', 'brand-guidelines', 'document-type'],
      outputTypes: ['document-template', 'style-guide', 'field-definitions'],
      domains: ['templates', 'design', 'branding', 'layout', 'formatting'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['create_template'],
      maxTokenBudget: 45000,
      maxCostUsdBudget: 0.45,
    },
    persona: {
      systemPromptAddition: 'You are a document template designer. Create polished, professional templates that reflect brand identity and streamline document creation.',
      specialInstructions: [
        'Include placeholder merge fields with clear labels',
        'Design for both digital viewing and print',
        'Add conditional sections for optional content blocks',
      ],
    },
    icon: 'layout',
    color: '#A855F7',
  },
  {
    agentTypeId: 'documents.nda-generator',
    displayName: 'NDA Generator',
    domain: AgentDomain.Documents,
    category: AgentCategory.Legal,
    baseType: AgentType.Legal,
    description: 'Generates non-disclosure agreements with configurable terms, durations, exclusions, and jurisdiction-specific clauses.',
    capabilities: {
      tools: ['create_template', 'add_contact', 'create_page'],
      connectors: ['origina-documents'],
      inputTypes: ['nda-type', 'parties', 'terms-config', 'jurisdiction'],
      outputTypes: ['nda-document', 'clause-options', 'signing-ready-doc'],
      domains: ['nda', 'confidentiality', 'non-disclosure', 'legal'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['create_template'],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 0.40,
    },
    persona: {
      systemPromptAddition: 'You are an NDA drafting specialist. Generate comprehensive, enforceable non-disclosure agreements tailored to specific business needs.',
      specialInstructions: [
        'Offer mutual vs. unilateral NDA options',
        'Include standard carve-outs for public information',
        'Adapt language to specified jurisdiction requirements',
      ],
    },
    icon: 'file-lock',
    color: '#1E40AF',
  },
  {
    agentTypeId: 'documents.proposal-builder',
    displayName: 'Proposal Builder',
    domain: AgentDomain.Documents,
    category: AgentCategory.Business,
    baseType: AgentType.Sales,
    description: 'Creates professional business proposals with executive summaries, scope definitions, pricing tables, and terms and conditions.',
    capabilities: {
      tools: ['create_template', 'create_page', 'search_pages'],
      connectors: ['origina-documents'],
      inputTypes: ['proposal-brief', 'pricing-data', 'company-info'],
      outputTypes: ['proposal-document', 'pricing-table', 'executive-summary'],
      domains: ['proposals', 'sales', 'pricing', 'scope', 'rfp'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['create_template'],
      maxTokenBudget: 60000,
      maxCostUsdBudget: 0.60,
    },
    persona: {
      systemPromptAddition: 'You are a business proposal writer. Craft compelling proposals that clearly communicate value and win deals.',
      specialInstructions: [
        'Lead with client pain points and your solution',
        'Include clear pricing with optional tiers',
        'Add case studies or social proof when available',
      ],
    },
    icon: 'presentation',
    color: '#16A34A',
  },
  {
    agentTypeId: 'documents.clause-library-manager',
    displayName: 'Clause Library Manager',
    domain: AgentDomain.Documents,
    category: AgentCategory.Legal,
    baseType: AgentType.Legal,
    description: 'Manages a reusable library of legal clauses with version tracking, categorization, and smart clause recommendations for document assembly.',
    capabilities: {
      tools: ['search_pages', 'create_page', 'get_workspace_stats'],
      connectors: ['origina-documents'],
      inputTypes: ['clause-text', 'category', 'version-notes'],
      outputTypes: ['clause-library', 'clause-recommendations', 'version-history'],
      domains: ['clauses', 'library', 'legal-text', 'reusable', 'versions'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 0.25,
    },
    persona: {
      systemPromptAddition: 'You are a legal clause librarian. Organize, categorize, and recommend reusable legal text for efficient document assembly.',
      specialInstructions: [
        'Tag clauses with jurisdiction and document type applicability',
        'Track clause versions with change summaries',
        'Suggest alternative clause options ranked by risk level',
      ],
    },
    icon: 'library',
    color: '#7C3AED',
  },
  {
    agentTypeId: 'documents.redline-comparator',
    displayName: 'Redline Comparator',
    domain: AgentDomain.Documents,
    category: AgentCategory.Legal,
    baseType: AgentType.Reviewer,
    description: 'Compares document versions to produce redline markups highlighting additions, deletions, and modifications with change summaries.',
    capabilities: {
      tools: ['search_pages', 'create_page'],
      connectors: ['origina-documents'],
      inputTypes: ['document-v1', 'document-v2', 'comparison-config'],
      outputTypes: ['redline-document', 'change-summary', 'diff-report'],
      domains: ['redline', 'comparison', 'diff', 'versions', 'changes'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 0.50,
    },
    persona: {
      systemPromptAddition: 'You are a document comparison expert. Produce clear, accurate redlines that make every change visible and understandable.',
      specialInstructions: [
        'Categorize changes as substantive vs. formatting',
        'Summarize the impact of material changes',
        'Flag changes to key terms like pricing, dates, and obligations',
      ],
    },
    icon: 'diff',
    color: '#DC2626',
  },
  {
    agentTypeId: 'documents.contact-manager',
    displayName: 'Contact Manager',
    domain: AgentDomain.Documents,
    category: AgentCategory.Business,
    baseType: AgentType.Coordinator,
    description: 'Manages document recipients and signing contacts with deduplication, role assignment, and contact information validation.',
    capabilities: {
      tools: ['add_contact', 'search_pages', 'get_workspace_stats'],
      connectors: ['origina-documents'],
      inputTypes: ['contact-list', 'role-assignments', 'validation-rules'],
      outputTypes: ['contact-directory', 'validation-report', 'dedup-results'],
      domains: ['contacts', 'recipients', 'signers', 'directory', 'people'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.15,
    },
    persona: {
      systemPromptAddition: 'You are a contact management specialist. Keep signing contact lists clean, current, and properly organized.',
      specialInstructions: [
        'Validate email addresses and phone numbers',
        'Detect and merge duplicate contacts',
        'Maintain role history for recurring signers',
      ],
    },
    icon: 'contact',
    color: '#0891B2',
  },
  {
    agentTypeId: 'documents.expiration-monitor',
    displayName: 'Expiration Monitor',
    domain: AgentDomain.Documents,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Monitors document expiration dates and renewal deadlines, sending proactive alerts before contracts lapse or require action.',
    capabilities: {
      tools: ['search_pages', 'get_workspace_stats', 'create_page'],
      connectors: ['origina-documents', 'origina-notifications'],
      inputTypes: ['document-list', 'alert-rules', 'date-range'],
      outputTypes: ['expiration-report', 'renewal-calendar', 'alert-schedule'],
      domains: ['expiration', 'renewal', 'deadlines', 'monitoring', 'alerts'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.20,
    },
    persona: {
      systemPromptAddition: 'You are a contract lifecycle monitor. Track every expiration date and ensure nothing slips through the cracks.',
      specialInstructions: [
        'Alert 90, 60, and 30 days before expiration by default',
        'Identify auto-renewal clauses and their notice periods',
        'Prioritize expirations by contract value and risk',
      ],
    },
    icon: 'clock',
    color: '#D97706',
  },
  {
    agentTypeId: 'documents.bulk-sender',
    displayName: 'Bulk Sender',
    domain: AgentDomain.Documents,
    category: AgentCategory.Business,
    baseType: AgentType.Coordinator,
    description: 'Sends documents for signature to multiple recipients in bulk with personalized merge fields, staggered delivery, and tracking.',
    capabilities: {
      tools: ['create_template', 'add_contact', 'search_pages', 'get_workspace_stats'],
      connectors: ['origina-documents', 'origina-notifications'],
      inputTypes: ['template-id', 'recipient-list', 'merge-data', 'schedule'],
      outputTypes: ['send-report', 'delivery-status', 'completion-tracker'],
      domains: ['bulk-send', 'mass-signing', 'batch', 'delivery'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['create_template', 'add_contact'],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 0.60,
    },
    persona: {
      systemPromptAddition: 'You are a bulk document operations specialist. Send personalized documents at scale while maintaining quality and compliance.',
      specialInstructions: [
        'Validate all merge fields before sending',
        'Stagger delivery to avoid email throttling',
        'Provide real-time completion dashboard',
      ],
    },
    icon: 'send',
    color: '#3B82F6',
  },
  {
    agentTypeId: 'documents.compliance-checker',
    displayName: 'Compliance Checker',
    domain: AgentDomain.Documents,
    category: AgentCategory.Legal,
    baseType: AgentType.Compliance,
    description: 'Checks documents against regulatory requirements and internal policies, flagging missing clauses, non-compliant language, and required disclosures.',
    capabilities: {
      tools: ['search_pages', 'create_page', 'get_workspace_stats'],
      connectors: ['origina-documents'],
      inputTypes: ['document-id', 'compliance-framework', 'policy-rules'],
      outputTypes: ['compliance-report', 'missing-items', 'remediation-suggestions'],
      domains: ['compliance', 'regulatory', 'policy', 'requirements', 'disclosure'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 0.50,
    },
    persona: {
      systemPromptAddition: 'You are a regulatory compliance analyst. Verify documents meet all applicable requirements and flag gaps clearly.',
      specialInstructions: [
        'Check against industry-specific regulations (GDPR, HIPAA, SOX)',
        'Verify required disclosure language is present',
        'Prioritize findings by compliance risk level',
      ],
    },
    icon: 'check-circle',
    color: '#059669',
  },
  {
    agentTypeId: 'documents.version-controller',
    displayName: 'Version Controller',
    domain: AgentDomain.Documents,
    category: AgentCategory.Technical,
    baseType: AgentType.Developer,
    description: 'Manages document versions with branching, merging, conflict resolution, and version history navigation for collaborative editing.',
    capabilities: {
      tools: ['search_pages', 'create_page', 'get_workspace_stats'],
      connectors: ['origina-documents'],
      inputTypes: ['document-id', 'version-action', 'merge-config'],
      outputTypes: ['version-tree', 'diff-report', 'merge-result'],
      domains: ['versions', 'history', 'branching', 'merging', 'collaboration'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 0.25,
    },
    persona: {
      systemPromptAddition: 'You are a document version control specialist. Track every change and make it easy to navigate document history.',
      specialInstructions: [
        'Automatically tag versions at key milestones (sent, signed, amended)',
        'Provide clear version comparison summaries',
        'Support branching for parallel review tracks',
      ],
    },
    icon: 'git-commit',
    color: '#475569',
  },
  {
    agentTypeId: 'documents.sow-generator',
    displayName: 'SOW Generator',
    domain: AgentDomain.Documents,
    category: AgentCategory.Business,
    baseType: AgentType.Writer,
    description: 'Generates statements of work with detailed scope, deliverables, timelines, acceptance criteria, and payment milestones.',
    capabilities: {
      tools: ['create_template', 'create_page', 'search_pages'],
      connectors: ['origina-documents'],
      inputTypes: ['project-brief', 'scope-requirements', 'timeline-constraints'],
      outputTypes: ['sow-document', 'milestone-schedule', 'deliverables-matrix'],
      domains: ['sow', 'scope', 'deliverables', 'milestones', 'services'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['create_template'],
      maxTokenBudget: 60000,
      maxCostUsdBudget: 0.60,
    },
    persona: {
      systemPromptAddition: 'You are a statement of work author. Draft precise, unambiguous SOWs that protect both parties and set clear expectations.',
      specialInstructions: [
        'Define measurable acceptance criteria for each deliverable',
        'Link payment milestones to specific deliverable completions',
        'Include clear assumptions and exclusions sections',
      ],
    },
    icon: 'file-text',
    color: '#0D9488',
  },
  {
    agentTypeId: 'documents.invoice-generator',
    displayName: 'Invoice Generator',
    domain: AgentDomain.Documents,
    category: AgentCategory.Business,
    baseType: AgentType.Finance,
    description: 'Creates professional invoices from templates with line items, tax calculations, payment terms, and branded formatting.',
    capabilities: {
      tools: ['create_template', 'add_contact', 'create_page'],
      connectors: ['origina-documents', 'origina-accounting'],
      inputTypes: ['invoice-data', 'template-id', 'tax-config'],
      outputTypes: ['invoice-document', 'payment-link', 'accounting-entry'],
      domains: ['invoices', 'billing', 'payments', 'accounts-receivable'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['create_template'],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 0.30,
    },
    persona: {
      systemPromptAddition: 'You are an invoicing specialist. Generate accurate, professional invoices that facilitate prompt payment.',
      specialInstructions: [
        'Calculate taxes based on jurisdiction rules',
        'Include clear payment terms and methods',
        'Number invoices sequentially for accounting compliance',
      ],
    },
    icon: 'receipt',
    color: '#16A34A',
  },
  {
    agentTypeId: 'documents.data-extractor',
    displayName: 'Data Extractor',
    domain: AgentDomain.Documents,
    category: AgentCategory.Technical,
    baseType: AgentType.Analyst,
    description: 'Extracts structured data from unstructured documents including dates, amounts, names, addresses, and custom fields using AI parsing.',
    capabilities: {
      tools: ['search_pages', 'create_page', 'get_workspace_stats'],
      connectors: ['origina-documents'],
      inputTypes: ['document-pdf', 'extraction-schema', 'field-definitions'],
      outputTypes: ['extracted-data', 'confidence-scores', 'review-queue'],
      domains: ['extraction', 'parsing', 'ocr', 'structured-data', 'fields'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 0.40,
    },
    persona: {
      systemPromptAddition: 'You are a document data extraction specialist. Pull structured data from unstructured documents with high accuracy.',
      specialInstructions: [
        'Report confidence scores for each extracted field',
        'Flag ambiguous extractions for human review',
        'Handle multi-page documents and complex layouts',
      ],
    },
    icon: 'scan',
    color: '#8B5CF6',
  },
  {
    agentTypeId: 'documents.reminder-scheduler',
    displayName: 'Reminder Scheduler',
    domain: AgentDomain.Documents,
    category: AgentCategory.Business,
    baseType: AgentType.Coordinator,
    description: 'Schedules and sends signing reminders with escalating urgency, personalized messages, and configurable frequency to improve completion rates.',
    capabilities: {
      tools: ['search_pages', 'add_contact', 'get_workspace_stats'],
      connectors: ['origina-documents', 'origina-notifications'],
      inputTypes: ['document-id', 'reminder-schedule', 'escalation-rules'],
      outputTypes: ['reminder-plan', 'delivery-report', 'completion-impact'],
      domains: ['reminders', 'follow-up', 'escalation', 'nudges', 'completion'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.15,
    },
    persona: {
      systemPromptAddition: 'You are a signing completion specialist. Design reminder cadences that are effective without being annoying.',
      specialInstructions: [
        'Start with gentle reminders, escalate tone over time',
        'Respect business hours and timezone differences',
        'Pause reminders when signers are on vacation',
      ],
    },
    icon: 'bell-ring',
    color: '#EA580C',
  },
  {
    agentTypeId: 'documents.legal-review-assistant',
    displayName: 'Legal Review Assistant',
    domain: AgentDomain.Documents,
    category: AgentCategory.Legal,
    baseType: AgentType.Reviewer,
    description: 'Assists legal teams in reviewing documents by flagging ambiguous language, missing definitions, inconsistent terms, and potential issues.',
    capabilities: {
      tools: ['search_pages', 'create_page', 'get_workspace_stats'],
      connectors: ['origina-documents'],
      inputTypes: ['document-text', 'review-checklist', 'legal-standards'],
      outputTypes: ['review-comments', 'issue-list', 'suggestion-markup'],
      domains: ['review', 'legal', 'markup', 'comments', 'issues'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 70000,
      maxCostUsdBudget: 0.70,
    },
    persona: {
      systemPromptAddition: 'You are a legal review assistant. Identify issues that could create liability, ambiguity, or enforceability problems.',
      specialInstructions: [
        'Check for defined terms used inconsistently',
        'Flag vague language like "reasonable" or "timely" without definitions',
        'Verify cross-references point to correct sections',
      ],
    },
    icon: 'scale',
    color: '#991B1B',
  },
  {
    agentTypeId: 'documents.employment-agreement-builder',
    displayName: 'Employment Agreement Builder',
    domain: AgentDomain.Documents,
    category: AgentCategory.People,
    baseType: AgentType.HR,
    description: 'Generates employment agreements, offer letters, and contractor agreements with jurisdiction-compliant terms and configurable clauses.',
    capabilities: {
      tools: ['create_template', 'add_contact', 'create_page'],
      connectors: ['origina-documents'],
      inputTypes: ['position-details', 'compensation-data', 'jurisdiction', 'employment-type'],
      outputTypes: ['agreement-document', 'clause-selections', 'signing-package'],
      domains: ['employment', 'offer-letter', 'contractor', 'hr', 'hiring'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['create_template'],
      maxTokenBudget: 45000,
      maxCostUsdBudget: 0.45,
    },
    persona: {
      systemPromptAddition: 'You are an employment documentation specialist. Draft compliant employment agreements tailored to each role and jurisdiction.',
      specialInstructions: [
        'Include jurisdiction-specific required clauses',
        'Adapt non-compete terms to enforceable standards',
        'Clearly separate base compensation, equity, and benefits',
      ],
    },
    icon: 'briefcase',
    color: '#2563EB',
  },
  {
    agentTypeId: 'documents.document-classifier',
    displayName: 'Document Classifier',
    domain: AgentDomain.Documents,
    category: AgentCategory.Technical,
    baseType: AgentType.Analyst,
    description: 'Automatically classifies uploaded documents by type (contract, invoice, NDA, proposal) and routes them to appropriate workflows.',
    capabilities: {
      tools: ['search_pages', 'get_workspace_stats'],
      connectors: ['origina-documents'],
      inputTypes: ['document-upload', 'classification-rules'],
      outputTypes: ['document-type', 'confidence-score', 'routing-decision'],
      domains: ['classification', 'routing', 'sorting', 'categorization', 'triage'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.10,
    },
    persona: {
      systemPromptAddition: 'You are a document classification expert. Quickly categorize documents and route them to the right workflow.',
      specialInstructions: [
        'Use first-page content and metadata for fast classification',
        'Support custom document type definitions',
        'Route low-confidence results to manual review',
      ],
    },
    icon: 'folder-input',
    color: '#F59E0B',
  },
  {
    agentTypeId: 'documents.signing-ceremony-guide',
    displayName: 'Signing Ceremony Guide',
    domain: AgentDomain.Documents,
    category: AgentCategory.Business,
    baseType: AgentType.CustomerSuccess,
    description: 'Guides signers through the document signing process with step-by-step instructions, field highlighting, and a progress indicator.',
    capabilities: {
      tools: ['search_pages', 'add_contact'],
      connectors: ['origina-documents'],
      inputTypes: ['document-id', 'signer-id', 'signing-preferences'],
      outputTypes: ['signing-guide', 'progress-status', 'completion-confirmation'],
      domains: ['signing', 'ceremony', 'guide', 'onboarding', 'ux'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.10,
    },
    persona: {
      systemPromptAddition: 'You are a signing experience guide. Make the document signing process intuitive and friction-free for every signer.',
      specialInstructions: [
        'Highlight the next field to sign or fill',
        'Provide plain-language descriptions of what each field means',
        'Celebrate completion with a confirmation summary',
      ],
    },
    icon: 'hand',
    color: '#10B981',
  },
  {
    agentTypeId: 'documents.document-summarizer',
    displayName: 'Document Summarizer',
    domain: AgentDomain.Documents,
    category: AgentCategory.Core,
    baseType: AgentType.Writer,
    description: 'Creates concise summaries of long documents with key points, action items, and section-by-section breakdowns for quick review.',
    capabilities: {
      tools: ['search_pages', 'create_page', 'get_workspace_stats'],
      connectors: ['origina-documents'],
      inputTypes: ['document-text', 'summary-length', 'focus-areas'],
      outputTypes: ['executive-summary', 'key-points', 'action-items'],
      domains: ['summary', 'abstract', 'overview', 'key-points', 'tldr'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 0.50,
    },
    persona: {
      systemPromptAddition: 'You are a document summarization expert. Distill lengthy documents into clear, actionable summaries without losing critical details.',
      specialInstructions: [
        'Preserve exact figures, dates, and names from the source',
        'Structure summaries with headers matching document sections',
        'Highlight decisions, commitments, and next steps',
      ],
    },
    icon: 'file-minus',
    color: '#64748B',
  },
  {
    agentTypeId: 'documents.accessibility-checker',
    displayName: 'Accessibility Checker',
    domain: AgentDomain.Documents,
    category: AgentCategory.Technical,
    baseType: AgentType.Reviewer,
    description: 'Checks documents for accessibility compliance including alt text, reading order, color contrast, and screen reader compatibility.',
    capabilities: {
      tools: ['search_pages', 'create_page'],
      connectors: ['origina-documents'],
      inputTypes: ['document-id', 'accessibility-standard'],
      outputTypes: ['accessibility-report', 'remediation-guide', 'compliance-score'],
      domains: ['accessibility', 'a11y', 'wcag', 'screen-reader', 'compliance'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.20,
    },
    persona: {
      systemPromptAddition: 'You are a document accessibility specialist. Ensure all documents are usable by everyone regardless of ability.',
      specialInstructions: [
        'Check against WCAG 2.1 AA standards',
        'Verify logical reading order for screen readers',
        'Flag insufficient color contrast ratios',
      ],
    },
    icon: 'accessibility',
    color: '#0D9488',
  },
  {
    agentTypeId: 'documents.translation-coordinator',
    displayName: 'Translation Coordinator',
    domain: AgentDomain.Documents,
    category: AgentCategory.Creative,
    baseType: AgentType.Translation,
    description: 'Coordinates document translations across languages, maintaining formatting, legal precision, and terminology consistency.',
    capabilities: {
      tools: ['create_page', 'search_pages', 'get_workspace_stats'],
      connectors: ['origina-documents'],
      inputTypes: ['source-document', 'target-languages', 'glossary'],
      outputTypes: ['translated-document', 'translation-notes', 'glossary-updates'],
      domains: ['translation', 'localization', 'multilingual', 'languages'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 60000,
      maxCostUsdBudget: 0.60,
    },
    persona: {
      systemPromptAddition: 'You are a document translation coordinator. Ensure translations preserve legal meaning, cultural context, and formatting.',
      specialInstructions: [
        'Maintain consistent terminology using project glossaries',
        'Flag culturally sensitive content that needs localization',
        'Preserve document layout and field positions across languages',
      ],
    },
    icon: 'languages',
    color: '#6D28D9',
  },
  {
    agentTypeId: 'documents.power-of-attorney-builder',
    displayName: 'Power of Attorney Builder',
    domain: AgentDomain.Documents,
    category: AgentCategory.Legal,
    baseType: AgentType.Legal,
    description: 'Generates power of attorney documents with configurable authority scope, duration limits, and jurisdiction-specific requirements.',
    capabilities: {
      tools: ['create_template', 'add_contact', 'create_page'],
      connectors: ['origina-documents'],
      inputTypes: ['poa-type', 'authority-scope', 'parties', 'jurisdiction'],
      outputTypes: ['poa-document', 'authority-matrix', 'signing-requirements'],
      domains: ['power-of-attorney', 'delegation', 'authority', 'legal'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['create_template'],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 0.40,
    },
    persona: {
      systemPromptAddition: 'You are a power of attorney drafting specialist. Create properly scoped POA documents that meet jurisdictional requirements.',
      specialInstructions: [
        'Clearly define and limit the scope of authority granted',
        'Include revocation provisions and expiration dates',
        'Note notarization and witness requirements by jurisdiction',
      ],
    },
    icon: 'stamp',
    color: '#78716C',
  },
  {
    agentTypeId: 'documents.document-archiver',
    displayName: 'Document Archiver',
    domain: AgentDomain.Documents,
    category: AgentCategory.Technical,
    baseType: AgentType.DevOps,
    description: 'Archives completed documents with proper retention policies, metadata tagging, searchable indexing, and compliance-grade storage.',
    capabilities: {
      tools: ['search_pages', 'get_workspace_stats', 'create_page'],
      connectors: ['origina-documents', 'archive-storage'],
      inputTypes: ['document-id', 'retention-policy', 'archive-config'],
      outputTypes: ['archive-record', 'retention-schedule', 'retrieval-index'],
      domains: ['archive', 'retention', 'storage', 'records-management'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.20,
    },
    persona: {
      systemPromptAddition: 'You are a records management specialist. Archive documents with proper retention policies and instant retrievability.',
      specialInstructions: [
        'Apply retention schedules based on document type and jurisdiction',
        'Index all metadata for full-text and faceted search',
        'Support legal hold requests to prevent premature deletion',
      ],
    },
    icon: 'archive',
    color: '#334155',
  },
  {
    agentTypeId: 'documents.pricing-table-builder',
    displayName: 'Pricing Table Builder',
    domain: AgentDomain.Documents,
    category: AgentCategory.Business,
    baseType: AgentType.Sales,
    description: 'Creates interactive pricing tables within documents with optional line items, quantity selectors, discount rules, and total calculations.',
    capabilities: {
      tools: ['create_template', 'create_page', 'search_pages'],
      connectors: ['origina-documents'],
      inputTypes: ['product-catalog', 'pricing-rules', 'discount-tiers'],
      outputTypes: ['pricing-table', 'quote-document', 'pricing-config'],
      domains: ['pricing', 'quotes', 'line-items', 'discounts', 'calculations'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['create_template'],
      maxTokenBudget: 35000,
      maxCostUsdBudget: 0.35,
    },
    persona: {
      systemPromptAddition: 'You are a pricing and quoting specialist. Build clear pricing tables that make it easy for clients to select options and understand costs.',
      specialInstructions: [
        'Include optional items that recipients can select',
        'Show subtotals, taxes, and grand totals clearly',
        'Support volume discounts and tiered pricing',
      ],
    },
    icon: 'table',
    color: '#F97316',
  },
  {
    agentTypeId: 'documents.notarization-coordinator',
    displayName: 'Notarization Coordinator',
    domain: AgentDomain.Documents,
    category: AgentCategory.Legal,
    baseType: AgentType.Coordinator,
    description: 'Coordinates remote online notarization sessions with identity verification, video conferencing, and digital seal application.',
    capabilities: {
      tools: ['add_contact', 'search_pages', 'get_workspace_stats'],
      connectors: ['origina-documents', 'notary-service'],
      inputTypes: ['document-id', 'notarization-type', 'party-info'],
      outputTypes: ['notarization-session', 'identity-verification', 'notarized-document'],
      domains: ['notarization', 'ron', 'identity', 'verification', 'seal'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['add_contact'],
      maxTokenBudget: 35000,
      maxCostUsdBudget: 0.50,
    },
    persona: {
      systemPromptAddition: 'You are a notarization process coordinator. Manage remote notarization sessions smoothly while ensuring legal compliance.',
      specialInstructions: [
        'Verify state-specific RON requirements before scheduling',
        'Coordinate identity verification steps in advance',
        'Ensure proper digital seal and certificate application',
      ],
    },
    icon: 'badge-check',
    color: '#B91C1C',
  },
  {
    agentTypeId: 'documents.document-analytics',
    displayName: 'Document Analytics',
    domain: AgentDomain.Documents,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Provides analytics on document performance including time-to-sign, completion rates, bottleneck identification, and engagement metrics.',
    capabilities: {
      tools: ['get_workspace_stats', 'search_pages', 'create_page'],
      connectors: ['origina-documents'],
      inputTypes: ['date-range', 'document-type-filter', 'team-filter'],
      outputTypes: ['analytics-dashboard', 'performance-report', 'bottleneck-analysis'],
      domains: ['analytics', 'metrics', 'performance', 'insights', 'reporting'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 0.25,
    },
    persona: {
      systemPromptAddition: 'You are a document operations analyst. Measure and optimize document workflows with data-driven insights.',
      specialInstructions: [
        'Track time-to-sign as the primary performance metric',
        'Identify signers who consistently cause delays',
        'Recommend process improvements based on completion patterns',
      ],
    },
    icon: 'trending-up',
    color: '#22C55E',
  },
]
