import { AgentDomain, AgentCategory, AgentType, CostTier, LatencyProfile } from '../../types'
import type { AgentCapabilityManifest } from '../../types'

export const AGENTS: AgentCapabilityManifest[] = [
  {
    agentTypeId: 'inbox.email-triager',
    displayName: 'Email Triager',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Core,
    baseType: AgentType.Coordinator,
    description: 'Automatically triages incoming emails by urgency, topic, and sender importance, routing them to appropriate folders or team members.',
    capabilities: {
      tools: ['mark_all_read', 'send_notification', 'get_workspace_stats'],
      connectors: ['orchestree-inbox', 'orchestree-notifications'],
      inputTypes: ['email-message', 'sender-context', 'triage-rules'],
      outputTypes: ['triage-decision', 'folder-assignment', 'priority-label'],
      domains: ['triage', 'email', 'routing', 'sorting', 'inbox'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.10,
    },
    persona: {
      systemPromptAddition: 'You are an email triage expert. Route every message to the right place with the right priority in seconds.',
      specialInstructions: [
        'Prioritize messages from VIP contacts and active deals',
        'Detect urgency signals in subject lines and body text',
        'Learn from user re-triage actions to improve accuracy',
      ],
    },
    icon: 'inbox',
    color: '#3B82F6',
  },
  {
    agentTypeId: 'inbox.priority-classifier',
    displayName: 'Priority Classifier',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Assigns priority levels to incoming messages based on sender importance, content urgency, deadline mentions, and historical patterns.',
    capabilities: {
      tools: ['send_notification', 'get_workspace_stats', 'get_upcoming_deadlines'],
      connectors: ['orchestree-inbox'],
      inputTypes: ['message-content', 'sender-profile', 'priority-rules'],
      outputTypes: ['priority-level', 'urgency-score', 'classification-reason'],
      domains: ['priority', 'urgency', 'classification', 'importance', 'ranking'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.10,
    },
    persona: {
      systemPromptAddition: 'You are a message priority analyst. Determine the true urgency of every message to help users focus on what matters.',
      specialInstructions: [
        'Weight sender seniority and relationship in priority scoring',
        'Detect deadline mentions and time-sensitive language',
        'Separate genuine urgency from artificial urgency',
      ],
    },
    icon: 'arrow-up-circle',
    color: '#DC2626',
  },
  {
    agentTypeId: 'inbox.auto-responder',
    displayName: 'Auto-Responder',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Business,
    baseType: AgentType.Writer,
    description: 'Drafts context-aware automatic responses for common message types including meeting requests, info queries, and acknowledgments.',
    capabilities: {
      tools: ['send_notification', 'get_workspace_stats'],
      connectors: ['orchestree-inbox'],
      inputTypes: ['incoming-message', 'response-templates', 'user-context'],
      outputTypes: ['draft-response', 'suggested-actions', 'send-confirmation'],
      domains: ['auto-reply', 'response', 'draft', 'acknowledgment', 'reply'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['send_notification'],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.25,
    },
    persona: {
      systemPromptAddition: 'You are an intelligent auto-responder. Draft helpful, natural-sounding replies that match the user communication style.',
      specialInstructions: [
        'Match tone and formality level to the incoming message',
        'Never auto-send without user approval for new contacts',
        'Include relevant context from workspace data in responses',
      ],
    },
    icon: 'reply',
    color: '#6366F1',
  },
  {
    agentTypeId: 'inbox.thread-summarizer',
    displayName: 'Thread Summarizer',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Core,
    baseType: AgentType.Writer,
    description: 'Summarizes long email threads into concise digests with key decisions, action items, and the current status of discussions.',
    capabilities: {
      tools: ['get_workspace_stats', 'send_notification'],
      connectors: ['orchestree-inbox'],
      inputTypes: ['email-thread', 'summary-length', 'focus-areas'],
      outputTypes: ['thread-summary', 'action-items', 'decision-log'],
      domains: ['summary', 'digest', 'thread', 'recap', 'overview'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 0.40,
    },
    persona: {
      systemPromptAddition: 'You are a conversation summarization expert. Distill lengthy threads into clear, actionable summaries.',
      specialInstructions: [
        'Identify the key decisions and who made them',
        'Extract all action items with assigned owners',
        'Note unresolved questions or pending decisions',
      ],
    },
    icon: 'align-left',
    color: '#8B5CF6',
  },
  {
    agentTypeId: 'inbox.action-item-extractor',
    displayName: 'Action Item Extractor',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Extracts action items, commitments, and follow-ups from messages and threads, creating tasks with owners and deadlines.',
    capabilities: {
      tools: ['get_workspace_stats', 'get_upcoming_deadlines', 'send_notification'],
      connectors: ['orchestree-inbox', 'orchestree-projects'],
      inputTypes: ['message-content', 'thread-context', 'participant-list'],
      outputTypes: ['action-item-list', 'task-assignments', 'deadline-schedule'],
      domains: ['action-items', 'tasks', 'follow-ups', 'commitments', 'todos'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.20,
    },
    persona: {
      systemPromptAddition: 'You are an action item detection specialist. Find every commitment and follow-up buried in email conversations.',
      specialInstructions: [
        'Detect implicit commitments like "I will" and "let me check"',
        'Assign owners based on who made the commitment',
        'Infer deadlines from context when not explicitly stated',
      ],
    },
    icon: 'check-square',
    color: '#059669',
  },
  {
    agentTypeId: 'inbox.spam-detector',
    displayName: 'Spam Detector',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Technical,
    baseType: AgentType.Security,
    description: 'Identifies spam, phishing attempts, and suspicious messages using content analysis, sender reputation, and link verification.',
    capabilities: {
      tools: ['mark_all_read', 'send_notification'],
      connectors: ['orchestree-inbox'],
      inputTypes: ['email-message', 'sender-data', 'link-list'],
      outputTypes: ['spam-score', 'threat-assessment', 'safe-sender-list'],
      domains: ['spam', 'phishing', 'security', 'threats', 'filtering'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.10,
    },
    persona: {
      systemPromptAddition: 'You are an email security analyst. Detect spam and phishing with precision while minimizing false positives.',
      specialInstructions: [
        'Check sender domain against known phishing patterns',
        'Analyze links for URL spoofing and redirects',
        'Flag urgency manipulation tactics used in social engineering',
      ],
    },
    icon: 'shield-alert',
    color: '#B91C1C',
  },
  {
    agentTypeId: 'inbox.meeting-scheduler',
    displayName: 'Meeting Scheduler',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Business,
    baseType: AgentType.Coordinator,
    description: 'Handles meeting scheduling requests from emails by checking availability, suggesting times, and sending calendar invitations.',
    capabilities: {
      tools: ['send_notification', 'get_workspace_stats', 'get_upcoming_deadlines'],
      connectors: ['orchestree-inbox', 'orchestree-scheduling'],
      inputTypes: ['scheduling-request', 'participant-list', 'time-preferences'],
      outputTypes: ['available-slots', 'meeting-invite', 'confirmation'],
      domains: ['meetings', 'scheduling', 'calendar', 'availability', 'invitations'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['send_notification'],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.25,
    },
    persona: {
      systemPromptAddition: 'You are a meeting coordination assistant. Find optimal meeting times and handle scheduling logistics seamlessly.',
      specialInstructions: [
        'Check all participants calendars for conflicts',
        'Respect time zone differences and working hours',
        'Suggest buffer time between back-to-back meetings',
      ],
    },
    icon: 'calendar-plus',
    color: '#0891B2',
  },
  {
    agentTypeId: 'inbox.follow-up-tracker',
    displayName: 'Follow-Up Tracker',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Business,
    baseType: AgentType.Coordinator,
    description: 'Tracks sent messages awaiting responses, reminds users to follow up, and escalates overdue communications.',
    capabilities: {
      tools: ['send_notification', 'get_upcoming_deadlines', 'get_workspace_stats'],
      connectors: ['orchestree-inbox'],
      inputTypes: ['sent-messages', 'follow-up-rules', 'response-deadlines'],
      outputTypes: ['pending-responses', 'follow-up-reminders', 'escalation-alerts'],
      domains: ['follow-up', 'tracking', 'responses', 'reminders', 'escalation'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.15,
    },
    persona: {
      systemPromptAddition: 'You are a follow-up tracking specialist. Ensure no important sent message goes unanswered beyond the expected timeframe.',
      specialInstructions: [
        'Track expected response time based on message type',
        'Suggest follow-up message drafts after waiting period',
        'Escalate to manager if critical messages are overdue',
      ],
    },
    icon: 'clock',
    color: '#D97706',
  },
  {
    agentTypeId: 'inbox.email-composer',
    displayName: 'Email Composer',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Creative,
    baseType: AgentType.Writer,
    description: 'Drafts professional emails with appropriate tone, structure, and content based on user intent, recipient context, and communication guidelines.',
    capabilities: {
      tools: ['send_notification', 'get_workspace_stats'],
      connectors: ['orchestree-inbox'],
      inputTypes: ['email-intent', 'recipient-info', 'key-points', 'tone'],
      outputTypes: ['email-draft', 'subject-line-options', 'tone-analysis'],
      domains: ['compose', 'writing', 'drafting', 'email', 'communication'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 0.30,
    },
    persona: {
      systemPromptAddition: 'You are a professional email writer. Draft clear, effective emails that achieve the intended outcome.',
      specialInstructions: [
        'Adapt writing style to match company communication norms',
        'Keep emails concise with clear calls to action',
        'Suggest compelling subject lines that drive opens',
      ],
    },
    icon: 'edit-3',
    color: '#4338CA',
  },
  {
    agentTypeId: 'inbox.unsubscribe-manager',
    displayName: 'Unsubscribe Manager',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Technical,
    baseType: AgentType.Developer,
    description: 'Identifies newsletter and marketing subscriptions, helps bulk unsubscribe from unwanted lists, and maintains subscription preferences.',
    capabilities: {
      tools: ['mark_all_read', 'send_notification'],
      connectors: ['orchestree-inbox'],
      inputTypes: ['subscription-list', 'preference-rules', 'keep-list'],
      outputTypes: ['subscription-audit', 'unsubscribe-actions', 'cleaned-inbox-report'],
      domains: ['unsubscribe', 'subscriptions', 'newsletters', 'cleanup', 'preferences'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['mark_all_read'],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.15,
    },
    persona: {
      systemPromptAddition: 'You are a subscription management specialist. Clean up inbox clutter by identifying and removing unwanted subscriptions.',
      specialInstructions: [
        'Categorize subscriptions by type and engagement level',
        'Flag subscriptions with no opens in the past 90 days',
        'Preserve important newsletters the user actively reads',
      ],
    },
    icon: 'x-circle',
    color: '#EF4444',
  },
  {
    agentTypeId: 'inbox.contact-enricher',
    displayName: 'Contact Enricher',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Business,
    baseType: AgentType.Researcher,
    description: 'Enriches email contact profiles with job titles, company info, social links, and interaction history from inbox conversations.',
    capabilities: {
      tools: ['get_workspace_stats', 'send_notification'],
      connectors: ['orchestree-inbox', 'enrichment-api'],
      inputTypes: ['email-address', 'contact-context', 'enrichment-fields'],
      outputTypes: ['enriched-profile', 'company-info', 'interaction-history'],
      domains: ['contacts', 'enrichment', 'profiles', 'company-data', 'people'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 0.30,
    },
    persona: {
      systemPromptAddition: 'You are a contact intelligence specialist. Build rich profiles for email contacts to improve relationship management.',
      specialInstructions: [
        'Extract job titles and company names from email signatures',
        'Track communication frequency and recency',
        'Identify key contacts based on interaction patterns',
      ],
    },
    icon: 'user-plus',
    color: '#2563EB',
  },
  {
    agentTypeId: 'inbox.sentiment-analyzer',
    displayName: 'Sentiment Analyzer',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Analyzes emotional tone and sentiment of incoming messages to flag upset customers, escalation risks, and positive feedback.',
    capabilities: {
      tools: ['send_notification', 'get_workspace_stats'],
      connectors: ['orchestree-inbox'],
      inputTypes: ['message-content', 'sender-history', 'context'],
      outputTypes: ['sentiment-score', 'emotion-labels', 'escalation-risk'],
      domains: ['sentiment', 'emotion', 'tone', 'satisfaction', 'mood'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.10,
    },
    persona: {
      systemPromptAddition: 'You are a communication sentiment analyst. Detect emotional undertones to help prioritize and handle messages appropriately.',
      specialInstructions: [
        'Distinguish frustration from casual negative language',
        'Flag escalation risk when sentiment trends negative over a thread',
        'Highlight positive feedback for team morale tracking',
      ],
    },
    icon: 'smile',
    color: '#F59E0B',
  },
  {
    agentTypeId: 'inbox.digest-generator',
    displayName: 'Digest Generator',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Core,
    baseType: AgentType.Writer,
    description: 'Generates daily or weekly inbox digests summarizing key messages, action items, and important updates across all communication channels.',
    capabilities: {
      tools: ['get_workspace_stats', 'get_upcoming_deadlines', 'mark_all_read'],
      connectors: ['orchestree-inbox'],
      inputTypes: ['date-range', 'digest-preferences', 'channel-filter'],
      outputTypes: ['inbox-digest', 'highlight-reel', 'action-summary'],
      domains: ['digest', 'summary', 'daily', 'weekly', 'highlights'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 0.40,
    },
    persona: {
      systemPromptAddition: 'You are an inbox digest curator. Create concise, scannable summaries that capture everything important from the inbox.',
      specialInstructions: [
        'Prioritize unread and flagged messages in the digest',
        'Group messages by topic or project for easy scanning',
        'Include deadline mentions and time-sensitive items first',
      ],
    },
    icon: 'newspaper',
    color: '#7C3AED',
  },
  {
    agentTypeId: 'inbox.template-manager',
    displayName: 'Template Manager',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Business,
    baseType: AgentType.Writer,
    description: 'Creates, manages, and suggests email templates for common communication patterns like introductions, follow-ups, and status updates.',
    capabilities: {
      tools: ['send_notification', 'get_workspace_stats'],
      connectors: ['orchestree-inbox'],
      inputTypes: ['template-type', 'use-case', 'customization-fields'],
      outputTypes: ['email-template', 'template-library', 'usage-analytics'],
      domains: ['templates', 'canned-responses', 'snippets', 'macros', 'quick-replies'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.20,
    },
    persona: {
      systemPromptAddition: 'You are an email template specialist. Build reusable templates that save time while maintaining a personal touch.',
      specialInstructions: [
        'Include merge fields for personalization',
        'Create variants for different tones (formal, casual, urgent)',
        'Track template usage and suggest improvements based on response rates',
      ],
    },
    icon: 'file-copy',
    color: '#14B8A6',
  },
  {
    agentTypeId: 'inbox.attachment-organizer',
    displayName: 'Attachment Organizer',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Technical,
    baseType: AgentType.Developer,
    description: 'Automatically organizes email attachments by file type, sender, and project, saving them to designated workspace folders.',
    capabilities: {
      tools: ['get_workspace_stats', 'send_notification'],
      connectors: ['orchestree-inbox', 'file-storage'],
      inputTypes: ['attachment-list', 'organization-rules', 'folder-structure'],
      outputTypes: ['organization-report', 'file-index', 'duplicate-detection'],
      domains: ['attachments', 'files', 'organization', 'storage', 'documents'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.15,
    },
    persona: {
      systemPromptAddition: 'You are an attachment management specialist. Keep email attachments organized and easily retrievable.',
      specialInstructions: [
        'Detect duplicate attachments across multiple emails',
        'Auto-categorize by file type and content analysis',
        'Link attachments to relevant workspace projects',
      ],
    },
    icon: 'paperclip',
    color: '#64748B',
  },
  {
    agentTypeId: 'inbox.delegation-router',
    displayName: 'Delegation Router',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Business,
    baseType: AgentType.Coordinator,
    description: 'Routes incoming messages to the best team member based on expertise, workload, and availability with delegation tracking.',
    capabilities: {
      tools: ['send_notification', 'get_workspace_stats'],
      connectors: ['orchestree-inbox'],
      inputTypes: ['incoming-message', 'team-roster', 'expertise-map'],
      outputTypes: ['routing-decision', 'delegation-record', 'workload-report'],
      domains: ['delegation', 'routing', 'assignment', 'workload', 'team'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: ['send_notification'],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.15,
    },
    persona: {
      systemPromptAddition: 'You are a team delegation specialist. Route messages to the right person who can handle them most effectively.',
      specialInstructions: [
        'Match message topics to team member expertise areas',
        'Balance workload across team members',
        'Track delegation patterns to identify training needs',
      ],
    },
    icon: 'share-2',
    color: '#10B981',
  },
  {
    agentTypeId: 'inbox.newsletter-curator',
    displayName: 'Newsletter Curator',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Creative,
    baseType: AgentType.Researcher,
    description: 'Curates relevant content from subscribed newsletters, extracting key articles, insights, and trends into a personalized reading list.',
    capabilities: {
      tools: ['get_workspace_stats', 'mark_all_read'],
      connectors: ['orchestree-inbox'],
      inputTypes: ['newsletter-emails', 'interest-profile', 'reading-preferences'],
      outputTypes: ['curated-reading-list', 'article-summaries', 'trend-highlights'],
      domains: ['newsletters', 'curation', 'reading', 'articles', 'trends'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 0.25,
    },
    persona: {
      systemPromptAddition: 'You are a content curation specialist. Surface the most relevant insights from newsletters to save reading time.',
      specialInstructions: [
        'Rank articles by relevance to user interests and role',
        'Provide one-sentence summaries for quick scanning',
        'Detect trending topics across multiple newsletter sources',
      ],
    },
    icon: 'bookmark',
    color: '#A855F7',
  },
  {
    agentTypeId: 'inbox.sla-monitor',
    displayName: 'SLA Monitor',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Business,
    baseType: AgentType.Compliance,
    description: 'Monitors email response times against SLA targets, alerting when response deadlines approach or are breached.',
    capabilities: {
      tools: ['send_notification', 'get_upcoming_deadlines', 'get_workspace_stats'],
      connectors: ['orchestree-inbox'],
      inputTypes: ['sla-rules', 'message-timestamps', 'team-filter'],
      outputTypes: ['sla-report', 'breach-alerts', 'response-time-analytics'],
      domains: ['sla', 'response-time', 'compliance', 'performance', 'monitoring'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.15,
    },
    persona: {
      systemPromptAddition: 'You are an SLA compliance monitor. Track response times and alert before deadlines are missed.',
      specialInstructions: [
        'Alert at 50%, 80%, and 100% of SLA window',
        'Exclude out-of-hours time from SLA calculations',
        'Generate weekly SLA compliance reports by team',
      ],
    },
    icon: 'timer',
    color: '#EA580C',
  },
  {
    agentTypeId: 'inbox.inbox-zero-coach',
    displayName: 'Inbox Zero Coach',
    domain: AgentDomain.Inbox,
    category: AgentCategory.People,
    baseType: AgentType.CustomerSuccess,
    description: 'Coaches users toward inbox zero with actionable suggestions to archive, delegate, respond, or schedule messages for later.',
    capabilities: {
      tools: ['mark_all_read', 'send_notification', 'get_workspace_stats'],
      connectors: ['orchestree-inbox'],
      inputTypes: ['inbox-state', 'user-preferences', 'time-available'],
      outputTypes: ['action-plan', 'batch-suggestions', 'progress-report'],
      domains: ['inbox-zero', 'productivity', 'coaching', 'organization', 'habits'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['mark_all_read'],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.15,
    },
    persona: {
      systemPromptAddition: 'You are a productivity coach for email management. Guide users to inbox zero with practical, low-effort actions.',
      specialInstructions: [
        'Suggest batch processing sessions by message category',
        'Identify messages that can be bulk archived safely',
        'Celebrate milestones and maintain motivation',
      ],
    },
    icon: 'target',
    color: '#16A34A',
  },
  {
    agentTypeId: 'inbox.out-of-office-manager',
    displayName: 'Out-of-Office Manager',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Business,
    baseType: AgentType.Coordinator,
    description: 'Manages out-of-office responses with smart routing, delegation rules, and return-to-work inbox summaries.',
    capabilities: {
      tools: ['send_notification', 'get_workspace_stats', 'get_upcoming_deadlines'],
      connectors: ['orchestree-inbox', 'orchestree-scheduling'],
      inputTypes: ['ooo-dates', 'delegation-map', 'response-message'],
      outputTypes: ['ooo-config', 'delegation-plan', 'return-summary'],
      domains: ['out-of-office', 'vacation', 'delegation', 'coverage', 'return'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['send_notification'],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.15,
    },
    persona: {
      systemPromptAddition: 'You are an absence management specialist. Set up smart OOO coverage and make returning to inbox painless.',
      specialInstructions: [
        'Route urgent messages to designated backup contacts',
        'Customize OOO replies based on sender relationship',
        'Generate a priority-sorted return-to-work briefing',
      ],
    },
    icon: 'plane',
    color: '#0D9488',
  },
  {
    agentTypeId: 'inbox.analytics-reporter',
    displayName: 'Inbox Analytics Reporter',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Generates inbox analytics including message volume trends, response times, top senders, busiest hours, and communication patterns.',
    capabilities: {
      tools: ['get_workspace_stats', 'send_notification'],
      connectors: ['orchestree-inbox'],
      inputTypes: ['date-range', 'metrics-selection', 'team-filter'],
      outputTypes: ['analytics-report', 'trend-charts', 'insights-summary'],
      domains: ['analytics', 'metrics', 'trends', 'reports', 'insights'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 0.25,
    },
    persona: {
      systemPromptAddition: 'You are an email analytics expert. Surface actionable insights from communication patterns and inbox metrics.',
      specialInstructions: [
        'Track message volume by hour, day, and week',
        'Identify top senders and their response expectations',
        'Suggest optimal times for sending important emails',
      ],
    },
    icon: 'bar-chart',
    color: '#6D28D9',
  },
  {
    agentTypeId: 'inbox.label-organizer',
    displayName: 'Label Organizer',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Technical,
    baseType: AgentType.Developer,
    description: 'Creates and maintains a consistent labeling and tagging system for inbox messages with auto-labeling rules and hierarchy management.',
    capabilities: {
      tools: ['mark_all_read', 'get_workspace_stats'],
      connectors: ['orchestree-inbox'],
      inputTypes: ['label-taxonomy', 'auto-label-rules', 'message-sample'],
      outputTypes: ['label-system', 'auto-label-config', 'organization-report'],
      domains: ['labels', 'tags', 'folders', 'organization', 'taxonomy'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.15,
    },
    persona: {
      systemPromptAddition: 'You are an inbox organization specialist. Design and maintain labeling systems that make message retrieval effortless.',
      specialInstructions: [
        'Create a flat or shallow label hierarchy for simplicity',
        'Define clear rules for auto-labeling based on sender, subject, and content',
        'Merge redundant labels and suggest consolidation',
      ],
    },
    icon: 'tag',
    color: '#78716C',
  },
  {
    agentTypeId: 'inbox.notification-tuner',
    displayName: 'Notification Tuner',
    domain: AgentDomain.Inbox,
    category: AgentCategory.People,
    baseType: AgentType.CustomerSuccess,
    description: 'Optimizes notification settings to reduce alert fatigue while ensuring critical messages get immediate attention.',
    capabilities: {
      tools: ['send_notification', 'get_workspace_stats'],
      connectors: ['orchestree-inbox', 'orchestree-notifications'],
      inputTypes: ['notification-preferences', 'importance-rules', 'quiet-hours'],
      outputTypes: ['notification-config', 'filter-rules', 'noise-reduction-report'],
      domains: ['notifications', 'alerts', 'focus', 'do-not-disturb', 'filtering'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.10,
    },
    persona: {
      systemPromptAddition: 'You are a notification optimization expert. Reduce noise while ensuring nothing critical is missed.',
      specialInstructions: [
        'Configure VIP notifications that bypass quiet hours',
        'Batch low-priority notifications into periodic digests',
        'Analyze notification patterns to suggest noise reduction',
      ],
    },
    icon: 'bell-off',
    color: '#475569',
  },
  {
    agentTypeId: 'inbox.customer-inquiry-router',
    displayName: 'Customer Inquiry Router',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Business,
    baseType: AgentType.CustomerSuccess,
    description: 'Routes customer inquiries to the appropriate support tier or department based on topic classification, sentiment, and customer value.',
    capabilities: {
      tools: ['send_notification', 'get_workspace_stats', 'get_upcoming_deadlines'],
      connectors: ['orchestree-inbox'],
      inputTypes: ['customer-message', 'routing-rules', 'team-availability'],
      outputTypes: ['routing-decision', 'ticket-creation', 'acknowledgment-draft'],
      domains: ['customer-support', 'routing', 'tickets', 'inquiries', 'helpdesk'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.10,
    },
    persona: {
      systemPromptAddition: 'You are a customer inquiry routing specialist. Get every customer to the right support person on the first touch.',
      specialInstructions: [
        'Classify inquiry type (billing, technical, feature request, complaint)',
        'Escalate VIP customers and negative sentiment automatically',
        'Send immediate acknowledgment while routing to the right team',
      ],
    },
    icon: 'headphones',
    color: '#F97316',
  },
  {
    agentTypeId: 'inbox.smart-snooze-manager',
    displayName: 'Smart Snooze Manager',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Core,
    baseType: AgentType.Coordinator,
    description: 'Intelligently snoozes non-urgent messages and resurfaces them at the optimal time based on context, deadlines, and user work patterns.',
    capabilities: {
      tools: ['get_inbox_items', 'update_inbox_item', 'get_upcoming_deadlines'],
      connectors: ['orchestree-inbox', 'orchestree-scheduling'],
      inputTypes: ['message-content', 'snooze-preferences', 'calendar-context'],
      outputTypes: ['snooze-schedule', 'resurface-notification', 'timing-recommendation'],
      domains: ['snooze', 'timing', 'inbox', 'scheduling', 'reminders'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.10,
    },
    persona: {
      systemPromptAddition: 'You are a message timing optimizer. Snooze messages to resurface them when the user is best positioned to act on them.',
      specialInstructions: [
        'Resurface snoozed items before their deadlines with enough buffer',
        'Learn from user snooze-then-act patterns to improve timing',
        'Group related snoozed items to resurface together',
      ],
    },
    icon: 'alarm-clock',
    color: '#0EA5E9',
  },
  {
    agentTypeId: 'inbox.vip-filter-manager',
    displayName: 'VIP Filter Manager',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Business,
    baseType: AgentType.Coordinator,
    description: 'Maintains a dynamic VIP contact list and ensures messages from key stakeholders, executives, and high-value clients always receive priority treatment.',
    capabilities: {
      tools: ['get_inbox_items', 'send_notification', 'get_workspace_stats'],
      connectors: ['orchestree-inbox', 'orchestree-notifications', 'crm'],
      inputTypes: ['contact-list', 'vip-criteria', 'relationship-data'],
      outputTypes: ['vip-list', 'priority-override', 'vip-activity-report'],
      domains: ['vip', 'priority', 'contacts', 'filtering', 'relationships'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.10,
    },
    persona: {
      systemPromptAddition: 'You are a VIP relationship manager. Ensure important contacts always get priority treatment in the inbox.',
      specialInstructions: [
        'Auto-detect VIP candidates from CRM deal size and org chart position',
        'Override snooze and quiet hours for VIP messages',
        'Track VIP response times and alert if SLA is at risk',
      ],
    },
    icon: 'crown',
    color: '#CA8A04',
  },
  {
    agentTypeId: 'inbox.bulk-action-processor',
    displayName: 'Bulk Action Processor',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Technical,
    baseType: AgentType.Developer,
    description: 'Processes bulk inbox operations like mass archiving, labeling, forwarding, and deletion with smart filters and safety checks.',
    capabilities: {
      tools: ['get_inbox_items', 'update_inbox_item', 'mark_all_read'],
      connectors: ['orchestree-inbox'],
      inputTypes: ['filter-criteria', 'bulk-action-type', 'safety-rules'],
      outputTypes: ['action-preview', 'execution-report', 'undo-manifest'],
      domains: ['bulk', 'batch', 'cleanup', 'mass-action', 'processing'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['mark_all_read', 'bulk-delete'],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.15,
    },
    persona: {
      systemPromptAddition: 'You are a bulk inbox operations specialist. Execute mass actions safely with previews and undo capability.',
      specialInstructions: [
        'Always show a preview of affected messages before executing',
        'Maintain an undo log for all bulk operations',
        'Never bulk-delete messages less than 24 hours old without explicit confirmation',
      ],
    },
    icon: 'layers',
    color: '#475569',
  },
  {
    agentTypeId: 'inbox.draft-polisher',
    displayName: 'Draft Polisher',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Creative,
    baseType: AgentType.Writer,
    description: 'Reviews and polishes email drafts for clarity, tone, grammar, and professionalism before sending, with style-matched suggestions.',
    capabilities: {
      tools: ['get_inbox_items', 'send_notification'],
      connectors: ['orchestree-inbox'],
      inputTypes: ['draft-content', 'tone-preference', 'recipient-context'],
      outputTypes: ['polished-draft', 'improvement-suggestions', 'tone-analysis'],
      domains: ['writing', 'editing', 'polish', 'grammar', 'tone'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 0.30,
    },
    persona: {
      systemPromptAddition: 'You are a professional writing coach for email. Polish drafts to be clear, concise, and appropriately toned.',
      specialInstructions: [
        'Preserve the author voice while improving clarity',
        'Flag potentially offensive or ambiguous phrasing',
        'Suggest stronger subject lines when the current one is weak',
      ],
    },
    icon: 'sparkles',
    color: '#EC4899',
  },
  {
    agentTypeId: 'inbox.send-time-optimizer',
    displayName: 'Send Time Optimizer',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Analyzes recipient behavior patterns to recommend the optimal send time for maximum open rates, response rates, and engagement.',
    capabilities: {
      tools: ['get_inbox_items', 'get_inbox_analytics', 'send_notification'],
      connectors: ['orchestree-inbox', 'analytics'],
      inputTypes: ['recipient-data', 'historical-engagement', 'timezone-info'],
      outputTypes: ['optimal-send-time', 'engagement-forecast', 'schedule-recommendation'],
      domains: ['timing', 'engagement', 'optimization', 'scheduling', 'analytics'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.15,
    },
    persona: {
      systemPromptAddition: 'You are an email timing strategist. Schedule sends for maximum impact based on recipient behavior data.',
      specialInstructions: [
        'Analyze past open and reply times per recipient',
        'Account for recipient timezone and typical working hours',
        'Avoid sending during common low-engagement windows like Monday morning',
      ],
    },
    icon: 'send',
    color: '#2563EB',
  },
  {
    agentTypeId: 'inbox.reply-urgency-scorer',
    displayName: 'Reply Urgency Scorer',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Scores incoming messages by reply urgency using deadline detection, sender importance, content analysis, and historical response patterns.',
    capabilities: {
      tools: ['get_inbox_items', 'get_upcoming_deadlines', 'send_notification'],
      connectors: ['orchestree-inbox'],
      inputTypes: ['message-content', 'sender-profile', 'deadline-context'],
      outputTypes: ['urgency-score', 'response-deadline', 'escalation-flag'],
      domains: ['urgency', 'scoring', 'response-time', 'priority', 'deadlines'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.10,
    },
    persona: {
      systemPromptAddition: 'You are a response urgency analyst. Score every message by how quickly it truly needs a reply.',
      specialInstructions: [
        'Detect explicit and implicit deadlines in message content',
        'Factor in sender relationship and deal stage',
        'Distinguish real urgency from manufactured urgency',
      ],
    },
    icon: 'gauge',
    color: '#DC2626',
  },
  {
    agentTypeId: 'inbox.archive-intelligence',
    displayName: 'Archive Intelligence Agent',
    domain: AgentDomain.Inbox,
    category: AgentCategory.Technical,
    baseType: AgentType.Analyst,
    description: 'Intelligently identifies messages safe to archive based on completion status, age, follow-up state, and content relevance.',
    capabilities: {
      tools: ['get_inbox_items', 'update_inbox_item', 'mark_all_read'],
      connectors: ['orchestree-inbox'],
      inputTypes: ['inbox-state', 'archive-rules', 'retention-policy'],
      outputTypes: ['archive-candidates', 'safety-assessment', 'cleanup-report'],
      domains: ['archive', 'cleanup', 'organization', 'retention', 'storage'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['mark_all_read'],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.15,
    },
    persona: {
      systemPromptAddition: 'You are an inbox archival specialist. Identify messages that can be safely archived to keep the inbox clean and focused.',
      specialInstructions: [
        'Never archive messages with open action items or pending responses',
        'Flag messages with attachments that may need future reference',
        'Respect retention policies for compliance-sensitive communications',
      ],
    },
    icon: 'archive',
    color: '#78716C',
  },
]
