import { AgentDomain, AgentCategory, AgentType, CostTier, LatencyProfile } from '../../types'
import type { AgentCapabilityManifest } from '../../types'

export const AGENTS: AgentCapabilityManifest[] = [
  {
    agentTypeId: 'projects.sprint-planner',
    displayName: 'Sprint Planning Agent',
    domain: AgentDomain.Projects,
    category: AgentCategory.Core,
    baseType: AgentType.Planner,
    description: 'Plans sprint scope by analyzing team velocity, capacity, and backlog priorities to recommend optimal sprint commitments.',
    capabilities: {
      tools: ['list_issues', 'create_cycle', 'create_goal', 'get_workspace_stats'],
      connectors: ['jira', 'linear', 'github'],
      inputTypes: ['backlog', 'velocity-data', 'team-capacity'],
      outputTypes: ['sprint-plan', 'capacity-analysis', 'commitment-recommendation'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['finalize-sprint'],
      maxTokenBudget: 60000,
      maxCostUsdBudget: 2.5,
    },
    persona: {
      systemPromptAddition: 'You are a sprint planning facilitator. Balance ambition with realism using historical velocity to size commitments.',
      specialInstructions: ['Use rolling 3-sprint velocity average', 'Reserve 20% capacity for unplanned work'],
    },
    icon: 'IterationCcw',
    color: '#4F46E5',
  },
  {
    agentTypeId: 'projects.backlog-groomer',
    displayName: 'Backlog Grooming Agent',
    domain: AgentDomain.Projects,
    category: AgentCategory.Core,
    baseType: AgentType.Planner,
    description: 'Reviews and refines the product backlog by identifying stale items, suggesting story splits, adding acceptance criteria, and recommending priority changes.',
    capabilities: {
      tools: ['list_issues', 'create_issue', 'get_workspace_stats'],
      connectors: ['linear', 'jira'],
      inputTypes: ['backlog-item', 'user-story', 'acceptance-criteria'],
      outputTypes: ['refined-story', 'priority-recommendation', 'split-suggestion'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You are a backlog refinement specialist. Ensure every story is well-defined, properly sized, and has clear acceptance criteria.',
      specialInstructions: ['Flag stories without acceptance criteria', 'Suggest splits for items estimated over 8 points'],
    },
    icon: 'ListChecks',
    color: '#8B5CF6',
  },
  {
    agentTypeId: 'projects.standup-reporter',
    displayName: 'Standup Report Agent',
    domain: AgentDomain.Projects,
    category: AgentCategory.Core,
    baseType: AgentType.Writer,
    description: 'Generates daily standup summaries by analyzing recent commits, issue transitions, and PR activity to provide what was done, what is planned, and blockers.',
    capabilities: {
      tools: ['list_issues', 'get_workspace_stats', 'get_upcoming_deadlines'],
      connectors: ['github', 'linear', 'slack'],
      inputTypes: ['commit-log', 'issue-transition', 'pr-activity'],
      outputTypes: ['standup-summary', 'blocker-list', 'progress-report'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You are a standup facilitator. Summarize each team member\'s progress concisely and highlight blockers that need attention.',
      specialInstructions: ['Group updates by team member', 'Highlight items with no progress in 2+ days'],
    },
    icon: 'Users',
    color: '#10B981',
  },
  {
    agentTypeId: 'projects.velocity-tracker',
    displayName: 'Velocity Tracking Agent',
    domain: AgentDomain.Projects,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Tracks sprint velocity trends, analyzes estimation accuracy, and identifies patterns affecting team throughput.',
    capabilities: {
      tools: ['list_issues', 'create_cycle', 'get_workspace_stats'],
      connectors: ['linear', 'jira'],
      inputTypes: ['sprint-data', 'estimation-history', 'completion-rate'],
      outputTypes: ['velocity-chart', 'estimation-accuracy-report', 'throughput-analysis'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You are a velocity analytics specialist. Provide data-driven insights on team throughput and estimation patterns.',
      specialInstructions: ['Track both story points and issue count velocity', 'Flag estimation outliers for retrospective discussion'],
    },
    icon: 'Gauge',
    color: '#0EA5E9',
  },
  {
    agentTypeId: 'projects.risk-assessor',
    displayName: 'Project Risk Assessor',
    domain: AgentDomain.Projects,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Identifies project risks by analyzing schedule slippage, scope changes, resource constraints, and dependency delays, then recommends mitigations.',
    capabilities: {
      tools: ['list_issues', 'get_upcoming_deadlines', 'get_workspace_stats'],
      connectors: ['linear', 'jira', 'confluence'],
      inputTypes: ['project-plan', 'milestone-status', 'resource-allocation'],
      outputTypes: ['risk-register', 'mitigation-plan', 'risk-heatmap'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You are a project risk analyst. Proactively identify risks before they become issues and propose concrete mitigation strategies.',
      specialInstructions: ['Assess probability and impact for each risk', 'Escalate high-probability, high-impact risks immediately'],
    },
    icon: 'AlertTriangle',
    color: '#F59E0B',
  },
  {
    agentTypeId: 'projects.dependency-mapper',
    displayName: 'Dependency Mapping Agent',
    domain: AgentDomain.Projects,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Analyzes issue relationships to build dependency graphs, identifies critical path items, and detects circular dependencies or bottlenecks.',
    capabilities: {
      tools: ['list_issues', 'create_issue', 'get_workspace_stats'],
      connectors: ['linear', 'jira', 'github'],
      inputTypes: ['issue-list', 'dependency-link', 'milestone'],
      outputTypes: ['dependency-graph', 'critical-path', 'bottleneck-report'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You are a dependency analysis specialist. Map all blocking relationships and highlight the critical path to delivery.',
      specialInstructions: ['Detect circular dependencies and flag them as errors', 'Identify single points of failure in the dependency chain'],
    },
    icon: 'GitBranch',
    color: '#6366F1',
  },
  {
    agentTypeId: 'projects.release-coordinator',
    displayName: 'Release Coordination Agent',
    domain: AgentDomain.Projects,
    category: AgentCategory.Core,
    baseType: AgentType.Coordinator,
    description: 'Coordinates release activities including feature freeze tracking, changelog generation, release notes, and deployment readiness checks.',
    capabilities: {
      tools: ['list_issues', 'create_cycle', 'get_upcoming_deadlines', 'get_workspace_stats'],
      connectors: ['github', 'linear', 'slack', 'ci-cd'],
      inputTypes: ['release-plan', 'feature-list', 'test-results'],
      outputTypes: ['release-checklist', 'changelog', 'release-notes'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['trigger-release', 'approve-hotfix'],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You are a release manager. Ensure smooth, predictable releases with thorough pre-release validation and clear communication.',
      specialInstructions: ['Verify all blocker issues are resolved before release', 'Generate changelog from merged PRs since last release'],
    },
    icon: 'Rocket',
    color: '#DC2626',
  },
  {
    agentTypeId: 'projects.issue-triager',
    displayName: 'Issue Triage Agent',
    domain: AgentDomain.Projects,
    category: AgentCategory.Core,
    baseType: AgentType.Coordinator,
    description: 'Automatically triages new issues by analyzing content, assigning priority, suggesting labels, and routing to the appropriate team or assignee.',
    capabilities: {
      tools: ['list_issues', 'create_issue', 'get_workspace_stats'],
      connectors: ['github', 'linear', 'jira'],
      inputTypes: ['issue', 'bug-report', 'feature-request'],
      outputTypes: ['triage-result', 'priority-assignment', 'routing-suggestion'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 10000,
      maxCostUsdBudget: 0.2,
    },
    persona: {
      systemPromptAddition: 'You are an issue triage specialist. Quickly classify, prioritize, and route incoming issues to minimize response time.',
      specialInstructions: ['Auto-label based on affected area detection', 'Escalate security-related issues to P0 immediately'],
    },
    icon: 'Inbox',
    color: '#14B8A6',
  },
  {
    agentTypeId: 'projects.epic-tracker',
    displayName: 'Epic Progress Tracker',
    domain: AgentDomain.Projects,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Monitors epic-level progress by aggregating child issue status, calculating completion percentages, and projecting delivery dates.',
    capabilities: {
      tools: ['list_issues', 'create_goal', 'get_upcoming_deadlines'],
      connectors: ['linear', 'jira'],
      inputTypes: ['epic', 'child-issues', 'target-date'],
      outputTypes: ['epic-progress-report', 'delivery-projection', 'scope-change-alert'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 0.8,
    },
    persona: {
      systemPromptAddition: 'You are an epic tracking specialist. Provide clear progress visibility and early warning when epics are at risk of missing targets.',
      specialInstructions: ['Calculate completion by both count and story points', 'Flag epics with growing scope (issues added after start)'],
    },
    icon: 'Mountain',
    color: '#7C3AED',
  },
  {
    agentTypeId: 'projects.retro-facilitator',
    displayName: 'Retrospective Facilitator',
    domain: AgentDomain.Projects,
    category: AgentCategory.Core,
    baseType: AgentType.Coordinator,
    description: 'Facilitates sprint retrospectives by gathering data, identifying patterns, and helping the team create actionable improvement items.',
    capabilities: {
      tools: ['list_issues', 'create_issue', 'get_workspace_stats'],
      connectors: ['linear', 'slack', 'miro'],
      inputTypes: ['sprint-metrics', 'team-feedback', 'action-item-history'],
      outputTypes: ['retro-summary', 'action-items', 'improvement-trend'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You are a retrospective facilitator. Create a safe space for reflection and turn feedback into concrete, trackable action items.',
      specialInstructions: ['Track completion of previous retro action items', 'Use start/stop/continue format by default'],
    },
    icon: 'RotateCcw',
    color: '#EC4899',
  },
  {
    agentTypeId: 'projects.scope-creep-detector',
    displayName: 'Scope Creep Detector',
    domain: AgentDomain.Projects,
    category: AgentCategory.Core,
    baseType: AgentType.Reviewer,
    description: 'Monitors project scope by tracking new issues added mid-sprint, requirement changes, and feature additions that were not in the original plan.',
    capabilities: {
      tools: ['list_issues', 'get_workspace_stats', 'get_upcoming_deadlines'],
      connectors: ['linear', 'jira'],
      inputTypes: ['sprint-snapshot', 'issue-changelog', 'original-scope'],
      outputTypes: ['scope-change-report', 'creep-alert', 'impact-assessment'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You are a scope management specialist. Detect unplanned additions early and quantify their impact on delivery timelines.',
      specialInstructions: ['Compare current sprint scope to commitment snapshot', 'Calculate net change in story points since sprint start'],
    },
    icon: 'Expand',
    color: '#D97706',
  },
  {
    agentTypeId: 'projects.estimation-helper',
    displayName: 'Estimation Helper Agent',
    domain: AgentDomain.Projects,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Assists with story point estimation by analyzing similar historical issues, comparing complexity factors, and suggesting point values.',
    capabilities: {
      tools: ['list_issues', 'get_workspace_stats'],
      connectors: ['linear', 'jira'],
      inputTypes: ['issue-description', 'historical-estimates', 'complexity-factors'],
      outputTypes: ['estimate-suggestion', 'comparison-set', 'confidence-range'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You are an estimation coach. Help teams estimate more accurately by referencing similar past work and identifying complexity drivers.',
      specialInstructions: ['Provide 3 reference stories of similar complexity', 'Use modified Fibonacci scale: 1, 2, 3, 5, 8, 13'],
    },
    icon: 'Scale',
    color: '#0891B2',
  },
  {
    agentTypeId: 'projects.burndown-analyst',
    displayName: 'Burndown Analysis Agent',
    domain: AgentDomain.Projects,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Analyzes sprint burndown and burnup charts, detects trajectory deviations, and forecasts sprint completion likelihood.',
    capabilities: {
      tools: ['list_issues', 'create_cycle', 'get_workspace_stats'],
      connectors: ['linear', 'jira'],
      inputTypes: ['sprint-data', 'daily-progress', 'ideal-burndown'],
      outputTypes: ['burndown-analysis', 'completion-forecast', 'deviation-alert'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You are a sprint analytics specialist. Identify burndown anomalies early and forecast whether the sprint goal is achievable.',
      specialInstructions: ['Alert when actual exceeds ideal by more than 15%', 'Account for weekends and team capacity changes'],
    },
    icon: 'LineChart',
    color: '#2563EB',
  },
  {
    agentTypeId: 'projects.tech-debt-tracker',
    displayName: 'Technical Debt Tracker',
    domain: AgentDomain.Projects,
    category: AgentCategory.Technical,
    baseType: AgentType.Developer,
    description: 'Identifies, categorizes, and prioritizes technical debt items across the codebase, tracking debt-to-feature ratios and recommending paydown schedules.',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'get_workspace_stats'],
      connectors: ['github', 'sonarqube', 'linear'],
      inputTypes: ['code-analysis', 'todo-comments', 'architecture-review'],
      outputTypes: ['debt-inventory', 'priority-ranking', 'paydown-plan'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You are a tech debt analyst. Quantify the cost of technical debt and build a compelling case for strategic debt reduction.',
      specialInstructions: ['Categorize by type: code, architecture, dependency, test, documentation', 'Estimate interest cost (maintenance burden) per item'],
    },
    icon: 'Bug',
    color: '#EF4444',
  },
  {
    agentTypeId: 'projects.milestone-planner',
    displayName: 'Milestone Planning Agent',
    domain: AgentDomain.Projects,
    category: AgentCategory.Core,
    baseType: AgentType.Planner,
    description: 'Creates and manages project milestones, breaking down large goals into phased deliverables with clear success criteria and target dates.',
    capabilities: {
      tools: ['create_goal', 'list_issues', 'create_cycle', 'get_upcoming_deadlines'],
      connectors: ['linear', 'jira', 'notion'],
      inputTypes: ['project-goal', 'feature-list', 'resource-plan'],
      outputTypes: ['milestone-plan', 'phase-breakdown', 'success-criteria'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['publish-milestone'],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You are a milestone planning specialist. Define clear, measurable milestones that create natural checkpoints for project progress.',
      specialInstructions: ['Each milestone should have 3-5 measurable success criteria', 'Build in buffer between dependent milestones'],
    },
    icon: 'Flag',
    color: '#059669',
  },
  {
    agentTypeId: 'projects.workload-balancer',
    displayName: 'Workload Balancing Agent',
    domain: AgentDomain.Projects,
    category: AgentCategory.Core,
    baseType: AgentType.Coordinator,
    description: 'Analyzes team workload distribution, identifies over-allocated or under-utilized team members, and suggests reassignment to balance the load.',
    capabilities: {
      tools: ['list_issues', 'get_workspace_stats', 'get_upcoming_deadlines'],
      connectors: ['linear', 'jira', 'hr-system'],
      inputTypes: ['assignment-data', 'capacity-plan', 'pto-calendar'],
      outputTypes: ['workload-heatmap', 'reassignment-suggestion', 'capacity-alert'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['reassign-work'],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You are a resource management specialist. Ensure equitable work distribution and prevent burnout from over-allocation.',
      specialInstructions: ['Consider skill-match when suggesting reassignments', 'Account for PTO and part-time schedules'],
    },
    icon: 'Users',
    color: '#A855F7',
  },
  {
    agentTypeId: 'projects.pr-reviewer',
    displayName: 'PR Review Coordinator',
    domain: AgentDomain.Projects,
    category: AgentCategory.Technical,
    baseType: AgentType.Reviewer,
    description: 'Manages pull request workflows by assigning reviewers, tracking review turnaround times, and ensuring PRs meet team standards before merge.',
    capabilities: {
      tools: ['list_issues', 'get_workspace_stats'],
      connectors: ['github', 'gitlab', 'linear'],
      inputTypes: ['pull-request', 'review-policy', 'reviewer-availability'],
      outputTypes: ['reviewer-assignment', 'review-reminder', 'merge-readiness-check'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You are a code review coordinator. Ensure timely reviews, balanced reviewer load, and adherence to review standards.',
      specialInstructions: ['Rotate reviewers to spread knowledge', 'Escalate PRs pending review for more than 24 hours'],
    },
    icon: 'GitPullRequest',
    color: '#16A34A',
  },
  {
    agentTypeId: 'projects.qa-planner',
    displayName: 'QA Planning Agent',
    domain: AgentDomain.Projects,
    category: AgentCategory.Technical,
    baseType: AgentType.Planner,
    description: 'Creates test plans from user stories, identifies test scenarios, determines test coverage requirements, and prioritizes testing effort.',
    capabilities: {
      tools: ['list_issues', 'create_issue', 'get_workspace_stats'],
      connectors: ['linear', 'jira', 'testmo'],
      inputTypes: ['user-story', 'acceptance-criteria', 'test-history'],
      outputTypes: ['test-plan', 'test-scenario-list', 'coverage-matrix'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You are a QA planning specialist. Design comprehensive test plans that maximize defect detection with efficient test coverage.',
      specialInstructions: ['Include positive, negative, and edge case scenarios', 'Prioritize tests by risk and business impact'],
    },
    icon: 'TestTube2',
    color: '#0D9488',
  },
  {
    agentTypeId: 'projects.roadmap-visualizer',
    displayName: 'Roadmap Visualization Agent',
    domain: AgentDomain.Projects,
    category: AgentCategory.Core,
    baseType: AgentType.Designer,
    description: 'Generates visual roadmaps from epics, milestones, and release timelines, creating stakeholder-friendly views of planned deliverables.',
    capabilities: {
      tools: ['list_issues', 'create_goal', 'get_upcoming_deadlines', 'get_workspace_stats'],
      connectors: ['linear', 'notion', 'figma'],
      inputTypes: ['epic-list', 'milestone-timeline', 'theme-grouping'],
      outputTypes: ['roadmap-view', 'timeline-chart', 'stakeholder-summary'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You are a roadmap communication specialist. Create clear, visually appealing roadmaps that align stakeholders around priorities.',
      specialInstructions: ['Group by strategic theme, not team', 'Show confidence levels for items beyond 2 quarters'],
    },
    icon: 'Map',
    color: '#E11D48',
  },
  {
    agentTypeId: 'projects.changelog-generator',
    displayName: 'Changelog Generator',
    domain: AgentDomain.Projects,
    category: AgentCategory.Core,
    baseType: AgentType.Writer,
    description: 'Automatically generates changelogs from merged PRs, completed issues, and release tags, categorizing changes by type.',
    capabilities: {
      tools: ['list_issues', 'get_workspace_stats'],
      connectors: ['github', 'linear'],
      inputTypes: ['merged-prs', 'completed-issues', 'release-tag'],
      outputTypes: ['changelog', 'release-notes', 'user-facing-summary'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You are a technical writer for release communication. Generate clear, categorized changelogs from development activity.',
      specialInstructions: ['Categorize as Features, Improvements, Bug Fixes, Breaking Changes', 'Write user-facing summaries, not developer jargon'],
    },
    icon: 'FileText',
    color: '#64748B',
  },
  {
    agentTypeId: 'projects.cross-team-coordinator',
    displayName: 'Cross-Team Coordination Agent',
    domain: AgentDomain.Projects,
    category: AgentCategory.Core,
    baseType: AgentType.Coordinator,
    description: 'Manages dependencies and communication between multiple teams working on shared features, tracking handoff points and integration milestones.',
    capabilities: {
      tools: ['list_issues', 'create_issue', 'create_goal', 'get_upcoming_deadlines'],
      connectors: ['linear', 'slack', 'jira'],
      inputTypes: ['cross-team-dependency', 'integration-plan', 'team-schedule'],
      outputTypes: ['coordination-plan', 'handoff-checklist', 'integration-status'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You are a cross-team coordination specialist. Ensure seamless collaboration between teams with clear communication and tracked handoffs.',
      specialInstructions: ['Maintain a shared dependency board', 'Schedule sync points at integration milestones'],
    },
    icon: 'Network',
    color: '#0284C7',
  },
  {
    agentTypeId: 'projects.incident-responder',
    displayName: 'Incident Response Coordinator',
    domain: AgentDomain.Projects,
    category: AgentCategory.Technical,
    baseType: AgentType.Coordinator,
    description: 'Manages incident response workflows from detection through resolution, coordinating responders, tracking timelines, and generating post-mortems.',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'get_workspace_stats'],
      connectors: ['pagerduty', 'slack', 'linear', 'datadog'],
      inputTypes: ['incident-alert', 'severity-assessment', 'impact-report'],
      outputTypes: ['incident-timeline', 'action-assignment', 'post-mortem'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You are an incident commander. Coordinate response efforts calmly and methodically, ensuring clear communication and rapid resolution.',
      specialInstructions: ['Assign roles immediately: IC, comms lead, tech lead', 'Update status page every 30 minutes during active incidents'],
    },
    icon: 'Siren',
    color: '#DC2626',
  },
  {
    agentTypeId: 'projects.feature-flag-manager',
    displayName: 'Feature Flag Manager',
    domain: AgentDomain.Projects,
    category: AgentCategory.Technical,
    baseType: AgentType.Developer,
    description: 'Manages feature flag lifecycle from creation through rollout and cleanup, tracking rollout percentages and flag dependencies.',
    capabilities: {
      tools: ['list_issues', 'create_issue', 'get_workspace_stats'],
      connectors: ['launchdarkly', 'github', 'linear'],
      inputTypes: ['flag-definition', 'rollout-plan', 'flag-cleanup-request'],
      outputTypes: ['flag-status', 'rollout-schedule', 'stale-flag-report'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['full-rollout', 'flag-deletion'],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You are a feature flag operations specialist. Manage safe, gradual rollouts and ensure flags are cleaned up after full deployment.',
      specialInstructions: ['Flag stale flags older than 30 days at 100% rollout', 'Create cleanup issues automatically after full rollout'],
    },
    icon: 'Flag',
    color: '#F97316',
  },
  {
    agentTypeId: 'projects.stakeholder-updater',
    displayName: 'Stakeholder Update Agent',
    domain: AgentDomain.Projects,
    category: AgentCategory.Core,
    baseType: AgentType.Writer,
    description: 'Generates tailored stakeholder status updates by aggregating project progress, risks, and upcoming milestones into executive-friendly summaries.',
    capabilities: {
      tools: ['list_issues', 'get_upcoming_deadlines', 'get_workspace_stats'],
      connectors: ['linear', 'notion', 'email', 'slack'],
      inputTypes: ['project-status', 'milestone-progress', 'risk-register'],
      outputTypes: ['status-report', 'executive-summary', 'weekly-update'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['send-update'],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.8,
    },
    persona: {
      systemPromptAddition: 'You are a project communication specialist. Craft clear, concise updates that give stakeholders the right level of detail.',
      specialInstructions: ['Use red/amber/green status indicators', 'Lead with key decisions needed, then progress, then risks'],
    },
    icon: 'Mail',
    color: '#475569',
  },
  {
    agentTypeId: 'projects.definition-of-done-checker',
    displayName: 'Definition of Done Checker',
    domain: AgentDomain.Projects,
    category: AgentCategory.Core,
    baseType: AgentType.Reviewer,
    description: 'Verifies that completed issues meet the team\'s Definition of Done criteria including code review, testing, documentation, and acceptance sign-off.',
    capabilities: {
      tools: ['list_issues', 'get_workspace_stats'],
      connectors: ['github', 'linear', 'jira'],
      inputTypes: ['completed-issue', 'dod-checklist', 'pr-status'],
      outputTypes: ['dod-compliance-report', 'missing-criteria-alert', 'reopen-recommendation'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 10000,
      maxCostUsdBudget: 0.2,
    },
    persona: {
      systemPromptAddition: 'You are a quality gate enforcer. Verify every item meets DoD criteria before it can be considered truly complete.',
      specialInstructions: ['Check for linked PR, tests, and documentation', 'Reopen issues that are marked done without meeting all criteria'],
    },
    icon: 'CheckCircle',
    color: '#16A34A',
  },
  {
    agentTypeId: 'projects.sprint-goal-monitor',
    displayName: 'Sprint Goal Monitor',
    domain: AgentDomain.Projects,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Tracks progress toward sprint goals, distinguishing between goal-aligned and non-goal work, and alerting when goal achievement is at risk.',
    capabilities: {
      tools: ['list_issues', 'create_goal', 'get_workspace_stats'],
      connectors: ['linear', 'jira'],
      inputTypes: ['sprint-goal', 'issue-status', 'goal-alignment-mapping'],
      outputTypes: ['goal-progress-report', 'at-risk-alert', 'alignment-analysis'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You are a sprint goal guardian. Keep the team focused on goal-aligned work and provide early warning when goals are threatened.',
      specialInstructions: ['Classify each issue as goal-aligned or non-goal work', 'Alert if non-goal work exceeds 30% of sprint effort'],
    },
    icon: 'Target',
    color: '#B91C1C',
  },
  {
    agentTypeId: 'projects.team-health-monitor',
    displayName: 'Team Health Monitor',
    domain: AgentDomain.Projects,
    category: AgentCategory.People,
    baseType: AgentType.HR,
    description: 'Monitors team health indicators including overtime patterns, context-switching frequency, meeting load, and engagement signals to prevent burnout.',
    capabilities: {
      tools: ['list_issues', 'get_workspace_stats', 'get_upcoming_deadlines'],
      connectors: ['linear', 'slack', 'calendar', 'hr-system'],
      inputTypes: ['work-patterns', 'meeting-data', 'engagement-survey'],
      outputTypes: ['health-report', 'burnout-risk-alert', 'wellbeing-recommendation'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You are a team wellbeing analyst. Identify early warning signs of burnout and recommend interventions to maintain sustainable pace.',
      specialInstructions: ['Monitor after-hours commit patterns', 'Flag individuals with 3+ consecutive sprints of over-allocation'],
    },
    icon: 'Heart',
    color: '#EC4899',
  },
  {
    agentTypeId: 'projects.cycle-time-optimizer',
    displayName: 'Cycle Time Optimizer',
    domain: AgentDomain.Projects,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Analyzes issue cycle times across workflow stages to identify bottlenecks, slow-moving items, and opportunities to reduce time-to-delivery.',
    capabilities: {
      tools: ['list_issues', 'get_workspace_stats'],
      connectors: ['linear', 'jira'],
      inputTypes: ['issue-changelog', 'workflow-definition', 'cycle-time-history'],
      outputTypes: ['cycle-time-report', 'bottleneck-analysis', 'process-improvement'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You are a flow efficiency analyst. Identify where work gets stuck and recommend process changes to reduce cycle time.',
      specialInstructions: ['Break down cycle time by workflow stage', 'Calculate flow efficiency (active time / total time)'],
    },
    icon: 'Timer',
    color: '#0891B2',
  },
  {
    agentTypeId: 'projects.automation-builder',
    displayName: 'Project Automation Builder',
    domain: AgentDomain.Projects,
    category: AgentCategory.Technical,
    baseType: AgentType.Developer,
    description: 'Creates and maintains project management automations including auto-assignment rules, status transitions, notification triggers, and SLA enforcement.',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'get_workspace_stats'],
      connectors: ['linear', 'zapier', 'github-actions'],
      inputTypes: ['automation-rule', 'trigger-definition', 'workflow-template'],
      outputTypes: ['automation-config', 'rule-test-result', 'automation-report'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['deploy-automation'],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.8,
    },
    persona: {
      systemPromptAddition: 'You are a project automation engineer. Build reliable automations that reduce manual work and enforce team processes.',
      specialInstructions: ['Test automations in dry-run mode first', 'Include error handling and fallback actions'],
    },
    icon: 'Workflow',
    color: '#6D28D9',
  },
  {
    agentTypeId: 'projects.duplicate-detector',
    displayName: 'Duplicate Issue Detector',
    domain: AgentDomain.Projects,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Identifies duplicate and near-duplicate issues in the backlog using semantic similarity analysis, suggesting merges to reduce clutter.',
    capabilities: {
      tools: ['list_issues', 'get_workspace_stats'],
      connectors: ['linear', 'jira'],
      inputTypes: ['issue-list', 'new-issue', 'similarity-threshold'],
      outputTypes: ['duplicate-candidates', 'merge-suggestion', 'dedup-report'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['merge-issues'],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You are a backlog deduplication specialist. Find duplicate issues using both keyword and semantic matching to keep the backlog clean.',
      specialInstructions: ['Use title and description for similarity scoring', 'Consider issues duplicate at 85%+ similarity'],
    },
    icon: 'Copy',
    color: '#78716C',
  },
  {
    agentTypeId: 'projects.sla-monitor',
    displayName: 'SLA Monitoring Agent',
    domain: AgentDomain.Projects,
    category: AgentCategory.Core,
    baseType: AgentType.Compliance,
    description: 'Monitors service level agreements for response and resolution times, alerting when SLAs are at risk and reporting on compliance rates.',
    capabilities: {
      tools: ['list_issues', 'get_upcoming_deadlines', 'get_workspace_stats'],
      connectors: ['linear', 'zendesk', 'jira-service-desk'],
      inputTypes: ['sla-definition', 'ticket-data', 'response-timestamp'],
      outputTypes: ['sla-status', 'breach-alert', 'compliance-report'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You are an SLA compliance monitor. Track response and resolution times against targets and escalate before breaches occur.',
      specialInstructions: ['Alert at 75% of SLA time elapsed', 'Exclude paused/waiting-on-customer time from SLA calculations'],
    },
    icon: 'AlarmClock',
    color: '#CA8A04',
  },
  {
    agentTypeId: 'projects.capacity-planner',
    displayName: 'Capacity Planning Agent',
    domain: AgentDomain.Projects,
    category: AgentCategory.Core,
    baseType: AgentType.Planner,
    description: 'Forecasts team capacity for upcoming sprints or quarters by factoring in team size, holidays, PTO, on-call rotations, and project commitments.',
    capabilities: {
      tools: ['list_issues', 'create_cycle', 'get_upcoming_deadlines', 'get_workspace_stats'],
      connectors: ['hr-system', 'calendar', 'linear'],
      inputTypes: ['team-roster', 'pto-calendar', 'on-call-schedule', 'sprint-schedule'],
      outputTypes: ['capacity-forecast', 'staffing-recommendation', 'sprint-capacity'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You are a capacity planning specialist. Provide accurate capacity forecasts that account for all known availability factors.',
      specialInstructions: ['Deduct 20% for meetings and overhead', 'Factor in ramp-up time for new team members'],
    },
    icon: 'BarChart3',
    color: '#1D4ED8',
  },
  {
    agentTypeId: 'projects.documentation-tracker',
    displayName: 'Documentation Tracking Agent',
    domain: AgentDomain.Projects,
    category: AgentCategory.Core,
    baseType: AgentType.Writer,
    description: 'Tracks documentation coverage for features and APIs, identifying undocumented or outdated docs and creating update tasks.',
    capabilities: {
      tools: ['list_issues', 'create_issue', 'get_workspace_stats'],
      connectors: ['github', 'notion', 'linear'],
      inputTypes: ['feature-list', 'api-changelog', 'doc-inventory'],
      outputTypes: ['coverage-report', 'update-task', 'staleness-alert'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.8,
    },
    persona: {
      systemPromptAddition: 'You are a documentation coverage analyst. Ensure every shipped feature has corresponding up-to-date documentation.',
      specialInstructions: ['Create doc tasks automatically for features without docs', 'Flag docs not updated in 6+ months for review'],
    },
    icon: 'BookOpen',
    color: '#9333EA',
  },
  {
    agentTypeId: 'projects.onboarding-guide',
    displayName: 'Developer Onboarding Guide',
    domain: AgentDomain.Projects,
    category: AgentCategory.People,
    baseType: AgentType.Coordinator,
    description: 'Guides new developers through onboarding by creating personalized task lists, suggesting starter issues, and tracking onboarding milestone completion.',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'get_workspace_stats'],
      connectors: ['linear', 'notion', 'slack'],
      inputTypes: ['onboarding-template', 'new-hire-profile', 'team-context'],
      outputTypes: ['onboarding-plan', 'starter-issue-list', 'progress-checklist'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.8,
    },
    persona: {
      systemPromptAddition: 'You are a developer onboarding specialist. Create a welcoming, structured onboarding experience that gets new hires productive quickly.',
      specialInstructions: ['Select good-first-issue tickets matching the new hire\'s skills', 'Schedule 1:1s with key team members in week 1'],
    },
    icon: 'GraduationCap',
    color: '#0EA5E9',
  },
  {
    agentTypeId: 'projects.meeting-reducer',
    displayName: 'Meeting Optimization Agent',
    domain: AgentDomain.Projects,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Analyzes meeting patterns across the team, identifies unnecessary or overlapping meetings, and suggests async alternatives to reclaim focus time.',
    capabilities: {
      tools: ['get_workspace_stats', 'get_upcoming_deadlines'],
      connectors: ['calendar', 'slack', 'linear'],
      inputTypes: ['meeting-schedule', 'meeting-outcome', 'focus-time-data'],
      outputTypes: ['meeting-audit', 'optimization-plan', 'async-alternative'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.8,
    },
    persona: {
      systemPromptAddition: 'You are a meeting efficiency analyst. Help teams reclaim focus time by eliminating unnecessary meetings and improving the ones that remain.',
      specialInstructions: ['Flag recurring meetings with low attendance', 'Suggest async alternatives for status update meetings'],
    },
    icon: 'Clock',
    color: '#92400E',
  },
  {
    agentTypeId: 'projects.priority-ranker',
    displayName: 'Priority Ranking Agent',
    domain: AgentDomain.Projects,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Applies RICE, WSJF, or custom scoring frameworks to rank backlog items objectively based on reach, impact, confidence, and effort.',
    capabilities: {
      tools: ['list_issues', 'create_issue', 'get_workspace_stats'],
      connectors: ['linear', 'jira'],
      inputTypes: ['backlog-item', 'scoring-criteria', 'strategic-goals'],
      outputTypes: ['priority-ranking', 'score-breakdown', 'recommendation'],
      domains: ['projects'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You are a product prioritization specialist. Apply structured frameworks to make backlog prioritization objective and transparent.',
      specialInstructions: ['Default to RICE scoring unless team specifies otherwise', 'Re-score items when strategic goals change'],
    },
    icon: 'ArrowUpDown',
    color: '#4338CA',
  },
]
