import { AgentDomain, AgentCategory, AgentType, CostTier, LatencyProfile } from '../../types'
import type { AgentCapabilityManifest } from '../../types'

export const AGENTS: AgentCapabilityManifest[] = [
  {
    agentTypeId: 'scheduling.booking-optimizer',
    displayName: 'Booking Optimizer Agent',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Planner,
    description: 'Optimizes booking distribution across available time slots to maximize utilization, minimize gaps, and balance workload throughout the day.',
    capabilities: {
      tools: ['create_booking', 'list_bookings', 'get_availability_summary', 'analyze_bookings'],
      connectors: ['calendly', 'google-calendar', 'outlook'],
      inputTypes: ['booking-request', 'availability-window', 'optimization-preference'],
      outputTypes: ['optimized-schedule', 'slot-recommendation', 'utilization-report'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You are a scheduling optimization specialist. Maximize calendar utilization while preserving buffer time and focus blocks.',
      specialInstructions: ['Batch similar meeting types together', 'Maintain 15-minute buffers between back-to-back meetings'],
    },
    icon: 'CalendarClock',
    color: '#4F46E5',
  },
  {
    agentTypeId: 'scheduling.no-show-predictor',
    displayName: 'No-Show Prediction Agent',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Predicts booking no-show probability based on historical patterns, attendee behavior, booking lead time, and external factors.',
    capabilities: {
      tools: ['list_bookings', 'get_no_show_stats', 'analyze_bookings'],
      connectors: ['calendly', 'crm'],
      inputTypes: ['booking-data', 'attendee-history', 'no-show-history'],
      outputTypes: ['no-show-prediction', 'risk-score', 'overbooking-recommendation'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.8,
    },
    persona: {
      systemPromptAddition: 'You are a scheduling analytics specialist. Predict no-show likelihood to enable proactive communication and overbooking strategies.',
      specialInstructions: ['Weight recent attendee history more heavily', 'Factor in day-of-week and time-of-day patterns'],
    },
    icon: 'UserX',
    color: '#EF4444',
  },
  {
    agentTypeId: 'scheduling.availability-manager',
    displayName: 'Availability Manager Agent',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Coordinator,
    description: 'Manages availability windows across multiple calendars, event types, and team members, automatically adjusting based on workload and preferences.',
    capabilities: {
      tools: ['get_availability_summary', 'create_event_type', 'list_bookings', 'review_calendar_health'],
      connectors: ['google-calendar', 'outlook', 'calendly'],
      inputTypes: ['calendar-data', 'availability-preference', 'working-hours'],
      outputTypes: ['availability-update', 'conflict-resolution', 'optimal-window'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['block-full-day'],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You are an availability management specialist. Balance meeting accessibility with protected focus time and personal boundaries.',
      specialInstructions: ['Protect at least 2 focus blocks per day', 'Sync availability across all connected calendars'],
    },
    icon: 'CalendarCheck',
    color: '#10B981',
  },
  {
    agentTypeId: 'scheduling.conflict-resolver',
    displayName: 'Calendar Conflict Resolver',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Coordinator,
    description: 'Detects and resolves calendar conflicts by analyzing meeting priorities, attendee importance, and rescheduling possibilities.',
    capabilities: {
      tools: ['list_bookings', 'cancel_booking', 'create_booking', 'get_availability_summary'],
      connectors: ['google-calendar', 'outlook'],
      inputTypes: ['conflicting-events', 'priority-rules', 'attendee-preferences'],
      outputTypes: ['resolution-suggestion', 'reschedule-option', 'conflict-report'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: ['cancel-meeting', 'reschedule-external'],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You are a calendar conflict resolution specialist. Resolve double-bookings quickly by evaluating priority and finding alternatives.',
      specialInstructions: ['Prioritize external meetings over internal', 'Suggest the earliest available alternative slot'],
    },
    icon: 'AlertCircle',
    color: '#F59E0B',
  },
  {
    agentTypeId: 'scheduling.timezone-coordinator',
    displayName: 'Timezone Coordination Agent',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Coordinator,
    description: 'Finds optimal meeting times across multiple timezones, accounting for working hours, cultural preferences, and daylight saving transitions.',
    capabilities: {
      tools: ['get_availability_summary', 'create_booking', 'list_bookings'],
      connectors: ['google-calendar', 'outlook', 'world-time-api'],
      inputTypes: ['participant-timezones', 'working-hours', 'meeting-duration'],
      outputTypes: ['optimal-time-suggestion', 'timezone-overlap-map', 'fairness-rotation'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You are a global scheduling coordinator. Find meeting times that respect everyone\'s working hours and rotate inconvenient times fairly.',
      specialInstructions: ['Never schedule outside 7am-9pm local time', 'Rotate early/late meeting times across participants'],
    },
    icon: 'Globe',
    color: '#0EA5E9',
  },
  {
    agentTypeId: 'scheduling.reminder-manager',
    displayName: 'Smart Reminder Agent',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Coordinator,
    description: 'Sends intelligent meeting reminders with context, preparation materials, and agenda items based on meeting type and attendee preferences.',
    capabilities: {
      tools: ['list_bookings', 'analyze_bookings', 'get_no_show_stats'],
      connectors: ['email', 'slack', 'sms', 'calendly'],
      inputTypes: ['upcoming-booking', 'reminder-preferences', 'meeting-context'],
      outputTypes: ['reminder-message', 'prep-materials', 'confirmation-request'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 10000,
      maxCostUsdBudget: 0.2,
    },
    persona: {
      systemPromptAddition: 'You are a meeting preparation specialist. Send timely reminders with relevant context to maximize meeting effectiveness.',
      specialInstructions: ['Include agenda and prep materials in reminders', 'Send extra reminders for attendees with high no-show history'],
    },
    icon: 'Bell',
    color: '#8B5CF6',
  },
  {
    agentTypeId: 'scheduling.waitlist-manager',
    displayName: 'Waitlist Manager Agent',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Coordinator,
    description: 'Manages booking waitlists when slots are full, automatically notifying waitlisted attendees when cancellations create openings.',
    capabilities: {
      tools: ['get_waitlist_summary', 'create_booking', 'cancel_booking', 'list_bookings'],
      connectors: ['calendly', 'email'],
      inputTypes: ['waitlist-entry', 'cancellation-event', 'priority-rules'],
      outputTypes: ['waitlist-notification', 'slot-offer', 'waitlist-status'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 10000,
      maxCostUsdBudget: 0.2,
    },
    persona: {
      systemPromptAddition: 'You are a waitlist operations specialist. Fill cancelled slots quickly and fairly from the waitlist.',
      specialInstructions: ['Offer slots in waitlist order by default', 'Give 2-hour response window before moving to next person'],
    },
    icon: 'ListOrdered',
    color: '#6366F1',
  },
  {
    agentTypeId: 'scheduling.calendar-health-reviewer',
    displayName: 'Calendar Health Reviewer',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Analyzes calendar health metrics including meeting-to-focus ratio, fragmentation, back-to-back meeting chains, and total meeting hours.',
    capabilities: {
      tools: ['review_calendar_health', 'list_bookings', 'analyze_bookings', 'get_availability_summary'],
      connectors: ['google-calendar', 'outlook'],
      inputTypes: ['calendar-data', 'health-criteria', 'benchmark-data'],
      outputTypes: ['health-report', 'improvement-suggestion', 'meeting-diet-plan'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.8,
    },
    persona: {
      systemPromptAddition: 'You are a calendar wellness analyst. Assess calendar health and recommend changes to improve productivity and prevent burnout.',
      specialInstructions: ['Flag days with more than 6 hours of meetings', 'Measure calendar fragmentation (number of context switches)'],
    },
    icon: 'HeartPulse',
    color: '#EC4899',
  },
  {
    agentTypeId: 'scheduling.event-type-designer',
    displayName: 'Event Type Designer',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Designer,
    description: 'Creates and optimizes event type configurations including duration, buffer times, question sets, and booking page layouts.',
    capabilities: {
      tools: ['create_event_type', 'analyze_bookings', 'get_availability_summary'],
      connectors: ['calendly', 'acuity'],
      inputTypes: ['meeting-purpose', 'booking-requirements', 'brand-guidelines'],
      outputTypes: ['event-type-config', 'booking-page', 'optimization-suggestion'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['publish-event-type'],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You are a booking experience designer. Create event types that collect the right information and provide a smooth booking experience.',
      specialInstructions: ['Limit pre-booking questions to 3-5', 'Include appropriate buffer time based on meeting type'],
    },
    icon: 'Wand2',
    color: '#14B8A6',
  },
  {
    agentTypeId: 'scheduling.reschedule-handler',
    displayName: 'Reschedule Handler Agent',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Coordinator,
    description: 'Handles reschedule requests by finding alternative times, managing cascading impacts, and communicating changes to all affected parties.',
    capabilities: {
      tools: ['cancel_booking', 'create_booking', 'get_availability_summary', 'list_bookings'],
      connectors: ['calendly', 'google-calendar', 'email'],
      inputTypes: ['reschedule-request', 'constraint-set', 'attendee-preferences'],
      outputTypes: ['alternative-slots', 'reschedule-confirmation', 'impact-assessment'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: ['reschedule-recurring-series'],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You are a reschedule coordination specialist. Handle changes gracefully while minimizing disruption to all parties involved.',
      specialInstructions: ['Offer 3 alternative times sorted by convenience', 'Check for downstream meeting impacts before confirming'],
    },
    icon: 'RefreshCw',
    color: '#D97706',
  },
  {
    agentTypeId: 'scheduling.booking-analytics',
    displayName: 'Booking Analytics Agent',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Provides comprehensive analytics on booking patterns including popular times, conversion rates, average meeting duration, and capacity utilization.',
    capabilities: {
      tools: ['analyze_bookings', 'list_bookings', 'get_no_show_stats', 'get_availability_summary'],
      connectors: ['calendly', 'analytics'],
      inputTypes: ['booking-history', 'event-type-data', 'conversion-funnel'],
      outputTypes: ['booking-analytics-report', 'trend-analysis', 'optimization-insight'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 35000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You are a scheduling analytics specialist. Provide data-driven insights to optimize booking rates and calendar efficiency.',
      specialInstructions: ['Track booking-to-completion conversion rate', 'Identify peak and off-peak booking windows'],
    },
    icon: 'BarChart2',
    color: '#2563EB',
  },
  {
    agentTypeId: 'scheduling.group-scheduler',
    displayName: 'Group Scheduling Agent',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Coordinator,
    description: 'Coordinates group meetings by collecting availability from multiple participants and finding optimal times that maximize attendance.',
    capabilities: {
      tools: ['create_booking', 'get_availability_summary', 'list_bookings'],
      connectors: ['google-calendar', 'outlook', 'calendly', 'doodle'],
      inputTypes: ['participant-list', 'availability-poll', 'meeting-constraints'],
      outputTypes: ['group-availability-matrix', 'optimal-time', 'attendance-forecast'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['book-for-group'],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You are a group scheduling coordinator. Find times that work for the most people while accommodating key stakeholders.',
      specialInstructions: ['Prioritize required attendees over optional', 'Present top 3 options with attendance counts'],
    },
    icon: 'Users',
    color: '#7C3AED',
  },
  {
    agentTypeId: 'scheduling.recurring-optimizer',
    displayName: 'Recurring Meeting Optimizer',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Analyzes recurring meetings for effectiveness, attendance patterns, and necessity, recommending frequency changes or async alternatives.',
    capabilities: {
      tools: ['list_bookings', 'analyze_bookings', 'review_calendar_health'],
      connectors: ['google-calendar', 'outlook', 'slack'],
      inputTypes: ['recurring-meeting-data', 'attendance-history', 'agenda-history'],
      outputTypes: ['optimization-recommendation', 'frequency-suggestion', 'async-alternative'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['modify-recurring-series'],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.8,
    },
    persona: {
      systemPromptAddition: 'You are a recurring meeting analyst. Evaluate whether recurring meetings justify their time investment and suggest improvements.',
      specialInstructions: ['Flag meetings with consistently low attendance', 'Suggest async alternatives for status update meetings'],
    },
    icon: 'Repeat',
    color: '#0891B2',
  },
  {
    agentTypeId: 'scheduling.travel-time-calculator',
    displayName: 'Travel Time Calculator',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Planner,
    description: 'Calculates travel time between in-person meetings and automatically blocks appropriate transit buffer in the calendar.',
    capabilities: {
      tools: ['list_bookings', 'create_booking', 'get_availability_summary'],
      connectors: ['google-maps', 'google-calendar', 'outlook'],
      inputTypes: ['meeting-location', 'transport-mode', 'traffic-data'],
      outputTypes: ['travel-time-estimate', 'buffer-block', 'route-suggestion'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 10000,
      maxCostUsdBudget: 0.2,
    },
    persona: {
      systemPromptAddition: 'You are a logistics planning specialist. Calculate accurate travel times and ensure calendars account for transit between locations.',
      specialInstructions: ['Add 15% buffer to estimated travel time', 'Factor in time of day for traffic estimates'],
    },
    icon: 'Car',
    color: '#64748B',
  },
  {
    agentTypeId: 'scheduling.prep-time-allocator',
    displayName: 'Prep Time Allocator',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Planner,
    description: 'Automatically allocates preparation time before important meetings based on meeting type, agenda complexity, and attendee seniority.',
    capabilities: {
      tools: ['list_bookings', 'create_booking', 'get_availability_summary'],
      connectors: ['google-calendar', 'outlook'],
      inputTypes: ['meeting-metadata', 'prep-time-rules', 'attendee-info'],
      outputTypes: ['prep-block', 'material-checklist', 'prep-reminder'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You are a meeting preparation planner. Ensure adequate prep time is allocated before important meetings.',
      specialInstructions: ['Allocate 30 min prep for executive meetings, 15 min for team meetings', 'Include relevant document links in prep blocks'],
    },
    icon: 'BookOpen',
    color: '#A855F7',
  },
  {
    agentTypeId: 'scheduling.cancellation-analyzer',
    displayName: 'Cancellation Pattern Analyzer',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Analyzes booking cancellation patterns to identify trends, root causes, and opportunities to reduce cancellation rates.',
    capabilities: {
      tools: ['analyze_bookings', 'get_no_show_stats', 'list_bookings'],
      connectors: ['calendly', 'analytics'],
      inputTypes: ['cancellation-data', 'booking-metadata', 'customer-segment'],
      outputTypes: ['cancellation-report', 'trend-analysis', 'retention-recommendation'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 0.8,
    },
    persona: {
      systemPromptAddition: 'You are a booking retention analyst. Identify cancellation drivers and recommend strategies to improve booking completion rates.',
      specialInstructions: ['Segment cancellations by reason, timing, and event type', 'Compare cancellation rates against industry benchmarks'],
    },
    icon: 'XCircle',
    color: '#DC2626',
  },
  {
    agentTypeId: 'scheduling.focus-time-protector',
    displayName: 'Focus Time Protector',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Planner,
    description: 'Proactively blocks and defends focus time on calendars, analyzing meeting patterns to create and maintain uninterrupted deep work blocks.',
    capabilities: {
      tools: ['get_availability_summary', 'list_bookings', 'review_calendar_health', 'create_booking'],
      connectors: ['google-calendar', 'outlook', 'slack'],
      inputTypes: ['focus-preferences', 'calendar-data', 'productivity-patterns'],
      outputTypes: ['focus-block', 'protection-report', 'schedule-adjustment'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['decline-meeting-request'],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You are a deep work advocate. Protect and maximize uninterrupted focus time by intelligently blocking calendar time.',
      specialInstructions: ['Schedule focus blocks during peak productivity hours', 'Consolidate meetings to free up longer focus blocks'],
    },
    icon: 'Shield',
    color: '#059669',
  },
  {
    agentTypeId: 'scheduling.capacity-forecaster',
    displayName: 'Scheduling Capacity Forecaster',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Forecasts booking demand based on historical patterns, seasonal trends, and marketing campaigns to proactively manage capacity.',
    capabilities: {
      tools: ['analyze_bookings', 'list_bookings', 'get_availability_summary', 'get_waitlist_summary'],
      connectors: ['calendly', 'analytics', 'crm'],
      inputTypes: ['booking-history', 'seasonal-data', 'campaign-calendar'],
      outputTypes: ['demand-forecast', 'capacity-recommendation', 'staffing-suggestion'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You are a capacity planning analyst for scheduling. Forecast demand to ensure adequate availability without over-provisioning.',
      specialInstructions: ['Identify seasonal booking patterns', 'Factor in planned marketing campaigns and promotions'],
    },
    icon: 'TrendingUp',
    color: '#1D4ED8',
  },
  {
    agentTypeId: 'scheduling.follow-up-scheduler',
    displayName: 'Follow-Up Scheduler Agent',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Coordinator,
    description: 'Automatically schedules follow-up meetings after completed bookings based on meeting outcomes, cadence rules, and relationship stage.',
    capabilities: {
      tools: ['create_booking', 'list_bookings', 'get_availability_summary', 'analyze_bookings'],
      connectors: ['calendly', 'crm', 'email'],
      inputTypes: ['completed-booking', 'follow-up-rules', 'relationship-stage'],
      outputTypes: ['follow-up-booking', 'cadence-suggestion', 'timing-recommendation'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['send-follow-up-invite'],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You are a relationship cadence specialist. Schedule follow-ups at the right intervals to maintain engagement without over-communicating.',
      specialInstructions: ['Default follow-up intervals: 1 week for prospects, 2 weeks for customers', 'Include meeting summary in follow-up invite'],
    },
    icon: 'CornerDownRight',
    color: '#CA8A04',
  },
  {
    agentTypeId: 'scheduling.round-robin-manager',
    displayName: 'Round Robin Manager',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Coordinator,
    description: 'Manages round-robin meeting assignment across team members, ensuring fair distribution based on availability, workload, and expertise.',
    capabilities: {
      tools: ['create_booking', 'list_bookings', 'get_availability_summary', 'analyze_bookings'],
      connectors: ['calendly', 'google-calendar', 'crm'],
      inputTypes: ['team-roster', 'booking-request', 'distribution-rules'],
      outputTypes: ['assignment-decision', 'balance-report', 'rotation-schedule'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 10000,
      maxCostUsdBudget: 0.2,
    },
    persona: {
      systemPromptAddition: 'You are a round-robin assignment specialist. Distribute meetings fairly while matching the right team member to each booking.',
      specialInstructions: ['Weight distribution by current workload, not just count', 'Override round-robin for skill-matched bookings'],
    },
    icon: 'Shuffle',
    color: '#6D28D9',
  },
  {
    agentTypeId: 'scheduling.meeting-cost-calculator',
    displayName: 'Meeting Cost Calculator',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Calculates the dollar cost of meetings based on attendee salaries, meeting duration, and opportunity cost to help justify or eliminate meetings.',
    capabilities: {
      tools: ['list_bookings', 'analyze_bookings', 'review_calendar_health'],
      connectors: ['google-calendar', 'hr-system'],
      inputTypes: ['meeting-data', 'salary-bands', 'opportunity-cost-model'],
      outputTypes: ['meeting-cost-report', 'roi-analysis', 'elimination-recommendation'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You are a meeting economics analyst. Quantify the true cost of meetings to drive more intentional scheduling decisions.',
      specialInstructions: ['Calculate per-meeting and weekly aggregate costs', 'Flag meetings with cost exceeding $1000 per occurrence'],
    },
    icon: 'DollarSign',
    color: '#B45309',
  },
  {
    agentTypeId: 'scheduling.intake-form-builder',
    displayName: 'Intake Form Builder',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Designer,
    description: 'Creates intelligent pre-booking intake forms that collect the right information based on event type, routing needs, and preparation requirements.',
    capabilities: {
      tools: ['create_event_type', 'analyze_bookings'],
      connectors: ['calendly', 'typeform'],
      inputTypes: ['event-type-config', 'intake-requirements', 'routing-rules'],
      outputTypes: ['intake-form', 'conditional-logic', 'routing-recommendation'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You are a booking form design specialist. Create intake forms that gather essential context without creating booking friction.',
      specialInstructions: ['Limit required fields to absolute minimum', 'Use conditional logic to show relevant questions only'],
    },
    icon: 'FormInput',
    color: '#0D9488',
  },
  {
    agentTypeId: 'scheduling.agenda-builder',
    displayName: 'Agenda Builder Agent',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Writer,
    description: 'Creates structured meeting agendas based on meeting purpose, attendees, previous meeting notes, and open action items.',
    capabilities: {
      tools: ['list_bookings', 'analyze_bookings'],
      connectors: ['notion', 'google-docs', 'calendar'],
      inputTypes: ['meeting-purpose', 'attendee-list', 'previous-notes', 'open-actions'],
      outputTypes: ['meeting-agenda', 'time-allocation', 'pre-read-list'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You are a meeting facilitation specialist. Create focused agendas that keep meetings on track and productive.',
      specialInstructions: ['Allocate specific time to each agenda item', 'Start with open action items from previous meeting'],
    },
    icon: 'ListTodo',
    color: '#4338CA',
  },
  {
    agentTypeId: 'scheduling.booking-page-optimizer',
    displayName: 'Booking Page Optimizer',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Marketing,
    description: 'Optimizes booking page conversion rates by analyzing drop-off points, testing copy variations, and streamlining the booking flow.',
    capabilities: {
      tools: ['create_event_type', 'analyze_bookings', 'get_availability_summary'],
      connectors: ['calendly', 'analytics', 'ab-testing'],
      inputTypes: ['booking-funnel-data', 'page-analytics', 'user-feedback'],
      outputTypes: ['optimization-plan', 'copy-variation', 'conversion-report'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['publish-page-changes'],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You are a booking conversion specialist. Optimize every step of the booking flow to maximize conversion rates.',
      specialInstructions: ['Analyze funnel drop-off at each step', 'Test one variable at a time for clear attribution'],
    },
    icon: 'MousePointerClick',
    color: '#E11D48',
  },
  {
    agentTypeId: 'scheduling.multi-calendar-sync',
    displayName: 'Multi-Calendar Sync Agent',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.DevOps,
    description: 'Synchronizes availability and bookings across multiple calendar platforms, resolving conflicts and maintaining consistent state.',
    capabilities: {
      tools: ['list_bookings', 'get_availability_summary', 'create_booking', 'cancel_booking'],
      connectors: ['google-calendar', 'outlook', 'apple-calendar', 'calendly'],
      inputTypes: ['calendar-event', 'sync-rule', 'conflict-policy'],
      outputTypes: ['sync-status', 'conflict-resolution', 'sync-report'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You are a calendar synchronization specialist. Maintain consistent availability across all connected calendars in real time.',
      specialInstructions: ['Resolve conflicts using last-write-wins by default', 'Log all sync operations for debugging'],
    },
    icon: 'RefreshCcw',
    color: '#475569',
  },
  {
    agentTypeId: 'scheduling.seasonal-adjuster',
    displayName: 'Seasonal Schedule Adjuster',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Planner,
    description: 'Adjusts availability and booking configurations for seasonal changes, holidays, company events, and special periods.',
    capabilities: {
      tools: ['create_event_type', 'get_availability_summary', 'list_bookings', 'analyze_bookings'],
      connectors: ['google-calendar', 'hr-system', 'calendly'],
      inputTypes: ['holiday-calendar', 'seasonal-rule', 'company-event'],
      outputTypes: ['schedule-adjustment', 'holiday-block', 'seasonal-config'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['apply-company-wide-adjustment'],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You are a seasonal scheduling planner. Proactively adjust calendars for holidays, company events, and seasonal patterns.',
      specialInstructions: ['Block company holidays 30 days in advance', 'Reduce availability during traditionally slow periods'],
    },
    icon: 'Snowflake',
    color: '#92400E',
  },
  {
    agentTypeId: 'scheduling.overbooking-strategist',
    displayName: 'Overbooking Strategist',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Implements strategic overbooking based on no-show probability models to maximize slot utilization without creating double-booking issues.',
    capabilities: {
      tools: ['analyze_bookings', 'get_no_show_stats', 'list_bookings', 'get_waitlist_summary'],
      connectors: ['calendly', 'analytics'],
      inputTypes: ['no-show-model', 'booking-capacity', 'risk-tolerance'],
      outputTypes: ['overbooking-recommendation', 'risk-assessment', 'utilization-forecast'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['enable-overbooking'],
      maxTokenBudget: 35000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You are an overbooking strategy analyst. Balance utilization maximization against the risk of double-bookings using statistical models.',
      specialInstructions: ['Never overbook more than historical no-show rate', 'Have a backup plan for when all booked attendees show up'],
    },
    icon: 'Layers',
    color: '#F97316',
  },
  {
    agentTypeId: 'scheduling.buffer-time-optimizer',
    displayName: 'Buffer Time Optimizer',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Planner,
    description: 'Analyzes meeting transitions and recommends optimal buffer times between events based on meeting type, cognitive load, and location changes.',
    capabilities: {
      tools: ['get_bookings', 'analyze_booking_patterns', 'check_availability'],
      connectors: ['google-calendar', 'outlook'],
      inputTypes: ['meeting-sequence', 'transition-data', 'buffer-preferences'],
      outputTypes: ['buffer-recommendation', 'transition-plan', 'schedule-adjustment'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You are a calendar transition specialist. Optimize buffer times to prevent meeting fatigue and ensure smooth transitions between events.',
      specialInstructions: ['Add longer buffers after high-intensity meetings', 'Account for virtual-to-in-person transition times'],
    },
    icon: 'Timer',
    color: '#6366F1',
  },
  {
    agentTypeId: 'scheduling.meeting-duration-optimizer',
    displayName: 'Meeting Duration Optimizer',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Analyzes meeting durations against actual usage patterns and recommends optimal lengths to eliminate wasted time and improve productivity.',
    capabilities: {
      tools: ['analyze_booking_patterns', 'get_bookings', 'manage_event_type'],
      connectors: ['google-calendar', 'outlook', 'zoom'],
      inputTypes: ['meeting-duration-data', 'attendance-patterns', 'early-end-rates'],
      outputTypes: ['duration-recommendation', 'time-savings-report', 'efficiency-score'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.8,
    },
    persona: {
      systemPromptAddition: 'You are a meeting efficiency analyst. Identify meetings that are too long or too short and recommend optimal durations.',
      specialInstructions: ['Prefer 25/50-minute meetings over 30/60 to build in transition time', 'Flag meetings that consistently end early as candidates for shortening'],
    },
    icon: 'Hourglass',
    color: '#D946EF',
  },
  {
    agentTypeId: 'scheduling.overbooking-preventer',
    displayName: 'Overbooking Preventer',
    domain: AgentDomain.Scheduling,
    category: AgentCategory.Core,
    baseType: AgentType.Compliance,
    description: 'Monitors calendar capacity in real time and prevents overbooking by enforcing daily meeting limits, rest requirements, and capacity thresholds.',
    capabilities: {
      tools: ['check_availability', 'get_bookings', 'analyze_booking_patterns'],
      connectors: ['google-calendar', 'outlook', 'calendly'],
      inputTypes: ['booking-capacity', 'daily-limits', 'wellness-rules'],
      outputTypes: ['capacity-alert', 'booking-block', 'wellness-report'],
      domains: ['scheduling'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 10000,
      maxCostUsdBudget: 0.2,
    },
    persona: {
      systemPromptAddition: 'You are a calendar capacity guardian. Prevent overbooking and protect schedule health by enforcing sustainable meeting limits.',
      specialInstructions: ['Enforce maximum 6 hours of meetings per day', 'Block new bookings when daily limit is reached'],
    },
    icon: 'ShieldAlert',
    color: '#B91C1C',
  },
]
