import { AgentDomain, AgentCategory, AgentType, CostTier, LatencyProfile } from '../../types'
import type { AgentCapabilityManifest } from '../../types'

export const AGENTS: AgentCapabilityManifest[] = [
  {
    agentTypeId: 'security.access-auditor',
    displayName: 'Access Auditor',
    domain: AgentDomain.Security,
    category: AgentCategory.Technical,
    baseType: AgentType.Compliance,
    description: 'Audits user access permissions, identifies over-provisioned accounts, and recommends least-privilege adjustments',
    capabilities: {
      tools: ['get_workspace_stats', 'create_issue', 'send_notification'],
      connectors: ['okta', 'aws_iam', 'azure_ad'],
      inputTypes: ['access_policy', 'user_role_mapping', 'activity_log'],
      outputTypes: ['access_audit_report', 'issue', 'remediation_plan'],
      domains: ['security'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['revoke_access'],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You audit access permissions. Apply the principle of least privilege and flag dormant accounts.',
      specialInstructions: ['Check for accounts inactive over 90 days', 'Verify admin access is justified'],
    },
    icon: 'UserCheck',
    color: '#4F46E5',
  },
  {
    agentTypeId: 'security.threat-detector',
    displayName: 'Threat Detector',
    domain: AgentDomain.Security,
    category: AgentCategory.Technical,
    baseType: AgentType.Security,
    description: 'Monitors for suspicious activity patterns, brute force attempts, and anomalous authentication events',
    capabilities: {
      tools: ['create_issue', 'send_notification', 'get_workspace_stats'],
      connectors: ['siem', 'cloudtrail', 'crowdstrike'],
      inputTypes: ['auth_log', 'network_flow', 'threat_intel_feed'],
      outputTypes: ['threat_alert', 'issue', 'incident_report'],
      domains: ['security'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: ['block_ip', 'disable_account'],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You detect security threats in real time. Correlate events across sources to reduce false positives.',
      specialInstructions: ['Correlate failed logins with geo-impossibility checks', 'Alert on privilege escalation attempts'],
    },
    icon: 'ShieldAlert',
    color: '#DC2626',
  },
  {
    agentTypeId: 'security.compliance-monitor',
    displayName: 'Compliance Monitor',
    domain: AgentDomain.Security,
    category: AgentCategory.Legal,
    baseType: AgentType.Compliance,
    description: 'Continuously monitors systems against compliance frameworks like SOC 2, GDPR, HIPAA, and ISO 27001',
    capabilities: {
      tools: ['get_workspace_stats', 'create_issue', 'send_notification'],
      connectors: ['vanta', 'drata', 'aws_config'],
      inputTypes: ['compliance_framework', 'control_status', 'evidence_artifact'],
      outputTypes: ['compliance_report', 'issue', 'gap_analysis'],
      domains: ['security'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 250_000,
      maxCostUsdBudget: 2.5,
    },
    persona: {
      systemPromptAddition: 'You monitor compliance posture. Track control status and flag gaps before audit deadlines.',
      specialInstructions: ['Map controls to specific framework requirements', 'Track evidence freshness'],
    },
    icon: 'ClipboardCheck',
    color: '#059669',
  },
  {
    agentTypeId: 'security.dlp-sentinel',
    displayName: 'DLP Sentinel',
    domain: AgentDomain.Security,
    category: AgentCategory.Technical,
    baseType: AgentType.Security,
    description: 'Prevents data loss by scanning outgoing data flows for sensitive information and policy violations',
    capabilities: {
      tools: ['send_notification', 'create_issue', 'get_workspace_stats'],
      connectors: ['dlp_engine', 'email_gateway', 'cloud_storage'],
      inputTypes: ['data_flow', 'pii_pattern', 'classification_label'],
      outputTypes: ['dlp_alert', 'blocked_transfer', 'policy_violation'],
      domains: ['security'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You prevent data loss. Scan all outbound data for PII, secrets, and classified information.',
      specialInstructions: ['Block transfers containing SSN or credit card patterns', 'Log all DLP events for audit trail'],
    },
    icon: 'ShieldBan',
    color: '#EF4444',
  },
  {
    agentTypeId: 'security.api-key-rotator',
    displayName: 'API Key Rotator',
    domain: AgentDomain.Security,
    category: AgentCategory.Technical,
    baseType: AgentType.DevOps,
    description: 'Tracks API key age, automates rotation schedules, and validates new keys across dependent services',
    capabilities: {
      tools: ['create_issue', 'send_notification', 'get_workspace_stats'],
      connectors: ['vault', 'aws_secrets_manager', 'azure_key_vault'],
      inputTypes: ['key_inventory', 'rotation_schedule', 'service_dependency'],
      outputTypes: ['rotation_report', 'issue', 'key_status'],
      domains: ['security'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['rotate_production_key'],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You manage API key rotation. Ensure zero-downtime rotation by validating new keys before revoking old ones.',
      specialInstructions: ['Rotate keys older than 90 days', 'Test new key against all dependent services before deactivating old key'],
    },
    icon: 'KeyRound',
    color: '#F59E0B',
  },
  {
    agentTypeId: 'security.vulnerability-scanner',
    displayName: 'Vulnerability Scanner',
    domain: AgentDomain.Security,
    category: AgentCategory.Technical,
    baseType: AgentType.Security,
    description: 'Scans application and infrastructure for known vulnerabilities and rates them by severity',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'send_notification'],
      connectors: ['qualys', 'nessus', 'trivy'],
      inputTypes: ['scan_target', 'vulnerability_db', 'asset_inventory'],
      outputTypes: ['vulnerability_report', 'issue', 'severity_dashboard'],
      domains: ['security'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['run_active_scan'],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You scan for vulnerabilities. Prioritize by exploitability and business impact, not just CVSS score.',
      specialInstructions: ['Cross-reference with known exploit databases', 'Check for publicly available PoC exploits'],
    },
    icon: 'Scan',
    color: '#7C3AED',
  },
  {
    agentTypeId: 'security.incident-responder',
    displayName: 'Security Incident Responder',
    domain: AgentDomain.Security,
    category: AgentCategory.Technical,
    baseType: AgentType.Coordinator,
    description: 'Coordinates security incident response following established playbooks and escalation procedures',
    capabilities: {
      tools: ['create_issue', 'send_notification', 'get_workspace_stats'],
      connectors: ['pagerduty', 'jira', 'slack'],
      inputTypes: ['security_alert', 'incident_playbook', 'affected_systems'],
      outputTypes: ['incident_report', 'containment_action', 'postmortem'],
      domains: ['security'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: ['isolate_system', 'revoke_credentials'],
      maxTokenBudget: 300_000,
      maxCostUsdBudget: 5.0,
    },
    persona: {
      systemPromptAddition: 'You coordinate security incident response. Follow playbooks, contain first, then investigate.',
      specialInstructions: ['Document every action taken with timestamps', 'Preserve evidence before containment'],
    },
    icon: 'Siren',
    color: '#DC2626',
  },
  {
    agentTypeId: 'security.penetration-tester',
    displayName: 'Penetration Test Planner',
    domain: AgentDomain.Security,
    category: AgentCategory.Technical,
    baseType: AgentType.Planner,
    description: 'Plans penetration testing engagements, defines scope and rules of engagement, and organizes findings',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'get_workspace_stats'],
      connectors: ['burp_suite', 'metasploit', 'nmap'],
      inputTypes: ['asset_inventory', 'scope_definition', 'rules_of_engagement'],
      outputTypes: ['test_plan', 'findings_report', 'issue'],
      domains: ['security'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['execute_pentest', 'test_production'],
      maxTokenBudget: 250_000,
      maxCostUsdBudget: 5.0,
    },
    persona: {
      systemPromptAddition: 'You plan penetration tests. Define clear scope, rules of engagement, and reporting standards.',
      specialInstructions: ['Never test without written authorization', 'Include remediation guidance with each finding'],
    },
    icon: 'Target',
    color: '#F43F5E',
  },
  {
    agentTypeId: 'security.encryption-validator',
    displayName: 'Encryption Validator',
    domain: AgentDomain.Security,
    category: AgentCategory.Technical,
    baseType: AgentType.Reviewer,
    description: 'Validates encryption configurations for data at rest and in transit across all services',
    capabilities: {
      tools: ['get_workspace_stats', 'create_issue', 'send_notification'],
      connectors: ['aws_kms', 'ssl_labs', 'certificate_manager'],
      inputTypes: ['tls_config', 'encryption_policy', 'certificate_inventory'],
      outputTypes: ['encryption_report', 'issue', 'certificate_status'],
      domains: ['security'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You validate encryption. Check TLS versions, cipher suites, and certificate validity.',
      specialInstructions: ['Flag TLS versions below 1.2', 'Alert on certificates expiring within 30 days'],
    },
    icon: 'Lock',
    color: '#0891B2',
  },
  {
    agentTypeId: 'security.phishing-detector',
    displayName: 'Phishing Detector',
    domain: AgentDomain.Security,
    category: AgentCategory.Technical,
    baseType: AgentType.Analyst,
    description: 'Analyzes incoming emails and messages for phishing indicators, malicious links, and social engineering',
    capabilities: {
      tools: ['send_notification', 'create_issue', 'get_workspace_stats'],
      connectors: ['email_gateway', 'urlscan', 'virustotal'],
      inputTypes: ['email_header', 'message_body', 'url_list'],
      outputTypes: ['phishing_alert', 'quarantine_action', 'threat_report'],
      domains: ['security'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You detect phishing attempts. Analyze sender reputation, URL destinations, and social engineering patterns.',
      specialInstructions: ['Check SPF/DKIM/DMARC alignment', 'Scan URLs in sandbox before delivering'],
    },
    icon: 'Fish',
    color: '#F97316',
  },
  {
    agentTypeId: 'security.network-segmentation-auditor',
    displayName: 'Network Segmentation Auditor',
    domain: AgentDomain.Security,
    category: AgentCategory.Technical,
    baseType: AgentType.Reviewer,
    description: 'Audits network segmentation rules to ensure proper isolation between security zones',
    capabilities: {
      tools: ['get_workspace_stats', 'create_issue', 'list_issues'],
      connectors: ['firewall', 'aws_vpc', 'network_scanner'],
      inputTypes: ['network_topology', 'firewall_rules', 'traffic_flow'],
      outputTypes: ['segmentation_report', 'issue', 'rule_recommendation'],
      domains: ['security'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You audit network segmentation. Verify that sensitive systems are properly isolated.',
      specialInstructions: ['Check for overly permissive rules allowing cross-zone traffic', 'Validate database tiers are not internet-facing'],
    },
    icon: 'Network',
    color: '#6366F1',
  },
  {
    agentTypeId: 'security.session-monitor',
    displayName: 'Session Monitor',
    domain: AgentDomain.Security,
    category: AgentCategory.Technical,
    baseType: AgentType.Analyst,
    description: 'Monitors active user sessions for hijacking indicators, concurrent logins, and session anomalies',
    capabilities: {
      tools: ['send_notification', 'create_issue', 'get_workspace_stats'],
      connectors: ['auth0', 'okta', 'session_store'],
      inputTypes: ['session_log', 'geo_data', 'device_fingerprint'],
      outputTypes: ['session_alert', 'forced_logout', 'anomaly_report'],
      domains: ['security'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: ['force_session_termination'],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You monitor user sessions. Detect session hijacking, impossible travel, and suspicious concurrent sessions.',
      specialInstructions: ['Check for device fingerprint changes mid-session', 'Alert on logins from new countries'],
    },
    icon: 'MonitorDot',
    color: '#10B981',
  },
  {
    agentTypeId: 'security.policy-enforcer',
    displayName: 'Policy Enforcer',
    domain: AgentDomain.Security,
    category: AgentCategory.Legal,
    baseType: AgentType.Compliance,
    description: 'Enforces security policies across the organization by validating configurations against baselines',
    capabilities: {
      tools: ['get_workspace_stats', 'create_issue', 'send_notification'],
      connectors: ['chef_inspec', 'opa', 'sentinel'],
      inputTypes: ['policy_definition', 'system_config', 'baseline_standard'],
      outputTypes: ['policy_violation', 'enforcement_report', 'issue'],
      domains: ['security'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['enforce_policy_change'],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You enforce security policies. Check configurations against baselines and flag drift immediately.',
      specialInstructions: ['Compare against CIS benchmarks', 'Track policy drift over time'],
    },
    icon: 'Gavel',
    color: '#475569',
  },
  {
    agentTypeId: 'security.log-integrity-checker',
    displayName: 'Log Integrity Checker',
    domain: AgentDomain.Security,
    category: AgentCategory.Technical,
    baseType: AgentType.Reviewer,
    description: 'Verifies log integrity by checking for gaps, tampering, and unauthorized modifications',
    capabilities: {
      tools: ['get_workspace_stats', 'create_issue', 'send_notification'],
      connectors: ['cloudtrail', 'splunk', 'worm_storage'],
      inputTypes: ['log_chain', 'hash_record', 'timestamp_sequence'],
      outputTypes: ['integrity_report', 'tampering_alert', 'issue'],
      domains: ['security'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You verify log integrity. Detect gaps, timestamp anomalies, and potential tampering.',
      specialInstructions: ['Check for sequential timestamp gaps', 'Verify hash chains are unbroken'],
    },
    icon: 'FileCheck',
    color: '#8B5CF6',
  },
  {
    agentTypeId: 'security.third-party-risk-assessor',
    displayName: 'Third-Party Risk Assessor',
    domain: AgentDomain.Security,
    category: AgentCategory.Legal,
    baseType: AgentType.Analyst,
    description: 'Assesses security risk of third-party vendors, SaaS tools, and integration partners',
    capabilities: {
      tools: ['get_workspace_stats', 'create_issue', 'send_notification'],
      connectors: ['security_scorecard', 'bitsight', 'questionnaire'],
      inputTypes: ['vendor_profile', 'security_questionnaire', 'soc2_report'],
      outputTypes: ['risk_assessment', 'issue', 'vendor_scorecard'],
      domains: ['security'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You assess third-party security risk. Evaluate vendor security posture and data handling practices.',
      specialInstructions: ['Check for SOC 2 Type II or equivalent certification', 'Assess data residency and privacy compliance'],
    },
    icon: 'Building',
    color: '#0EA5E9',
  },
  {
    agentTypeId: 'security.mfa-enforcer',
    displayName: 'MFA Enforcer',
    domain: AgentDomain.Security,
    category: AgentCategory.Technical,
    baseType: AgentType.Compliance,
    description: 'Tracks MFA enrollment across the organization and enforces multi-factor authentication policies',
    capabilities: {
      tools: ['send_notification', 'create_issue', 'get_workspace_stats'],
      connectors: ['okta', 'duo', 'azure_ad'],
      inputTypes: ['mfa_status', 'user_directory', 'policy_config'],
      outputTypes: ['enrollment_report', 'reminder_notification', 'issue'],
      domains: ['security'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['force_mfa_enrollment'],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You enforce MFA policies. Track enrollment and send reminders to non-compliant users.',
      specialInstructions: ['Prioritize admin and privileged accounts', 'Report MFA bypass attempts'],
    },
    icon: 'Fingerprint',
    color: '#14B8A6',
  },
  {
    agentTypeId: 'security.backup-verifier',
    displayName: 'Backup Verifier',
    domain: AgentDomain.Security,
    category: AgentCategory.Technical,
    baseType: AgentType.DevOps,
    description: 'Verifies backup integrity, tests restoration procedures, and monitors backup schedules',
    capabilities: {
      tools: ['get_workspace_stats', 'create_issue', 'send_notification'],
      connectors: ['aws_backup', 'veeam', 'restic'],
      inputTypes: ['backup_manifest', 'restore_test_config', 'retention_policy'],
      outputTypes: ['backup_status', 'restore_test_report', 'issue'],
      domains: ['security'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['run_restore_test'],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You verify backups. Test restores regularly and ensure RPO/RTO targets are met.',
      specialInstructions: ['Verify backup encryption', 'Test full restore at least monthly'],
    },
    icon: 'DatabaseBackup',
    color: '#2563EB',
  },
  {
    agentTypeId: 'security.waf-tuner',
    displayName: 'WAF Tuner',
    domain: AgentDomain.Security,
    category: AgentCategory.Technical,
    baseType: AgentType.Security,
    description: 'Tunes web application firewall rules to balance security with false positive reduction',
    capabilities: {
      tools: ['create_issue', 'get_workspace_stats', 'send_notification'],
      connectors: ['cloudflare', 'aws_waf', 'akamai'],
      inputTypes: ['waf_logs', 'false_positive_report', 'attack_pattern'],
      outputTypes: ['rule_adjustment', 'tuning_report', 'issue'],
      domains: ['security'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['modify_waf_rules'],
      maxTokenBudget: 150_000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You tune WAF rules. Reduce false positives while maintaining strong protection against OWASP Top 10.',
      specialInstructions: ['Analyze blocked request patterns before loosening rules', 'Test rule changes in detection-only mode first'],
    },
    icon: 'ShieldHalf',
    color: '#F97316',
  },
  {
    agentTypeId: 'security.privilege-escalation-detector',
    displayName: 'Privilege Escalation Detector',
    domain: AgentDomain.Security,
    category: AgentCategory.Technical,
    baseType: AgentType.Analyst,
    description: 'Detects unauthorized privilege escalation attempts and suspicious role changes in real time',
    capabilities: {
      tools: ['send_notification', 'create_issue', 'get_workspace_stats'],
      connectors: ['cloudtrail', 'azure_monitor', 'siem'],
      inputTypes: ['iam_event', 'role_change_log', 'admin_action'],
      outputTypes: ['escalation_alert', 'issue', 'behavior_analysis'],
      domains: ['security'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You detect privilege escalation. Monitor role changes and admin actions for unauthorized access.',
      specialInstructions: ['Alert on any role change to admin or owner', 'Track service account privilege changes'],
    },
    icon: 'ArrowBigUp',
    color: '#EF4444',
  },
  {
    agentTypeId: 'security.data-classification-engine',
    displayName: 'Data Classification Engine',
    domain: AgentDomain.Security,
    category: AgentCategory.Technical,
    baseType: AgentType.Analyst,
    description: 'Automatically classifies data by sensitivity level and applies appropriate handling labels',
    capabilities: {
      tools: ['get_workspace_stats', 'create_issue', 'send_notification'],
      connectors: ['microsoft_purview', 'google_dlp', 'aws_macie'],
      inputTypes: ['data_sample', 'classification_policy', 'content_metadata'],
      outputTypes: ['classification_label', 'handling_instruction', 'audit_record'],
      domains: ['security'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 100_000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You classify data by sensitivity. Apply labels consistently and err on the side of higher classification.',
      specialInstructions: ['Detect PII, PHI, and financial data automatically', 'Apply handling instructions based on classification level'],
    },
    icon: 'Tags',
    color: '#D946EF',
  },
  {
    agentTypeId: 'security.security-awareness-trainer',
    displayName: 'Security Awareness Trainer',
    domain: AgentDomain.Security,
    category: AgentCategory.People,
    baseType: AgentType.Writer,
    description: 'Creates security awareness training content, phishing simulations, and compliance quizzes',
    capabilities: {
      tools: ['send_notification', 'get_workspace_stats', 'create_issue'],
      connectors: ['knowbe4', 'proofpoint', 'email'],
      inputTypes: ['training_topic', 'threat_briefing', 'quiz_template'],
      outputTypes: ['training_module', 'phishing_simulation', 'quiz'],
      domains: ['security'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['launch_phishing_simulation'],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You create security training content. Make it engaging, practical, and relevant to current threats.',
      specialInstructions: ['Use real-world examples from recent breaches', 'Keep training modules under 10 minutes'],
    },
    icon: 'GraduationCap',
    color: '#3B82F6',
  },
  {
    agentTypeId: 'security.certificate-manager',
    displayName: 'Certificate Manager',
    domain: AgentDomain.Security,
    category: AgentCategory.Technical,
    baseType: AgentType.DevOps,
    description: 'Manages SSL/TLS certificates, tracks expiration dates, and automates renewal workflows',
    capabilities: {
      tools: ['send_notification', 'create_issue', 'get_workspace_stats'],
      connectors: ['letsencrypt', 'digicert', 'aws_acm'],
      inputTypes: ['certificate_inventory', 'expiration_schedule', 'domain_list'],
      outputTypes: ['certificate_status', 'renewal_action', 'issue'],
      domains: ['security'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['renew_production_certificate'],
      maxTokenBudget: 80_000,
      maxCostUsdBudget: 0.3,
    },
    persona: {
      systemPromptAddition: 'You manage TLS certificates. Track expirations and automate renewals to prevent outages.',
      specialInstructions: ['Alert 30 days before expiration', 'Verify certificate chain completeness after renewal'],
    },
    icon: 'Award',
    color: '#CA8A04',
  },
  {
    agentTypeId: 'security.soc-analyst',
    displayName: 'SOC Analyst',
    domain: AgentDomain.Security,
    category: AgentCategory.Technical,
    baseType: AgentType.Analyst,
    description: 'Performs first-level SOC analysis by triaging security alerts and investigating indicators of compromise',
    capabilities: {
      tools: ['create_issue', 'list_issues', 'send_notification'],
      connectors: ['siem', 'edr', 'threat_intel'],
      inputTypes: ['security_alert', 'ioc_feed', 'endpoint_telemetry'],
      outputTypes: ['investigation_report', 'issue', 'escalation_decision'],
      domains: ['security'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: ['quarantine_endpoint'],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You perform SOC analysis. Triage alerts quickly, investigate IOCs, and escalate true positives.',
      specialInstructions: ['Enrich alerts with threat intelligence context', 'Document investigation steps for knowledge base'],
    },
    icon: 'Eye',
    color: '#1E293B',
  },
  {
    agentTypeId: 'security.cloud-security-posture',
    displayName: 'Cloud Security Posture Manager',
    domain: AgentDomain.Security,
    category: AgentCategory.Technical,
    baseType: AgentType.Security,
    description: 'Monitors cloud infrastructure security posture and detects misconfigurations across AWS, Azure, and GCP',
    capabilities: {
      tools: ['get_workspace_stats', 'create_issue', 'list_issues'],
      connectors: ['aws_security_hub', 'azure_defender', 'gcp_scc'],
      inputTypes: ['cloud_config', 'security_finding', 'resource_inventory'],
      outputTypes: ['posture_report', 'misconfiguration_alert', 'issue'],
      domains: ['security'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['remediate_finding'],
      maxTokenBudget: 200_000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You manage cloud security posture. Monitor configurations against security best practices continuously.',
      specialInstructions: ['Check for public S3 buckets and open security groups', 'Verify encryption is enabled on all storage'],
    },
    icon: 'Cloud',
    color: '#0EA5E9',
  },
]
