import { AgentDomain, AgentCategory, AgentType, CostTier, LatencyProfile } from '../../types'
import type { AgentCapabilityManifest } from '../../types'

export const AGENTS: AgentCapabilityManifest[] = [
  {
    agentTypeId: 'tax.w2-extractor',
    displayName: 'W-2 Extractor',
    domain: AgentDomain.Tax,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Extracts wage, tax withholding, and employer data from W-2 forms using OCR and field mapping with accuracy validation.',
    capabilities: {
      tools: ['analyze_tax_document', 'create_tax_filing', 'explain_tax_field'],
      connectors: ['origina-tax'],
      inputTypes: ['w2-image', 'w2-pdf', 'employer-data'],
      outputTypes: ['w2-data', 'extraction-report', 'validation-results'],
      domains: ['w2', 'wages', 'withholding', 'extraction', 'payroll'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 35000,
      maxCostUsdBudget: 0.35,
    },
    persona: {
      systemPromptAddition: 'You are a W-2 processing specialist. Extract every box value accurately and flag discrepancies against known employer data.',
      specialInstructions: [
        'Validate Box 1 wages against Box 3 and Box 5 for consistency',
        'Cross-reference employer EIN against IRS records',
        'Flag state-specific boxes that differ from federal',
      ],
    },
    icon: 'file-spreadsheet',
    color: '#2563EB',
  },
  {
    agentTypeId: 'tax.1099-processor',
    displayName: '1099 Processor',
    domain: AgentDomain.Tax,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Processes all 1099 form variants (NEC, INT, DIV, MISC, B, R, S) with automatic form type detection and data extraction.',
    capabilities: {
      tools: ['analyze_tax_document', 'create_tax_filing', 'explain_tax_field'],
      connectors: ['origina-tax'],
      inputTypes: ['1099-document', 'payer-info', 'form-type'],
      outputTypes: ['1099-data', 'form-classification', 'schedule-mapping'],
      domains: ['1099', 'contractor', 'dividends', 'interest', 'income'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 35000,
      maxCostUsdBudget: 0.35,
    },
    persona: {
      systemPromptAddition: 'You are a 1099 processing expert. Identify the form variant, extract all fields, and map data to the correct tax schedules.',
      specialInstructions: [
        'Auto-detect 1099 variant from document layout',
        'Map extracted income to correct Schedule lines',
        'Flag backup withholding amounts for credit calculations',
      ],
    },
    icon: 'file-digit',
    color: '#3B82F6',
  },
  {
    agentTypeId: 'tax.deduction-finder',
    displayName: 'Deduction Finder',
    domain: AgentDomain.Tax,
    category: AgentCategory.Business,
    baseType: AgentType.Researcher,
    description: 'Identifies eligible tax deductions and credits based on taxpayer profile, income sources, and expenses with IRS citation references.',
    capabilities: {
      tools: ['suggest_deductions', 'analyze_tax_document', 'explain_tax_field'],
      connectors: ['origina-tax'],
      inputTypes: ['taxpayer-profile', 'expense-list', 'income-summary'],
      outputTypes: ['deduction-list', 'savings-estimate', 'eligibility-report'],
      domains: ['deductions', 'credits', 'savings', 'itemized', 'standard'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 0.50,
    },
    persona: {
      systemPromptAddition: 'You are a tax deduction specialist. Find every legitimate deduction and credit the taxpayer qualifies for.',
      specialInstructions: [
        'Compare standard deduction vs. itemized to recommend the better option',
        'Cite specific IRS publications and code sections',
        'Estimate dollar savings for each deduction found',
      ],
    },
    icon: 'search',
    color: '#16A34A',
  },
  {
    agentTypeId: 'tax.form-validator',
    displayName: 'Form Validator',
    domain: AgentDomain.Tax,
    category: AgentCategory.Technical,
    baseType: AgentType.Reviewer,
    description: 'Validates completed tax forms against IRS specifications, checking field calculations, cross-form consistency, and filing requirements.',
    capabilities: {
      tools: ['review_filing', 'analyze_tax_document', 'explain_tax_field'],
      connectors: ['origina-tax'],
      inputTypes: ['tax-return', 'form-id', 'validation-level'],
      outputTypes: ['validation-report', 'error-list', 'fix-instructions'],
      domains: ['validation', 'errors', 'calculations', 'compliance', 'accuracy'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 0.25,
    },
    persona: {
      systemPromptAddition: 'You are a tax form validation expert. Catch every mathematical error, missing field, and inconsistency before filing.',
      specialInstructions: [
        'Verify all arithmetic across schedules and forms',
        'Check required attachments are present',
        'Validate SSN and EIN format and check digits',
      ],
    },
    icon: 'check-square',
    color: '#059669',
  },
  {
    agentTypeId: 'tax.filing-compliance-checker',
    displayName: 'Filing Compliance Checker',
    domain: AgentDomain.Tax,
    category: AgentCategory.Legal,
    baseType: AgentType.Compliance,
    description: 'Verifies tax filings meet all federal, state, and local compliance requirements including deadlines, required forms, and filing thresholds.',
    capabilities: {
      tools: ['review_filing', 'check_submission_status', 'get_upcoming_deadlines'],
      connectors: ['origina-tax'],
      inputTypes: ['filing-package', 'jurisdiction-list', 'taxpayer-type'],
      outputTypes: ['compliance-report', 'missing-forms', 'deadline-calendar'],
      domains: ['compliance', 'filing', 'deadlines', 'requirements', 'jurisdiction'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 0.40,
    },
    persona: {
      systemPromptAddition: 'You are a tax filing compliance specialist. Ensure every filing meets all jurisdictional requirements and deadlines.',
      specialInstructions: [
        'Check filing threshold requirements for each jurisdiction',
        'Verify estimated tax payment compliance',
        'Flag extension deadlines when standard deadline will be missed',
      ],
    },
    icon: 'shield-check',
    color: '#7C3AED',
  },
  {
    agentTypeId: 'tax.interview-guide',
    displayName: 'Tax Interview Guide',
    domain: AgentDomain.Tax,
    category: AgentCategory.People,
    baseType: AgentType.CustomerSuccess,
    description: 'Guides taxpayers through a conversational tax interview to gather all necessary information for accurate return preparation.',
    capabilities: {
      tools: ['explain_tax_field', 'suggest_deductions', 'create_tax_filing'],
      connectors: ['origina-tax'],
      inputTypes: ['taxpayer-responses', 'filing-status', 'prior-year-data'],
      outputTypes: ['interview-summary', 'data-collection', 'missing-info-list'],
      domains: ['interview', 'intake', 'questionnaire', 'onboarding', 'guidance'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.20,
    },
    persona: {
      systemPromptAddition: 'You are a friendly tax interview guide. Ask clear, simple questions to gather all the information needed for an accurate return.',
      specialInstructions: [
        'Use plain language, not tax jargon',
        'Ask follow-up questions based on previous answers',
        'Track which sections are complete and what info is still needed',
      ],
    },
    icon: 'message-circle',
    color: '#0891B2',
  },
  {
    agentTypeId: 'tax.document-classifier',
    displayName: 'Tax Document Classifier',
    domain: AgentDomain.Tax,
    category: AgentCategory.Technical,
    baseType: AgentType.Analyst,
    description: 'Classifies uploaded tax documents by form type, tax year, and relevance, routing them to the correct processing pipeline.',
    capabilities: {
      tools: ['analyze_tax_document', 'explain_tax_field'],
      connectors: ['origina-tax'],
      inputTypes: ['document-upload', 'classification-hint'],
      outputTypes: ['document-type', 'tax-year', 'routing-decision'],
      domains: ['classification', 'document-type', 'routing', 'sorting', 'triage'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.10,
    },
    persona: {
      systemPromptAddition: 'You are a tax document triage specialist. Quickly identify document types and route them for proper processing.',
      specialInstructions: [
        'Detect form type from header and layout within seconds',
        'Extract tax year from document dates and form revision',
        'Flag non-tax documents that were uploaded by mistake',
      ],
    },
    icon: 'folder-search',
    color: '#F59E0B',
  },
  {
    agentTypeId: 'tax.estimated-tax-calculator',
    displayName: 'Estimated Tax Calculator',
    domain: AgentDomain.Tax,
    category: AgentCategory.Business,
    baseType: AgentType.Finance,
    description: 'Calculates quarterly estimated tax payments based on projected income, withholdings, and prior year safe harbor amounts.',
    capabilities: {
      tools: ['create_tax_filing', 'analyze_tax_document', 'get_upcoming_deadlines'],
      connectors: ['origina-tax'],
      inputTypes: ['income-projection', 'withholding-data', 'prior-year-tax'],
      outputTypes: ['estimated-payments', 'quarterly-schedule', 'penalty-analysis'],
      domains: ['estimated-tax', 'quarterly', 'safe-harbor', 'penalties', 'projections'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 35000,
      maxCostUsdBudget: 0.35,
    },
    persona: {
      systemPromptAddition: 'You are an estimated tax payment specialist. Calculate accurate quarterly payments that avoid underpayment penalties.',
      specialInstructions: [
        'Use both current year and prior year safe harbor methods',
        'Account for irregular income patterns in payment timing',
        'Calculate potential underpayment penalty exposure',
      ],
    },
    icon: 'calculator',
    color: '#4338CA',
  },
  {
    agentTypeId: 'tax.state-tax-coordinator',
    displayName: 'State Tax Coordinator',
    domain: AgentDomain.Tax,
    category: AgentCategory.Business,
    baseType: AgentType.Coordinator,
    description: 'Manages multi-state tax filing requirements for taxpayers with income in multiple jurisdictions, handling allocation and credits.',
    capabilities: {
      tools: ['create_tax_filing', 'review_filing', 'check_submission_status'],
      connectors: ['origina-tax'],
      inputTypes: ['state-income-list', 'residency-info', 'w2-state-data'],
      outputTypes: ['state-filing-plan', 'allocation-schedule', 'credit-calculations'],
      domains: ['state-tax', 'multi-state', 'allocation', 'reciprocity', 'nexus'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['create_tax_filing'],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 0.50,
    },
    persona: {
      systemPromptAddition: 'You are a multi-state tax specialist. Navigate the complexities of state tax obligations and credit allocations.',
      specialInstructions: [
        'Identify all states with filing requirements based on income sources',
        'Apply reciprocity agreements to avoid double taxation',
        'Calculate resident credits for taxes paid to other states',
      ],
    },
    icon: 'map',
    color: '#DC2626',
  },
  {
    agentTypeId: 'tax.depreciation-calculator',
    displayName: 'Depreciation Calculator',
    domain: AgentDomain.Tax,
    category: AgentCategory.Business,
    baseType: AgentType.Finance,
    description: 'Calculates depreciation schedules for business assets using MACRS, Section 179, and bonus depreciation with optimal method selection.',
    capabilities: {
      tools: ['suggest_deductions', 'create_tax_filing', 'explain_tax_field'],
      connectors: ['origina-tax'],
      inputTypes: ['asset-list', 'purchase-dates', 'business-use-pct'],
      outputTypes: ['depreciation-schedule', 'method-comparison', 'form-4562-data'],
      domains: ['depreciation', 'macrs', 'section-179', 'assets', 'amortization'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 35000,
      maxCostUsdBudget: 0.35,
    },
    persona: {
      systemPromptAddition: 'You are a depreciation and asset specialist. Optimize depreciation methods to maximize current-year deductions.',
      specialInstructions: [
        'Compare Section 179, bonus depreciation, and standard MACRS for each asset',
        'Track listed property business use percentages',
        'Generate Form 4562 data ready for filing',
      ],
    },
    icon: 'trending-down',
    color: '#6D28D9',
  },
  {
    agentTypeId: 'tax.schedule-c-advisor',
    displayName: 'Schedule C Advisor',
    domain: AgentDomain.Tax,
    category: AgentCategory.Business,
    baseType: AgentType.Finance,
    description: 'Assists sole proprietors with Schedule C preparation including income categorization, expense classification, and home office deduction calculations.',
    capabilities: {
      tools: ['suggest_deductions', 'create_tax_filing', 'explain_tax_field'],
      connectors: ['origina-tax'],
      inputTypes: ['business-income', 'expense-categories', 'home-office-info'],
      outputTypes: ['schedule-c-draft', 'expense-analysis', 'audit-risk-assessment'],
      domains: ['schedule-c', 'self-employment', 'business-expenses', 'sole-proprietor'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['create_tax_filing'],
      maxTokenBudget: 45000,
      maxCostUsdBudget: 0.45,
    },
    persona: {
      systemPromptAddition: 'You are a sole proprietor tax advisor. Maximize legitimate business deductions while minimizing audit risk.',
      specialInstructions: [
        'Classify expenses into correct Schedule C categories',
        'Calculate home office deduction using both simplified and actual methods',
        'Flag expense ratios that exceed IRS audit triggers',
      ],
    },
    icon: 'store',
    color: '#0D9488',
  },
  {
    agentTypeId: 'tax.capital-gains-calculator',
    displayName: 'Capital Gains Calculator',
    domain: AgentDomain.Tax,
    category: AgentCategory.Business,
    baseType: AgentType.Finance,
    description: 'Calculates capital gains and losses from investment transactions with cost basis tracking, wash sale detection, and Schedule D preparation.',
    capabilities: {
      tools: ['analyze_tax_document', 'create_tax_filing', 'explain_tax_field'],
      connectors: ['origina-tax'],
      inputTypes: ['trade-history', 'cost-basis-data', '1099-b-forms'],
      outputTypes: ['gains-summary', 'schedule-d-draft', 'wash-sale-report'],
      domains: ['capital-gains', 'investments', 'cost-basis', 'wash-sale', 'schedule-d'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 0.40,
    },
    persona: {
      systemPromptAddition: 'You are an investment tax specialist. Calculate gains accurately, detect wash sales, and optimize tax-loss harvesting opportunities.',
      specialInstructions: [
        'Detect wash sale violations within 30-day windows',
        'Identify tax-loss harvesting opportunities before year-end',
        'Reconcile broker 1099-B data against actual trade records',
      ],
    },
    icon: 'line-chart',
    color: '#10B981',
  },
  {
    agentTypeId: 'tax.rental-property-advisor',
    displayName: 'Rental Property Advisor',
    domain: AgentDomain.Tax,
    category: AgentCategory.Business,
    baseType: AgentType.Finance,
    description: 'Manages tax implications of rental properties including Schedule E preparation, depreciation, passive activity rules, and material participation tests.',
    capabilities: {
      tools: ['suggest_deductions', 'create_tax_filing', 'explain_tax_field'],
      connectors: ['origina-tax'],
      inputTypes: ['rental-income', 'property-expenses', 'ownership-info'],
      outputTypes: ['schedule-e-draft', 'passive-activity-analysis', 'depreciation-schedule'],
      domains: ['rental', 'schedule-e', 'passive-activity', 'real-estate', 'property'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['create_tax_filing'],
      maxTokenBudget: 45000,
      maxCostUsdBudget: 0.45,
    },
    persona: {
      systemPromptAddition: 'You are a rental property tax expert. Navigate passive activity rules and maximize allowable deductions for landlords.',
      specialInstructions: [
        'Apply passive activity loss limitation rules correctly',
        'Calculate REPS (Real Estate Professional Status) qualification',
        'Track suspended passive losses for future use',
      ],
    },
    icon: 'home',
    color: '#78716C',
  },
  {
    agentTypeId: 'tax.tax-field-explainer',
    displayName: 'Tax Field Explainer',
    domain: AgentDomain.Tax,
    category: AgentCategory.People,
    baseType: AgentType.CustomerSuccess,
    description: 'Explains individual tax form fields, lines, and boxes in plain language with examples and IRS instruction references.',
    capabilities: {
      tools: ['explain_tax_field', 'analyze_tax_document'],
      connectors: ['origina-tax'],
      inputTypes: ['form-id', 'field-id', 'context-question'],
      outputTypes: ['field-explanation', 'examples', 'irs-reference'],
      domains: ['explanation', 'help', 'education', 'fields', 'instructions'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.10,
    },
    persona: {
      systemPromptAddition: 'You are a tax educator. Explain complex tax concepts and form fields in simple, jargon-free language anyone can understand.',
      specialInstructions: [
        'Use real-world examples to illustrate each concept',
        'Reference specific IRS instructions and publications',
        'Anticipate follow-up questions and address them proactively',
      ],
    },
    icon: 'help-circle',
    color: '#0EA5E9',
  },
  {
    agentTypeId: 'tax.amendment-preparer',
    displayName: 'Amendment Preparer',
    domain: AgentDomain.Tax,
    category: AgentCategory.Business,
    baseType: AgentType.Tax,
    description: 'Prepares Form 1040-X amended returns by identifying changes from the original filing, calculating adjustments, and generating explanations.',
    capabilities: {
      tools: ['create_tax_filing', 'review_filing', 'analyze_tax_document'],
      connectors: ['origina-tax'],
      inputTypes: ['original-return', 'correction-items', 'amendment-reason'],
      outputTypes: ['form-1040x', 'change-explanation', 'refund-or-balance-due'],
      domains: ['amendment', '1040-x', 'correction', 'adjusted-return'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['create_tax_filing'],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 0.50,
    },
    persona: {
      systemPromptAddition: 'You are a tax amendment specialist. Prepare accurate 1040-X forms with clear explanations for each change.',
      specialInstructions: [
        'Compare original and corrected amounts for each changed line',
        'Write clear, IRS-acceptable explanations for each change',
        'Calculate the correct refund or additional tax due',
      ],
    },
    icon: 'file-edit',
    color: '#EA580C',
  },
  {
    agentTypeId: 'tax.audit-risk-assessor',
    displayName: 'Audit Risk Assessor',
    domain: AgentDomain.Tax,
    category: AgentCategory.Legal,
    baseType: AgentType.Compliance,
    description: 'Assesses audit risk by analyzing return characteristics against known IRS DIF score factors, industry benchmarks, and red flag patterns.',
    capabilities: {
      tools: ['review_filing', 'analyze_tax_document', 'suggest_deductions'],
      connectors: ['origina-tax'],
      inputTypes: ['tax-return', 'industry-code', 'income-level'],
      outputTypes: ['risk-score', 'red-flag-report', 'mitigation-suggestions'],
      domains: ['audit', 'risk', 'dif-score', 'red-flags', 'triggers'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 0.40,
    },
    persona: {
      systemPromptAddition: 'You are a tax audit risk analyst. Identify return characteristics that may trigger IRS scrutiny and suggest risk mitigation.',
      specialInstructions: [
        'Compare expense ratios against IRS industry benchmarks',
        'Flag common audit triggers like high charitable deductions',
        'Suggest documentation to support high-risk deductions',
      ],
    },
    icon: 'alert-triangle',
    color: '#DC2626',
  },
  {
    agentTypeId: 'tax.extension-filer',
    displayName: 'Extension Filer',
    domain: AgentDomain.Tax,
    category: AgentCategory.Business,
    baseType: AgentType.Tax,
    description: 'Prepares and tracks tax extension filings (Form 4868 for individuals, Form 7004 for businesses) with estimated payment calculations.',
    capabilities: {
      tools: ['create_tax_filing', 'check_submission_status', 'get_upcoming_deadlines'],
      connectors: ['origina-tax'],
      inputTypes: ['taxpayer-info', 'estimated-tax-liability', 'filing-type'],
      outputTypes: ['extension-form', 'payment-voucher', 'new-deadline'],
      domains: ['extension', 'form-4868', 'form-7004', 'deadline', 'payment'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['create_tax_filing'],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.15,
    },
    persona: {
      systemPromptAddition: 'You are a tax extension filing specialist. Prepare timely extensions with accurate estimated payments to avoid penalties.',
      specialInstructions: [
        'Calculate estimated payment to avoid underpayment penalty',
        'Track extension deadlines for both federal and state',
        'Confirm electronic filing acceptance with status checks',
      ],
    },
    icon: 'clock',
    color: '#D97706',
  },
  {
    agentTypeId: 'tax.charity-deduction-validator',
    displayName: 'Charity Deduction Validator',
    domain: AgentDomain.Tax,
    category: AgentCategory.Business,
    baseType: AgentType.Reviewer,
    description: 'Validates charitable contribution deductions by checking organization eligibility, receipt requirements, and AGI limitation compliance.',
    capabilities: {
      tools: ['suggest_deductions', 'review_filing', 'explain_tax_field'],
      connectors: ['origina-tax'],
      inputTypes: ['donation-list', 'receipt-documents', 'agi-amount'],
      outputTypes: ['validation-report', 'eligible-deductions', 'documentation-gaps'],
      domains: ['charity', 'donations', 'contributions', '501c3', 'receipts'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.20,
    },
    persona: {
      systemPromptAddition: 'You are a charitable deduction validation specialist. Verify every donation meets IRS requirements for deductibility.',
      specialInstructions: [
        'Verify 501(c)(3) status of each recipient organization',
        'Check receipt requirements for donations over $250',
        'Apply AGI percentage limitations by donation type',
      ],
    },
    icon: 'heart',
    color: '#E11D48',
  },
  {
    agentTypeId: 'tax.business-entity-advisor',
    displayName: 'Business Entity Advisor',
    domain: AgentDomain.Tax,
    category: AgentCategory.Business,
    baseType: AgentType.Finance,
    description: 'Analyzes optimal business entity structure (LLC, S-Corp, C-Corp, partnership) based on tax implications, liability, and growth plans.',
    capabilities: {
      tools: ['suggest_deductions', 'explain_tax_field', 'analyze_tax_document'],
      connectors: ['origina-tax'],
      inputTypes: ['business-profile', 'income-projections', 'ownership-structure'],
      outputTypes: ['entity-comparison', 'tax-impact-analysis', 'recommendation'],
      domains: ['entity', 'llc', 's-corp', 'c-corp', 'partnership', 'structure'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 60000,
      maxCostUsdBudget: 0.60,
    },
    persona: {
      systemPromptAddition: 'You are a business entity tax advisor. Compare entity structures to find the optimal tax treatment for each business situation.',
      specialInstructions: [
        'Model tax outcomes for each entity type with actual numbers',
        'Factor in self-employment tax savings for S-Corp elections',
        'Consider state-specific entity tax implications',
      ],
    },
    icon: 'building',
    color: '#4338CA',
  },
  {
    agentTypeId: 'tax.payroll-tax-calculator',
    displayName: 'Payroll Tax Calculator',
    domain: AgentDomain.Tax,
    category: AgentCategory.Business,
    baseType: AgentType.Finance,
    description: 'Calculates employer and employee payroll tax obligations including FICA, FUTA, state unemployment, and additional Medicare tax.',
    capabilities: {
      tools: ['create_tax_filing', 'explain_tax_field', 'get_upcoming_deadlines'],
      connectors: ['origina-tax'],
      inputTypes: ['payroll-data', 'employee-count', 'state-list'],
      outputTypes: ['payroll-tax-summary', 'deposit-schedule', 'form-941-data'],
      domains: ['payroll', 'fica', 'futa', 'unemployment', 'withholding'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 35000,
      maxCostUsdBudget: 0.35,
    },
    persona: {
      systemPromptAddition: 'You are a payroll tax calculation expert. Compute accurate payroll obligations and ensure timely deposits.',
      specialInstructions: [
        'Apply wage base limits for Social Security accurately',
        'Calculate additional Medicare tax for high earners',
        'Determine deposit frequency (monthly vs. semi-weekly)',
      ],
    },
    icon: 'wallet',
    color: '#0891B2',
  },
  {
    agentTypeId: 'tax.tax-planning-advisor',
    displayName: 'Tax Planning Advisor',
    domain: AgentDomain.Tax,
    category: AgentCategory.Business,
    baseType: AgentType.Planner,
    description: 'Provides year-round tax planning strategies including income timing, deduction acceleration, retirement contributions, and year-end moves.',
    capabilities: {
      tools: ['suggest_deductions', 'analyze_tax_document', 'explain_tax_field', 'get_upcoming_deadlines'],
      connectors: ['origina-tax'],
      inputTypes: ['financial-snapshot', 'tax-goals', 'life-events'],
      outputTypes: ['planning-recommendations', 'action-timeline', 'savings-projection'],
      domains: ['planning', 'strategy', 'optimization', 'year-end', 'future'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 60000,
      maxCostUsdBudget: 0.60,
    },
    persona: {
      systemPromptAddition: 'You are a proactive tax planning strategist. Identify opportunities to minimize tax liability through smart timing and structuring.',
      specialInstructions: [
        'Consider multi-year tax bracket impact for income shifting',
        'Recommend retirement contribution strategies (traditional vs. Roth)',
        'Time capital gains harvesting with tax bracket analysis',
      ],
    },
    icon: 'lightbulb',
    color: '#6366F1',
  },
  {
    agentTypeId: 'tax.submission-tracker',
    displayName: 'Submission Tracker',
    domain: AgentDomain.Tax,
    category: AgentCategory.Business,
    baseType: AgentType.Coordinator,
    description: 'Tracks e-file submissions, rejection resolution, acceptance confirmations, and refund status across all filed returns.',
    capabilities: {
      tools: ['check_submission_status', 'get_upcoming_deadlines', 'review_filing'],
      connectors: ['origina-tax'],
      inputTypes: ['filing-id', 'tracking-number', 'status-request'],
      outputTypes: ['submission-status', 'rejection-details', 'refund-timeline'],
      domains: ['e-file', 'submission', 'tracking', 'rejection', 'acceptance'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Realtime,
      requiresApproval: [],
      maxTokenBudget: 15000,
      maxCostUsdBudget: 0.10,
    },
    persona: {
      systemPromptAddition: 'You are a tax filing status tracker. Monitor submissions and resolve rejections quickly to ensure timely processing.',
      specialInstructions: [
        'Check submission status within 24 hours of filing',
        'Provide clear rejection reason explanations',
        'Guide through rejection resolution steps',
      ],
    },
    icon: 'radar',
    color: '#14B8A6',
  },
  {
    agentTypeId: 'tax.retirement-contribution-optimizer',
    displayName: 'Retirement Contribution Optimizer',
    domain: AgentDomain.Tax,
    category: AgentCategory.Business,
    baseType: AgentType.Finance,
    description: 'Optimizes retirement account contributions across 401(k), IRA, SEP, SIMPLE, and HSA accounts for maximum tax benefit.',
    capabilities: {
      tools: ['suggest_deductions', 'explain_tax_field', 'analyze_tax_document'],
      connectors: ['origina-tax'],
      inputTypes: ['income-data', 'account-types', 'contribution-history'],
      outputTypes: ['contribution-plan', 'tax-savings-analysis', 'limit-tracking'],
      domains: ['retirement', '401k', 'ira', 'sep', 'hsa', 'contributions'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 35000,
      maxCostUsdBudget: 0.35,
    },
    persona: {
      systemPromptAddition: 'You are a retirement contribution tax optimizer. Maximize tax-advantaged savings across all available account types.',
      specialInstructions: [
        'Track contribution limits across all account types',
        'Compare traditional vs. Roth contributions based on tax bracket',
        'Identify catch-up contribution eligibility for age 50+',
      ],
    },
    icon: 'piggy-bank',
    color: '#059669',
  },
  {
    agentTypeId: 'tax.international-tax-advisor',
    displayName: 'International Tax Advisor',
    domain: AgentDomain.Tax,
    category: AgentCategory.Legal,
    baseType: AgentType.Tax,
    description: 'Handles international tax obligations including FBAR, Form 8938, foreign tax credits, tax treaty benefits, and GILTI calculations.',
    capabilities: {
      tools: ['create_tax_filing', 'review_filing', 'explain_tax_field'],
      connectors: ['origina-tax'],
      inputTypes: ['foreign-income', 'foreign-accounts', 'treaty-country'],
      outputTypes: ['fbar-form', 'form-8938', 'foreign-tax-credit', 'treaty-analysis'],
      domains: ['international', 'fbar', 'foreign-income', 'treaty', 'gilti'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Expensive,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['create_tax_filing'],
      maxTokenBudget: 60000,
      maxCostUsdBudget: 0.60,
    },
    persona: {
      systemPromptAddition: 'You are an international tax specialist. Navigate complex cross-border tax obligations and treaty benefits with precision.',
      specialInstructions: [
        'Determine FBAR and Form 8938 filing requirements independently',
        'Apply tax treaty provisions to reduce double taxation',
        'Calculate foreign tax credit vs. foreign earned income exclusion trade-offs',
      ],
    },
    icon: 'globe',
    color: '#7C3AED',
  },
  {
    agentTypeId: 'tax.deadline-monitor',
    displayName: 'Deadline Monitor',
    domain: AgentDomain.Tax,
    category: AgentCategory.Business,
    baseType: AgentType.Coordinator,
    description: 'Monitors all tax filing, payment, and compliance deadlines with proactive alerts, calendar integration, and jurisdiction-specific tracking.',
    capabilities: {
      tools: ['get_upcoming_deadlines', 'check_submission_status', 'review_filing'],
      connectors: ['origina-tax', 'origina-scheduling'],
      inputTypes: ['taxpayer-profile', 'filing-types', 'alert-preferences'],
      outputTypes: ['deadline-calendar', 'alert-schedule', 'compliance-timeline'],
      domains: ['deadlines', 'calendar', 'alerts', 'reminders', 'compliance-dates'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.15,
    },
    persona: {
      systemPromptAddition: 'You are a tax deadline watchdog. Never let a filing or payment deadline pass without advance notice.',
      specialInstructions: [
        'Alert at 30, 14, 7, and 1 day before each deadline',
        'Account for weekends and holidays in deadline calculations',
        'Track extension deadlines separately from original deadlines',
      ],
    },
    icon: 'alarm-clock',
    color: '#B91C1C',
  },
  {
    agentTypeId: 'tax.sales-tax-calculator',
    displayName: 'Sales Tax Calculator',
    domain: AgentDomain.Tax,
    category: AgentCategory.Business,
    baseType: AgentType.Finance,
    description: 'Calculates sales tax obligations across jurisdictions with nexus determination, exemption handling, and filing schedule management.',
    capabilities: {
      tools: ['create_tax_filing', 'get_upcoming_deadlines', 'explain_tax_field'],
      connectors: ['origina-tax'],
      inputTypes: ['sales-data', 'jurisdiction-list', 'nexus-info'],
      outputTypes: ['sales-tax-summary', 'nexus-analysis', 'filing-schedule'],
      domains: ['sales-tax', 'nexus', 'use-tax', 'exemptions', 'jurisdiction'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['create_tax_filing'],
      maxTokenBudget: 35000,
      maxCostUsdBudget: 0.35,
    },
    persona: {
      systemPromptAddition: 'You are a sales tax compliance specialist. Navigate multi-jurisdiction sales tax with accurate nexus analysis and rate calculations.',
      specialInstructions: [
        'Determine economic nexus thresholds for each state',
        'Apply product-specific tax rates and exemptions',
        'Track filing frequency requirements per jurisdiction',
      ],
    },
    icon: 'shopping-cart',
    color: '#475569',
  },
  {
    agentTypeId: 'tax.crypto-tax-calculator',
    displayName: 'Crypto Tax Calculator',
    domain: AgentDomain.Tax,
    category: AgentCategory.Business,
    baseType: AgentType.Finance,
    description: 'Calculates cryptocurrency tax obligations from trading, staking, mining, and DeFi activities with cost basis tracking across exchanges.',
    capabilities: {
      tools: ['analyze_tax_document', 'create_tax_filing', 'explain_tax_field'],
      connectors: ['origina-tax'],
      inputTypes: ['exchange-history', 'wallet-transactions', 'staking-rewards'],
      outputTypes: ['crypto-tax-report', 'cost-basis-summary', 'schedule-d-data'],
      domains: ['cryptocurrency', 'bitcoin', 'defi', 'staking', 'mining', 'nft'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 45000,
      maxCostUsdBudget: 0.45,
    },
    persona: {
      systemPromptAddition: 'You are a cryptocurrency tax specialist. Track cost basis across exchanges and wallets for accurate crypto tax reporting.',
      specialInstructions: [
        'Support FIFO, LIFO, and specific identification methods',
        'Handle cross-chain transactions and bridge events',
        'Classify staking, airdrops, and mining as ordinary income',
      ],
    },
    icon: 'bitcoin',
    color: '#F97316',
  },
  {
    agentTypeId: 'tax.prior-year-comparator',
    displayName: 'Prior Year Comparator',
    domain: AgentDomain.Tax,
    category: AgentCategory.Business,
    baseType: AgentType.Analyst,
    description: 'Compares current year tax data against prior year returns to identify significant changes, anomalies, and potential audit triggers.',
    capabilities: {
      tools: ['analyze_tax_document', 'review_filing', 'suggest_deductions'],
      connectors: ['origina-tax'],
      inputTypes: ['current-year-data', 'prior-year-return', 'comparison-config'],
      outputTypes: ['comparison-report', 'variance-analysis', 'anomaly-flags'],
      domains: ['comparison', 'year-over-year', 'variance', 'trends', 'anomaly'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 0.40,
    },
    persona: {
      systemPromptAddition: 'You are a tax year comparison analyst. Spot meaningful changes between years and explain their tax implications.',
      specialInstructions: [
        'Flag line items with greater than 20% year-over-year change',
        'Explain whether changes increase or decrease audit risk',
        'Identify new deductions or credits available this year',
      ],
    },
    icon: 'git-compare',
    color: '#64748B',
  },
]
