import { AgentDomain, AgentCategory, AgentType, CostTier, LatencyProfile } from '../../types'
import type { AgentCapabilityManifest } from '../../types'

export const AGENTS: AgentCapabilityManifest[] = [
  {
    agentTypeId: 'workspace.content-writer',
    displayName: 'Content Writer Agent',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Creative,
    baseType: AgentType.Writer,
    description: 'Creates and refines written content for pages, documents, and knowledge bases using brand voice guidelines and audience context.',
    capabilities: {
      tools: ['create_page', 'search_pages', 'add_block', 'get_workspace_stats'],
      connectors: ['notion', 'google-docs', 'grammarly'],
      inputTypes: ['content-brief', 'brand-guidelines', 'topic-outline'],
      outputTypes: ['page-content', 'blog-post', 'knowledge-article'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['publish-content'],
      maxTokenBudget: 80000,
      maxCostUsdBudget: 3.0,
    },
    persona: {
      systemPromptAddition: 'You are a professional content writer. Produce clear, engaging content that matches the brand voice and serves the target audience.',
      specialInstructions: ['Follow brand tone guidelines strictly', 'Include relevant internal links to existing pages'],
    },
    icon: 'Pen',
    color: '#4F46E5',
  },
  {
    agentTypeId: 'workspace.wiki-curator',
    displayName: 'Wiki Curator Agent',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Core,
    baseType: AgentType.Coordinator,
    description: 'Maintains wiki structure and content freshness by organizing pages, updating navigation, removing outdated content, and enforcing documentation standards.',
    capabilities: {
      tools: ['search_pages', 'create_page', 'add_block', 'get_workspace_stats'],
      connectors: ['notion', 'confluence'],
      inputTypes: ['page-inventory', 'structure-proposal', 'staleness-report'],
      outputTypes: ['reorganization-plan', 'archive-recommendation', 'structure-update'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['archive-pages', 'restructure-navigation'],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You are a knowledge management curator. Keep the wiki organized, current, and easy to navigate for all team members.',
      specialInstructions: ['Flag pages not updated in 90+ days', 'Maintain a consistent page hierarchy depth of max 4 levels'],
    },
    icon: 'Library',
    color: '#8B5CF6',
  },
  {
    agentTypeId: 'workspace.template-builder',
    displayName: 'Template Builder Agent',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Creative,
    baseType: AgentType.Designer,
    description: 'Creates reusable page and document templates based on common patterns, team needs, and best practices for consistent content creation.',
    capabilities: {
      tools: ['create_page', 'add_block', 'search_pages'],
      connectors: ['notion', 'google-docs'],
      inputTypes: ['template-request', 'content-pattern', 'team-workflow'],
      outputTypes: ['page-template', 'document-template', 'template-guide'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You are a template design specialist. Create templates that standardize content creation while remaining flexible for different use cases.',
      specialInstructions: ['Include placeholder text with instructions', 'Add metadata fields for categorization'],
    },
    icon: 'LayoutTemplate',
    color: '#10B981',
  },
  {
    agentTypeId: 'workspace.knowledge-linker',
    displayName: 'Knowledge Linker Agent',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Core,
    baseType: AgentType.Researcher,
    description: 'Identifies and creates cross-references between related pages, building a rich knowledge graph that improves content discoverability.',
    capabilities: {
      tools: ['search_pages', 'add_block', 'get_workspace_stats'],
      connectors: ['notion', 'confluence'],
      inputTypes: ['page-content', 'topic-taxonomy', 'link-suggestion-request'],
      outputTypes: ['link-suggestion', 'knowledge-graph', 'orphan-page-report'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 35000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You are a knowledge graph specialist. Build meaningful connections between content to maximize discoverability and context.',
      specialInstructions: ['Prioritize bidirectional links', 'Identify orphan pages with no incoming links'],
    },
    icon: 'Link',
    color: '#0EA5E9',
  },
  {
    agentTypeId: 'workspace.page-analyzer',
    displayName: 'Page Analytics Agent',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Analyzes page engagement metrics including views, edits, comments, and sharing patterns to identify high-value and underperforming content.',
    capabilities: {
      tools: ['search_pages', 'get_workspace_stats'],
      connectors: ['notion', 'analytics'],
      inputTypes: ['page-metrics', 'engagement-data', 'content-inventory'],
      outputTypes: ['engagement-report', 'content-performance', 'optimization-suggestion'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 0.8,
    },
    persona: {
      systemPromptAddition: 'You are a content analytics specialist. Provide insights on content performance to guide editorial and curation decisions.',
      specialInstructions: ['Rank pages by engagement score (views + edits + comments)', 'Flag high-traffic pages with low edit frequency as potentially stale'],
    },
    icon: 'BarChart',
    color: '#6366F1',
  },
  {
    agentTypeId: 'workspace.meeting-notes-synthesizer',
    displayName: 'Meeting Notes Synthesizer',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Core,
    baseType: AgentType.Writer,
    description: 'Transforms raw meeting transcripts into structured notes with key decisions, action items, attendees, and follow-up tasks.',
    capabilities: {
      tools: ['create_page', 'add_block', 'search_pages'],
      connectors: ['otter-ai', 'zoom', 'google-meet', 'notion'],
      inputTypes: ['meeting-transcript', 'agenda', 'attendee-list'],
      outputTypes: ['meeting-notes', 'action-item-list', 'decision-log'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You are a meeting documentation specialist. Extract key decisions, action items, and insights from meeting content accurately.',
      specialInstructions: ['Assign owners and due dates to all action items', 'Link decisions to relevant project pages'],
    },
    icon: 'ClipboardList',
    color: '#F59E0B',
  },
  {
    agentTypeId: 'workspace.onboarding-guide',
    displayName: 'Workspace Onboarding Guide',
    domain: AgentDomain.Workspace,
    category: AgentCategory.People,
    baseType: AgentType.Coordinator,
    description: 'Creates personalized onboarding experiences for new workspace members by curating essential reading, setting up page structures, and guiding navigation.',
    capabilities: {
      tools: ['create_page', 'search_pages', 'add_block', 'get_workspace_stats'],
      connectors: ['notion', 'slack', 'hr-system'],
      inputTypes: ['new-member-profile', 'team-context', 'onboarding-template'],
      outputTypes: ['onboarding-checklist', 'reading-list', 'workspace-guide'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.8,
    },
    persona: {
      systemPromptAddition: 'You are a workspace onboarding specialist. Make new members productive quickly by guiding them to the most relevant content.',
      specialInstructions: ['Curate a top-10 must-read pages list', 'Create a personal workspace page for the new member'],
    },
    icon: 'Compass',
    color: '#14B8A6',
  },
  {
    agentTypeId: 'workspace.sop-writer',
    displayName: 'SOP Writer Agent',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Core,
    baseType: AgentType.Writer,
    description: 'Creates and maintains Standard Operating Procedures by interviewing process owners, documenting step-by-step workflows, and adding visual aids.',
    capabilities: {
      tools: ['create_page', 'add_block', 'search_pages'],
      connectors: ['notion', 'google-docs', 'loom'],
      inputTypes: ['process-description', 'interview-notes', 'existing-sop'],
      outputTypes: ['sop-document', 'process-flowchart', 'revision-history'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['publish-sop'],
      maxTokenBudget: 60000,
      maxCostUsdBudget: 2.5,
    },
    persona: {
      systemPromptAddition: 'You are an SOP documentation specialist. Write clear, actionable procedures that anyone can follow without prior knowledge.',
      specialInstructions: ['Use numbered steps with clear action verbs', 'Include decision points and exception handling'],
    },
    icon: 'FileCheck2',
    color: '#DC2626',
  },
  {
    agentTypeId: 'workspace.search-optimizer',
    displayName: 'Search Optimization Agent',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Improves workspace search quality by analyzing search queries, identifying content gaps, optimizing page titles and tags, and building synonyms.',
    capabilities: {
      tools: ['search_pages', 'add_block', 'get_workspace_stats'],
      connectors: ['notion', 'algolia'],
      inputTypes: ['search-query-log', 'zero-result-queries', 'page-metadata'],
      outputTypes: ['search-improvement', 'tag-suggestion', 'synonym-mapping'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 0.8,
    },
    persona: {
      systemPromptAddition: 'You are a search relevance specialist. Improve content findability by optimizing metadata, tags, and search indexes.',
      specialInstructions: ['Analyze top zero-result queries weekly', 'Suggest tags for untagged pages based on content analysis'],
    },
    icon: 'Search',
    color: '#7C3AED',
  },
  {
    agentTypeId: 'workspace.translation-agent',
    displayName: 'Content Translation Agent',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Creative,
    baseType: AgentType.Translation,
    description: 'Translates workspace content into multiple languages while maintaining terminology consistency, brand voice, and formatting.',
    capabilities: {
      tools: ['create_page', 'search_pages', 'add_block'],
      connectors: ['notion', 'translation-memory'],
      inputTypes: ['source-content', 'target-language', 'glossary'],
      outputTypes: ['translated-content', 'translation-memory-update', 'quality-report'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['publish-translation'],
      maxTokenBudget: 60000,
      maxCostUsdBudget: 2.5,
    },
    persona: {
      systemPromptAddition: 'You are a professional translator. Produce natural, accurate translations that preserve the original meaning and brand voice.',
      specialInstructions: ['Use established glossary terms consistently', 'Preserve all formatting and links from the source'],
    },
    icon: 'Languages',
    color: '#0891B2',
  },
  {
    agentTypeId: 'workspace.changelog-writer',
    displayName: 'Workspace Changelog Writer',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Core,
    baseType: AgentType.Writer,
    description: 'Tracks and documents changes across the workspace, generating human-readable changelogs for important page updates and structural changes.',
    capabilities: {
      tools: ['search_pages', 'create_page', 'add_block'],
      connectors: ['notion', 'slack'],
      inputTypes: ['page-changelog', 'edit-history', 'workspace-activity'],
      outputTypes: ['changelog-entry', 'weekly-digest', 'change-summary'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You are a workspace change communicator. Keep the team informed about important content changes with clear, concise summaries.',
      specialInstructions: ['Group changes by area or team', 'Highlight breaking changes to SOPs or processes'],
    },
    icon: 'History',
    color: '#64748B',
  },
  {
    agentTypeId: 'workspace.faq-builder',
    displayName: 'FAQ Builder Agent',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Core,
    baseType: AgentType.Writer,
    description: 'Builds and maintains FAQ pages by analyzing common questions from Slack, support tickets, and search queries, with accurate sourced answers.',
    capabilities: {
      tools: ['create_page', 'add_block', 'search_pages', 'get_workspace_stats'],
      connectors: ['slack', 'zendesk', 'notion'],
      inputTypes: ['common-questions', 'support-ticket', 'search-query-log'],
      outputTypes: ['faq-page', 'answer-update', 'question-clustering'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['publish-faq'],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You are an FAQ specialist. Build comprehensive, well-organized FAQ content from real user questions with accurate, sourced answers.',
      specialInstructions: ['Link answers to authoritative source pages', 'Group FAQs by topic with clear section headers'],
    },
    icon: 'HelpCircle',
    color: '#E11D48',
  },
  {
    agentTypeId: 'workspace.style-guide-enforcer',
    displayName: 'Style Guide Enforcer',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Creative,
    baseType: AgentType.Reviewer,
    description: 'Reviews workspace content against brand style guidelines, checking for tone, formatting, terminology, and visual consistency.',
    capabilities: {
      tools: ['search_pages', 'add_block', 'get_workspace_stats'],
      connectors: ['notion', 'grammarly'],
      inputTypes: ['page-content', 'style-guide', 'brand-voice-doc'],
      outputTypes: ['style-violation', 'correction-suggestion', 'compliance-score'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You are a brand and style compliance reviewer. Ensure all content adheres to the organization\'s style guide and voice.',
      specialInstructions: ['Check heading hierarchy, list formatting, and capitalization', 'Enforce terminology from the approved glossary'],
    },
    icon: 'Palette',
    color: '#F97316',
  },
  {
    agentTypeId: 'workspace.content-recycler',
    displayName: 'Content Recycling Agent',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Creative,
    baseType: AgentType.Writer,
    description: 'Repurposes existing workspace content into different formats such as summaries, presentations, social posts, and email newsletters.',
    capabilities: {
      tools: ['search_pages', 'create_page', 'add_block'],
      connectors: ['notion', 'canva', 'mailchimp'],
      inputTypes: ['source-page', 'target-format', 'audience-profile'],
      outputTypes: ['repurposed-content', 'format-adaptation', 'distribution-plan'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['publish-externally'],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You are a content repurposing specialist. Transform existing content into new formats that reach different audiences effectively.',
      specialInstructions: ['Adapt length and depth for the target format', 'Maintain key messages across all formats'],
    },
    icon: 'Recycle',
    color: '#16A34A',
  },
  {
    agentTypeId: 'workspace.taxonomy-builder',
    displayName: 'Taxonomy Builder Agent',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Designs and maintains content taxonomies, tag hierarchies, and categorization systems that organize workspace knowledge logically.',
    capabilities: {
      tools: ['search_pages', 'add_block', 'get_workspace_stats'],
      connectors: ['notion', 'confluence'],
      inputTypes: ['content-inventory', 'existing-taxonomy', 'classification-request'],
      outputTypes: ['taxonomy-structure', 'tag-hierarchy', 'classification-guide'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 1,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['restructure-taxonomy'],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You are an information architecture specialist. Design intuitive taxonomies that make content easy to find and organize.',
      specialInstructions: ['Limit taxonomy depth to 4 levels', 'Use mutually exclusive, collectively exhaustive categories'],
    },
    icon: 'FolderTree',
    color: '#475569',
  },
  {
    agentTypeId: 'workspace.policy-manager',
    displayName: 'Policy Documentation Manager',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Legal,
    baseType: AgentType.Compliance,
    description: 'Manages company policy documents including version control, review schedules, acknowledgment tracking, and compliance monitoring.',
    capabilities: {
      tools: ['create_page', 'search_pages', 'add_block', 'get_workspace_stats'],
      connectors: ['notion', 'docusign', 'hr-system'],
      inputTypes: ['policy-document', 'review-schedule', 'compliance-requirement'],
      outputTypes: ['policy-update', 'review-reminder', 'acknowledgment-report'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['publish-policy', 'update-policy'],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You are a policy management specialist. Ensure all policies are current, properly versioned, and acknowledged by relevant personnel.',
      specialInstructions: ['Schedule annual reviews for all policies', 'Track acknowledgment completion rates by department'],
    },
    icon: 'ScrollText',
    color: '#B91C1C',
  },
  {
    agentTypeId: 'workspace.report-generator',
    displayName: 'Report Generator Agent',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Core,
    baseType: AgentType.Writer,
    description: 'Generates periodic reports (weekly, monthly, quarterly) by aggregating data from multiple workspace sources into structured, readable documents.',
    capabilities: {
      tools: ['create_page', 'search_pages', 'add_block', 'get_workspace_stats'],
      connectors: ['notion', 'google-sheets', 'bi-platform'],
      inputTypes: ['report-template', 'data-source', 'reporting-period'],
      outputTypes: ['periodic-report', 'executive-summary', 'data-visualization'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['distribute-report'],
      maxTokenBudget: 60000,
      maxCostUsdBudget: 2.5,
    },
    persona: {
      systemPromptAddition: 'You are a business reporting specialist. Create clear, data-driven reports that provide actionable insights for decision-makers.',
      specialInstructions: ['Lead with key takeaways before detailed data', 'Include period-over-period comparisons'],
    },
    icon: 'FileBarChart',
    color: '#2563EB',
  },
  {
    agentTypeId: 'workspace.content-archiver',
    displayName: 'Content Archival Agent',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Core,
    baseType: AgentType.Coordinator,
    description: 'Identifies content eligible for archival based on age, activity, and relevance criteria, then manages the archival process while preserving access.',
    capabilities: {
      tools: ['search_pages', 'get_workspace_stats'],
      connectors: ['notion', 'cold-storage'],
      inputTypes: ['page-activity-log', 'archival-policy', 'content-age-report'],
      outputTypes: ['archival-recommendation', 'archive-manifest', 'retention-report'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['archive-content', 'delete-permanently'],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.8,
    },
    persona: {
      systemPromptAddition: 'You are a content lifecycle manager. Balance workspace cleanliness with content preservation based on clear retention policies.',
      specialInstructions: ['Never archive without checking for incoming links first', 'Apply 90-day grace period before deletion'],
    },
    icon: 'Archive',
    color: '#78716C',
  },
  {
    agentTypeId: 'workspace.diagram-builder',
    displayName: 'Diagram Builder Agent',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Creative,
    baseType: AgentType.Designer,
    description: 'Creates diagrams, flowcharts, architecture diagrams, and visual representations from text descriptions to enhance documentation.',
    capabilities: {
      tools: ['add_block', 'create_page', 'search_pages'],
      connectors: ['mermaid', 'excalidraw', 'miro'],
      inputTypes: ['text-description', 'process-flow', 'system-architecture'],
      outputTypes: ['diagram', 'flowchart', 'architecture-diagram'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 25000,
      maxCostUsdBudget: 0.8,
    },
    persona: {
      systemPromptAddition: 'You are a visual documentation specialist. Create clear, well-labeled diagrams that communicate complex systems at a glance.',
      specialInstructions: ['Use consistent shapes and colors for element types', 'Include a legend for non-obvious symbols'],
    },
    icon: 'PenTool',
    color: '#A855F7',
  },
  {
    agentTypeId: 'workspace.glossary-maintainer',
    displayName: 'Glossary Maintainer Agent',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Core,
    baseType: AgentType.Writer,
    description: 'Maintains organization-wide glossaries and term definitions, detecting new terms in content and ensuring consistent terminology usage.',
    capabilities: {
      tools: ['search_pages', 'create_page', 'add_block'],
      connectors: ['notion', 'confluence'],
      inputTypes: ['new-content', 'term-candidate', 'existing-glossary'],
      outputTypes: ['glossary-entry', 'term-definition', 'consistency-report'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You are a terminology management specialist. Maintain accurate, consistent definitions for all organization-specific terms.',
      specialInstructions: ['Detect acronyms and ensure they are defined', 'Cross-reference with industry standard definitions'],
    },
    icon: 'BookA',
    color: '#0D9488',
  },
  {
    agentTypeId: 'workspace.permissions-auditor',
    displayName: 'Permissions Audit Agent',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Core,
    baseType: AgentType.Security,
    description: 'Audits workspace page permissions to identify over-shared content, permission gaps, and access patterns that may violate information security policies.',
    capabilities: {
      tools: ['search_pages', 'get_workspace_stats'],
      connectors: ['notion', 'google-workspace', 'okta'],
      inputTypes: ['permission-matrix', 'access-log', 'security-policy'],
      outputTypes: ['permissions-audit', 'risk-finding', 'remediation-plan'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['revoke-access'],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You are a workspace security auditor. Ensure content access follows the principle of least privilege and complies with security policies.',
      specialInstructions: ['Flag publicly shared internal documents', 'Check for departed employees with remaining access'],
    },
    icon: 'ShieldCheck',
    color: '#EF4444',
  },
  {
    agentTypeId: 'workspace.content-summarizer',
    displayName: 'Content Summarizer Agent',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Core,
    baseType: AgentType.Writer,
    description: 'Creates executive summaries, TLDRs, and key takeaways from long-form content to improve information accessibility.',
    capabilities: {
      tools: ['search_pages', 'add_block', 'get_workspace_stats'],
      connectors: ['notion', 'google-docs'],
      inputTypes: ['long-form-content', 'summary-request', 'audience-level'],
      outputTypes: ['executive-summary', 'tldr', 'key-takeaways'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You are a content condensation specialist. Distill complex documents into clear, accurate summaries without losing critical information.',
      specialInstructions: ['Preserve all key decisions and action items', 'Adjust summary depth based on audience level'],
    },
    icon: 'AlignLeft',
    color: '#CA8A04',
  },
  {
    agentTypeId: 'workspace.runbook-writer',
    displayName: 'Runbook Writer Agent',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Technical,
    baseType: AgentType.Writer,
    description: 'Creates operational runbooks for common tasks, incident response, and maintenance procedures with step-by-step instructions and troubleshooting guides.',
    capabilities: {
      tools: ['create_page', 'add_block', 'search_pages'],
      connectors: ['notion', 'pagerduty', 'datadog'],
      inputTypes: ['operational-procedure', 'incident-history', 'system-architecture'],
      outputTypes: ['runbook', 'troubleshooting-guide', 'escalation-path'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: ['publish-runbook'],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You are an operational documentation specialist. Write clear runbooks that enable any on-call engineer to resolve issues independently.',
      specialInstructions: ['Include rollback steps for every change procedure', 'Add expected outputs for verification steps'],
    },
    icon: 'Terminal',
    color: '#1E3A5F',
  },
  {
    agentTypeId: 'workspace.newsletter-composer',
    displayName: 'Internal Newsletter Composer',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Creative,
    baseType: AgentType.Writer,
    description: 'Composes internal newsletters by curating workspace highlights, new content, team updates, and upcoming events into engaging digests.',
    capabilities: {
      tools: ['search_pages', 'create_page', 'add_block', 'get_workspace_stats'],
      connectors: ['notion', 'email', 'slack'],
      inputTypes: ['workspace-activity', 'team-updates', 'event-calendar'],
      outputTypes: ['newsletter-draft', 'digest-email', 'highlights-summary'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['send-newsletter'],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You are an internal communications writer. Create engaging newsletters that keep the team informed and connected.',
      specialInstructions: ['Lead with the most impactful news', 'Keep sections short with links to full content'],
    },
    icon: 'Newspaper',
    color: '#EC4899',
  },
  {
    agentTypeId: 'workspace.duplicate-finder',
    displayName: 'Duplicate Content Finder',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Core,
    baseType: AgentType.Analyst,
    description: 'Identifies duplicate or near-duplicate pages in the workspace using content similarity analysis, suggesting merges to reduce redundancy.',
    capabilities: {
      tools: ['search_pages', 'get_workspace_stats'],
      connectors: ['notion', 'confluence'],
      inputTypes: ['page-inventory', 'similarity-threshold', 'content-hash'],
      outputTypes: ['duplicate-report', 'merge-suggestion', 'canonical-recommendation'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['merge-pages'],
      maxTokenBudget: 30000,
      maxCostUsdBudget: 1.0,
    },
    persona: {
      systemPromptAddition: 'You are a content deduplication specialist. Find redundant content and recommend canonical versions to maintain a single source of truth.',
      specialInstructions: ['Compare titles, headings, and first paragraphs for quick matching', 'Recommend the most recently updated version as canonical'],
    },
    icon: 'Copy',
    color: '#92400E',
  },
  {
    agentTypeId: 'workspace.accessibility-checker',
    displayName: 'Content Accessibility Checker',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Core,
    baseType: AgentType.Reviewer,
    description: 'Reviews workspace content for accessibility compliance including alt text, heading structure, color contrast, and reading level.',
    capabilities: {
      tools: ['search_pages', 'add_block', 'get_workspace_stats'],
      connectors: ['notion', 'axe-core'],
      inputTypes: ['page-content', 'accessibility-standards', 'image-list'],
      outputTypes: ['accessibility-report', 'remediation-list', 'compliance-score'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You are an accessibility compliance reviewer. Ensure all content is accessible to users with disabilities following WCAG guidelines.',
      specialInstructions: ['Check for missing alt text on all images', 'Verify heading hierarchy is sequential without skipping levels'],
    },
    icon: 'Eye',
    color: '#0284C7',
  },
  {
    agentTypeId: 'workspace.brainstorm-facilitator',
    displayName: 'Brainstorm Facilitator Agent',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Creative,
    baseType: AgentType.Coordinator,
    description: 'Facilitates brainstorming sessions by generating prompts, organizing ideas, identifying themes, and synthesizing outputs into actionable plans.',
    capabilities: {
      tools: ['create_page', 'add_block', 'search_pages'],
      connectors: ['miro', 'figma-jam', 'notion'],
      inputTypes: ['brainstorm-topic', 'participant-input', 'constraint-set'],
      outputTypes: ['idea-collection', 'theme-synthesis', 'action-plan'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 2,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You are a brainstorming facilitator. Generate diverse ideas, avoid groupthink, and synthesize inputs into structured outcomes.',
      specialInstructions: ['Use divergent thinking first, then convergent', 'Encourage wild ideas before evaluating feasibility'],
    },
    icon: 'Lightbulb',
    color: '#FBBF24',
  },
  {
    agentTypeId: 'workspace.competitive-intel',
    displayName: 'Competitive Intelligence Agent',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Business,
    baseType: AgentType.Researcher,
    description: 'Maintains competitive intelligence pages by tracking competitor updates, analyzing product changes, and updating battle cards.',
    capabilities: {
      tools: ['create_page', 'search_pages', 'add_block', 'get_workspace_stats'],
      connectors: ['web-scraper', 'crunchbase', 'notion'],
      inputTypes: ['competitor-list', 'news-feed', 'product-update'],
      outputTypes: ['competitive-briefing', 'battle-card', 'market-landscape'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: [],
      maxTokenBudget: 50000,
      maxCostUsdBudget: 2.0,
    },
    persona: {
      systemPromptAddition: 'You are a competitive intelligence analyst. Track competitor moves and provide strategic insights to inform product and go-to-market decisions.',
      specialInstructions: ['Update battle cards within 48 hours of competitor changes', 'Verify all claims with primary sources'],
    },
    icon: 'Radar',
    color: '#6D28D9',
  },
  {
    agentTypeId: 'workspace.data-privacy-scanner',
    displayName: 'Data Privacy Scanner',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Legal,
    baseType: AgentType.Compliance,
    description: 'Scans workspace content for personally identifiable information (PII), sensitive data, and privacy policy violations to ensure data protection compliance.',
    capabilities: {
      tools: ['search_pages', 'get_workspace_stats'],
      connectors: ['notion', 'dlp-scanner'],
      inputTypes: ['page-content', 'privacy-policy', 'data-classification'],
      outputTypes: ['pii-finding', 'remediation-task', 'privacy-compliance-report'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 3,
      costTier: CostTier.Standard,
      latencyProfile: LatencyProfile.Batch,
      requiresApproval: ['redact-content'],
      maxTokenBudget: 40000,
      maxCostUsdBudget: 1.5,
    },
    persona: {
      systemPromptAddition: 'You are a data privacy specialist. Identify sensitive data exposure in workspace content and recommend remediation actions.',
      specialInstructions: ['Scan for email addresses, phone numbers, SSNs, and financial data', 'Flag content shared externally that contains internal-only data'],
    },
    icon: 'ScanEye',
    color: '#DC2626',
  },
  {
    agentTypeId: 'workspace.readability-improver',
    displayName: 'Readability Improvement Agent',
    domain: AgentDomain.Workspace,
    category: AgentCategory.Creative,
    baseType: AgentType.Reviewer,
    description: 'Analyzes content readability using Flesch-Kincaid and other metrics, then suggests improvements to make content clearer and more accessible.',
    capabilities: {
      tools: ['search_pages', 'add_block', 'get_workspace_stats'],
      connectors: ['notion', 'hemingway', 'grammarly'],
      inputTypes: ['page-content', 'target-audience', 'readability-target'],
      outputTypes: ['readability-score', 'improvement-suggestion', 'simplified-version'],
      domains: ['workspace'],
    },
    constraints: {
      maxConcurrency: 5,
      costTier: CostTier.Cheap,
      latencyProfile: LatencyProfile.Interactive,
      requiresApproval: [],
      maxTokenBudget: 20000,
      maxCostUsdBudget: 0.5,
    },
    persona: {
      systemPromptAddition: 'You are a readability optimization specialist. Make content clearer and more accessible without losing technical accuracy.',
      specialInstructions: ['Target grade 8-10 reading level for general content', 'Break long sentences and replace jargon with plain language'],
    },
    icon: 'GlassesIcon',
    color: '#4338CA',
  },
]
