import { AgentType, AgentCategory } from '../types'
import type { AgentTypeDefinition } from '../types'

export const AGENT_DEFINITIONS: AgentTypeDefinition[] = [
  // ─── Core ───────────────────────────────────────────────────────────
  {
    type: AgentType.Planner,
    label: 'Planner',
    description: 'Breaks down complex tasks into actionable plans with clear milestones',
    icon: 'ClipboardList',
    color: '#4F46E5',
    category: AgentCategory.Core,
    useCases: [
      'Break a product launch into phases',
      'Create sprint plans for engineering teams',
      'Map project dependencies and timelines',
    ],
    capabilities: ['Task decomposition', 'Milestone planning', 'Dependency mapping', 'Timeline estimation'],
    defaultSteps: [
      { label: 'Analyzing requirements', durationMs: 2000 },
      { label: 'Identifying dependencies', durationMs: 1500 },
      { label: 'Creating task breakdown', durationMs: 2500 },
      { label: 'Setting milestones', durationMs: 1000 },
      { label: 'Finalizing plan', durationMs: 1500 },
    ],
  },
  {
    type: AgentType.Researcher,
    label: 'Researcher',
    description: 'Gathers information, analyzes data sources, and synthesizes findings',
    icon: 'Search',
    color: '#0891B2',
    category: AgentCategory.Core,
    useCases: [
      'Research market trends and competitor landscape',
      'Gather data for quarterly business reviews',
      'Investigate best practices for new initiatives',
    ],
    capabilities: ['Data collection', 'Source analysis', 'Pattern recognition', 'Research synthesis'],
    defaultSteps: [
      { label: 'Defining research scope', durationMs: 1500 },
      { label: 'Gathering primary sources', durationMs: 3000 },
      { label: 'Analyzing data patterns', durationMs: 2500 },
      { label: 'Cross-referencing findings', durationMs: 2000 },
      { label: 'Compiling research brief', durationMs: 1500 },
    ],
  },
  {
    type: AgentType.Analyst,
    label: 'Analyst',
    description: 'Processes data, identifies trends, and generates actionable insights',
    icon: 'BarChart3',
    color: '#059669',
    category: AgentCategory.Core,
    useCases: [
      'Analyze quarterly revenue trends',
      'Create data visualizations for board meetings',
      'Identify customer behavior patterns',
    ],
    capabilities: ['Statistical analysis', 'Trend detection', 'Data visualization', 'Insight generation'],
    defaultSteps: [
      { label: 'Collecting data points', durationMs: 2000 },
      { label: 'Running statistical analysis', durationMs: 2500 },
      { label: 'Identifying trends', durationMs: 2000 },
      { label: 'Generating visualizations', durationMs: 1500 },
      { label: 'Preparing insights report', durationMs: 1500 },
    ],
  },
  {
    type: AgentType.Reviewer,
    label: 'Reviewer',
    description: 'Reviews work quality, checks for issues, and provides feedback',
    icon: 'CheckSquare',
    color: '#DC2626',
    category: AgentCategory.Core,
    useCases: [
      'Review code PRs for quality and bugs',
      'Proofread documents before publishing',
      'Audit deliverables against requirements',
    ],
    capabilities: ['Quality assessment', 'Issue detection', 'Feedback generation', 'Standards compliance'],
    defaultSteps: [
      { label: 'Reviewing requirements compliance', durationMs: 2000 },
      { label: 'Checking code quality', durationMs: 2500 },
      { label: 'Testing edge cases', durationMs: 2000 },
      { label: 'Writing review comments', durationMs: 1500 },
    ],
  },
  {
    type: AgentType.Coordinator,
    label: 'Coordinator',
    description: 'Orchestrates team workflow, manages handoffs, and ensures alignment',
    icon: 'Users',
    color: '#6366F1',
    category: AgentCategory.Core,
    useCases: [
      'Coordinate cross-team project handoffs',
      'Draft meeting agendas and follow-ups',
      'Manage stakeholder communications',
    ],
    capabilities: ['Task distribution', 'Progress monitoring', 'Blocker resolution', 'Team reporting'],
    defaultSteps: [
      { label: 'Assessing team readiness', durationMs: 1500 },
      { label: 'Distributing tasks', durationMs: 1000 },
      { label: 'Monitoring progress', durationMs: 2000 },
      { label: 'Resolving blockers', durationMs: 2000 },
      { label: 'Compiling team report', durationMs: 1500 },
    ],
  },

  // ─── Creative ───────────────────────────────────────────────────────
  {
    type: AgentType.Writer,
    label: 'Writer',
    description: 'Creates clear, structured content from drafts to polished documents',
    icon: 'PenTool',
    color: '#7C3AED',
    category: AgentCategory.Creative,
    useCases: [
      'Draft blog posts and thought leadership articles',
      'Write product documentation and guides',
      'Compose emails, proposals, and memos',
    ],
    capabilities: ['Content structuring', 'Draft writing', 'Language refinement', 'Tone adaptation'],
    defaultSteps: [
      { label: 'Outlining structure', durationMs: 1500 },
      { label: 'Writing first draft', durationMs: 3000 },
      { label: 'Refining language', durationMs: 2000 },
      { label: 'Adding details and examples', durationMs: 2500 },
      { label: 'Final polish', durationMs: 1000 },
    ],
  },
  {
    type: AgentType.Designer,
    label: 'Designer',
    description: 'Creates wireframes, prototypes, and visual design specifications',
    icon: 'Palette',
    color: '#EC4899',
    category: AgentCategory.Creative,
    useCases: [
      'Design landing page wireframes',
      'Create UI component specifications',
      'Build design system tokens and guidelines',
    ],
    capabilities: ['Wireframing', 'Mockup creation', 'Design tokens', 'Accessibility review'],
    defaultSteps: [
      { label: 'Reviewing design requirements', durationMs: 1500 },
      { label: 'Sketching wireframes', durationMs: 2500 },
      { label: 'Creating high-fidelity mockups', durationMs: 3000 },
      { label: 'Defining design tokens', durationMs: 1500 },
      { label: 'Preparing design handoff', durationMs: 1000 },
    ],
  },
  {
    type: AgentType.Translation,
    label: 'Translation',
    description: 'Multi-language translation, localization, and cultural adaptation',
    icon: 'Languages',
    color: '#14B8A6',
    category: AgentCategory.Creative,
    useCases: [
      'Translate product pages for international markets',
      'Localize marketing copy for cultural relevance',
      'Adapt documentation for regional audiences',
    ],
    capabilities: ['Language detection', 'Translation', 'Idiom localization', 'Format adaptation'],
    defaultSteps: [
      { label: 'Detecting source language', durationMs: 1000 },
      { label: 'Translating content', durationMs: 3000 },
      { label: 'Localizing idioms', durationMs: 2000 },
      { label: 'Adapting formatting', durationMs: 1500 },
      { label: 'Quality checking', durationMs: 1500 },
    ],
  },
  {
    type: AgentType.SEO,
    label: 'SEO',
    description: 'Keyword research, content optimization, competitor analysis, and rankings',
    icon: 'Globe',
    color: '#84CC16',
    category: AgentCategory.Creative,
    useCases: [
      'Research high-value keywords for content strategy',
      'Optimize landing pages for search rankings',
      'Analyze competitor SEO strategies',
    ],
    capabilities: ['Keyword research', 'Competitor analysis', 'Content optimization', 'Meta tag creation'],
    defaultSteps: [
      { label: 'Researching keywords', durationMs: 2000 },
      { label: 'Analyzing competitors', durationMs: 2500 },
      { label: 'Optimizing content', durationMs: 2000 },
      { label: 'Building meta tags', durationMs: 1500 },
      { label: 'Tracking rankings', durationMs: 1000 },
    ],
  },
  {
    type: AgentType.SocialMedia,
    label: 'Social Media',
    description: 'Content calendar, post generation, hashtag strategy, and analytics',
    icon: 'Share2',
    color: '#E879F9',
    category: AgentCategory.Creative,
    useCases: [
      'Build a monthly content calendar',
      'Generate platform-specific social posts',
      'Analyze engagement metrics and optimize strategy',
    ],
    capabilities: ['Trend analysis', 'Content scheduling', 'Post crafting', 'Hashtag optimization'],
    defaultSteps: [
      { label: 'Analyzing trends', durationMs: 2000 },
      { label: 'Generating content calendar', durationMs: 2500 },
      { label: 'Crafting posts', durationMs: 2000 },
      { label: 'Optimizing hashtags', durationMs: 1500 },
      { label: 'Projecting engagement', durationMs: 1000 },
    ],
  },

  // ─── Technical ──────────────────────────────────────────────────────
  {
    type: AgentType.Developer,
    label: 'Developer',
    description: 'Implements features, writes code, and handles technical architecture',
    icon: 'Code2',
    color: '#F59E0B',
    category: AgentCategory.Technical,
    useCases: [
      'Implement new product features end-to-end',
      'Write unit and integration tests',
      'Refactor legacy code for maintainability',
    ],
    capabilities: ['Feature implementation', 'Test writing', 'Code review', 'Architecture design'],
    defaultSteps: [
      { label: 'Setting up project structure', durationMs: 1500 },
      { label: 'Implementing core logic', durationMs: 3000 },
      { label: 'Writing unit tests', durationMs: 2000 },
      { label: 'Integrating components', durationMs: 2500 },
      { label: 'Running build checks', durationMs: 1000 },
      { label: 'Code cleanup', durationMs: 1000 },
    ],
  },
  {
    type: AgentType.Security,
    label: 'Security',
    description: 'Vulnerability assessment, access review, and incident playbooks',
    icon: 'Shield',
    color: '#EF4444',
    category: AgentCategory.Technical,
    useCases: [
      'Run security vulnerability assessments',
      'Audit user access controls and permissions',
      'Create incident response playbooks',
    ],
    capabilities: ['Attack surface scanning', 'Vulnerability identification', 'Access review', 'Remediation planning'],
    defaultSteps: [
      { label: 'Scanning attack surface', durationMs: 2500 },
      { label: 'Identifying vulnerabilities', durationMs: 3000 },
      { label: 'Reviewing access controls', durationMs: 2000 },
      { label: 'Assessing risk levels', durationMs: 1500 },
      { label: 'Building remediation plan', durationMs: 2000 },
    ],
  },
  {
    type: AgentType.DevOps,
    label: 'DevOps',
    description: 'CI/CD pipeline config, deployment checklists, monitoring, and infra planning',
    icon: 'Server',
    color: '#A855F7',
    category: AgentCategory.Technical,
    useCases: [
      'Configure CI/CD pipelines for new services',
      'Create deployment and rollback checklists',
      'Set up monitoring and alerting dashboards',
    ],
    capabilities: ['Infrastructure auditing', 'Pipeline configuration', 'Monitoring setup', 'Runbook creation'],
    defaultSteps: [
      { label: 'Auditing infrastructure', durationMs: 2000 },
      { label: 'Configuring pipeline', durationMs: 2500 },
      { label: 'Setting up monitoring', durationMs: 2000 },
      { label: 'Creating runbooks', durationMs: 1500 },
      { label: 'Validating deployment', durationMs: 1500 },
    ],
  },

  // ─── Business & Sales ───────────────────────────────────────────────
  {
    type: AgentType.Sales,
    label: 'Sales',
    description: 'Lead scoring, outreach sequences, proposal generation',
    icon: 'TrendingUp',
    color: '#F97316',
    category: AgentCategory.Business,
    useCases: [
      'Score and prioritize inbound leads',
      'Generate personalized outreach sequences',
      'Create tailored sales proposals',
    ],
    capabilities: ['Lead qualification', 'Prospect profiling', 'Outreach crafting', 'Pipeline scoring'],
    defaultSteps: [
      { label: 'Qualifying leads', durationMs: 2000 },
      { label: 'Building prospect profiles', durationMs: 2500 },
      { label: 'Crafting outreach', durationMs: 2000 },
      { label: 'Generating proposal', durationMs: 2500 },
      { label: 'Scoring pipeline', durationMs: 1000 },
    ],
  },
  {
    type: AgentType.Marketing,
    label: 'Marketing',
    description: 'Campaign creation, content strategy, ad copy, and audience targeting',
    icon: 'Megaphone',
    color: '#8B5CF6',
    category: AgentCategory.Business,
    useCases: [
      'Design multi-channel marketing campaigns',
      'Create A/B test variants for ad copy',
      'Build audience segments for targeted outreach',
    ],
    capabilities: ['Audience analysis', 'Campaign building', 'Ad variant creation', 'Metrics tracking'],
    defaultSteps: [
      { label: 'Analyzing audience', durationMs: 2000 },
      { label: 'Crafting messaging', durationMs: 2000 },
      { label: 'Building campaign', durationMs: 2500 },
      { label: 'Creating ad variants', durationMs: 2000 },
      { label: 'Setting metrics', durationMs: 1000 },
    ],
  },
  {
    type: AgentType.Finance,
    label: 'Finance',
    description: 'Invoice processing, expense tracking, budget forecasts, financial reports',
    icon: 'DollarSign',
    color: '#10B981',
    category: AgentCategory.Business,
    useCases: [
      'Generate monthly budget forecasts',
      'Categorize and track business expenses',
      'Produce financial summary reports',
    ],
    capabilities: ['Data collection', 'Transaction categorization', 'Forecasting', 'Report generation'],
    defaultSteps: [
      { label: 'Collecting financial data', durationMs: 2000 },
      { label: 'Categorizing transactions', durationMs: 2500 },
      { label: 'Running forecasts', durationMs: 2000 },
      { label: 'Building budget model', durationMs: 2500 },
      { label: 'Generating report', durationMs: 1500 },
    ],
  },

  // ─── Legal & Compliance ─────────────────────────────────────────────
  {
    type: AgentType.Legal,
    label: 'Legal',
    description: 'Contract review, clause extraction, risk flagging, and legal summaries',
    icon: 'Scale',
    color: '#6366F1',
    category: AgentCategory.Legal,
    useCases: [
      'Review vendor contracts for risk clauses',
      'Extract key terms from legal documents',
      'Summarize legal obligations and deadlines',
    ],
    capabilities: ['Document parsing', 'Clause extraction', 'Risk identification', 'Compliance checking'],
    defaultSteps: [
      { label: 'Parsing document', durationMs: 2000 },
      { label: 'Extracting clauses', durationMs: 2500 },
      { label: 'Identifying risks', durationMs: 2000 },
      { label: 'Checking compliance', durationMs: 2000 },
      { label: 'Preparing summary', durationMs: 1500 },
    ],
  },
  {
    type: AgentType.Compliance,
    label: 'Compliance',
    description: 'Regulatory checking, audit prep, policy enforcement, and risk assessment',
    icon: 'ShieldCheck',
    color: '#0EA5E9',
    category: AgentCategory.Legal,
    useCases: [
      'Prepare for regulatory audits',
      'Check product features against compliance requirements',
      'Generate policy adherence reports',
    ],
    capabilities: ['Regulation scanning', 'Requirement mapping', 'Violation flagging', 'Audit reporting'],
    defaultSteps: [
      { label: 'Scanning regulations', durationMs: 2000 },
      { label: 'Mapping requirements', durationMs: 2500 },
      { label: 'Checking adherence', durationMs: 2000 },
      { label: 'Flagging violations', durationMs: 1500 },
      { label: 'Generating audit report', durationMs: 2000 },
    ],
  },

  // ─── People & Culture ───────────────────────────────────────────────
  {
    type: AgentType.HR,
    label: 'HR',
    description: 'Job descriptions, candidate screening, onboarding checklists, and surveys',
    icon: 'UserPlus',
    color: '#D946EF',
    category: AgentCategory.People,
    useCases: [
      'Write job descriptions for open roles',
      'Screen candidate applications automatically',
      'Build onboarding checklists for new hires',
    ],
    capabilities: ['Role analysis', 'Description drafting', 'Screening criteria', 'Onboarding planning'],
    defaultSteps: [
      { label: 'Analyzing role requirements', durationMs: 1500 },
      { label: 'Drafting description', durationMs: 2500 },
      { label: 'Screening criteria', durationMs: 2000 },
      { label: 'Building onboarding plan', durationMs: 2000 },
      { label: 'Creating survey', durationMs: 1500 },
    ],
  },
  {
    type: AgentType.CustomerSuccess,
    label: 'Customer Success',
    description: 'Ticket triage, response drafting, NPS analysis, and churn prediction',
    icon: 'HeartHandshake',
    color: '#F43F5E',
    category: AgentCategory.People,
    useCases: [
      'Triage and prioritize support tickets',
      'Draft customer response templates',
      'Analyze NPS scores and predict churn',
    ],
    capabilities: ['Ticket triage', 'Sentiment analysis', 'Response drafting', 'Churn prediction'],
    defaultSteps: [
      { label: 'Triaging tickets', durationMs: 2000 },
      { label: 'Analyzing sentiment', durationMs: 2500 },
      { label: 'Drafting responses', durationMs: 2000 },
      { label: 'Computing NPS scores', durationMs: 1500 },
      { label: 'Predicting churn risk', durationMs: 2000 },
    ],
  },
]

export function getDefinition(type: AgentType): AgentTypeDefinition | undefined {
  return AGENT_DEFINITIONS.find(d => d.type === type)
}
